'use strict';
const assert = require('node:assert/strict');
const mastery = require('../webapp/bert-world-mastery.js');
const memory = new Map();
const storage = { getItem: (key) => memory.get(key) || null, setItem: (key, value) => memory.set(key, value) };
assert.equal(mastery.qualifies(11, [{ kind: 'bird-run-bird', predator: false }], []), false);
assert.equal(mastery.qualifies(11, [{ kind: 'bird-run-bird', predator: true }], []), true);
assert.equal(mastery.qualifies(12, [{ kind: 'storm-sail', weatherLevel: 1 }], []), false);
assert.equal(mastery.qualifies(12, [{ kind: 'wind-branch', weatherLevel: 2 }], []), true);
assert.equal(mastery.qualifies(12, [{ kind: 'decorative-leaf', weatherLevel: 3 }], []), false);
assert.equal(mastery.qualifies(10, [{ id: 19, kind: 'edm-crowd-ball', crowdSize: 3 }], [{ id: 19, kind: 'edm-crowd-ball' }]), false);
assert.equal(mastery.qualifies(10, [{ id: 19, kind: 'edm-crowd-ball', crowdSize: 3 }], []), true);
assert.equal(mastery.qualifies(10, [{ id: 7, kind: 'edm-crowd-ball', crowdSize: 2 }], []), false);
assert.equal(mastery.award(10, storage).awarded, true);
assert.equal(mastery.award(10, storage).awarded, false);
assert.deepEqual(mastery.read(storage), { 10: true });
assert.deepEqual(mastery.read({ getItem() { throw Error('private mode'); } }), {});
assert.equal(mastery.award(999, storage).awarded, false);
console.log('world mastery: 13 assertions passed');
