/* Español. Las claves son los textos daneses originales. */
window.BertI18n.register('es', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · VUELA UNA RONDA PARA MARCAR TU PRIMERA PUNTUACIÓN',
    ' · MÆRKE: {0}': ' · INSIGNIA: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · JUEGA UN DUELO CON AMIGOS PARA TENER UN RIVAL',
    '+{0} fjer til reden': '+{0} plumas para el nido',
    '+{0} fjer · {1} låst op': '+{0} plumas · {1} desbloqueado',
    '0 / 0 POINT': '0 / 0 PUNTOS',
    '20 point til bronze': '20 puntos para el bronce',
    '3 SPILFORMER · 9 BANER': '3 MODOS · 9 NIVELES',
    '3 baner · hold op/ned': '3 niveles · mantén arriba/abajo',
    '3 baner · præcision': '3 niveles · precisión',
    '3 baner · tap': '3 niveles · toca',
    '9 baner · nye verdener': '9 niveles · nuevos mundos',
    'ACCEPTÉR': 'ACEPTAR',
    'AFSLUT TUREN': 'TERMINAR LA RONDA',
    'Alle baner': 'Todos los niveles',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Todos los héroes tienen la misma velocidad y zona de impacto. Gánalos jugando o ahorra plumas.',
    'Alle pointkrav i trin {0} er klaret.': 'Todos los requisitos de puntos del nivel {0} están cumplidos.',
    'Alle spil': 'Todos los juegos',
    'Alle tider': 'Siempre',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Has usado los tres intentos. Pide a tu amigo un nuevo duelo.',
    'BANEN ER LÅST': 'NIVEL BLOQUEADO',
    'BEKRÆFT · {0} FJER': 'CONFIRMAR · {0} PLUMAS',
    'BERTS GARDEROBE': 'EL ARMARIO DE BERT',
    'BERTS REDE': 'EL NIDO DE BERT',
    'BERTS REDNINGSREDE': 'EL NIDO DE RESCATE DE BERT',
    'BEVÆGELIGE TÅRNE': 'TORRES MÓVILES',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} estrellas · solo récord local del evento',
    'Bane': 'Nivel',
    'Banen er låst': 'El nivel está bloqueado',
    'Bedst på level {0} · {1}': 'Mejor en el nivel {0} · {1}',
    'Bert The Bird appikon': 'Icono de la app Bert The Bird',
    'Bert The Bird bliver installeret': 'Bert The Bird se está instalando',
    'Bert The Bird er installeret': 'Bert The Bird está instalado',
    'Bert The Bird spilcanvas': 'Área de juego de Bert The Bird',
    'Bert flyver': 'Bert volando',
    'Bevægelse i koncertlys': 'Movimiento en las luces del concierto',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Gasta 12 plumas en un giro. Cinco casillas devuelven a Bert al nivel. Una casilla termina la ronda.',
    'DAGENS MISSIONER': 'MISIONES DE HOY',
    'DAGENS RUTE': 'RUTA DE HOY',
    'DAGENS RUTE · MÅL {0}': 'RUTA DE HOY · META {0}',
    'DENNE TUR': 'ESTA RONDA',
    'DIN FLYVETUR': 'TU VUELO',
    'DIN HELT': 'TU HÉROE',
    'DIN SALDO': 'TU SALDO',
    'DINE VENNEDUELLER': 'TUS DUELOS CON AMIGOS',
    'DREJ TELEFONEN': 'GIRA EL TELÉFONO',
    'DU ER UDFORDRET': 'TE HAN DESAFIADO',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'GANASTE EL DUELO · devuelve el desafío · {0} estrellas',
    'Den sjældneste fugl · køb for fjer': 'El pájaro más raro · compra con plumas',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Este nivel no se puede usar para duelos clasificados con amigos.',
    'Dit navn': 'Tu nombre',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Tu nombre aparece en la clasificación y junto a tus récords.',
    'Du mangler fjer fra dagens missioner': 'Te faltan plumas de las misiones de hoy',
    'EDM-VERDEN · LOKALT': 'MUNDO EDM · LOCAL',
    'EPISK': 'ÉPICO',
    'EVENT · BIRD RUN · TESTBANE': 'EVENTO · BIRD RUN · NIVEL DE PRUEBA',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENTO · NEON ENCORE · NIVEL DE PRUEBA',
    'EVENT · STORMLINE · TESTBANE': 'EVENTO · STORMLINE · NIVEL DE PRUEBA',
    'EVENTYR': 'AVENTURA',
    'EVENTYR · {0}': 'AVENTURA · {0}',
    'Episk helt · kun til dig · valgt': 'Héroe épico · solo para ti · elegido',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Héroe épico · solo para ti. Toca para elegir.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Una vida de rescate permanente absorbe un choque en cada ronda. Tras un choque también puedes gastar 12 plumas en un giro de rescate. Siempre puedes seguir jugando sin energía ni esperas.',
    'FAST + BEVÆGELIG': 'FIJO + MÓVIL',
    'FASTE TÅRNE': 'TORRES FIJAS',
    'FJER': 'PLUMAS',
    'FJER RETUR': 'PLUMAS DEVUELTAS',
    'FJER · PRIMÆRT VINDES I SPILLET': 'PLUMAS · SE GANAN SOBRE TODO JUGANDO',
    'FLYV': 'VOLAR',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'VUELA POR TRES PUERTAS DE NUBES · GOLPEA LA PLACA DORADA · IZQUIERDA SUBE · DERECHA BAJA',
    'FLYV IGEN': 'VOLAR OTRA VEZ',
    'FLYV VIDERE': 'SEGUIR VOLANDO',
    'FLYVETUREN ER SAT PÅ PAUSE': 'EL VUELO ESTÁ EN PAUSA',
    'FODBOLD-BERT': 'BERT FUTBOLERO',
    'FOKUS': 'FOCO',
    'FOKUS OM {0}': 'FOCO EN {0}',
    'FORBI': 'FALLADO',
    'FORBI GULDPLADEN': 'FALLASTE LA PLACA DORADA',
    'FORSTÅET': 'ENTENDIDO',
    'FORTRYD': 'CANCELAR',
    'FORTSÆT': 'CONTINUAR',
    'FRI AF ROVFUGLEN': 'LIBRE DE LA RAPAZ',
    'FUGL BAGFRA': 'PÁJARO POR DETRÁS',
    'FUGLEVERDEN · LOKALT': 'MUNDO DE PÁJAROS · LOCAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Cuatro mundos de evento locales gratis sin clasificación global',
    'Flyv samlet i 3 minutter': 'Vuela 3 minutos en total',
    'Flyvetid': 'Tiempo de vuelo',
    'Fodbold-Bert': 'Bert Futbolero',
    'Forbindelsen er tilbage': 'La conexión ha vuelto',
    'Fremgang mod oplåsning': 'Progreso para desbloquear',
    'Fugle · rovfugl': 'Pájaros · rapaz',
    'FÆRDIG': 'LISTO',
    'FØLG STJERNESTRØMMEN': 'SIGUE LA CORRIENTE DE ESTRELLAS',
    'FØLGER DIG KORT · {0}s': 'TE SIGUE UN MOMENTO · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · LA RONDA TERMINA',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} RESULTADOS',
    'GODT RAMT': 'BUEN GOLPE',
    'GRATIS REDNING': 'RESCATE GRATIS',
    'GRUNDFLYVNING': 'VUELO BÁSICO',
    'GULD': 'ORO',
    'GULD-BERT': 'BERT DORADO',
    'Guld-Bert': 'Bert Dorado',
    'HAV BERT PÅ STARTSKÆRMEN': 'TEN A BERT EN LA PANTALLA DE INICIO',
    'HAVNEN': 'EL PUERTO',
    'Havnen': 'El Puerto',
    'HENT FJER': 'RECOGER PLUMAS',
    'HENT SPILLET': 'DESCARGAR EL JUEGO',
    'HENT +{0}': 'RECOGER +{0}',
    '+{0} FJER': '+{0} PLUMAS',
    'HENTER RESULTATER …': 'CARGANDO RESULTADOS …',
    'HENTET': 'RECOGIDO',
    'HOLD OP/NED': 'MANTÉN ARRIBA/ABAJO',
    'HOVEDMENU': 'MENÚ PRINCIPAL',
    'HVAD HEDDER DU?': '¿CÓMO TE LLAMAS?',
    'HVORDAN VIL DU FLYVE?': '¿CÓMO QUIERES VOLAR?',
    'HYPERFART': 'HIPERVELOCIDAD',
    'Haptisk feedback': 'Respuesta háptica',
    'Har altid en pakke med · køb for fjer': 'Siempre lleva un paquete · compra con plumas',
    'Hele Bert The Bird er lavet til landscape.': 'Bert The Bird está hecho para pantalla horizontal.',
    'Hemmelig helt': 'Héroe secreto',
    'Hent en mission syv dage i træk': 'Recoge una misión siete días seguidos',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Recoge {0} recompensas de misión en total; tienes {1}.',
    'Henter resultater …': 'Cargando resultados …',
    'Høj fart': 'Alta velocidad',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'En Safari: Compartir → Añadir a pantalla de inicio. Espera a «Listo para jugar sin conexión» y abre el icono una vez con internet antes de probar el modo avión.',
    'I dag': 'Hoy',
    'IKKE NU': 'AHORA NO',
    'INDSTILLINGER': 'AJUSTES',
    'INSTALLÉR WEBAPP': 'INSTALAR WEB APP',
    'ISTAPPER & SPIDSER': 'CARÁMBANOS Y PÚAS',
    'Isbjerget': 'El Iceberg',
    'ISBJERGET': 'EL ICEBERG',
    'Bert gør klar til at flyve …': 'Bert se prepara para volar …',
    'Ingen rekord endnu': 'Aún no hay récord',
    'Installér som webapp': 'Instalar como web app',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Instala desde el menú del navegador. Espera a «Listo para jugar sin conexión» y abre la app una vez con internet antes de probar sin conexión.',
    'KANT': 'BORDE',
    'KLAR DAGENS MÅL': 'CUMPLE LA META DE HOY',
    'KLARET': 'HECHO',
    'KONCERT · TESTBANE': 'CONCIERTO · NIVEL DE PRUEBA',
    'KRANER & MÅGER': 'GRÚAS Y GAVIOTAS',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'SOLO TUS RESULTADOS LOCALES · LA TABLA ONLINE NO ESTÁ DISPONIBLE',
    'KVALIFIKATIONSBANEN': 'EL NIVEL CLASIFICATORIO',
    'Klar dagens rute': 'Completa la ruta de hoy',
    'Klar dagens rute én gang': 'Completa la ruta de hoy una vez',
    'Klar hele forrige trin og missionskravet først': 'Completa primero todo el nivel anterior y el requisito de misiones',
    'Klar hele trin {0}: {1}.': 'Completa todo el nivel {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Completa el nivel clasificatorio para abrir este desafío.',
    'Klar til offline-spil': 'Listo para jugar sin conexión',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Supera al menos tres bolas en una ola de concierto',
    'KØB': 'COMPRAR',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'COMPRA VIDAS FIJAS O UN GIRO DE RESCATE',
    'KØB · {0} FJER': 'COMPRAR · {0} PLUMAS',
    'KØBT': 'COMPRADO',
    'LAVA & BOBLER': 'LAVA Y BURBUJAS',
    'LEVENDE FORHINDRINGER': 'OBSTÁCULOS VIVOS',
    'LEVERING': 'ENTREGA',
    'LYD & FEEDBACK': 'SONIDO Y RESPUESTA',
    'LYDLØS': 'SILENCIOSO',
    'Level 1 · Mål 30': 'Nivel 1 · Meta 30',
    'Luk': 'Cerrar',
    'Luk garderoben': 'Cerrar el armario',
    'Lydeffekter': 'Efectos de sonido',
    'Lydløs og hurtig · køb for fjer': 'Silencioso y rápido · compra con plumas',
    'LÅS OP · 20 FJER': 'DESBLOQUEAR · 20 PLUMAS',
    'LÅS OP · {0} FJER': 'DESBLOQUEAR · {0} PLUMAS',
    'LÅST BANE': 'NIVEL BLOQUEADO',
    'LÅST OP': 'DESBLOQUEADO',
    'LÆR KORRIDOREN': 'APRENDE EL CORREDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Desbloqueado. Toca el personaje para elegirlo.',
    'MAKS LÅST OP': 'MÁXIMO DESBLOQUEADO',
    'MINISPIL · SKY RELAY · LOKALT': 'MINIJUEGO · SKY RELAY · LOCAL',
    'MISSIONER': 'MISIONES',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MÓVIL: LADO IZQUIERDO = ARRIBA · LADO DERECHO = ABAJO',
    'Missioner': 'Misiones',
    'Mod vinden': 'Contra el viento',
    'Musik': 'Música',
    'MÅGEN MOGENS': 'MOGENS LA GAVIOTA',
    'Mågen Mogens': 'Mogens la Gaviota',
    'MÅL: 3 BOLDE': 'META: 3 BOLAS',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'META: SUPERA UNA OLA CON TRES BOLAS · IZQUIERDA SUBE · DERECHA BAJA',
    'MÅL: ROVFUGL': 'META: RAPAZ',
    'MÅL: STORM': 'META: TORMENTA',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'META: ESQUIVA UNA RAPAZ · IZQUIERDA SUBE · DERECHA BAJA',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'META: ESQUIVA UN OBJETO DE LA TORMENTA · SIGUE BANDERAS Y HOJAS',
    'MÆRKE VUNDET': 'INSIGNIA GANADA',
    'MØRKE & SKILTE': 'OSCURIDAD Y LETREROS',
    'Måned': 'Mes',
    'NED': 'ABAJO',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} estrellas · solo récord local del evento',
    'NINJA-BERT': 'BERT NINJA',
    'Ninja-Bert': 'Bert Ninja',
    'NIVEAU {0}! · {1}': '¡NIVEL {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING DESBLOQUEADO · VUELO PERFECTO',
    'NY BANE': 'NIVEL NUEVO',
    'NY REKORD!': '¡NUEVO RÉCORD!',
    'NYE VERDENER': 'NUEVOS MUNDOS',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NUEVO NIVEL: LOS TRES NIVELES ESTÁN ABIERTOS · {0} estrellas recogidas',
    'NATTEBYEN': 'LA CIUDAD NOCTURNA',
    'Nattebyen': 'La Ciudad Nocturna',
    'Ny mobilversion indlæst': 'Nueva versión móvil cargada',
    'Nyt redningsliv låst op': 'Nueva vida de rescate desbloqueada',
    'NÆSTE UDFORDRING': 'SIGUIENTE DESAFÍO',
    'Nå 120 point i Desert': 'Llega a 120 puntos en Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Llega a 180 puntos sin fallar una estrella ni chocar',
    'Nå 300 point på én tur': 'Llega a 300 puntos en una ronda',
    'Nå bronze i Jungle uden redning': 'Consigue bronce en Jungle sin rescate',
    'Nå bronze i alle ni baner': 'Consigue bronce en los nueve niveles',
    'Nå bronze i alle tre Classic-baner': 'Consigue bronce en los tres niveles Classic',
    'Nå en streak på 12': 'Consigue una racha de 12',
    'OMVENDT STYRING': 'CONTROLES INVERTIDOS',
    'OP': 'ARRIBA',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'El modo sin conexión aún no está listo · conéctate a internet',
    'PAKKE-BERT': 'BERT PAQUETE',
    'Pakke-Bert': 'Bert Paquete',
    'PERMANENT REDE-FORDEL': 'VENTAJA PERMANENTE DEL NIDO',
    'PERSONLIG REKORD': 'RÉCORD PERSONAL',
    'PILOTER': 'PILOTOS',
    'POINT ×2': 'PUNTOS ×2',
    'PORTE & KLOKKE': 'PUERTAS Y CAMPANA',
    'PRINSESSE SØS': 'PRINCESA SØS',
    'Prinsesse Søs': 'Princesa Søs',
    'PRÆCISION': 'PRECISIÓN',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'VUELO DE PRECISIÓN · PRUEBA LOCAL',
    'PRÆCISIONSRUTE · LOKALT': 'RUTA DE PRECISIÓN · LOCAL',
    'PUBLIKUMSVØLGE': 'OLA DEL PÚBLICO',
    'Pause spillet': 'Pausar el juego',
    'Periode': 'Periodo',
    'Personlig highscore': 'Récord personal',
    'Pilotnavn': 'Nombre de piloto',
    'Pingvin med jetpack · køb for fjer': 'Pingüino con jetpack · compra con plumas',
    'Point': 'Puntos',
    'Porte · vindklokke': 'Puertas · campanilla',
    'PORT {0}/3': 'PUERTA {0}/3',
    'PORT {0}/3 · {1}': 'PUERTA {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RONDA {0} · PUERTA {1}/3',
    'KLANG! +{0} · RUNDE {1}': '¡DING! +{0} · RONDA {1}',
    'Præcisionsflyvning': 'Vuelo de precisión',
    'RAM GULDPLADEN': 'GOLPEA LA PLACA DORADA',
    'RAMT': 'ACERTADO',
    'RANGLISTE': 'CLASIFICACIÓN',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'RESCATADO · TUS 12 PLUMAS VUELVEN',
    'REDDET · {0}': 'RESCATADO · {0}',
    'REDNINGSLIV': 'VIDA DE RESCATE',
    'REDNINGSLIV 0/3': 'VIDAS DE RESCATE 0/3',
    'REDNINGSLIV {0}/{1}': 'VIDAS DE RESCATE {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'EL NIDO DE RESCATE GIRA …',
    'REDNINGSSPIN': 'GIRO DE RESCATE',
    'RENT GENNEM': 'LIMPIO',
    'RIGGE & BOLDE': 'ESTRUCTURAS Y BOLAS',
    'ROTORER & BØJER': 'ROTORES Y BOYAS',
    'ROVFUGL': 'RAPAZ',
    'ROVFUGL BAGFRA': 'RAPAZ POR DETRÁS',
    'FUGL': 'PÁJARO',
    'BAGFRA': 'POR DETRÁS',
    'FORFRA': 'DE FRENTE',
    'RUTEN AFSLUTTET': 'RUTA TERMINADA',
    'Redningsliv tilbage': 'Vidas de rescate restantes',
    'Rigge · bolde': 'Estructuras · bolas',
    'SJÆLDEN': 'RARO',
    'SKIFT BANE': 'CAMBIAR NIVEL',
    'SKJOLD': 'ESCUDO',
    'SKJOLD BRUGT · 2s': 'ESCUDO USADO · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · GOLPEASTE {0} DE LA PUERTA {1} · 0 PUNTOS · OTRA VEZ',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 PUNTOS · OTRA VEZ',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 PUERTAS · {1}% PRECISIÓN · SOLO LOCAL',
    'TOPPEN': 'LA PARTE SUPERIOR',
    'BUNDEN': 'LA PARTE INFERIOR',
    'SKYRING RAMT': 'ANILLO DE NUBE GOLPEADO',
    'SPIL': 'JUGAR',
    'SPIL KVALIFIKATION': 'JUGAR CLASIFICACIÓN',
    'SPIL →': 'JUGAR →',
    'SPIL {0}': 'JUGAR {0}',
    'SPIN FOR AT SE DIN REDNING': 'GIRA PARA VER TU RESCATE',
    'SPIN · 12 FJER': 'GIRAR · 12 PLUMAS',
    'SPIN · {0} FJER': 'GIRAR · {0} PLUMAS',
    'START FORFRA': 'EMPEZAR DE NUEVO',
    'STARTBANE': 'NIVEL INICIAL',
    'STJERNEREGN': 'LLUVIA DE ESTRELLAS',
    'STIGER': 'SUBE',
    'DYKKER': 'BAJA EN PICADO',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · VIENTO Y COSAS VOLANDO · {0} estrellas · solo récord local del evento',
    'STREAK REDDET · GUARD BRUGT': 'RACHA SALVADA · GUARD USADO',
    'STORMPILOT': 'PILOTO DE TORMENTA',
    'Saml 20 stjerner til reden': 'Recoge 20 estrellas para el nido',
    'Saml 250 stjerner i alt': 'Recoge 250 estrellas en total',
    'Scoretype': 'Tipo de puntuación',
    'Skriv dit navn': 'Escribe tu nombre',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Juega Bird Run, un mundo local de pájaros. Esquiva la rapaz anunciada. Sin clasificación global.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Juega Neon Encore, un mundo local de concierto. Sobrevive a una ola completa con al menos tres bolas. Sin clasificación global.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Juega Sky Relay, una ruta local corta de precisión por tres anillos de nubes. Puedes chocar arriba y abajo del anillo. Golpea la placa dorada de la campanilla. Sin clasificación global.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Juega Stormline, un mundo local de viento. Esquiva un objeto volador en la tormenta. Sin clasificación global.',
    'Spiltype': 'Modo de juego',
    'Start Quick Flight': 'Iniciar Quick Flight',
    'Starthelt · Klar til at flyve': 'Héroe inicial · Listo para volar',
    'Starthelt': 'Héroe inicial',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard listo: salva una estrella fallada',
    'Streak Guard reddede din streak': 'Streak Guard salvó tu racha',
    'Sur havnemåge · køb for fjer': 'Gaviota gruñona del puerto · compra con plumas',
    'SØLV': 'PLATA',
    'BRONZE': 'BRONCE',
    'Sådan virker Berts rede': 'Así funciona el nido de Bert',
    'TAP': 'TOCA',
    'TAP FOR AT FLYVE · {0}': 'TOCA PARA VOLAR · {0}',
    'TESTBANE': 'NIVEL DE PRUEBA',
    'TIDEN UDE': 'SE ACABÓ EL TIEMPO',
    'TILBAGE': 'ATRÁS',
    'TRYK FOR AT STARTE': 'TOCA PARA EMPEZAR',
    'TUNG': 'PESADO',
    'TUNG · STIGER LANGSOMT': 'PESADO · SUBE DESPACIO',
    'Tid': 'Tiempo',
    'Tilgængelige helte': 'Héroes disponibles',
    'UDFORDR EN VEN': 'DESAFÍA A UN AMIGO',
    'Udfordringen er klar': 'El desafío está listo',
    'Udfordringslink klar': 'Enlace del desafío listo',
    'Udfordringslink kopieret': 'Enlace del desafío copiado',
    'Uge': 'Semana',
    'Undvig den varslede ørn eller grib': 'Esquiva el águila o el buitre anunciado',
    'Undvig en flyvende genstand i storm eller orkan': 'Esquiva un objeto volador en tormenta o huracán',
    'VELKOMMEN': 'BIENVENIDO',
    'VENNEDUEL': 'DUELO CON AMIGOS',
    'VENNER': 'AMIGOS',
    'VERDEN': 'MUNDO',
    'VENNER FRA DUELLER': 'AMIGOS DE DUELOS',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'AMIGOS DE DUELOS · {0} RIVALES · {1} RESULTADOS',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LADO IZQUIERDO = ARRIBA · LADO DERECHO = ABAJO',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · IZQUIERDA SUBE · DERECHA BAJA',
    'VERDEN KLARET': 'MUNDO COMPLETADO',
    'VERDEN KLARET · LOKALT': 'MUNDO COMPLETADO · LOCAL',
    'VIND & GENSTANDE': 'VIENTO Y OBJETOS',
    'VIND · TESTBANE': 'VIENTO · NIVEL DE PRUEBA',
    'VIND · {0}': 'VIENTO · {0}',
    'VINDKLOKKEN RAMT': 'CAMPANILLA GOLPEADA',
    'VINDVERDEN · LOKALT': 'MUNDO DE VIENTO · LOCAL',
    'Vindmøller': 'Los Molinos',
    'VINDMØLLER': 'LOS MOLINOS',
    'Vulkanen': 'El Volcán',
    'VULKANEN': 'EL VOLCÁN',
    'FJENDER & ANGREB': 'ENEMIGOS Y ATAQUES',
    'FUGLETRAFIK · TESTBANE': 'TRÁFICO DE PÁJAROS · NIVEL DE PRUEBA',
    'FUGLE & ROVFUGL': 'PÁJAROS Y RAPAZ',
    'FLAPPY-STYRING': 'CONTROLES FLAPPY',
    'FLAPPY-STYRING · TAP': 'CONTROLES FLAPPY · TOCA',
    'VUNDET': 'GANADO',
    'BEHOLDT': 'CONSERVADO',
    'Valgt og klar til at flyve': 'Elegido y listo para volar',
    'Vind bronze, sølv og guld': 'Gana bronce, plata y oro',
    'Vind ti vennedueller': 'Gana diez duelos con amigos',
    'Vind · genstande': 'Viento · objetos',
    'VÆLG HELT': 'ELIGE HÉROE',
    'VÆLG LEVEL': 'ELIGE NIVEL',
    'VÆLG SPILTYPE': 'ELIGE MODO',
    'Vælg Bert': 'Elegir Bert', 'Vælg Blok-Johan': 'Elegir Blok-Johan', 'Vælg BlueBert': 'Elegir BlueBert', 'Vælg BoneBeak': 'Elegir BoneBeak',
    'Vælg BrainBird': 'Elegir BrainBird', 'Vælg BrickBird': 'Elegir BrickBird', 'Vælg Coopinc': 'Elegir Coopinc', 'Vælg Fodbold-Bert': 'Elegir Bert Futbolero',
    'Vælg Guld-Bert': 'Elegir Bert Dorado', 'Vælg InkBird': 'Elegir InkBird', 'Vælg MechaBert': 'Elegir MechaBert', 'Vælg MossHex': 'Elegir MossHex',
    'Vælg Mågen Mogens': 'Elegir Mogens la Gaviota', 'Vælg Ninja-Bert': 'Elegir Bert Ninja', 'Vælg NoirWing': 'Elegir NoirWing', 'Vælg Pakke-Bert': 'Elegir Bert Paquete',
    'Vælg Pingo': 'Elegir Pingo', 'Vælg Prinsesse Søs': 'Elegir Princesa Søs', 'Vælg PrismWing': 'Elegir PrismWing', 'Vælg SkyClaw': 'Elegir SkyClaw',
    'Vælg Storm Royale': 'Elegir Storm Royale', 'Vælg SugarRush': 'Elegir SugarRush', 'Vælg Thor Obby': 'Elegir Thor Obby',
    'Vælg bane': 'Elegir nivel',
    'Vælg leaderboard': 'Elegir clasificación',
    'Vælg level': 'Elegir nivel',
    'Vælg spiltype': 'Elegir modo',
    'Vælg {0}, {1}': 'Elegir {0}, {1}',
    'købt': 'comprado',
    'låst op': 'desbloqueado',
    '{0} ER LÅST': '{0} ESTÁ BLOQUEADO',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} hizo {1} puntos. Tienes {2} intentos en el mismo nivel y su vuelo se muestra como una sombra.',
    '{0} forsøg tilbage · slå {1} point': '{0} intentos restantes · supera {1} puntos',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} te desafía a superar {1} puntos. Tienes tres intentos.',
    '{0} låst op for {1} fjer': '{0} desbloqueado por {1} plumas',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} bloqueado. {1}. {2} de {3}. Precio alternativo {4} plumas.',
    '{0} missionsbelønninger': '{0} recompensas de misión',
    '{0} missionsbelønninger er hentet.': '{0} recompensas de misión recogidas.',
    '{0} point til næste medalje': '{0} puntos para la siguiente medalla',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Cuando se cumplan ambos requisitos se abrirá todo el nivel {2}.',
    '{0} · {1} FASTE LIV': '{0} · {1} VIDAS FIJAS',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, bloqueado. Toca para ver el requisito',
    '{0}, åben, personlig rekord {1}': '{0}, abierto, récord personal {1}',
    '{0} · Mål {1}': '{0} · Meta {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} NIVELES · {2}/{3} MISIONES',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} NIVELES · {2}/{3} MIS.',
    '{0} BANER · {1}': '{0} NIVELES · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} ABIERTOS · {2}',
    'DU MANGLER {0} FJER': 'TE FALTAN {0} PLUMAS',
    'BESKYTTET · {0}s': 'PROTEGIDO · {0}s',
    'ÅBN DAGENS MISSIONER': 'ABRIR MISIONES DE HOY',
    'ÅBN GARDEROBE · 17 HELTE': 'ABRIR ARMARIO · 17 HÉROES',
    'ÅNDENDE PORTE': 'PUERTAS QUE RESPIRAN',
    'Åbn dagens missioner': 'Abrir misiones de hoy',
    'Åbn highscore': 'Abrir récords',
    'Åbn indstillinger': 'Abrir ajustes',
    'ÉN CHANCE MERE?': '¿UNA OPORTUNIDAD MÁS?',
    'Sprog': 'Idioma',
    'Automatisk (som telefonen)': 'Automático (como el teléfono)',
    'Dansk': 'Danés', 'Engelsk': 'Inglés', 'Norsk': 'Noruego', 'Svensk': 'Sueco', 'Tysk': 'Alemán', 'Spansk': 'Español', 'Fransk': 'Francés', 'Portugisisk': 'Portugués',
    '+1 FJER': '+1 PLUMA',
    'En ven': 'Un amigo',
    'Dig': 'Tú',
    'REKORD': 'RÉCORD',
    'Topflyvning': 'Vuelo perfecto',
    '{0} point i {1}': '{0} puntos en {1}',
    'en bane': 'un nivel',
    '{0} til trin {1} · {2} stjerner': '{0} para el nivel {1} · {2} estrellas',
    '{0} · {1} stjerner samlet': '{0} · {1} estrellas recogidas',
    '{0} FJER': '{0} PLUMAS',
    'TAP FOR AT FLYVE': 'TOCA PARA VOLAR',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Supera la puntuación de tu amigo en el mismo nivel. Tienes tres intentos y su vuelo fantasma te acompaña.",
    '{0}/{1} BRONZE': '{0}/{1} BRONCE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Consigue bronce (20 puntos) en los {0} niveles básicos para abrir Aventura. Tienes {1}.',
    'SØLV I {0}': 'PLATA EN {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Consigue plata (50 puntos) en {0} para abrir {1}.',
    'LAVAEN FALDER': 'LA LAVA BAJA',
    'GODT GREB · {0}s': 'BUEN AGARRE · {0}s',
    'VINDSTØD · OP': 'RÁFAGA · ARRIBA',
    'VINDSTØD · NED': 'RÁFAGA · ABAJO',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'HIELO RESBALADIZO: GIRA CON TIEMPO · RECOGE CRISTALES DE ESCARCHA',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'CUIDADO CON LAS RÁFAGAS · LAS FLECHAS INDICAN',
    'LAVAEN STIGER · SAML KØLESTEN': 'LA LAVA SUBE · RECOGE PIEDRAS FRÍAS',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'LA LUZ SE APAGA POCO A POCO · RECOGE FAROLILLOS',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'LOS CONTENEDORES SE MUEVEN · CUIDADO CON LAS GAVIOTAS',
    'Fugleklat': 'Caquita',
    'SPIS & KLAT': 'COME Y SUELTA',
    'PARAPLYEN REDDEDE DEM': 'EL PARAGUAS LOS SALVÓ',
    'GULDBIL! ×3': '¡COCHE DORADO! ×3',
    'PLASK!': '¡PLAF!',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'COME · TOCA 💩 PARA ACERTAR ABAJO',
    'Slip en klat': 'Soltar una caquita',
    'Alle helte flyver ens. Vind dem i spillet, eller spar fjer sammen.': 'Todos los héroes vuelan igual. Gánalos en el juego o ahorra plumas.',
    'ÅBN GARDEROBE': 'ABRIR ARMARIO',
    'OP · EVIGT SKJOLD · INGEN REKORDER': 'OP · ESCUDO ETERNO · SIN RÉCORDS',
    'FORSTØR': 'AGRANDAR',
    'FORMINDSK': 'ENCOGER',
    'FORSTØR · POINT ×2': 'AGRANDAR · PUNTOS ×2',
    'FØLG TUNNELEN · HOLD VENSTRE = OP · HØJRE = NED': 'SIGUE EL TÚNEL · IZQUIERDA = SUBIR · DERECHA = BAJAR',
    // Feedback 4. okt.: reden, æg, mærker, eventyr-låse, lyd.
    "Vælg én starthelt efter 10, 20, 30 og 40 ture": "Elige un héroe inicial tras 10, 20, 30 y 40 vuelos",
    "Nå 600 point på én tur": "Consigue 600 puntos en un vuelo",
    "Nå guld i alle tre Classic-baner": "Consigue oro en los tres niveles Classic",
    "Kun fra et æg i reden": "Solo de un huevo en el nido",
    "Kun fra et æg i reden (sjælden)": "Solo de un huevo en el nido (raro)",
    "Æggebert": "Huevobert",
    "ÆGGEBERT": "HUEVOBERT",
    "Vælg Æggebert": "Elige a Huevobert",
    "Klæk alle helte fra rugepladsen": "Eclosiona todos los héroes de la incubadora",
    "KLÆK ALLE": "ECLOSIONA TODOS",
    "Blød rede": "Nido blando",
    "Et sted at lande. Fjer bygger den videre.": "Un lugar para aterrizar. Las plumas lo amplían.",
    "Redningsfjer": "Pluma de rescate",
    "REDNINGSFJER": "PLUMA DE RESCATE",
    "Ét redningsliv på hver tur.": "Una vida de rescate en cada vuelo.",
    "Stærkere magnet": "Imán más fuerte",
    "Magneten trækker 30 % længere.": "El imán atrae un 30 % más lejos.",
    "Varmt skjold": "Escudo cálido",
    "Skjoldet holder 2 sekunder længere.": "El escudo dura 2 segundos más.",
    "Hurtig start": "Inicio rápido",
    "Usårlig med ekstra fart de første 5 sekunder.": "Invencible y más rápido los primeros 5 segundos.",
    "To redningsliv": "Dos vidas de rescate",
    "To redningsliv på hver tur.": "Dos vidas de rescate en cada vuelo.",
    "Guldrede": "Nido dorado",
    "Stjerner giver +1 point de første 10 sekunder.": "Las estrellas dan +1 punto los primeros 10 segundos.",
    "Første flyvetur": "Primer vuelo",
    "Gennemfør din første tur": "Termina tu primer vuelo",
    "Første stjerne": "Primera estrella",
    "Saml din første stjerne": "Recoge tu primera estrella",
    "Første fjer": "Primera pluma",
    "Find din første gyldne fjer": "Encuentra tu primera pluma dorada",
    "Vind din første bronzemedalje": "Gana tu primera medalla de bronce",
    "Ny ven": "Nuevo amigo",
    "Lås din første ekstra helt op": "Desbloquea tu primer héroe extra",
    "Sølv": "Plata",
    "Vind sølv på en bane": "Gana plata en un nivel",
    "Guld": "Oro",
    "Vind guld på en bane": "Gana oro en un nivel",
    "I flow": "En racha",
    "Nå en streak på 10": "Consigue una racha de 10",
    "Ustoppelig": "Imparable",
    "Nå en streak på 25": "Consigue una racha de 25",
    "Stjerneregn": "Lluvia de estrellas",
    "Saml 100 stjerner på én tur": "Recoge 100 estrellas en un vuelo",
    "Højtflyver": "Altos vuelos",
    "Få 500 point på én tur": "Consigue 500 puntos en un vuelo",
    "Udholdenhed": "Resistencia",
    "Flyv 3 minutter på én tur": "Vuela 3 minutos en un vuelo",
    "Fejlfri": "Impecable",
    "Guld uden redningsliv eller redningsspin": "Oro sin vidas ni giros de rescate",
    "Klassiker": "Clásico",
    "Bronze på alle Classic-baner": "Bronce en todos los niveles Classic",
    "Skorstensfejer": "Deshollinador",
    "Bronze på alle Flappy-baner": "Bronce en todos los niveles Flappy",
    "Tunnelrytter": "Jinete del túnel",
    "Bronze på alle Tunnel-baner": "Bronce en todos los niveles Tunnel",
    "Eventyrer": "Aventurero",
    "Lås Eventyr op": "Desbloquea Aventura",
    "Verdensflyver": "Volador mundial",
    "Sølv på alle seks eventyrbaner": "Plata en los seis niveles de aventura",
    "Lavalord": "Señor de la lava",
    "Guld på Vulkanen": "Oro en el Volcán",
    "Mesterskytte": "Tirador experto",
    "10 træffere i træk i Fugleklat": "10 aciertos seguidos en Caquita",
    "Publikumsvølge": "Ola del público",
    "Kom forbi tre bolde i én koncertbølge": "Supera tres pelotas en una ola del concierto",
    "Fri af rovfuglen": "Libre del halcón",
    "Undvig den varslede rovfugl": "Esquiva al ave rapaz anunciada",
    "Undvig en flyvende genstand i storm": "Esquiva un objeto volador en la tormenta",
    "Portløber": "Corredor de portales",
    "Klar alle tre porte i én Sky Relay-runde": "Supera los tres portales en una ronda de Sky Relay",
    "Ekstranummer": "Bis",
    "Sølv i Neon Encore": "Plata en Neon Encore",
    "Pakket ind": "Envuelto",
    "Bliv fanget af edderkoppen": "Deja que te atrape la araña",
    "Snack": "Tentempié",
    "Bliv fanget af slangen": "Deja que te atrape la serpiente",
    "Grillkylling": "Pollo asado",
    "Dø 50 gange i alt": "Choca 50 veces en total",
    "Flokken": "La bandada",
    "Lås 10 helte op": "Desbloquea 10 héroes",
    "Redebygger": "Constructor de nidos",
    "Saml 100 fjer i alt": "Recoge 100 plumas en total",
    "GAME OVER": "FIN DEL JUEGO",
    "MAGNET": "IMÁN",
    "Få bronze på alle tre Classic-baner for at åbne Havnen.": "Consigue bronce en los tres niveles Classic para abrir El Puerto.",
    "Få bronze på alle tre Flappy-baner for at åbne Nattebyen.": "Consigue bronce en los tres niveles Flappy para abrir La Ciudad Nocturna.",
    "Få bronze på alle tre Tunnel-baner for at åbne Vindmøller.": "Consigue bronce en los tres niveles Tunnel para abrir Los Molinos.",
    "Få sølv i to af Havnen, Nattebyen og Vindmøller for at åbne Vulkanen.": "Consigue plata en dos de El Puerto, La Ciudad Nocturna y Los Molinos para abrir El Volcán.",
    "GULD PÅ EN BANE": "ORO EN UN NIVEL",
    "SØLV I VULKANEN": "PLATA EN EL VOLCÁN",
    "Få sølv i Vulkanen og guld på én af grundbanerne for at åbne Isbjerget.": "Consigue plata en El Volcán y oro en un nivel básico para abrir El Iceberg.",
    "SØLV I ISBJERGET": "PLATA EN EL ICEBERG",
    "Få sølv i Isbjerget for at åbne Fugleklat.": "Consigue plata en El Iceberg para abrir Caquita.",
    "ÅBNER MED EVENTYR": "SE ABRE CON AVENTURA",
    "Testbanerne åbner sammen med den første eventyrverden.": "Los niveles de prueba se abren con el primer mundo de aventura.",
    "HEMMELIG": "SECRETO",
    "LÅST": "BLOQUEADO",
    "Låst. Tryk på helten for at se, hvordan du får den.": "Bloqueado. Toca al héroe para ver cómo conseguirlo.",
    "En hemmelig helt. Den hører til et særligt pilotnavn.": "Un héroe secreto. Pertenece a un nombre de piloto especial.",
    "Du kan vælge en starthelt nu.": "Ya puedes elegir un héroe inicial.",
    "Eller klæk den fra et æg, når reden har nået trin 4.": "O hazlo eclosionar de un huevo cuando el nido llegue al paso 4.",
    "REDEN ER FÆRDIG": "EL NIDO ESTÁ TERMINADO",
    "Alle syv trin er bygget. Flot!": "Los siete pasos están construidos. ¡Genial!",
    "Du fandt et æg! Det ligger i reden og ruger.": "¡Encontraste un huevo! Se está incubando en el nido.",
    "VÆLG EN NY HELT": "ELIGE UN NUEVO HÉROE",
    "Du må vælge én. De andre kan vælges efter 10 ture mere.": "Elige uno. Los demás tras 10 vuelos más.",
    "SENERE": "MÁS TARDE",
    "Én tur om dagen giver fjer": "Un vuelo al día da plumas",
    "Ruger et tilfældigt æg. Saml stjerner, så klækker det.": "Incubando un huevo aleatorio. Recoge estrellas y eclosionará.",
    "TOM": "VACÍO",
    "ALLE KLÆKKET": "TODOS ECLOSIONADOS",
    "Alle helte er klækket": "Todos los héroes han eclosionado",
    "fjer": "plumas",
    "sjælden": "raro",
    "Et æg ligger i reden. Saml stjerner, så klækker det.": "Hay un huevo en el nido. Recoge estrellas y eclosionará.",
    "ER DU SIKKER? TRYK IGEN": "¿SEGURO? TOCA OTRA VEZ",
    "GLOBAL HIGHSCORE": "PUNTUACIÓN GLOBAL",
    "Du mangler fjer. Flyv en tur, og klar dagens missioner.": "Te faltan plumas. Vuela y completa las misiones de hoy.",
    "{0}/3 CLASSIC": "{0}/3 CLASSIC",
    "{0}/3 FLAPPY": "{0}/3 FLAPPY",
    "{0}/3 TUNNEL": "{0}/3 TUNNEL",
    "SØLV {0}/2": "PLATA {0}/2",
    "LÅST · {0}/{1}": "BLOQUEADO · {0}/{1}",
    "Vælg den som starthelt efter {0} ture. Du har fløjet {1}.": "Elígelo como héroe inicial tras {0} vuelos. Llevas {1}.",
    "Klæk alle helte fra rugepladsen. {0}/{1} klækket.": "Eclosiona todos los héroes. {0}/{1} eclosionados.",
    "Bedrift: {0} ({1}/{2}).": "Hazaña: {0} ({1}/{2}).",
    "Eller klæk den fra et æg i reden: sikret æg {0} fjer.": "O hazlo eclosionar de un huevo: huevo elegido {0} plumas.",
    "Du har {0} fjer. Fjer får du af dagens missioner, en tur om dagen og sjældne fjer i banerne.": "Tienes {0} plumas. Las consigues con las misiones del día, un vuelo diario y plumas raras en los niveles.",
    "BYG · {0} FJER": "CONSTRUIR · {0} PLUMAS",
    "BYG · 20 FJER": "CONSTRUIR · 20 PLUMAS",
    "MANGLER {0} FJER": "FALTAN {0} PLUMAS",
    "{0} TURE FLØJET": "{0} VUELOS",
    "{0} er din nu": "{0} ya es tuyo",
    "Ægget klækkede: {0}!": "El huevo eclosionó: ¡{0}!",
    "{0} er klækket og venter i garderoben": "{0} ha eclosionado y te espera en el armario",
    "Ægget: {0}/{1} stjerner": "El huevo: {0}/{1} estrellas",
    "{0} fjer fundet": "{0} plumas encontradas",
    "Dag {0} i træk: +{1} fjer": "Día {0} seguido: +{1} plumas",
    "Reden: {0}/{1} til {2}": "Nido: {0}/{1} para {2}",
    "Nyt mærke: {0}": "Nueva insignia: {0}",
    "{0} dage i træk": "{0} días seguidos",
    "{0}/{1} STJERNER": "{0}/{1} ESTRELLAS",
    "Ruger: {0}": "Incubando: {0}",
    "{0} helte kan stadig klækkes": "Aún pueden eclosionar {0} héroes",
    "TILFÆLDIGT ÆG · {0} FJER": "HUEVO ALEATORIO · {0} PLUMAS",
    "SIKRET ÆG · {0} FJER": "HUEVO ELEGIDO · {0} PLUMAS",
    "TILFÆLDIGT ÆG": "HUEVO ALEATORIO",
    "SIKRET ÆG": "HUEVO ELEGIDO",
    "Et sikret æg med {0} ligger i reden": "Un huevo elegido con {0} está en el nido",
    "Reden er bygget: {0}": "Nido construido: {0}",
    "Dag {0} i træk · +{1} fjer til reden": "Día {0} seguido · +{1} plumas para el nido",
    "Bert The Bird – flyvespil og præcisionsverdener": "Bert The Bird – juego de vuelo y mundos de precisión",
    "PAUSE": "PAUSA",
    "REDEN": "EL NIDO",
    "Reden": "El nido",
    "Åbn reden": "Abrir el nido",
    "Luk reden": "Cerrar el nido",
    "Redens trin": "Pasos del nido",
    "NÆSTE TRIN": "SIGUIENTE PASO",
    "RUGEPLADSEN": "LA INCUBADORA",
    "FLYV HVER DAG": "VUELA CADA DÍA",
    "MÆRKER": "INSIGNIAS",
    "Fjer bygger reden. Hvert trin kan mærkes i spillet. Efter døden kan du bruge 12 fjer på ét redningsspin.": "Las plumas construyen el nido. Cada paso se nota en el juego. Tras chocar puedes gastar 12 plumas en un giro de rescate.",
    "Forrige helte": "Héroes anteriores",
    "Næste helte": "Siguientes héroes",
    "Musikstyrke": "Volumen de la música",
    "Lydstyrke for effekter": "Volumen de efectos",
    "Vælg helt til sikret æg": "Elige héroe para el huevo elegido",
    "Banens grafik kunne ikke indlæses.": "No se pudieron cargar los gráficos del nivel.",
    "Spillet kunne ikke indlæses. Prøv igen.": "No se pudo cargar el juego. Inténtalo de nuevo.",
    "NY HELT: {0} · {1}": "NUEVO HÉROE: {0} · {1}",
    "Klæk den fra et æg i reden: sikret æg {0} fjer.": "Hazlo eclosionar de un huevo: huevo elegido {0} plumas.",
    "Klæk den fra et æg, når reden har nået trin 4.": "Hazlo eclosionar de un huevo cuando el nido llegue al paso 4.",
    // Udfordringer (10. okt.)
    "Få 40 point uden redningsliv": "Consigue 40 puntos sin vida de rescate",
    "Få 80 point uden redningsliv": "Consigue 80 puntos sin vida de rescate",
    "Find en gylden fjer i en bane": "Encuentra una pluma dorada en un nivel",
    "Få 60 point uden at tage en power-up": "Consigue 60 puntos sin coger potenciadores",
    "Saml 400 stjerner i denne uge": "Recoge 400 estrellas esta semana",
    "Flyv 30 ture i denne uge": "Haz 30 vuelos esta semana",
    "Guld på 2 forskellige baner i denne uge": "Oro en 2 niveles distintos esta semana",
    "Slå din egen rekord 3 gange": "Supera tu récord 3 veces",
    "Flyv på 6 forskellige baner": "Vuela en 6 niveles distintos",
    "Flyv 30 minutter i denne uge": "Vuela 30 minutos esta semana",
    "Lynhurtig: styrt inden for 1 sekund": "Rapidísimo: choca en menos de 1 segundo",
    "Svaret på alt: præcis 42 point": "La respuesta a todo: exactamente 42 puntos",
    "Natteravn: flyv mellem midnat og kl. 4": "Búho nocturno: vuela entre medianoche y las 4",
    "Tålmodig: 60 sekunder uden en eneste stjerne": "Paciente: 60 segundos sin una sola estrella",
    "Sultestrejke: 30 sekunder og 0 stjerner": "Huelga de hambre: 30 segundos y 0 estrellas",
    "Jo større de er: styrt mens du er forstørret": "Cuanto más grandes: choca mientras eres grande",
    "Juleflyver: flyv juleaften": "Vuelo navideño: vuela en Nochebuena",
    "Hattrick: tre ture i træk med samme point": "Triplete: tres vuelos seguidos con la misma puntuación",
    "Garderobe-gal: flyv med 7 forskellige helte": "Fan del armario: vuela con 7 héroes distintos",
    "Maraton: 10 minutter på én tur": "Maratón: 10 minutos en un vuelo",
    "Ørkenrotte: 100 ture i Desert": "Rata del desierto: 100 vuelos en Desert",
    "Halvtreds: en streak på 50": "Cincuenta: una racha de 50",
    "Flappy-mester: 500 point i Flappy Bert": "Maestro Flappy: 500 puntos en Flappy Bert",
    "Bonk-serie: 5 styrt på 2 minutter": "Racha de golpes: 5 choques en 2 minutos",
    "Edderkoppens ven: fanget 10 gange": "Amigo de la araña: atrapado 10 veces",
    "Saml {0} stjerner i dag": "Recoge {0} estrellas hoy",
    "Flyv {0} minutter i alt i dag": "Vuela {0} minutos en total hoy",
    "Nå en streak på {0}": "Consigue una racha de {0}",
    "Flyv {0} ture i dag": "Haz {0} vuelos hoy",
    "Få {0} point på én tur": "Consigue {0} puntos en un vuelo",
    "Tag {0} power-ups i dag": "Coge {0} potenciadores hoy",
    "Flyv {0} sekunder på én tur": "Vuela {0} segundos en un vuelo",
    "Bronze i {0} i dag": "Bronce en {0} hoy",
    "Sølv i {0} i dag": "Plata en {0} hoy",
    "Guld i {0} i dag": "Oro en {0} hoy",
    "Tur nr. {0}": "Vuelo n.º {0}",
    "{0} stjerner i alt": "{0} estrellas en total",
    "{0} fjer samlet i alt": "{0} plumas en total",
    "{0} helte": "{0} héroes",
    "{0} mærker": "{0} insignias",
    "Reden på trin {0}": "Nido en el paso {0}",
    "{0} æg klækket": "{0} huevos eclosionados",
    "{0}: guld": "{0}: oro",
    "{0}: 200 point": "{0}: 200 puntos",
    "{0}: 60 point uden redning og power-ups": "{0}: 60 puntos sin rescate ni potenciadores",
    "??? (hemmelig udfordring)": "??? (desafío secreto)",
    "Tæt på: {0} ({1}/{2})": "Casi: {0} ({1}/{2})",
    "+{0} fjer · {1}": "+{0} plumas · {1}",
    "UGENS UDFORDRINGER": "DESAFÍOS DE LA SEMANA",
    "UDFORDRINGER": "DESAFÍOS",
    "MILEPÆLE": "HITOS",
    "MESTERSKAB": "MAESTRÍA",
    "HEMMELIGE": "SECRETOS",
    "NIVEAU {0}!": "¡NIVEL {0}!",
    "HVOR SKAL BERT HEN?": "¿ADÓNDE VA BERT?",
    "DIN REJSE": "TU VIAJE",
    "Ørkenen": "El desierto",
    "Junglen": "La jungla",
    "Himlen": "El cielo",
    "Byen": "La ciudad",
    "Tunnelen": "El túnel",
    "Natten": "La noche",
    "Vinden": "El viento",
    "Isen": "El hielo",
    "Fugleklat-øen": "Isla Caquita",
    "Spejlbanen": "Nivel espejo",
    "GLID & OPVIND · TESTBANE": "PLANEA Y CORRIENTES · NIVEL DE PRUEBA",
    "GLID & OPVIND": "PLANEA Y CORRIENTES",
    "Svæv": "Planear",
    "Vælg et andet navn": "Elige otro nombre",
    "FLOK & FORMATION · TESTBANE": "BANDADA Y FORMACIÓN · NIVEL DE PRUEBA",
    "FLOK & FORMATION": "BANDADA Y FORMACIÓN",
    "Fuglesværm": "Bandada",
    "Klistermærke fundet! Se det i albummet i reden": "¡Pegatina encontrada! Mírala en el álbum del nido",
    "KLISTERMÆRKER": "PEGATINAS",
    "Fem skjulte klistermærker i hver bane. Hold øje, mens du flyver.": "Cinco pegatinas escondidas en cada nivel. Mantén los ojos abiertos mientras vuelas.",
    "Flokken": "La Bandada",
    "UDFORDRER": "RETADOR",
    "NYT": "NUEVO",
    "FLOKKEN": "LA BANDADA",
    "ALLE MOD ALLE I EN STOR HIMMEL": "TODOS CONTRA TODOS EN UN GRAN CIELO",
});
