/* Español. Las claves son los textos daneses originales. */
window.BertI18n.register('es', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · VUELA UNA RONDA PARA MARCAR TU PRIMERA PUNTUACIÓN',
    ' · MÆRKE: {0}': ' · INSIGNIA: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · JUEGA UN DUELO CON AMIGOS PARA TENER UN RIVAL',
    '+{0} fjer til reden': '+{0} plumas para el nido',
    '+{0} fjer · {1} låst op': '+{0} plumas · {1} desbloqueado',
    '0 / 0 POINT': '0 / 0 PUNTOS',
    '20 point til bronze': '20 puntos para el bronce',
    '3 SPILFORMER · 9 BANER': '3 MODOS · 9 NIVELES',
    '3 baner · hold op/ned': '3 niveles · mantén arriba/abajo',
    '3 baner · præcision': '3 niveles · precisión',
    '3 baner · tap': '3 niveles · toca',
    '9 baner · nye verdener': '9 niveles · nuevos mundos',
    'ACCEPTÉR': 'ACEPTAR',
    'AFSLUT TUREN': 'TERMINAR LA RONDA',
    'Alle baner': 'Todos los niveles',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Todos los héroes tienen la misma velocidad y zona de impacto. Gánalos jugando o ahorra plumas.',
    'Alle pointkrav i trin {0} er klaret.': 'Todos los requisitos de puntos del nivel {0} están cumplidos.',
    'Alle spil': 'Todos los juegos',
    'Alle tider': 'Siempre',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Has usado los tres intentos. Pide a tu amigo un nuevo duelo.',
    'BANEN ER LÅST': 'NIVEL BLOQUEADO',
    'BEKRÆFT · {0} FJER': 'CONFIRMAR · {0} PLUMAS',
    'BERTS GARDEROBE': 'EL ARMARIO DE BERT',
    'BERTS REDE': 'EL NIDO DE BERT',
    'BERTS REDNINGSREDE': 'EL NIDO DE RESCATE DE BERT',
    'BEVÆGELIGE TÅRNE': 'TORRES MÓVILES',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} estrellas · solo récord local del evento',
    'Bane': 'Nivel',
    'Banen er låst': 'El nivel está bloqueado',
    'Bedst på level {0} · {1}': 'Mejor en el nivel {0} · {1}',
    'Bert The Bird appikon': 'Icono de la app Bert The Bird',
    'Bert The Bird bliver installeret': 'Bert The Bird se está instalando',
    'Bert The Bird er installeret': 'Bert The Bird está instalado',
    'Bert The Bird spilcanvas': 'Área de juego de Bert The Bird',
    'Bert flyver': 'Bert volando',
    'Bevægelse i koncertlys': 'Movimiento en las luces del concierto',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Gasta 12 plumas en un giro. Cinco casillas devuelven a Bert al nivel. Una casilla termina la ronda.',
    'DAGENS MISSIONER': 'MISIONES DE HOY',
    'DAGENS RUTE': 'RUTA DE HOY',
    'DAGENS RUTE · MÅL {0}': 'RUTA DE HOY · META {0}',
    'DENNE TUR': 'ESTA RONDA',
    'DIN FLYVETUR': 'TU VUELO',
    'DIN HELT': 'TU HÉROE',
    'DIN SALDO': 'TU SALDO',
    'DINE VENNEDUELLER': 'TUS DUELOS CON AMIGOS',
    'DREJ TELEFONEN': 'GIRA EL TELÉFONO',
    'DU ER UDFORDRET': 'TE HAN DESAFIADO',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'GANASTE EL DUELO · devuelve el desafío · {0} estrellas',
    'Den sjældneste fugl · køb for fjer': 'El pájaro más raro · compra con plumas',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Este nivel no se puede usar para duelos clasificados con amigos.',
    'Dit navn': 'Tu nombre',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Tu nombre aparece en la clasificación y junto a tus récords.',
    'Du mangler fjer fra dagens missioner': 'Te faltan plumas de las misiones de hoy',
    'EDM-VERDEN · LOKALT': 'MUNDO EDM · LOCAL',
    'EPISK': 'ÉPICO',
    'EVENT · BIRD RUN · TESTBANE': 'EVENTO · BIRD RUN · NIVEL DE PRUEBA',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENTO · NEON ENCORE · NIVEL DE PRUEBA',
    'EVENT · STORMLINE · TESTBANE': 'EVENTO · STORMLINE · NIVEL DE PRUEBA',
    'EVENTYR': 'AVENTURA',
    'EVENTYR · {0}': 'AVENTURA · {0}',
    'Episk helt · kun til dig · valgt': 'Héroe épico · solo para ti · elegido',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Héroe épico · solo para ti. Toca para elegir.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Una vida de rescate permanente absorbe un choque en cada ronda. Tras un choque también puedes gastar 12 plumas en un giro de rescate. Siempre puedes seguir jugando sin energía ni esperas.',
    'FAST + BEVÆGELIG': 'FIJO + MÓVIL',
    'FASTE TÅRNE': 'TORRES FIJAS',
    'FJER': 'PLUMAS',
    'FJER RETUR': 'PLUMAS DEVUELTAS',
    'FJER · PRIMÆRT VINDES I SPILLET': 'PLUMAS · SE GANAN SOBRE TODO JUGANDO',
    'FLYV': 'VOLAR',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'VUELA POR TRES PUERTAS DE NUBES · GOLPEA LA PLACA DORADA · IZQUIERDA SUBE · DERECHA BAJA',
    'FLYV IGEN': 'VOLAR OTRA VEZ',
    'FLYV VIDERE': 'SEGUIR VOLANDO',
    'FLYVETUREN ER SAT PÅ PAUSE': 'EL VUELO ESTÁ EN PAUSA',
    'FODBOLD-BERT': 'BERT FUTBOLERO',
    'FOKUS': 'FOCO',
    'FOKUS OM {0}': 'FOCO EN {0}',
    'FORBI': 'FALLADO',
    'FORBI GULDPLADEN': 'FALLASTE LA PLACA DORADA',
    'FORSTÅET': 'ENTENDIDO',
    'FORTRYD': 'CANCELAR',
    'FORTSÆT': 'CONTINUAR',
    'FRI AF ROVFUGLEN': 'LIBRE DE LA RAPAZ',
    'FUGL BAGFRA': 'PÁJARO POR DETRÁS',
    'FUGLEVERDEN · LOKALT': 'MUNDO DE PÁJAROS · LOCAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Cuatro mundos de evento locales gratis sin clasificación global',
    'Flyv samlet i 3 minutter': 'Vuela 3 minutos en total',
    'Flyvetid': 'Tiempo de vuelo',
    'Fodbold-Bert': 'Bert Futbolero',
    'Forbindelsen er tilbage': 'La conexión ha vuelto',
    'Fremgang mod oplåsning': 'Progreso para desbloquear',
    'Fugle · rovfugl': 'Pájaros · rapaz',
    'FÆRDIG': 'LISTO',
    'FØLG STJERNESTRØMMEN': 'SIGUE LA CORRIENTE DE ESTRELLAS',
    'FØLGER DIG KORT · {0}s': 'TE SIGUE UN MOMENTO · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · LA RONDA TERMINA',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} RESULTADOS',
    'GODT RAMT': 'BUEN GOLPE',
    'GRATIS REDNING': 'RESCATE GRATIS',
    'GRUNDFLYVNING': 'VUELO BÁSICO',
    'GULD': 'ORO',
    'GULD-BERT': 'BERT DORADO',
    'Guld-Bert': 'Bert Dorado',
    'HAV BERT PÅ STARTSKÆRMEN': 'TEN A BERT EN LA PANTALLA DE INICIO',
    'HAVNEN': 'EL PUERTO',
    'Havnen': 'El Puerto',
    'HENT FJER': 'RECOGER PLUMAS',
    'HENT SPILLET': 'DESCARGAR EL JUEGO',
    'HENT +{0}': 'RECOGER +{0}',
    '+{0} FJER': '+{0} PLUMAS',
    'HENTER RESULTATER …': 'CARGANDO RESULTADOS …',
    'HENTET': 'RECOGIDO',
    'HOLD OP/NED': 'MANTÉN ARRIBA/ABAJO',
    'HOVEDMENU': 'MENÚ PRINCIPAL',
    'HVAD HEDDER DU?': '¿CÓMO TE LLAMAS?',
    'HVORDAN VIL DU FLYVE?': '¿CÓMO QUIERES VOLAR?',
    'HYPERFART': 'HIPERVELOCIDAD',
    'Haptisk feedback': 'Respuesta háptica',
    'Har altid en pakke med · køb for fjer': 'Siempre lleva un paquete · compra con plumas',
    'Hele Bert The Bird er lavet til landscape.': 'Bert The Bird está hecho para pantalla horizontal.',
    'Hemmelig helt': 'Héroe secreto',
    'Hent en mission syv dage i træk': 'Recoge una misión siete días seguidos',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Recoge {0} recompensas de misión en total; tienes {1}.',
    'Henter resultater …': 'Cargando resultados …',
    'Høj fart': 'Alta velocidad',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'En Safari: Compartir → Añadir a pantalla de inicio. Espera a «Listo para jugar sin conexión» y abre el icono una vez con internet antes de probar el modo avión.',
    'I dag': 'Hoy',
    'IKKE NU': 'AHORA NO',
    'INDSTILLINGER': 'AJUSTES',
    'INSTALLÉR WEBAPP': 'INSTALAR WEB APP',
    'ISTAPPER & SPIDSER': 'CARÁMBANOS Y PÚAS',
    'Isbjerget': 'El Iceberg',
    'ISBJERGET': 'EL ICEBERG',
    'Indlæser originale Unity-assets …': 'Cargando recursos originales de Unity …',
    'Ingen rekord endnu': 'Aún no hay récord',
    'Installér som webapp': 'Instalar como web app',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Instala desde el menú del navegador. Espera a «Listo para jugar sin conexión» y abre la app una vez con internet antes de probar sin conexión.',
    'KANT': 'BORDE',
    'KLAR DAGENS MÅL': 'CUMPLE LA META DE HOY',
    'KLARET': 'HECHO',
    'KONCERT · TESTBANE': 'CONCIERTO · NIVEL DE PRUEBA',
    'KRANER & MÅGER': 'GRÚAS Y GAVIOTAS',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'SOLO TUS RESULTADOS LOCALES · LA TABLA ONLINE NO ESTÁ DISPONIBLE',
    'KVALIFIKATIONSBANEN': 'EL NIVEL CLASIFICATORIO',
    'Klar dagens rute': 'Completa la ruta de hoy',
    'Klar dagens rute én gang': 'Completa la ruta de hoy una vez',
    'Klar hele forrige trin og missionskravet først': 'Completa primero todo el nivel anterior y el requisito de misiones',
    'Klar hele trin {0}: {1}.': 'Completa todo el nivel {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Completa el nivel clasificatorio para abrir este desafío.',
    'Klar til offline-spil': 'Listo para jugar sin conexión',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Supera al menos tres bolas en una ola de concierto',
    'KØB': 'COMPRAR',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'COMPRA VIDAS FIJAS O UN GIRO DE RESCATE',
    'KØB · {0} FJER': 'COMPRAR · {0} PLUMAS',
    'KØBT': 'COMPRADO',
    'LAVA & BOBLER': 'LAVA Y BURBUJAS',
    'LEVENDE FORHINDRINGER': 'OBSTÁCULOS VIVOS',
    'LEVERING': 'ENTREGA',
    'LYD & FEEDBACK': 'SONIDO Y RESPUESTA',
    'LYDLØS': 'SILENCIOSO',
    'Level 1 · Mål 30': 'Nivel 1 · Meta 30',
    'Luk': 'Cerrar',
    'Luk garderoben': 'Cerrar el armario',
    'Lydeffekter': 'Efectos de sonido',
    'Lydløs og hurtig · køb for fjer': 'Silencioso y rápido · compra con plumas',
    'LÅS OP · 20 FJER': 'DESBLOQUEAR · 20 PLUMAS',
    'LÅS OP · {0} FJER': 'DESBLOQUEAR · {0} PLUMAS',
    'LÅST BANE': 'NIVEL BLOQUEADO',
    'LÅST OP': 'DESBLOQUEADO',
    'LÆR KORRIDOREN': 'APRENDE EL CORREDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Desbloqueado. Toca el personaje para elegirlo.',
    'MAKS LÅST OP': 'MÁXIMO DESBLOQUEADO',
    'MINISPIL · SKY RELAY · LOKALT': 'MINIJUEGO · SKY RELAY · LOCAL',
    'MISSIONER': 'MISIONES',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MÓVIL: LADO IZQUIERDO = ARRIBA · LADO DERECHO = ABAJO',
    'Missioner': 'Misiones',
    'Mod vinden': 'Contra el viento',
    'Musik': 'Música',
    'MÅGEN MOGENS': 'MOGENS LA GAVIOTA',
    'Mågen Mogens': 'Mogens la Gaviota',
    'MÅL: 3 BOLDE': 'META: 3 BOLAS',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'META: SUPERA UNA OLA CON TRES BOLAS · IZQUIERDA SUBE · DERECHA BAJA',
    'MÅL: ROVFUGL': 'META: RAPAZ',
    'MÅL: STORM': 'META: TORMENTA',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'META: ESQUIVA UNA RAPAZ · IZQUIERDA SUBE · DERECHA BAJA',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'META: ESQUIVA UN OBJETO DE LA TORMENTA · SIGUE BANDERAS Y HOJAS',
    'MÆRKE VUNDET': 'INSIGNIA GANADA',
    'MØRKE & SKILTE': 'OSCURIDAD Y LETREROS',
    'Måned': 'Mes',
    'NED': 'ABAJO',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} estrellas · solo récord local del evento',
    'NINJA-BERT': 'BERT NINJA',
    'Ninja-Bert': 'Bert Ninja',
    'NIVEAU {0}! · {1}': '¡NIVEL {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING DESBLOQUEADO · VUELO PERFECTO',
    'NY BANE': 'NIVEL NUEVO',
    'NY REKORD!': '¡NUEVO RÉCORD!',
    'NYE VERDENER': 'NUEVOS MUNDOS',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NUEVO NIVEL: LOS TRES NIVELES ESTÁN ABIERTOS · {0} estrellas recogidas',
    'NATTEBYEN': 'LA CIUDAD NOCTURNA',
    'Nattebyen': 'La Ciudad Nocturna',
    'Ny mobilversion indlæst': 'Nueva versión móvil cargada',
    'Nyt redningsliv låst op': 'Nueva vida de rescate desbloqueada',
    'NÆSTE UDFORDRING': 'SIGUIENTE DESAFÍO',
    'Nå 120 point i Desert': 'Llega a 120 puntos en Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Llega a 180 puntos sin fallar una estrella ni chocar',
    'Nå 300 point på én tur': 'Llega a 300 puntos en una ronda',
    'Nå bronze i Jungle uden redning': 'Consigue bronce en Jungle sin rescate',
    'Nå bronze i alle ni baner': 'Consigue bronce en los nueve niveles',
    'Nå bronze i alle tre Classic-baner': 'Consigue bronce en los tres niveles Classic',
    'Nå en streak på 12': 'Consigue una racha de 12',
    'OMVENDT STYRING': 'CONTROLES INVERTIDOS',
    'OP': 'ARRIBA',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'El modo sin conexión aún no está listo · conéctate a internet',
    'PAKKE-BERT': 'BERT PAQUETE',
    'Pakke-Bert': 'Bert Paquete',
    'PERMANENT REDE-FORDEL': 'VENTAJA PERMANENTE DEL NIDO',
    'PERSONLIG REKORD': 'RÉCORD PERSONAL',
    'PILOTER': 'PILOTOS',
    'POINT ×2': 'PUNTOS ×2',
    'PORTE & KLOKKE': 'PUERTAS Y CAMPANA',
    'PRINSESSE SØS': 'PRINCESA SØS',
    'Prinsesse Søs': 'Princesa Søs',
    'PRÆCISION': 'PRECISIÓN',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'VUELO DE PRECISIÓN · PRUEBA LOCAL',
    'PRÆCISIONSRUTE · LOKALT': 'RUTA DE PRECISIÓN · LOCAL',
    'PUBLIKUMSVØLGE': 'OLA DEL PÚBLICO',
    'Pause spillet': 'Pausar el juego',
    'Periode': 'Periodo',
    'Personlig highscore': 'Récord personal',
    'Pilotnavn': 'Nombre de piloto',
    'Pingvin med jetpack · køb for fjer': 'Pingüino con jetpack · compra con plumas',
    'Point': 'Puntos',
    'Porte · vindklokke': 'Puertas · campanilla',
    'PORT {0}/3': 'PUERTA {0}/3',
    'PORT {0}/3 · {1}': 'PUERTA {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RONDA {0} · PUERTA {1}/3',
    'KLANG! +{0} · RUNDE {1}': '¡DING! +{0} · RONDA {1}',
    'Præcisionsflyvning': 'Vuelo de precisión',
    'RAM GULDPLADEN': 'GOLPEA LA PLACA DORADA',
    'RAMT': 'ACERTADO',
    'RANGLISTE': 'CLASIFICACIÓN',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'RESCATADO · TUS 12 PLUMAS VUELVEN',
    'REDDET · {0}': 'RESCATADO · {0}',
    'REDNINGSLIV': 'VIDA DE RESCATE',
    'REDNINGSLIV 0/3': 'VIDAS DE RESCATE 0/3',
    'REDNINGSLIV {0}/{1}': 'VIDAS DE RESCATE {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'EL NIDO DE RESCATE GIRA …',
    'REDNINGSSPIN': 'GIRO DE RESCATE',
    'RENT GENNEM': 'LIMPIO',
    'RIGGE & BOLDE': 'ESTRUCTURAS Y BOLAS',
    'ROTORER & BØJER': 'ROTORES Y BOYAS',
    'ROVFUGL': 'RAPAZ',
    'ROVFUGL BAGFRA': 'RAPAZ POR DETRÁS',
    'FUGL': 'PÁJARO',
    'BAGFRA': 'POR DETRÁS',
    'FORFRA': 'DE FRENTE',
    'RUTEN AFSLUTTET': 'RUTA TERMINADA',
    'Redningsliv tilbage': 'Vidas de rescate restantes',
    'Rigge · bolde': 'Estructuras · bolas',
    'SJÆLDEN': 'RARO',
    'SKIFT BANE': 'CAMBIAR NIVEL',
    'SKJOLD': 'ESCUDO',
    'SKJOLD BRUGT · 2s': 'ESCUDO USADO · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · GOLPEASTE {0} DE LA PUERTA {1} · 0 PUNTOS · OTRA VEZ',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 PUNTOS · OTRA VEZ',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 PUERTAS · {1}% PRECISIÓN · SOLO LOCAL',
    'TOPPEN': 'LA PARTE SUPERIOR',
    'BUNDEN': 'LA PARTE INFERIOR',
    'SKYRING RAMT': 'ANILLO DE NUBE GOLPEADO',
    'SPIL': 'JUGAR',
    'SPIL KVALIFIKATION': 'JUGAR CLASIFICACIÓN',
    'SPIL →': 'JUGAR →',
    'SPIL {0}': 'JUGAR {0}',
    'SPIN FOR AT SE DIN REDNING': 'GIRA PARA VER TU RESCATE',
    'SPIN · 12 FJER': 'GIRAR · 12 PLUMAS',
    'SPIN · {0} FJER': 'GIRAR · {0} PLUMAS',
    'START FORFRA': 'EMPEZAR DE NUEVO',
    'STARTBANE': 'NIVEL INICIAL',
    'STJERNEREGN': 'LLUVIA DE ESTRELLAS',
    'STIGER': 'SUBE',
    'DYKKER': 'BAJA EN PICADO',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · VIENTO Y COSAS VOLANDO · {0} estrellas · solo récord local del evento',
    'STREAK REDDET · GUARD BRUGT': 'RACHA SALVADA · GUARD USADO',
    'STORMPILOT': 'PILOTO DE TORMENTA',
    'Saml 20 stjerner til reden': 'Recoge 20 estrellas para el nido',
    'Saml 250 stjerner i alt': 'Recoge 250 estrellas en total',
    'Scoretype': 'Tipo de puntuación',
    'Skriv dit navn': 'Escribe tu nombre',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Juega Bird Run, un mundo local de pájaros. Esquiva la rapaz anunciada. Sin clasificación global.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Juega Neon Encore, un mundo local de concierto. Sobrevive a una ola completa con al menos tres bolas. Sin clasificación global.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Juega Sky Relay, una ruta local corta de precisión por tres anillos de nubes. Puedes chocar arriba y abajo del anillo. Golpea la placa dorada de la campanilla. Sin clasificación global.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Juega Stormline, un mundo local de viento. Esquiva un objeto volador en la tormenta. Sin clasificación global.',
    'Spiltype': 'Modo de juego',
    'Start Quick Flight': 'Iniciar Quick Flight',
    'Starthelt · Klar til at flyve': 'Héroe inicial · Listo para volar',
    'Starthelt': 'Héroe inicial',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard listo: salva una estrella fallada',
    'Streak Guard reddede din streak': 'Streak Guard salvó tu racha',
    'Sur havnemåge · køb for fjer': 'Gaviota gruñona del puerto · compra con plumas',
    'SØLV': 'PLATA',
    'BRONZE': 'BRONCE',
    'Sådan virker Berts rede': 'Así funciona el nido de Bert',
    'TAP': 'TOCA',
    'TAP FOR AT FLYVE · {0}': 'TOCA PARA VOLAR · {0}',
    'TESTBANE': 'NIVEL DE PRUEBA',
    'TIDEN UDE': 'SE ACABÓ EL TIEMPO',
    'TILBAGE': 'ATRÁS',
    'TRYK FOR AT STARTE': 'TOCA PARA EMPEZAR',
    'TUNG': 'PESADO',
    'TUNG · STIGER LANGSOMT': 'PESADO · SUBE DESPACIO',
    'Tid': 'Tiempo',
    'Tilgængelige helte': 'Héroes disponibles',
    'UDFORDR EN VEN': 'DESAFÍA A UN AMIGO',
    'Udfordringen er klar': 'El desafío está listo',
    'Udfordringslink klar': 'Enlace del desafío listo',
    'Udfordringslink kopieret': 'Enlace del desafío copiado',
    'Uge': 'Semana',
    'Undvig den varslede ørn eller grib': 'Esquiva el águila o el buitre anunciado',
    'Undvig en flyvende genstand i storm eller orkan': 'Esquiva un objeto volador en tormenta o huracán',
    'VELKOMMEN': 'BIENVENIDO',
    'VENNEDUEL': 'DUELO CON AMIGOS',
    'VENNER': 'AMIGOS',
    'VERDEN': 'MUNDO',
    'VENNER FRA DUELLER': 'AMIGOS DE DUELOS',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'AMIGOS DE DUELOS · {0} RIVALES · {1} RESULTADOS',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LADO IZQUIERDO = ARRIBA · LADO DERECHO = ABAJO',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · IZQUIERDA SUBE · DERECHA BAJA',
    'VERDEN KLARET': 'MUNDO COMPLETADO',
    'VERDEN KLARET · LOKALT': 'MUNDO COMPLETADO · LOCAL',
    'VIND & GENSTANDE': 'VIENTO Y OBJETOS',
    'VIND · TESTBANE': 'VIENTO · NIVEL DE PRUEBA',
    'VIND · {0}': 'VIENTO · {0}',
    'VINDKLOKKEN RAMT': 'CAMPANILLA GOLPEADA',
    'VINDVERDEN · LOKALT': 'MUNDO DE VIENTO · LOCAL',
    'Vindmøller': 'Los Molinos',
    'VINDMØLLER': 'LOS MOLINOS',
    'Vulkanen': 'El Volcán',
    'VULKANEN': 'EL VOLCÁN',
    'FJENDER & ANGREB': 'ENEMIGOS Y ATAQUES',
    'FUGLETRAFIK · TESTBANE': 'TRÁFICO DE PÁJAROS · NIVEL DE PRUEBA',
    'FUGLE & ROVFUGL': 'PÁJAROS Y RAPAZ',
    'FLAPPY-STYRING': 'CONTROLES FLAPPY',
    'FLAPPY-STYRING · TAP': 'CONTROLES FLAPPY · TOCA',
    'VUNDET': 'GANADO',
    'BEHOLDT': 'CONSERVADO',
    'Valgt og klar til at flyve': 'Elegido y listo para volar',
    'Vind bronze, sølv og guld': 'Gana bronce, plata y oro',
    'Vind ti vennedueller': 'Gana diez duelos con amigos',
    'Vind · genstande': 'Viento · objetos',
    'VÆLG HELT': 'ELIGE HÉROE',
    'VÆLG LEVEL': 'ELIGE NIVEL',
    'VÆLG SPILTYPE': 'ELIGE MODO',
    'Vælg Bert': 'Elegir Bert', 'Vælg Blok-Johan': 'Elegir Blok-Johan', 'Vælg BlueBert': 'Elegir BlueBert', 'Vælg BoneBeak': 'Elegir BoneBeak',
    'Vælg BrainBird': 'Elegir BrainBird', 'Vælg BrickBird': 'Elegir BrickBird', 'Vælg Coopinc': 'Elegir Coopinc', 'Vælg Fodbold-Bert': 'Elegir Bert Futbolero',
    'Vælg Guld-Bert': 'Elegir Bert Dorado', 'Vælg InkBird': 'Elegir InkBird', 'Vælg MechaBert': 'Elegir MechaBert', 'Vælg MossHex': 'Elegir MossHex',
    'Vælg Mågen Mogens': 'Elegir Mogens la Gaviota', 'Vælg Ninja-Bert': 'Elegir Bert Ninja', 'Vælg NoirWing': 'Elegir NoirWing', 'Vælg Pakke-Bert': 'Elegir Bert Paquete',
    'Vælg Pingo': 'Elegir Pingo', 'Vælg Prinsesse Søs': 'Elegir Princesa Søs', 'Vælg PrismWing': 'Elegir PrismWing', 'Vælg SkyClaw': 'Elegir SkyClaw',
    'Vælg Storm Royale': 'Elegir Storm Royale', 'Vælg SugarRush': 'Elegir SugarRush', 'Vælg Thor Obby': 'Elegir Thor Obby',
    'Vælg bane': 'Elegir nivel',
    'Vælg leaderboard': 'Elegir clasificación',
    'Vælg level': 'Elegir nivel',
    'Vælg spiltype': 'Elegir modo',
    'Vælg {0}, {1}': 'Elegir {0}, {1}',
    'købt': 'comprado',
    'låst op': 'desbloqueado',
    '{0} ER LÅST': '{0} ESTÁ BLOQUEADO',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} hizo {1} puntos. Tienes {2} intentos en el mismo nivel y su vuelo se muestra como una sombra.',
    '{0} forsøg tilbage · slå {1} point': '{0} intentos restantes · supera {1} puntos',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} te desafía a superar {1} puntos. Tienes tres intentos.',
    '{0} låst op for {1} fjer': '{0} desbloqueado por {1} plumas',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} bloqueado. {1}. {2} de {3}. Precio alternativo {4} plumas.',
    '{0} missionsbelønninger': '{0} recompensas de misión',
    '{0} missionsbelønninger er hentet.': '{0} recompensas de misión recogidas.',
    '{0} point til næste medalje': '{0} puntos para la siguiente medalla',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Cuando se cumplan ambos requisitos se abrirá todo el nivel {2}.',
    '{0} · {1} FASTE LIV': '{0} · {1} VIDAS FIJAS',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, bloqueado. Toca para ver el requisito',
    '{0}, åben, personlig rekord {1}': '{0}, abierto, récord personal {1}',
    '{0} · Mål {1}': '{0} · Meta {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} NIVELES · {2}/{3} MISIONES',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} NIVELES · {2}/{3} MIS.',
    '{0} BANER · {1}': '{0} NIVELES · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} ABIERTOS · {2}',
    'DU MANGLER {0} FJER': 'TE FALTAN {0} PLUMAS',
    'BESKYTTET · {0}s': 'PROTEGIDO · {0}s',
    'ÅBN DAGENS MISSIONER': 'ABRIR MISIONES DE HOY',
    'ÅBN GARDEROBE · 17 HELTE': 'ABRIR ARMARIO · 17 HÉROES',
    'ÅNDENDE PORTE': 'PUERTAS QUE RESPIRAN',
    'Åbn dagens missioner': 'Abrir misiones de hoy',
    'Åbn highscore': 'Abrir récords',
    'Åbn indstillinger': 'Abrir ajustes',
    'ÉN CHANCE MERE?': '¿UNA OPORTUNIDAD MÁS?',
    'Sprog': 'Idioma',
    'Automatisk (som telefonen)': 'Automático (como el teléfono)',
    'Dansk': 'Danés', 'Engelsk': 'Inglés', 'Norsk': 'Noruego', 'Svensk': 'Sueco', 'Tysk': 'Alemán', 'Spansk': 'Español', 'Fransk': 'Francés', 'Portugisisk': 'Portugués',
    '+1 FJER': '+1 PLUMA',
    'En ven': 'Un amigo',
    'Dig': 'Tú',
    'REKORD': 'RÉCORD',
    'Topflyvning': 'Vuelo perfecto',
    '{0} point i {1}': '{0} puntos en {1}',
    'en bane': 'un nivel',
    '{0} til trin {1} · {2} stjerner': '{0} para el nivel {1} · {2} estrellas',
    '{0} · {1} stjerner samlet': '{0} · {1} estrellas recogidas',
    '{0} FJER': '{0} PLUMAS',
    'TAP FOR AT FLYVE': 'TOCA PARA VOLAR',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Supera la puntuación de tu amigo en el mismo nivel. Tienes tres intentos y su vuelo fantasma te acompaña.",
});
