/* English. Keys are the Danish source texts; {0}, {1} … are values filled in at runtime. */
window.BertI18n.register('en', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FLY A RUN TO SET YOUR FIRST SCORE',
    ' · MÆRKE: {0}': ' · BADGE: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · PLAY A FRIEND DUEL TO GET A RIVAL',
    '+{0} fjer til reden': '+{0} feathers for the nest',
    '+{0} fjer · {1} låst op': '+{0} feathers · {1} unlocked',
    '0 / 0 POINT': '0 / 0 POINTS',
    '20 point til bronze': '20 points to bronze',
    '3 SPILFORMER · 9 BANER': '3 GAME MODES · 9 LEVELS',
    '3 baner · hold op/ned': '3 levels · hold up/down',
    '3 baner · præcision': '3 levels · precision',
    '3 baner · tap': '3 levels · tap',
    '9 baner · nye verdener': '9 levels · new worlds',
    'ACCEPTÉR': 'ACCEPT',
    'AFSLUT TUREN': 'END THE RUN',
    'Alle baner': 'All levels',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Every hero has the same speed and hitbox. Win them in the game, or save up feathers.',
    'Alle pointkrav i trin {0} er klaret.': 'All score requirements in tier {0} are complete.',
    'Alle spil': 'All games',
    'Alle tider': 'All time',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'All three attempts are used. Ask your friend for a new duel.',
    'BANEN ER LÅST': 'LEVEL LOCKED',
    'BEKRÆFT · {0} FJER': 'CONFIRM · {0} FEATHERS',
    'BERTS GARDEROBE': "BERT'S WARDROBE",
    'BERTS REDE': "BERT'S NEST",
    'BERTS REDNINGSREDE': "BERT'S RESCUE NEST",
    'BEVÆGELIGE TÅRNE': 'MOVING TOWERS',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} stars · local event record only',
    'Bane': 'Level',
    'Banen er låst': 'The level is locked',
    'Bedst på level {0} · {1}': 'Best on level {0} · {1}',
    'Bert The Bird appikon': 'Bert The Bird app icon',
    'Bert The Bird bliver installeret': 'Bert The Bird is being installed',
    'Bert The Bird er installeret': 'Bert The Bird is installed',
    'Bert The Bird spilcanvas': 'Bert The Bird game canvas',
    'Bert flyver': 'Bert flying',
    'Bevægelse i koncertlys': 'Motion in concert lights',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Spend 12 feathers on one spin. Five fields send Bert back into the level. One field ends the run.',
    'DAGENS MISSIONER': "TODAY'S MISSIONS",
    'DAGENS RUTE': "TODAY'S ROUTE",
    'DAGENS RUTE · MÅL {0}': "TODAY'S ROUTE · GOAL {0}",
    'DENNE TUR': 'THIS RUN',
    'DIN FLYVETUR': 'YOUR FLIGHT',
    'DIN HELT': 'YOUR HERO',
    'DIN SALDO': 'YOUR BALANCE',
    'DINE VENNEDUELLER': 'YOUR FRIEND DUELS',
    'DREJ TELEFONEN': 'ROTATE YOUR PHONE',
    'DU ER UDFORDRET': 'YOU HAVE BEEN CHALLENGED',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'YOU WON THE DUEL · challenge back · {0} stars',
    'Den sjældneste fugl · køb for fjer': 'The rarest bird · buy with feathers',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'This level cannot be used for ranked friend duels.',
    'Dit navn': 'Your name',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Your name appears on the leaderboard and next to your records.',
    'Du mangler fjer fra dagens missioner': "You need feathers from today's missions",
    'EDM-VERDEN · LOKALT': 'EDM WORLD · LOCAL',
    'EPISK': 'EPIC',
    'EVENT · BIRD RUN · TESTBANE': 'EVENT · BIRD RUN · TEST LEVEL',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENT · NEON ENCORE · TEST LEVEL',
    'EVENT · STORMLINE · TESTBANE': 'EVENT · STORMLINE · TEST LEVEL',
    'EVENTYR': 'ADVENTURE',
    'EVENTYR · {0}': 'ADVENTURE · {0}',
    'Episk helt · kun til dig · valgt': 'Epic hero · just for you · selected',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Epic hero · just for you. Tap to select.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'A permanent rescue life absorbs one crash on every run. After a crash you can also spend 12 feathers on one rescue spin. You can always keep playing with no energy or waiting.',
    'FAST + BEVÆGELIG': 'FIXED + MOVING',
    'FASTE TÅRNE': 'FIXED TOWERS',
    'FJER': 'FEATHERS',
    'FJER RETUR': 'FEATHERS BACK',
    'FJER · PRIMÆRT VINDES I SPILLET': 'FEATHERS · MOSTLY WON IN THE GAME',
    'FLYV': 'FLY',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'FLY THROUGH THREE CLOUD GATES · HIT THE GOLD PLATE · LEFT UP · RIGHT DOWN',
    'FLYV IGEN': 'FLY AGAIN',
    'FLYV VIDERE': 'KEEP FLYING',
    'FLYVETUREN ER SAT PÅ PAUSE': 'THE FLIGHT IS PAUSED',
    'FODBOLD-BERT': 'FOOTBALL BERT',
    'FOKUS': 'FOCUS',
    'FOKUS OM {0}': 'FOCUS IN {0}',
    'FORBI': 'MISSED',
    'FORBI GULDPLADEN': 'MISSED THE GOLD PLATE',
    'FORSTÅET': 'GOT IT',
    'FORTRYD': 'CANCEL',
    'FORTSÆT': 'CONTINUE',
    'FRI AF ROVFUGLEN': 'FREE OF THE RAPTOR',
    'FUGL BAGFRA': 'BIRD FROM BEHIND',
    'FUGLEVERDEN · LOKALT': 'BIRD WORLD · LOCAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Four free local event worlds without a global leaderboard',
    'Flyv samlet i 3 minutter': 'Fly for 3 minutes in total',
    'Flyvetid': 'Flight time',
    'Fodbold-Bert': 'Football Bert',
    'Forbindelsen er tilbage': 'Connection is back',
    'Fremgang mod oplåsning': 'Progress towards unlocking',
    'Fugle · rovfugl': 'Birds · raptor',
    'FÆRDIG': 'DONE',
    'FØLG STJERNESTRØMMEN': 'FOLLOW THE STAR STREAM',
    'FØLGER DIG KORT · {0}s': 'TRACKING YOU BRIEFLY · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · THE RUN ENDS',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} RESULTS',
    'GODT RAMT': 'GOOD HIT',
    'GRATIS REDNING': 'FREE RESCUE',
    'GRUNDFLYVNING': 'BASIC FLIGHT',
    'GULD': 'GOLD',
    'GULD-BERT': 'GOLD BERT',
    'Guld-Bert': 'Gold Bert',
    'HAV BERT PÅ STARTSKÆRMEN': 'KEEP BERT ON YOUR HOME SCREEN',
    'HAVNEN': 'THE HARBOUR',
    'Havnen': 'The Harbour',
    'HENT FJER': 'CLAIM FEATHERS',
    'HENT SPILLET': 'GET THE GAME',
    'HENT +{0}': 'CLAIM +{0}',
    '+{0} FJER': '+{0} FEATHERS',
    'HENTER RESULTATER …': 'LOADING RESULTS …',
    'HENTET': 'CLAIMED',
    'HOLD OP/NED': 'HOLD UP/DOWN',
    'HOVEDMENU': 'MAIN MENU',
    'HVAD HEDDER DU?': "WHAT'S YOUR NAME?",
    'HVORDAN VIL DU FLYVE?': 'HOW DO YOU WANT TO FLY?',
    'HYPERFART': 'HYPERSPEED',
    'Haptisk feedback': 'Haptic feedback',
    'Har altid en pakke med · køb for fjer': 'Always carries a parcel · buy with feathers',
    'Hele Bert The Bird er lavet til landscape.': 'All of Bert The Bird is made for landscape.',
    'Hemmelig helt': 'Secret hero',
    'Hent en mission syv dage i træk': 'Claim a mission seven days in a row',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Claim {0} mission rewards in total; you have {1}.',
    'Henter resultater …': 'Loading results …',
    'Høj fart': 'High speed',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'In Safari: Share → Add to Home Screen. Wait for “Ready for offline play”, and open the icon once while online before testing in airplane mode.',
    'I dag': 'Today',
    'IKKE NU': 'NOT NOW',
    'INDSTILLINGER': 'SETTINGS',
    'INSTALLÉR WEBAPP': 'INSTALL WEB APP',
    'ISTAPPER & SPIDSER': 'ICICLES & SPIKES',
    'Isbjerget': 'The Iceberg',
    'ISBJERGET': 'THE ICEBERG',
    'Indlæser originale Unity-assets …': 'Loading original Unity assets …',
    'Ingen rekord endnu': 'No record yet',
    'Installér som webapp': 'Install as web app',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Install from the browser menu. Wait for “Ready for offline play”, and open the app once while online before testing offline.',
    'KANT': 'EDGE',
    'KLAR DAGENS MÅL': "COMPLETE TODAY'S GOAL",
    'KLARET': 'DONE',
    'KONCERT · TESTBANE': 'CONCERT · TEST LEVEL',
    'KRANER & MÅGER': 'CRANES & GULLS',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'ONLY YOUR LOCAL RESULTS · ONLINE SCOREBOARD IS NOT AVAILABLE',
    'KVALIFIKATIONSBANEN': 'THE QUALIFYING LEVEL',
    'Klar dagens rute': "Complete today's route",
    'Klar dagens rute én gang': "Complete today's route once",
    'Klar hele forrige trin og missionskravet først': 'Complete the whole previous tier and the mission requirement first',
    'Klar hele trin {0}: {1}.': 'Complete all of tier {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Complete the qualifying level to open this challenge.',
    'Klar til offline-spil': 'Ready for offline play',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Get past at least three balls in one concert wave',
    'KØB': 'BUY',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'BUY PERMANENT LIVES OR A RESCUE SPIN',
    'KØB · {0} FJER': 'BUY · {0} FEATHERS',
    'KØBT': 'BOUGHT',
    'LAVA & BOBLER': 'LAVA & BUBBLES',
    'LEVEL 1 · DESERT': 'LEVEL 1 · DESERT',
    'LEVENDE FORHINDRINGER': 'LIVING OBSTACLES',
    'LEVERING': 'DELIVERY',
    'LYD & FEEDBACK': 'SOUND & FEEDBACK',
    'LYDLØS': 'SILENT',
    'Level 1 · Mål 30': 'Level 1 · Goal 30',
    'Luk': 'Close',
    'Luk garderoben': 'Close the wardrobe',
    'Lydeffekter': 'Sound effects',
    'Lydløs og hurtig · køb for fjer': 'Silent and fast · buy with feathers',
    'LÅS OP · 20 FJER': 'UNLOCK · 20 FEATHERS',
    'LÅS OP · {0} FJER': 'UNLOCK · {0} FEATHERS',
    'LÅST BANE': 'LOCKED LEVEL',
    'LÅST OP': 'UNLOCKED',
    'LÆR KORRIDOREN': 'LEARN THE CORRIDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Unlocked. Tap the character to select.',
    'MAKS LÅST OP': 'MAX UNLOCKED',
    'MINISPIL · SKY RELAY · LOKALT': 'MINI GAME · SKY RELAY · LOCAL',
    'MISSIONER': 'MISSIONS',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MOBILE: LEFT SIDE = UP · RIGHT SIDE = DOWN',
    'Missioner': 'Missions',
    'Mod vinden': 'Against the wind',
    'Musik': 'Music',
    'MÅGEN MOGENS': 'MOGENS THE GULL',
    'Mågen Mogens': 'Mogens the Gull',
    'MÅL: 3 BOLDE': 'GOAL: 3 BALLS',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'GOAL: GET PAST A WAVE WITH THREE BALLS · LEFT UP · RIGHT DOWN',
    'MÅL: ROVFUGL': 'GOAL: RAPTOR',
    'MÅL: STORM': 'GOAL: STORM',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'GOAL: DODGE A RAPTOR · LEFT UP · RIGHT DOWN',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'GOAL: DODGE A STORM OBJECT · FOLLOW FLAGS AND LEAVES',
    'MÆRKE VUNDET': 'BADGE WON',
    'MØRKE & SKILTE': 'DARKNESS & SIGNS',
    'Måned': 'Month',
    'NED': 'DOWN',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} stars · local event record only',
    'NINJA-BERT': 'NINJA BERT',
    'Ninja-Bert': 'Ninja Bert',
    'NIVEAU {0}! · {1}': 'LEVEL {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING UNLOCKED · FLAWLESS FLIGHT',
    'NY BANE': 'NEW LEVEL',
    'NY REKORD!': 'NEW RECORD!',
    'NYE VERDENER': 'NEW WORLDS',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NEW TIER: ALL THREE LEVELS ARE OPEN · {0} stars collected',
    'NATTEBYEN': 'NIGHT CITY',
    'Nattebyen': 'Night City',
    'Ny mobilversion indlæst': 'New mobile version loaded',
    'Nyt redningsliv låst op': 'New rescue life unlocked',
    'NÆSTE UDFORDRING': 'NEXT CHALLENGE',
    'Nå 120 point i Desert': 'Reach 120 points in Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Reach 180 points without missing a star or hitting anything',
    'Nå 300 point på én tur': 'Reach 300 points in one run',
    'Nå bronze i Jungle uden redning': 'Reach bronze in Jungle without a rescue',
    'Nå bronze i alle ni baner': 'Reach bronze in all nine levels',
    'Nå bronze i alle tre Classic-baner': 'Reach bronze in all three Classic levels',
    'Nå en streak på 12': 'Reach a streak of 12',
    'OMVENDT STYRING': 'REVERSED CONTROLS',
    'OP': 'UP',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Offline is not ready yet · connect to the internet',
    'PAKKE-BERT': 'PARCEL BERT',
    'Pakke-Bert': 'Parcel Bert',
    'PERMANENT REDE-FORDEL': 'PERMANENT NEST PERK',
    'PERSONLIG REKORD': 'PERSONAL BEST',
    'PILOTER': 'PILOTS',
    'POINT ×2': 'POINTS ×2',
    'PORTE & KLOKKE': 'GATES & BELL',
    'PRINSESSE SØS': 'PRINCESS SØS',
    'Prinsesse Søs': 'Princess Søs',
    'PRÆCISION': 'PRECISION',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'PRECISION FLIGHT · LOCAL TRIAL',
    'PRÆCISIONSRUTE · LOKALT': 'PRECISION ROUTE · LOCAL',
    'PUBLIKUMSVØLGE': 'CROWD WAVE',
    'Pause spillet': 'Pause the game',
    'Periode': 'Period',
    'Personlig highscore': 'Personal high score',
    'Pilotnavn': 'Pilot name',
    'Pingvin med jetpack · køb for fjer': 'Penguin with a jetpack · buy with feathers',
    'Point': 'Points',
    'Porte · vindklokke': 'Gates · wind chime',
    'PORT {0}/3': 'GATE {0}/3',
    'PORT {0}/3 · {1}': 'GATE {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'ROUND {0} · GATE {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'DING! +{0} · ROUND {1}',
    'Præcisionsflyvning': 'Precision flight',
    'RAM GULDPLADEN': 'HIT THE GOLD PLATE',
    'RAMT': 'HIT',
    'RANGLISTE': 'LEADERBOARD',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'RESCUED · YOUR 12 FEATHERS COME BACK',
    'REDDET · {0}': 'RESCUED · {0}',
    'REDNINGSLIV': 'RESCUE LIFE',
    'REDNINGSLIV 0/3': 'RESCUE LIVES 0/3',
    'REDNINGSLIV {0}/{1}': 'RESCUE LIVES {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'THE RESCUE NEST IS SPINNING …',
    'REDNINGSSPIN': 'RESCUE SPIN',
    'RENT GENNEM': 'CLEAN THROUGH',
    'RIGGE & BOLDE': 'RIGS & BALLS',
    'ROTORER & BØJER': 'ROTORS & BUOYS',
    'ROVFUGL': 'RAPTOR',
    'ROVFUGL BAGFRA': 'RAPTOR FROM BEHIND',
    'FUGL': 'BIRD',
    'BAGFRA': 'FROM BEHIND',
    'FORFRA': 'FROM THE FRONT',
    'RUTEN AFSLUTTET': 'ROUTE FINISHED',
    'Redningsliv tilbage': 'Rescue lives left',
    'Rigge · bolde': 'Rigs · balls',
    'SJÆLDEN': 'RARE',
    'SKIFT BANE': 'CHANGE LEVEL',
    'SKJOLD': 'SHIELD',
    'SKJOLD BRUGT · 2s': 'SHIELD USED · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · HIT THE {0} OF GATE {1} · 0 POINTS · TRY AGAIN',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 POINTS · TRY AGAIN',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 GATES · {1}% PRECISION · LOCAL ONLY',
    'TOPPEN': 'TOP',
    'BUNDEN': 'BOTTOM',
    'SKYRING RAMT': 'CLOUD RING HIT',
    'SPIL': 'PLAY',
    'SPIL KVALIFIKATION': 'PLAY QUALIFIER',
    'SPIL →': 'PLAY →',
    'SPIL {0}': 'PLAY {0}',
    'SPIN FOR AT SE DIN REDNING': 'SPIN TO SEE YOUR RESCUE',
    'SPIN · 12 FJER': 'SPIN · 12 FEATHERS',
    'SPIN · {0} FJER': 'SPIN · {0} FEATHERS',
    'START FORFRA': 'START OVER',
    'STARTBANE': 'STARTING LEVEL',
    'STJERNEREGN': 'STAR SHOWER',
    'STIGER': 'CLIMBING',
    'DYKKER': 'DIVING',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · WIND AND FLYING THINGS · {0} stars · local event record only',
    'STREAK REDDET · GUARD BRUGT': 'STREAK SAVED · GUARD USED',
    'STORMPILOT': 'STORM PILOT',
    'Saml 20 stjerner til reden': 'Collect 20 stars for the nest',
    'Saml 250 stjerner i alt': 'Collect 250 stars in total',
    'Scoretype': 'Score type',
    'Skriv dit navn': 'Type your name',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Play Bird Run, a local bird world. Dodge the announced raptor. No global leaderboard.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Play Neon Encore, a local concert world. Survive a whole wave with at least three balls. No global leaderboard.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Play Sky Relay, a short local precision route through three cloud rings. The top and bottom of a ring can be hit. Hit the gold plate of the wind chime. No global leaderboard.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Play Stormline, a local wind world. Dodge a flying object in a storm. No global leaderboard.',
    'Spiltype': 'Game mode',
    'Start Quick Flight': 'Start Quick Flight',
    'Starthelt · Klar til at flyve': 'Starting hero · Ready to fly',
    'Starthelt': 'Starting hero',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard ready: saves one missed star',
    'Streak Guard reddede din streak': 'Streak Guard saved your streak',
    'Sur havnemåge · køb for fjer': 'Grumpy harbour gull · buy with feathers',
    'SØLV': 'SILVER',
    'BRONZE': 'BRONZE',
    'Sådan virker Berts rede': "How Bert's nest works",
    'TAP': 'TAP',
    'TAP FOR AT FLYVE · {0}': 'TAP TO FLY · {0}',
    'TESTBANE': 'TEST LEVEL',
    'TIDEN UDE': 'TIME IS UP',
    'TILBAGE': 'BACK',
    'TRYK FOR AT STARTE': 'TAP TO START',
    'TUNG': 'HEAVY',
    'TUNG · STIGER LANGSOMT': 'HEAVY · CLIMBS SLOWLY',
    'Tid': 'Time',
    'Tilgængelige helte': 'Available heroes',
    'UDFORDR EN VEN': 'CHALLENGE A FRIEND',
    'Udfordringen er klar': 'The challenge is ready',
    'Udfordringslink klar': 'Challenge link ready',
    'Udfordringslink kopieret': 'Challenge link copied',
    'Uge': 'Week',
    'Undvig den varslede ørn eller grib': 'Dodge the announced eagle or vulture',
    'Undvig en flyvende genstand i storm eller orkan': 'Dodge a flying object in a storm or hurricane',
    'VELKOMMEN': 'WELCOME',
    'VENNEDUEL': 'FRIEND DUEL',
    'VENNER': 'FRIENDS',
    'VERDEN': 'WORLD',
    'VENNER FRA DUELLER': 'FRIENDS FROM DUELS',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'FRIENDS FROM DUELS · {0} RIVALS · {1} RESULTS',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LEFT SIDE = UP · RIGHT SIDE = DOWN',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · LEFT UP · RIGHT DOWN',
    'VERDEN KLARET': 'WORLD COMPLETE',
    'VERDEN KLARET · LOKALT': 'WORLD COMPLETE · LOCAL',
    'VIND & GENSTANDE': 'WIND & OBJECTS',
    'VIND · TESTBANE': 'WIND · TEST LEVEL',
    'VIND · {0}': 'WIND · {0}',
    'VINDKLOKKEN RAMT': 'WIND CHIME HIT',
    'VINDVERDEN · LOKALT': 'WIND WORLD · LOCAL',
    'Vindmøller': 'Wind Turbines',
    'VINDMØLLER': 'WIND TURBINES',
    'Vulkanen': 'The Volcano',
    'VULKANEN': 'THE VOLCANO',
    'FJENDER & ANGREB': 'ENEMIES & ATTACKS',
    'FUGLETRAFIK · TESTBANE': 'BIRD TRAFFIC · TEST LEVEL',
    'FUGLE & ROVFUGL': 'BIRDS & RAPTOR',
    'FLAPPY-STYRING': 'FLAPPY CONTROLS',
    'FLAPPY-STYRING · TAP': 'FLAPPY CONTROLS · TAP',
    'VUNDET': 'WON',
    'BEHOLDT': 'KEPT',
    'Valgt og klar til at flyve': 'Selected and ready to fly',
    'Vind bronze, sølv og guld': 'Win bronze, silver and gold',
    'Vind ti vennedueller': 'Win ten friend duels',
    'Vind · genstande': 'Wind · objects',
    'VÆLG HELT': 'CHOOSE HERO',
    'VÆLG LEVEL': 'CHOOSE LEVEL',
    'VÆLG SPILTYPE': 'CHOOSE GAME MODE',
    'Vælg Bert': 'Select Bert',
    'Vælg Blok-Johan': 'Select Blok-Johan',
    'Vælg BlueBert': 'Select BlueBert',
    'Vælg BoneBeak': 'Select BoneBeak',
    'Vælg BrainBird': 'Select BrainBird',
    'Vælg BrickBird': 'Select BrickBird',
    'Vælg Coopinc': 'Select Coopinc',
    'Vælg Fodbold-Bert': 'Select Football Bert',
    'Vælg Guld-Bert': 'Select Gold Bert',
    'Vælg InkBird': 'Select InkBird',
    'Vælg MechaBert': 'Select MechaBert',
    'Vælg MossHex': 'Select MossHex',
    'Vælg Mågen Mogens': 'Select Mogens the Gull',
    'Vælg Ninja-Bert': 'Select Ninja Bert',
    'Vælg NoirWing': 'Select NoirWing',
    'Vælg Pakke-Bert': 'Select Parcel Bert',
    'Vælg Pingo': 'Select Pingo',
    'Vælg Prinsesse Søs': 'Select Princess Søs',
    'Vælg PrismWing': 'Select PrismWing',
    'Vælg SkyClaw': 'Select SkyClaw',
    'Vælg Storm Royale': 'Select Storm Royale',
    'Vælg SugarRush': 'Select SugarRush',
    'Vælg Thor Obby': 'Select Thor Obby',
    'Vælg bane': 'Choose level',
    'Vælg leaderboard': 'Choose leaderboard',
    'Vælg level': 'Choose level',
    'Vælg spiltype': 'Choose game mode',
    'Vælg {0}, {1}': 'Select {0}, {1}',
    'købt': 'bought',
    'låst op': 'unlocked',
    '{0} ER LÅST': '{0} IS LOCKED',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} scored {1} points. You have {2} attempts on the same level, and their flight is shown as a shadow.',
    '{0} forsøg tilbage · slå {1} point': '{0} attempts left · beat {1} points',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} has challenged you to beat {1} points. You have three attempts.',
    '{0} låst op for {1} fjer': '{0} unlocked for {1} feathers',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} locked. {1}. {2} of {3}. Alternative price {4} feathers.',
    '{0} missionsbelønninger': '{0} mission rewards',
    '{0} missionsbelønninger er hentet.': '{0} mission rewards have been claimed.',
    '{0} point til næste medalje': '{0} points to the next medal',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} When both requirements are met, all of tier {2} opens.',
    '{0} · {1} FASTE LIV': '{0} · {1} PERMANENT LIVES',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, locked. Tap to see the unlock requirement',
    '{0}, åben, personlig rekord {1}': '{0}, open, personal best {1}',
    '{0} · Mål {1}': '{0} · Goal {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} LEVELS · {2}/{3} MISSIONS',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} LEVELS · {2}/{3} MISS.',
    '{0} BANER · {1}': '{0} LEVELS · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} OPEN · {2}',
    'DU MANGLER {0} FJER': 'YOU NEED {0} MORE FEATHERS',
    'BESKYTTET · {0}s': 'PROTECTED · {0}s',
    'ÅBN DAGENS MISSIONER': "OPEN TODAY'S MISSIONS",
    'ÅBN GARDEROBE · 17 HELTE': 'OPEN WARDROBE · 17 HEROES',
    'ÅNDENDE PORTE': 'BREATHING GATES',
    'Åbn dagens missioner': "Open today's missions",
    'Åbn highscore': 'Open high score',
    'Åbn indstillinger': 'Open settings',
    'ÉN CHANCE MERE?': 'ONE MORE CHANCE?',
    'SPIL IGEN': 'PLAY AGAIN',
    'Sprog': 'Language',
    'Automatisk (som telefonen)': 'Automatic (same as the phone)',
    'Dansk': 'Danish',
    'Engelsk': 'English',
    'Sproget skifter, når spillet genindlæses.': 'The language changes when the game reloads.',
    '+1 FJER': '+1 FEATHER',
    'ISBJERGET': 'THE ICEBERG',
    'En ven': 'A friend',
    'REKORD': 'RECORD',
    'Topflyvning': 'Top flight',
    '{0} point i {1}': '{0} points in {1}',
    'en bane': 'a level',
    '{0} til trin {1} · {2} stjerner': '{0} for tier {1} · {2} stars',
    '{0} · {1} stjerner samlet': '{0} · {1} stars collected',
    '{0} FJER': '{0} FEATHERS',
    'TAP FOR AT FLYVE': 'TAP TO FLY',
    'Dig': 'You',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Beat your friend's score on exactly the same level. You have three attempts, and their ghost flight follows you.",
    '{0}/{1} BRONZE': '{0}/{1} BRONZE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Get bronze (20 points) on all {0} base levels to open Adventure. You have {1}.',
    'SØLV I {0}': 'SILVER IN {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Get silver (50 points) in {0} to open {1}.',
    'LAVAEN FALDER': 'THE LAVA SINKS',
    'GODT GREB · {0}s': 'GOOD GRIP · {0}s',
    'VINDSTØD · OP': 'GUST · UP',
    'VINDSTØD · NED': 'GUST · DOWN',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'SLIPPERY ICE: STEER EARLY · COLLECT FROST CRYSTALS',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'WATCH THE GUSTS · THE ARROWS SHOW THE WAY',
    'LAVAEN STIGER · SAML KØLESTEN': 'THE LAVA IS RISING · COLLECT COOLING STONES',
});
