/* Deutsch. Die Schlüssel sind die dänischen Ausgangstexte. */
window.BertI18n.register('de', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FLIEG EINE RUNDE FÜR DEINEN ERSTEN SCORE',
    ' · MÆRKE: {0}': ' · ABZEICHEN: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · SPIEL EIN FREUNDESDUELL FÜR EINEN RIVALEN',
    '+{0} fjer til reden': '+{0} Federn fürs Nest',
    '+{0} fjer · {1} låst op': '+{0} Federn · {1} freigeschaltet',
    '0 / 0 POINT': '0 / 0 PUNKTE',
    '20 point til bronze': '20 Punkte bis Bronze',
    '3 SPILFORMER · 9 BANER': '3 SPIELMODI · 9 LEVEL',
    '3 baner · hold op/ned': '3 Level · halten hoch/runter',
    '3 baner · præcision': '3 Level · Präzision',
    '3 baner · tap': '3 Level · tippen',
    '9 baner · nye verdener': '9 Level · neue Welten',
    'ACCEPTÉR': 'ANNEHMEN',
    'AFSLUT TUREN': 'RUNDE BEENDEN',
    'Alle baner': 'Alle Level',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Alle Helden haben dieselbe Geschwindigkeit und Hitbox. Gewinne sie im Spiel oder spare Federn.',
    'Alle pointkrav i trin {0} er klaret.': 'Alle Punktanforderungen in Stufe {0} sind erfüllt.',
    'Alle spil': 'Alle Spiele',
    'Alle tider': 'Gesamt',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Alle drei Versuche sind verbraucht. Bitte deinen Freund um ein neues Duell.',
    'BANEN ER LÅST': 'LEVEL GESPERRT',
    'BEKRÆFT · {0} FJER': 'BESTÄTIGEN · {0} FEDERN',
    'BERTS GARDEROBE': 'BERTS GARDEROBE',
    'BERTS REDE': 'BERTS NEST',
    'BERTS REDNINGSREDE': 'BERTS RETTUNGSNEST',
    'BEVÆGELIGE TÅRNE': 'BEWEGLICHE TÜRME',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} Sterne · nur lokaler Eventrekord',
    'Bane': 'Level',
    'Banen er låst': 'Das Level ist gesperrt',
    'Bedst på level {0} · {1}': 'Bestwert in Level {0} · {1}',
    'Bert The Bird appikon': 'Bert The Bird App-Symbol',
    'Bert The Bird bliver installeret': 'Bert The Bird wird installiert',
    'Bert The Bird er installeret': 'Bert The Bird ist installiert',
    'Bert The Bird spilcanvas': 'Bert The Bird Spielfläche',
    'Bert flyver': 'Bert fliegt',
    'Bevægelse i koncertlys': 'Bewegung im Konzertlicht',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Setze 12 Federn für eine Drehung ein. Fünf Felder schicken Bert zurück ins Level. Ein Feld beendet die Runde.',
    'DAGENS MISSIONER': 'TAGESMISSIONEN',
    'DAGENS RUTE': 'TAGESROUTE',
    'DAGENS RUTE · MÅL {0}': 'TAGESROUTE · ZIEL {0}',
    'DENNE TUR': 'DIESE RUNDE',
    'DIN FLYVETUR': 'DEIN FLUG',
    'DIN HELT': 'DEIN HELD',
    'DIN SALDO': 'DEIN GUTHABEN',
    'DINE VENNEDUELLER': 'DEINE FREUNDESDUELLE',
    'DREJ TELEFONEN': 'DREH DEIN HANDY',
    'DU ER UDFORDRET': 'DU WURDEST HERAUSGEFORDERT',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'DU HAST DAS DUELL GEWONNEN · fordere zurück · {0} Sterne',
    'Den sjældneste fugl · køb for fjer': 'Der seltenste Vogel · mit Federn kaufen',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Dieses Level kann nicht für gewertete Freundesduelle genutzt werden.',
    'Dit navn': 'Dein Name',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Dein Name steht in der Rangliste und bei deinen Rekorden.',
    'Du mangler fjer fra dagens missioner': 'Dir fehlen Federn aus den Tagesmissionen',
    'EDM-VERDEN · LOKALT': 'EDM-WELT · LOKAL',
    'EPISK': 'EPISCH',
    'EVENT · BIRD RUN · TESTBANE': 'EVENT · BIRD RUN · TESTLEVEL',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENT · NEON ENCORE · TESTLEVEL',
    'EVENT · STORMLINE · TESTBANE': 'EVENT · STORMLINE · TESTLEVEL',
    'EVENTYR': 'ABENTEUER',
    'EVENTYR · {0}': 'ABENTEUER · {0}',
    'Episk helt · kun til dig · valgt': 'Epischer Held · nur für dich · gewählt',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Epischer Held · nur für dich. Tippen zum Auswählen.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Ein dauerhaftes Rettungsleben fängt pro Runde einen Zusammenstoß ab. Nach einem Crash kannst du außerdem 12 Federn für eine Rettungsdrehung einsetzen. Du kannst immer ohne Energie oder Wartezeit weiterspielen.',
    'FAST + BEVÆGELIG': 'FEST + BEWEGLICH',
    'FASTE TÅRNE': 'FESTE TÜRME',
    'FJER': 'FEDERN',
    'FJER RETUR': 'FEDERN ZURÜCK',
    'FJER · PRIMÆRT VINDES I SPILLET': 'FEDERN · VOR ALLEM IM SPIEL GEWINNEN',
    'FLYV': 'FLIEGEN',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'FLIEG DURCH DREI WOLKENTORE · TRIFF DIE GOLDPLATTE · LINKS HOCH · RECHTS RUNTER',
    'FLYV IGEN': 'NOCHMAL FLIEGEN',
    'FLYV VIDERE': 'WEITERFLIEGEN',
    'FLYVETUREN ER SAT PÅ PAUSE': 'DER FLUG IST PAUSIERT',
    'FODBOLD-BERT': 'FUSSBALL-BERT',
    'FOKUS': 'FOKUS',
    'FOKUS OM {0}': 'FOKUS IN {0}',
    'FORBI': 'VORBEI',
    'FORBI GULDPLADEN': 'GOLDPLATTE VERFEHLT',
    'FORSTÅET': 'VERSTANDEN',
    'FORTRYD': 'ABBRECHEN',
    'FORTSÆT': 'WEITER',
    'FRI AF ROVFUGLEN': 'DEM RAUBVOGEL ENTKOMMEN',
    'FUGL BAGFRA': 'VOGEL VON HINTEN',
    'FUGLEVERDEN · LOKALT': 'VOGELWELT · LOKAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Vier kostenlose lokale Eventwelten ohne globale Rangliste',
    'Flyv samlet i 3 minutter': 'Flieg insgesamt 3 Minuten',
    'Flyvetid': 'Flugzeit',
    'Fodbold-Bert': 'Fußball-Bert',
    'Forbindelsen er tilbage': 'Verbindung ist wieder da',
    'Fremgang mod oplåsning': 'Fortschritt bis zur Freischaltung',
    'Fugle · rovfugl': 'Vögel · Raubvogel',
    'FÆRDIG': 'FERTIG',
    'FØLG STJERNESTRØMMEN': 'FOLGE DEM STERNENSTROM',
    'FØLGER DIG KORT · {0}s': 'FOLGT DIR KURZ · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · DIE RUNDE ENDET',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} ERGEBNISSE',
    'GODT RAMT': 'GUT GETROFFEN',
    'GRATIS REDNING': 'GRATIS-RETTUNG',
    'GRUNDFLYVNING': 'GRUNDFLUG',
    'GULD': 'GOLD',
    'GULD-BERT': 'GOLD-BERT',
    'Guld-Bert': 'Gold-Bert',
    'HAV BERT PÅ STARTSKÆRMEN': 'BERT AUF DEM HOME-BILDSCHIRM',
    'HAVNEN': 'DER HAFEN',
    'Havnen': 'Der Hafen',
    'HENT FJER': 'FEDERN ABHOLEN',
    'HENT SPILLET': 'SPIEL HOLEN',
    'HENT +{0}': 'ABHOLEN +{0}',
    '+{0} FJER': '+{0} FEDERN',
    'HENTER RESULTATER …': 'LADE ERGEBNISSE …',
    'HENTET': 'ABGEHOLT',
    'HOLD OP/NED': 'HALTEN HOCH/RUNTER',
    'HOVEDMENU': 'HAUPTMENÜ',
    'HVAD HEDDER DU?': 'WIE HEISST DU?',
    'HVORDAN VIL DU FLYVE?': 'WIE WILLST DU FLIEGEN?',
    'HYPERFART': 'HYPERSPEED',
    'Haptisk feedback': 'Haptisches Feedback',
    'Har altid en pakke med · køb for fjer': 'Hat immer ein Paket dabei · mit Federn kaufen',
    'Hele Bert The Bird er lavet til landscape.': 'Bert The Bird ist komplett fürs Querformat gemacht.',
    'Hemmelig helt': 'Geheimer Held',
    'Hent en mission syv dage i træk': 'Hol sieben Tage in Folge eine Mission ab',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Hol insgesamt {0} Missionsbelohnungen ab; du hast {1}.',
    'Henter resultater …': 'Lade Ergebnisse …',
    'Høj fart': 'Hohes Tempo',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'In Safari: Teilen → Zum Home-Bildschirm. Warte auf „Bereit für Offline-Spiel“ und öffne das Symbol einmal mit Internet, bevor du den Flugmodus testest.',
    'I dag': 'Heute',
    'IKKE NU': 'NICHT JETZT',
    'INDSTILLINGER': 'EINSTELLUNGEN',
    'INSTALLÉR WEBAPP': 'WEB-APP INSTALLIEREN',
    'ISTAPPER & SPIDSER': 'EISZAPFEN & SPITZEN',
    'Isbjerget': 'Der Eisberg',
    'ISBJERGET': 'DER EISBERG',
    'Bert gør klar til at flyve …': 'Bert macht sich startklar …',
    'Ingen rekord endnu': 'Noch kein Rekord',
    'Installér som webapp': 'Als Web-App installieren',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Über das Browsermenü installieren. Warte auf „Bereit für Offline-Spiel“ und öffne die App einmal mit Internet, bevor du offline testest.',
    'KANT': 'RAND',
    'KLAR DAGENS MÅL': 'TAGESZIEL SCHAFFEN',
    'KLARET': 'GESCHAFFT',
    'KONCERT · TESTBANE': 'KONZERT · TESTLEVEL',
    'KRANER & MÅGER': 'KRÄNE & MÖWEN',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'NUR DEINE LOKALEN ERGEBNISSE · ONLINE-RANGLISTE NICHT VERFÜGBAR',
    'KVALIFIKATIONSBANEN': 'DAS QUALIFIKATIONSLEVEL',
    'Klar dagens rute': 'Schaff die Tagesroute',
    'Klar dagens rute én gang': 'Schaff die Tagesroute einmal',
    'Klar hele forrige trin og missionskravet først': 'Schaff zuerst die ganze vorherige Stufe und die Missionsanforderung',
    'Klar hele trin {0}: {1}.': 'Schaff ganz Stufe {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Schaff das Qualifikationslevel, um diese Herausforderung zu öffnen.',
    'Klar til offline-spil': 'Bereit für Offline-Spiel',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Komm in einer Konzertwelle an mindestens drei Bällen vorbei',
    'KØB': 'KAUFEN',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'KAUF FESTE LEBEN ODER EINE RETTUNGSDREHUNG',
    'KØB · {0} FJER': 'KAUFEN · {0} FEDERN',
    'KØBT': 'GEKAUFT',
    'LAVA & BOBLER': 'LAVA & BLASEN',
    'LEVENDE FORHINDRINGER': 'LEBENDIGE HINDERNISSE',
    'LEVERING': 'LIEFERUNG',
    'LYD & FEEDBACK': 'TON & FEEDBACK',
    'LYDLØS': 'LAUTLOS',
    'Level 1 · Mål 30': 'Level 1 · Ziel 30',
    'Luk': 'Schließen',
    'Luk garderoben': 'Garderobe schließen',
    'Lydeffekter': 'Soundeffekte',
    'Lydløs og hurtig · køb for fjer': 'Lautlos und schnell · mit Federn kaufen',
    'LÅS OP · 20 FJER': 'FREISCHALTEN · 20 FEDERN',
    'LÅS OP · {0} FJER': 'FREISCHALTEN · {0} FEDERN',
    'LÅST BANE': 'GESPERRTES LEVEL',
    'LÅST OP': 'FREIGESCHALTET',
    'LÆR KORRIDOREN': 'LERN DEN KORRIDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Freigeschaltet. Tippe auf die Figur, um sie zu wählen.',
    'MAKS LÅST OP': 'MAXIMUM ERREICHT',
    'MINISPIL · SKY RELAY · LOKALT': 'MINISPIEL · SKY RELAY · LOKAL',
    'MISSIONER': 'MISSIONEN',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'HANDY: LINKE SEITE = HOCH · RECHTE SEITE = RUNTER',
    'Missioner': 'Missionen',
    'Mod vinden': 'Gegen den Wind',
    'Musik': 'Musik',
    'MÅGEN MOGENS': 'MÖWE MOGENS',
    'Mågen Mogens': 'Möwe Mogens',
    'MÅL: 3 BOLDE': 'ZIEL: 3 BÄLLE',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'ZIEL: KOMM AN EINER WELLE MIT DREI BÄLLEN VORBEI · LINKS HOCH · RECHTS RUNTER',
    'MÅL: ROVFUGL': 'ZIEL: RAUBVOGEL',
    'MÅL: STORM': 'ZIEL: STURM',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'ZIEL: WEICH EINEM RAUBVOGEL AUS · LINKS HOCH · RECHTS RUNTER',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'ZIEL: WEICH EINEM STURMOBJEKT AUS · FOLGE FAHNEN UND BLÄTTERN',
    'MÆRKE VUNDET': 'ABZEICHEN GEWONNEN',
    'MØRKE & SKILTE': 'DUNKELHEIT & SCHILDER',
    'Måned': 'Monat',
    'NED': 'RUNTER',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} Sterne · nur lokaler Eventrekord',
    'NINJA-BERT': 'NINJA-BERT',
    'Ninja-Bert': 'Ninja-Bert',
    'NIVEAU {0}! · {1}': 'STUFE {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING FREIGESCHALTET · FEHLERFREIER FLUG',
    'NY BANE': 'NEUES LEVEL',
    'NY REKORD!': 'NEUER REKORD!',
    'NYE VERDENER': 'NEUE WELTEN',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NEUE STUFE: ALLE DREI LEVEL SIND OFFEN · {0} Sterne gesammelt',
    'NATTEBYEN': 'DIE NACHTSTADT',
    'Nattebyen': 'Die Nachtstadt',
    'Ny mobilversion indlæst': 'Neue Mobilversion geladen',
    'Nyt redningsliv låst op': 'Neues Rettungsleben freigeschaltet',
    'NÆSTE UDFORDRING': 'NÄCHSTE HERAUSFORDERUNG',
    'Nå 120 point i Desert': 'Erreiche 120 Punkte in Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Erreiche 180 Punkte, ohne einen Stern zu verpassen oder etwas zu treffen',
    'Nå 300 point på én tur': 'Erreiche 300 Punkte in einer Runde',
    'Nå bronze i Jungle uden redning': 'Erreiche Bronze in Jungle ohne Rettung',
    'Nå bronze i alle ni baner': 'Erreiche Bronze in allen neun Leveln',
    'Nå bronze i alle tre Classic-baner': 'Erreiche Bronze in allen drei Classic-Leveln',
    'Nå en streak på 12': 'Erreiche einen Streak von 12',
    'OMVENDT STYRING': 'UMGEKEHRTE STEUERUNG',
    'OP': 'HOCH',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Offline ist noch nicht bereit · verbinde dich mit dem Internet',
    'PAKKE-BERT': 'PAKET-BERT',
    'Pakke-Bert': 'Paket-Bert',
    'PERMANENT REDE-FORDEL': 'DAUERHAFTER NEST-VORTEIL',
    'PERSONLIG REKORD': 'PERSÖNLICHER REKORD',
    'PILOTER': 'PILOTEN',
    'POINT ×2': 'PUNKTE ×2',
    'PORTE & KLOKKE': 'TORE & GLOCKE',
    'PRINSESSE SØS': 'PRINZESSIN SØS',
    'Prinsesse Søs': 'Prinzessin Søs',
    'PRÆCISION': 'PRÄZISION',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'PRÄZISIONSFLUG · LOKALE PROBE',
    'PRÆCISIONSRUTE · LOKALT': 'PRÄZISIONSROUTE · LOKAL',
    'PUBLIKUMSVØLGE': 'PUBLIKUMSWELLE',
    'Pause spillet': 'Spiel pausieren',
    'Periode': 'Zeitraum',
    'Personlig highscore': 'Persönlicher Highscore',
    'Pilotnavn': 'Pilotenname',
    'Pingvin med jetpack · køb for fjer': 'Pinguin mit Jetpack · mit Federn kaufen',
    'Point': 'Punkte',
    'Porte · vindklokke': 'Tore · Windspiel',
    'PORT {0}/3': 'TOR {0}/3',
    'PORT {0}/3 · {1}': 'TOR {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RUNDE {0} · TOR {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'KLANG! +{0} · RUNDE {1}',
    'Præcisionsflyvning': 'Präzisionsflug',
    'RAM GULDPLADEN': 'TRIFF DIE GOLDPLATTE',
    'RAMT': 'GETROFFEN',
    'RANGLISTE': 'RANGLISTE',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'GERETTET · DEINE 12 FEDERN KOMMEN ZURÜCK',
    'REDDET · {0}': 'GERETTET · {0}',
    'REDNINGSLIV': 'RETTUNGSLEBEN',
    'REDNINGSLIV 0/3': 'RETTUNGSLEBEN 0/3',
    'REDNINGSLIV {0}/{1}': 'RETTUNGSLEBEN {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'DAS RETTUNGSNEST DREHT SICH …',
    'REDNINGSSPIN': 'RETTUNGSDREHUNG',
    'RENT GENNEM': 'SAUBER DURCH',
    'RIGGE & BOLDE': 'TRAVERSEN & BÄLLE',
    'ROTORER & BØJER': 'ROTOREN & BOJEN',
    'ROVFUGL': 'RAUBVOGEL',
    'ROVFUGL BAGFRA': 'RAUBVOGEL VON HINTEN',
    'FUGL': 'VOGEL',
    'BAGFRA': 'VON HINTEN',
    'FORFRA': 'VON VORN',
    'RUTEN AFSLUTTET': 'ROUTE BEENDET',
    'Redningsliv tilbage': 'Rettungsleben übrig',
    'Rigge · bolde': 'Traversen · Bälle',
    'SJÆLDEN': 'SELTEN',
    'SKIFT BANE': 'LEVEL WECHSELN',
    'SKJOLD': 'SCHILD',
    'SKJOLD BRUGT · 2s': 'SCHILD VERBRAUCHT · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} VON TOR {1} GETROFFEN · 0 PUNKTE · NOCHMAL',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 PUNKTE · NOCHMAL',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 TORE · {1}% PRÄZISION · NUR LOKAL',
    'TOPPEN': 'OBEN',
    'BUNDEN': 'UNTEN',
    'SKYRING RAMT': 'WOLKENRING GETROFFEN',
    'SPIL': 'SPIELEN',
    'SPIL KVALIFIKATION': 'QUALIFIKATION SPIELEN',
    'SPIL →': 'SPIELEN →',
    'SPIL {0}': '{0} SPIELEN',
    'SPIN FOR AT SE DIN REDNING': 'DREH, UM DEINE RETTUNG ZU SEHEN',
    'SPIN · 12 FJER': 'DREHEN · 12 FEDERN',
    'SPIN · {0} FJER': 'DREHEN · {0} FEDERN',
    'START FORFRA': 'VON VORN',
    'STARTBANE': 'STARTLEVEL',
    'STJERNEREGN': 'STERNENREGEN',
    'STIGER': 'STEIGT',
    'DYKKER': 'STÜRZT',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · WIND UND FLIEGENDE DINGE · {0} Sterne · nur lokaler Eventrekord',
    'STREAK REDDET · GUARD BRUGT': 'STREAK GERETTET · GUARD VERBRAUCHT',
    'STORMPILOT': 'STURMPILOT',
    'Saml 20 stjerner til reden': 'Sammle 20 Sterne fürs Nest',
    'Saml 250 stjerner i alt': 'Sammle insgesamt 250 Sterne',
    'Scoretype': 'Wertung',
    'Skriv dit navn': 'Gib deinen Namen ein',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Spiel Bird Run, eine lokale Vogelwelt. Weich dem angekündigten Raubvogel aus. Keine globale Rangliste.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Spiel Neon Encore, eine lokale Konzertwelt. Überlebe eine ganze Welle mit mindestens drei Bällen. Keine globale Rangliste.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Spiel Sky Relay, eine kurze lokale Präzisionsroute durch drei Wolkenringe. Oben und unten kann man die Ringe treffen. Triff die Goldplatte des Windspiels. Keine globale Rangliste.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Spiel Stormline, eine lokale Windwelt. Weich einem fliegenden Objekt im Sturm aus. Keine globale Rangliste.',
    'Spiltype': 'Spielmodus',
    'Start Quick Flight': 'Quick Flight starten',
    'Starthelt · Klar til at flyve': 'Startheld · Bereit zum Fliegen',
    'Starthelt': 'Startheld',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard bereit: rettet einen verpassten Stern',
    'Streak Guard reddede din streak': 'Streak Guard hat deinen Streak gerettet',
    'Sur havnemåge · køb for fjer': 'Griesgrämige Hafenmöwe · mit Federn kaufen',
    'SØLV': 'SILBER',
    'BRONZE': 'BRONZE',
    'Sådan virker Berts rede': 'So funktioniert Berts Nest',
    'TAP': 'TIPPEN',
    'TAP FOR AT FLYVE · {0}': 'TIPPEN ZUM FLIEGEN · {0}',
    'TESTBANE': 'TESTLEVEL',
    'TIDEN UDE': 'ZEIT ABGELAUFEN',
    'TILBAGE': 'ZURÜCK',
    'TRYK FOR AT STARTE': 'TIPPEN ZUM STARTEN',
    'TUNG': 'SCHWER',
    'TUNG · STIGER LANGSOMT': 'SCHWER · STEIGT LANGSAM',
    'Tid': 'Zeit',
    'Tilgængelige helte': 'Verfügbare Helden',
    'UDFORDR EN VEN': 'FREUND HERAUSFORDERN',
    'Udfordringen er klar': 'Die Herausforderung ist bereit',
    'Udfordringslink klar': 'Herausforderungslink bereit',
    'Udfordringslink kopieret': 'Herausforderungslink kopiert',
    'Uge': 'Woche',
    'Undvig den varslede ørn eller grib': 'Weich dem angekündigten Adler oder Geier aus',
    'Undvig en flyvende genstand i storm eller orkan': 'Weich einem fliegenden Objekt in Sturm oder Orkan aus',
    'VELKOMMEN': 'WILLKOMMEN',
    'VENNEDUEL': 'FREUNDESDUELL',
    'VENNER': 'FREUNDE',
    'VERDEN': 'WELT',
    'VENNER FRA DUELLER': 'FREUNDE AUS DUELLEN',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'FREUNDE AUS DUELLEN · {0} RIVALEN · {1} ERGEBNISSE',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LINKE SEITE = HOCH · RECHTE SEITE = RUNTER',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · LINKS HOCH · RECHTS RUNTER',
    'VERDEN KLARET': 'WELT GESCHAFFT',
    'VERDEN KLARET · LOKALT': 'WELT GESCHAFFT · LOKAL',
    'VIND & GENSTANDE': 'WIND & OBJEKTE',
    'VIND · TESTBANE': 'WIND · TESTLEVEL',
    'VIND · {0}': 'WIND · {0}',
    'VINDKLOKKEN RAMT': 'WINDSPIEL GETROFFEN',
    'VINDVERDEN · LOKALT': 'WINDWELT · LOKAL',
    'Vindmøller': 'Windräder',
    'VINDMØLLER': 'WINDRÄDER',
    'Vulkanen': 'Der Vulkan',
    'VULKANEN': 'DER VULKAN',
    'FJENDER & ANGREB': 'FEINDE & ANGRIFFE',
    'FUGLETRAFIK · TESTBANE': 'VOGELVERKEHR · TESTLEVEL',
    'FUGLE & ROVFUGL': 'VÖGEL & RAUBVOGEL',
    'FLAPPY-STYRING': 'FLAPPY-STEUERUNG',
    'FLAPPY-STYRING · TAP': 'FLAPPY-STEUERUNG · TIPPEN',
    'VUNDET': 'GEWONNEN',
    'BEHOLDT': 'BEHALTEN',
    'Valgt og klar til at flyve': 'Gewählt und bereit zum Fliegen',
    'Vind bronze, sølv og guld': 'Gewinne Bronze, Silber und Gold',
    'Vind ti vennedueller': 'Gewinne zehn Freundesduelle',
    'Vind · genstande': 'Wind · Objekte',
    'VÆLG HELT': 'HELD WÄHLEN',
    'VÆLG LEVEL': 'LEVEL WÄHLEN',
    'VÆLG SPILTYPE': 'SPIELMODUS WÄHLEN',
    'Vælg Bert': 'Bert wählen', 'Vælg Blok-Johan': 'Blok-Johan wählen', 'Vælg BlueBert': 'BlueBert wählen', 'Vælg BoneBeak': 'BoneBeak wählen',
    'Vælg BrainBird': 'BrainBird wählen', 'Vælg BrickBird': 'BrickBird wählen', 'Vælg Coopinc': 'Coopinc wählen', 'Vælg Fodbold-Bert': 'Fußball-Bert wählen',
    'Vælg Guld-Bert': 'Gold-Bert wählen', 'Vælg InkBird': 'InkBird wählen', 'Vælg MechaBert': 'MechaBert wählen', 'Vælg MossHex': 'MossHex wählen',
    'Vælg Mågen Mogens': 'Möwe Mogens wählen', 'Vælg Ninja-Bert': 'Ninja-Bert wählen', 'Vælg NoirWing': 'NoirWing wählen', 'Vælg Pakke-Bert': 'Paket-Bert wählen',
    'Vælg Pingo': 'Pingo wählen', 'Vælg Prinsesse Søs': 'Prinzessin Søs wählen', 'Vælg PrismWing': 'PrismWing wählen', 'Vælg SkyClaw': 'SkyClaw wählen',
    'Vælg Storm Royale': 'Storm Royale wählen', 'Vælg SugarRush': 'SugarRush wählen', 'Vælg Thor Obby': 'Thor Obby wählen',
    'Vælg bane': 'Level wählen',
    'Vælg leaderboard': 'Rangliste wählen',
    'Vælg level': 'Level wählen',
    'Vælg spiltype': 'Spielmodus wählen',
    'Vælg {0}, {1}': '{0} wählen, {1}',
    'købt': 'gekauft',
    'låst op': 'freigeschaltet',
    '{0} ER LÅST': '{0} IST GESPERRT',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} hat {1} Punkte erreicht. Du hast {2} Versuche im selben Level, und der Flug wird als Schatten gezeigt.',
    '{0} forsøg tilbage · slå {1} point': '{0} Versuche übrig · schlag {1} Punkte',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} fordert dich heraus, {1} Punkte zu schlagen. Du hast drei Versuche.',
    '{0} låst op for {1} fjer': '{0} für {1} Federn freigeschaltet',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} gesperrt. {1}. {2} von {3}. Alternativ {4} Federn.',
    '{0} missionsbelønninger': '{0} Missionsbelohnungen',
    '{0} missionsbelønninger er hentet.': '{0} Missionsbelohnungen sind abgeholt.',
    '{0} point til næste medalje': '{0} Punkte bis zur nächsten Medaille',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Sind beide Anforderungen erfüllt, öffnet sich ganz Stufe {2}.',
    '{0} · {1} FASTE LIV': '{0} · {1} FESTE LEBEN',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, gesperrt. Tippen für die Anforderung',
    '{0}, åben, personlig rekord {1}': '{0}, offen, persönlicher Rekord {1}',
    '{0} · Mål {1}': '{0} · Ziel {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} LEVEL · {2}/{3} MISSIONEN',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} LEVEL · {2}/{3} MISS.',
    '{0} BANER · {1}': '{0} LEVEL · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} OFFEN · {2}',
    'DU MANGLER {0} FJER': 'DIR FEHLEN {0} FEDERN',
    'BESKYTTET · {0}s': 'GESCHÜTZT · {0}s',
    'ÅBN DAGENS MISSIONER': 'TAGESMISSIONEN ÖFFNEN',
    'ÅBN GARDEROBE · 17 HELTE': 'GARDEROBE ÖFFNEN · 17 HELDEN',
    'ÅNDENDE PORTE': 'ATMENDE TORE',
    'Åbn dagens missioner': 'Tagesmissionen öffnen',
    'Åbn highscore': 'Highscore öffnen',
    'Åbn indstillinger': 'Einstellungen öffnen',
    'ÉN CHANCE MERE?': 'NOCH EINE CHANCE?',
    'Sprog': 'Sprache',
    'Automatisk (som telefonen)': 'Automatisch (wie das Handy)',
    'Dansk': 'Dänisch', 'Engelsk': 'Englisch', 'Norsk': 'Norwegisch', 'Svensk': 'Schwedisch', 'Tysk': 'Deutsch', 'Spansk': 'Spanisch', 'Fransk': 'Französisch', 'Portugisisk': 'Portugiesisch',
    '+1 FJER': '+1 FEDER',
    'En ven': 'Ein Freund',
    'Dig': 'Du',
    'REKORD': 'REKORD',
    'Topflyvning': 'Spitzenflug',
    '{0} point i {1}': '{0} Punkte in {1}',
    'en bane': 'einem Level',
    '{0} til trin {1} · {2} stjerner': '{0} bis Stufe {1} · {2} Sterne',
    '{0} · {1} stjerner samlet': '{0} · {1} Sterne gesammelt',
    '{0} FJER': '{0} FEDERN',
    'TAP FOR AT FLYVE': 'TIPPEN ZUM FLIEGEN',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Schlag den Score deines Freundes im selben Level. Du hast drei Versuche, und sein Geisterflug begleitet dich.",
    '{0}/{1} BRONZE': '{0}/{1} BRONZE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Hol Bronze (20 Punkte) in allen {0} Grundlevels, um Abenteuer zu öffnen. Du hast {1}.',
    'SØLV I {0}': 'SILBER IN {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Hol Silber (50 Punkte) in {0}, um {1} zu öffnen.',
    'LAVAEN FALDER': 'DIE LAVA SINKT',
    'GODT GREB · {0}s': 'GUTER GRIFF · {0}s',
    'VINDSTØD · OP': 'BÖE · HOCH',
    'VINDSTØD · NED': 'BÖE · RUNTER',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'GLATTES EIS: FRÜH LENKEN · FROSTKRISTALLE SAMMELN',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'ACHTUNG BÖEN · DIE PFEILE ZEIGEN DIE RICHTUNG',
    'LAVAEN STIGER · SAML KØLESTEN': 'DIE LAVA STEIGT · KÜHLSTEINE SAMMELN',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'DAS LICHT ERLISCHT LANGSAM · LATERNEN SAMMELN',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'DIE CONTAINER BEWEGEN SICH · VORSICHT MÖWEN',
    'Fugleklat': 'Vogelklecks',
    'SPIS & KLAT': 'FRESSEN & KLECKSEN',
    'PARAPLYEN REDDEDE DEM': 'DER SCHIRM HAT SIE GERETTET',
    'GULDBIL! ×3': 'GOLDAUTO! ×3',
    'PLASK!': 'PLATSCH!',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'FRISS FUTTER · TIPPE 💩, UM ZIELE UNTEN ZU TREFFEN',
    'Slip en klat': 'Klecks fallen lassen',
    'Alle helte flyver ens. Vind dem i spillet, eller spar fjer sammen.': 'Alle Helden fliegen gleich. Gewinne sie im Spiel oder spare Federn.',
    'ÅBN GARDEROBE': 'GARDEROBE ÖFFNEN',
    'OP · EVIGT SKJOLD · INGEN REKORDER': 'OP · EWIGER SCHILD · KEINE REKORDE',
    'FORSTØR': 'VERGRÖSSERN',
    'FORMINDSK': 'VERKLEINERN',
    'FORSTØR · POINT ×2': 'VERGRÖSSERN · PUNKTE ×2',
    'FØLG TUNNELEN · HOLD VENSTRE = OP · HØJRE = NED': 'FOLGE DEM TUNNEL · LINKS HALTEN = HOCH · RECHTS = RUNTER',
    // Feedback 4. okt.: reden, æg, mærker, eventyr-låse, lyd.
    "Vælg én starthelt efter 10, 20, 30 og 40 ture": "Wähle einen Starthelden nach 10, 20, 30 und 40 Flügen",
    "Nå 600 point på én tur": "Erreiche 600 Punkte in einem Flug",
    "Nå guld i alle tre Classic-baner": "Hol Gold auf allen drei Classic-Strecken",
    "Kun fra et æg i reden": "Nur aus einem Ei im Nest",
    "Kun fra et æg i reden (sjælden)": "Nur aus einem Ei im Nest (selten)",
    "Æggebert": "Eierbert",
    "ÆGGEBERT": "EIERBERT",
    "Vælg Æggebert": "Wähle Eierbert",
    "Klæk alle helte fra rugepladsen": "Brüte alle Helden im Brutplatz aus",
    "KLÆK ALLE": "ALLE AUSBRÜTEN",
    "Blød rede": "Weiches Nest",
    "Et sted at lande. Fjer bygger den videre.": "Ein Ort zum Landen. Federn bauen es weiter aus.",
    "Redningsfjer": "Rettungsfeder",
    "REDNINGSFJER": "RETTUNGSFEDER",
    "Ét redningsliv på hver tur.": "Ein Rettungsleben pro Flug.",
    "Stærkere magnet": "Stärkerer Magnet",
    "Magneten trækker 30 % længere.": "Der Magnet zieht 30 % weiter.",
    "Varmt skjold": "Warmer Schild",
    "Skjoldet holder 2 sekunder længere.": "Der Schild hält 2 Sekunden länger.",
    "Hurtig start": "Schnellstart",
    "Usårlig med ekstra fart de første 5 sekunder.": "Unverwundbar mit Extra-Tempo in den ersten 5 Sekunden.",
    "To redningsliv": "Zwei Rettungsleben",
    "To redningsliv på hver tur.": "Zwei Rettungsleben pro Flug.",
    "Guldrede": "Goldnest",
    "Stjerner giver +1 point de første 10 sekunder.": "Sterne geben +1 Punkt in den ersten 10 Sekunden.",
    "Første flyvetur": "Erster Flug",
    "Gennemfør din første tur": "Beende deinen ersten Flug",
    "Første stjerne": "Erster Stern",
    "Saml din første stjerne": "Sammle deinen ersten Stern",
    "Første fjer": "Erste Feder",
    "Find din første gyldne fjer": "Finde deine erste goldene Feder",
    "Vind din første bronzemedalje": "Gewinne deine erste Bronzemedaille",
    "Ny ven": "Neuer Freund",
    "Lås din første ekstra helt op": "Schalte deinen ersten Extra-Helden frei",
    "Sølv": "Silber",
    "Vind sølv på en bane": "Gewinne Silber auf einer Strecke",
    "Guld": "Gold",
    "Vind guld på en bane": "Gewinne Gold auf einer Strecke",
    "I flow": "Im Flow",
    "Nå en streak på 10": "Erreiche eine Serie von 10",
    "Ustoppelig": "Unaufhaltsam",
    "Nå en streak på 25": "Erreiche eine Serie von 25",
    "Stjerneregn": "Sternenregen",
    "Saml 100 stjerner på én tur": "Sammle 100 Sterne in einem Flug",
    "Højtflyver": "Überflieger",
    "Få 500 point på én tur": "Erreiche 500 Punkte in einem Flug",
    "Udholdenhed": "Ausdauer",
    "Flyv 3 minutter på én tur": "Fliege 3 Minuten in einem Flug",
    "Fejlfri": "Fehlerlos",
    "Guld uden redningsliv eller redningsspin": "Gold ohne Rettungsleben oder Rettungsdreh",
    "Klassiker": "Klassiker",
    "Bronze på alle Classic-baner": "Bronze auf allen Classic-Strecken",
    "Skorstensfejer": "Schornsteinfeger",
    "Bronze på alle Flappy-baner": "Bronze auf allen Flappy-Strecken",
    "Tunnelrytter": "Tunnelreiter",
    "Bronze på alle Tunnel-baner": "Bronze auf allen Tunnel-Strecken",
    "Eventyrer": "Abenteurer",
    "Lås Eventyr op": "Schalte Abenteuer frei",
    "Verdensflyver": "Weltflieger",
    "Sølv på alle seks eventyrbaner": "Silber auf allen sechs Abenteuerstrecken",
    "Lavalord": "Lavafürst",
    "Guld på Vulkanen": "Gold auf dem Vulkan",
    "Mesterskytte": "Meisterschütze",
    "10 træffere i træk i Fugleklat": "10 Treffer am Stück in Vogelklecks",
    "Publikumsvølge": "Publikumswelle",
    "Kom forbi tre bolde i én koncertbølge": "Komm an drei Bällen in einer Konzertwelle vorbei",
    "Fri af rovfuglen": "Dem Raubvogel entkommen",
    "Undvig den varslede rovfugl": "Weiche dem angekündigten Raubvogel aus",
    "Undvig en flyvende genstand i storm": "Weiche im Sturm einem fliegenden Gegenstand aus",
    "Portløber": "Torläufer",
    "Klar alle tre porte i én Sky Relay-runde": "Schaffe alle drei Tore in einer Sky-Relay-Runde",
    "Ekstranummer": "Zugabe",
    "Sølv i Neon Encore": "Silber in Neon Encore",
    "Pakket ind": "Eingewickelt",
    "Bliv fanget af edderkoppen": "Lass dich von der Spinne fangen",
    "Snack": "Snack",
    "Bliv fanget af slangen": "Lass dich von der Schlange fangen",
    "Grillkylling": "Brathähnchen",
    "Dø 50 gange i alt": "Stürze insgesamt 50-mal",
    "Flokken": "Der Schwarm",
    "Lås 10 helte op": "Schalte 10 Helden frei",
    "Redebygger": "Nestbauer",
    "Saml 100 fjer i alt": "Sammle insgesamt 100 Federn",
    "GAME OVER": "GAME OVER",
    "MAGNET": "MAGNET",
    "Få bronze på alle tre Classic-baner for at åbne Havnen.": "Hol Bronze auf allen drei Classic-Strecken, um den Hafen zu öffnen.",
    "Få bronze på alle tre Flappy-baner for at åbne Nattebyen.": "Hol Bronze auf allen drei Flappy-Strecken, um die Nachtstadt zu öffnen.",
    "Få bronze på alle tre Tunnel-baner for at åbne Vindmøller.": "Hol Bronze auf allen drei Tunnel-Strecken, um die Windräder zu öffnen.",
    "Få sølv i to af Havnen, Nattebyen og Vindmøller for at åbne Vulkanen.": "Hol Silber in zwei von Hafen, Nachtstadt und Windrädern, um den Vulkan zu öffnen.",
    "GULD PÅ EN BANE": "GOLD AUF EINER STRECKE",
    "SØLV I VULKANEN": "SILBER IM VULKAN",
    "Få sølv i Vulkanen og guld på én af grundbanerne for at åbne Isbjerget.": "Hol Silber im Vulkan und Gold auf einer Grundstrecke, um den Eisberg zu öffnen.",
    "SØLV I ISBJERGET": "SILBER IM EISBERG",
    "Få sølv i Isbjerget for at åbne Fugleklat.": "Hol Silber im Eisberg, um Vogelklecks zu öffnen.",
    "ÅBNER MED EVENTYR": "ÖFFNET MIT ABENTEUER",
    "Testbanerne åbner sammen med den første eventyrverden.": "Die Teststrecken öffnen mit der ersten Abenteuerwelt.",
    "HEMMELIG": "GEHEIM",
    "LÅST": "GESPERRT",
    "Låst. Tryk på helten for at se, hvordan du får den.": "Gesperrt. Tippe auf den Helden, um zu sehen, wie du ihn bekommst.",
    "En hemmelig helt. Den hører til et særligt pilotnavn.": "Ein geheimer Held. Er gehört zu einem besonderen Pilotennamen.",
    "Du kan vælge en starthelt nu.": "Du kannst jetzt einen Starthelden wählen.",
    "Eller klæk den fra et æg, når reden har nået trin 4.": "Oder brüte ihn aus einem Ei, sobald das Nest Stufe 4 erreicht.",
    "REDEN ER FÆRDIG": "DAS NEST IST FERTIG",
    "Alle syv trin er bygget. Flot!": "Alle sieben Stufen sind gebaut. Super!",
    "Du fandt et æg! Det ligger i reden og ruger.": "Du hast ein Ei gefunden! Es wird im Nest ausgebrütet.",
    "VÆLG EN NY HELT": "WÄHLE EINEN NEUEN HELDEN",
    "Du må vælge én. De andre kan vælges efter 10 ture mere.": "Wähle einen. Die anderen nach 10 weiteren Flügen.",
    "SENERE": "SPÄTER",
    "Én tur om dagen giver fjer": "Ein Flug am Tag bringt Federn",
    "Ruger et tilfældigt æg. Saml stjerner, så klækker det.": "Brütet ein zufälliges Ei aus. Sammle Sterne, dann schlüpft es.",
    "TOM": "LEER",
    "ALLE KLÆKKET": "ALLE GESCHLÜPFT",
    "Alle helte er klækket": "Alle Helden sind geschlüpft",
    "fjer": "Federn",
    "sjælden": "selten",
    "Et æg ligger i reden. Saml stjerner, så klækker det.": "Ein Ei liegt im Nest. Sammle Sterne, dann schlüpft es.",
    "ER DU SIKKER? TRYK IGEN": "BIST DU SICHER? NOCHMAL TIPPEN",
    "GLOBAL HIGHSCORE": "GLOBALE BESTENLISTE",
    "Du mangler fjer. Flyv en tur, og klar dagens missioner.": "Dir fehlen Federn. Fliege eine Runde und schaffe die heutigen Missionen.",
    "{0}/3 CLASSIC": "{0}/3 CLASSIC",
    "{0}/3 FLAPPY": "{0}/3 FLAPPY",
    "{0}/3 TUNNEL": "{0}/3 TUNNEL",
    "SØLV {0}/2": "SILBER {0}/2",
    "LÅST · {0}/{1}": "GESPERRT · {0}/{1}",
    "Vælg den som starthelt efter {0} ture. Du har fløjet {1}.": "Wähle ihn nach {0} Flügen als Starthelden. Du bist {1} geflogen.",
    "Klæk alle helte fra rugepladsen. {0}/{1} klækket.": "Brüte alle Helden aus. {0}/{1} geschlüpft.",
    "Bedrift: {0} ({1}/{2}).": "Leistung: {0} ({1}/{2}).",
    "Eller klæk den fra et æg i reden: sikret æg {0} fjer.": "Oder brüte ihn aus einem Ei im Nest: gewähltes Ei {0} Federn.",
    "Du har {0} fjer. Fjer får du af dagens missioner, en tur om dagen og sjældne fjer i banerne.": "Du hast {0} Federn. Federn gibt es für Tagesmissionen, einen Flug pro Tag und seltene Federn auf den Strecken.",
    "BYG · {0} FJER": "BAUEN · {0} FEDERN",
    "BYG · 20 FJER": "BAUEN · 20 FEDERN",
    "MANGLER {0} FJER": "FEHLEN {0} FEDERN",
    "{0} TURE FLØJET": "{0} FLÜGE GEFLOGEN",
    "{0} er din nu": "{0} gehört jetzt dir",
    "Ægget klækkede: {0}!": "Das Ei ist geschlüpft: {0}!",
    "{0} er klækket og venter i garderoben": "{0} ist geschlüpft und wartet in der Garderobe",
    "Ægget: {0}/{1} stjerner": "Das Ei: {0}/{1} Sterne",
    "{0} fjer fundet": "{0} Federn gefunden",
    "Dag {0} i træk: +{1} fjer": "Tag {0} in Folge: +{1} Federn",
    "Reden: {0}/{1} til {2}": "Nest: {0}/{1} bis {2}",
    "Nyt mærke: {0}": "Neues Abzeichen: {0}",
    "{0} dage i træk": "{0} Tage in Folge",
    "{0}/{1} STJERNER": "{0}/{1} STERNE",
    "Ruger: {0}": "Brütet: {0}",
    "{0} helte kan stadig klækkes": "{0} Helden können noch schlüpfen",
    "TILFÆLDIGT ÆG · {0} FJER": "ZUFALLSEI · {0} FEDERN",
    "SIKRET ÆG · {0} FJER": "GEWÄHLTES EI · {0} FEDERN",
    "TILFÆLDIGT ÆG": "ZUFALLSEI",
    "SIKRET ÆG": "GEWÄHLTES EI",
    "Et sikret æg med {0} ligger i reden": "Ein gewähltes Ei mit {0} liegt im Nest",
    "Reden er bygget: {0}": "Nest gebaut: {0}",
    "Dag {0} i træk · +{1} fjer til reden": "Tag {0} in Folge · +{1} Federn fürs Nest",
    "Bert The Bird – flyvespil og præcisionsverdener": "Bert The Bird – Flugspiel und Präzisionswelten",
    "PAUSE": "PAUSE",
    "REDEN": "DAS NEST",
    "Reden": "Das Nest",
    "Åbn reden": "Nest öffnen",
    "Luk reden": "Nest schließen",
    "Redens trin": "Nest-Stufen",
    "NÆSTE TRIN": "NÄCHSTE STUFE",
    "RUGEPLADSEN": "DER BRUTPLATZ",
    "FLYV HVER DAG": "FLIEG JEDEN TAG",
    "MÆRKER": "ABZEICHEN",
    "Fjer bygger reden. Hvert trin kan mærkes i spillet. Efter døden kan du bruge 12 fjer på ét redningsspin.": "Federn bauen das Nest. Jede Stufe spürst du im Spiel. Nach einem Absturz kannst du 12 Federn für einen Rettungsdreh ausgeben.",
    "Forrige helte": "Vorherige Helden",
    "Næste helte": "Nächste Helden",
    "Musikstyrke": "Musiklautstärke",
    "Lydstyrke for effekter": "Effektlautstärke",
    "Vælg helt til sikret æg": "Held für das gewählte Ei wählen",
    "Banens grafik kunne ikke indlæses.": "Die Grafik der Strecke konnte nicht geladen werden.",
    "Spillet kunne ikke indlæses. Prøv igen.": "Das Spiel konnte nicht geladen werden. Versuch es noch einmal.",
    "NY HELT: {0} · {1}": "NEUER HELD: {0} · {1}",
    "Klæk den fra et æg i reden: sikret æg {0} fjer.": "Brüte ihn aus einem Ei im Nest: gewähltes Ei {0} Federn.",
    "Klæk den fra et æg, når reden har nået trin 4.": "Brüte ihn aus einem Ei, sobald das Nest Stufe 4 erreicht.",
    // Udfordringer (10. okt.)
    "Få 40 point uden redningsliv": "Erreiche 40 Punkte ohne Rettungsleben",
    "Få 80 point uden redningsliv": "Erreiche 80 Punkte ohne Rettungsleben",
    "Find en gylden fjer i en bane": "Finde eine goldene Feder auf einer Strecke",
    "Få 60 point uden at tage en power-up": "Erreiche 60 Punkte ohne Power-up",
    "Saml 400 stjerner i denne uge": "Sammle diese Woche 400 Sterne",
    "Flyv 30 ture i denne uge": "Fliege diese Woche 30 Runden",
    "Guld på 2 forskellige baner i denne uge": "Gold auf 2 verschiedenen Strecken diese Woche",
    "Slå din egen rekord 3 gange": "Brich deinen eigenen Rekord 3-mal",
    "Flyv på 6 forskellige baner": "Fliege auf 6 verschiedenen Strecken",
    "Flyv 30 minutter i denne uge": "Fliege diese Woche 30 Minuten",
    "Lynhurtig: styrt inden for 1 sekund": "Blitzschnell: Absturz in unter 1 Sekunde",
    "Svaret på alt: præcis 42 point": "Die Antwort auf alles: genau 42 Punkte",
    "Natteravn: flyv mellem midnat og kl. 4": "Nachteule: fliege zwischen Mitternacht und 4 Uhr",
    "Tålmodig: 60 sekunder uden en eneste stjerne": "Geduldig: 60 Sekunden ohne einen einzigen Stern",
    "Sultestrejke: 30 sekunder og 0 stjerner": "Hungerstreik: 30 Sekunden und 0 Sterne",
    "Jo større de er: styrt mens du er forstørret": "Je größer sie sind: stürze, während du groß bist",
    "Juleflyver: flyv juleaften": "Weihnachtsflieger: fliege an Heiligabend",
    "Hattrick: tre ture i træk med samme point": "Hattrick: drei Runden hintereinander mit gleicher Punktzahl",
    "Garderobe-gal: flyv med 7 forskellige helte": "Kleiderschrank-Fan: fliege mit 7 verschiedenen Helden",
    "Maraton: 10 minutter på én tur": "Marathon: 10 Minuten in einem Flug",
    "Ørkenrotte: 100 ture i Desert": "Wüstenratte: 100 Flüge in Desert",
    "Halvtreds: en streak på 50": "Fünfzig: eine Serie von 50",
    "Flappy-mester: 500 point i Flappy Bert": "Flappy-Meister: 500 Punkte in Flappy Bert",
    "Bonk-serie: 5 styrt på 2 minutter": "Bonk-Serie: 5 Abstürze in 2 Minuten",
    "Edderkoppens ven: fanget 10 gange": "Freund der Spinne: 10-mal gefangen",
    "Saml {0} stjerner i dag": "Sammle heute {0} Sterne",
    "Flyv {0} minutter i alt i dag": "Fliege heute insgesamt {0} Minuten",
    "Nå en streak på {0}": "Erreiche eine Serie von {0}",
    "Flyv {0} ture i dag": "Fliege heute {0} Runden",
    "Få {0} point på én tur": "Erreiche {0} Punkte in einem Flug",
    "Tag {0} power-ups i dag": "Sammle heute {0} Power-ups",
    "Flyv {0} sekunder på én tur": "Fliege {0} Sekunden in einem Flug",
    "Bronze i {0} i dag": "Heute Bronze in {0}",
    "Sølv i {0} i dag": "Heute Silber in {0}",
    "Guld i {0} i dag": "Heute Gold in {0}",
    "Tur nr. {0}": "Flug Nr. {0}",
    "{0} stjerner i alt": "{0} Sterne insgesamt",
    "{0} fjer samlet i alt": "{0} Federn insgesamt",
    "{0} helte": "{0} Helden",
    "{0} mærker": "{0} Abzeichen",
    "Reden på trin {0}": "Nest auf Stufe {0}",
    "{0} æg klækket": "{0} Eier geschlüpft",
    "{0}: guld": "{0}: Gold",
    "{0}: 200 point": "{0}: 200 Punkte",
    "{0}: 60 point uden redning og power-ups": "{0}: 60 Punkte ohne Rettung und Power-ups",
    "??? (hemmelig udfordring)": "??? (geheime Herausforderung)",
    "Tæt på: {0} ({1}/{2})": "Fast geschafft: {0} ({1}/{2})",
    "+{0} fjer · {1}": "+{0} Federn · {1}",
    "UGENS UDFORDRINGER": "WOCHEN-HERAUSFORDERUNGEN",
    "UDFORDRINGER": "HERAUSFORDERUNGEN",
    "MILEPÆLE": "MEILENSTEINE",
    "MESTERSKAB": "MEISTERSCHAFT",
    "HEMMELIGE": "GEHEIM",
    "NIVEAU {0}!": "STUFE {0}!",
    "HVOR SKAL BERT HEN?": "WOHIN FLIEGT BERT?",
    "DIN REJSE": "DEINE REISE",
    "Ørkenen": "Die Wüste",
    "Junglen": "Der Dschungel",
    "Himlen": "Der Himmel",
    "Byen": "Die Stadt",
    "Tunnelen": "Der Tunnel",
    "Natten": "Die Nacht",
    "Vinden": "Der Wind",
    "Isen": "Das Eis",
    "Fugleklat-øen": "Vogelklecks-Insel",
    "Spejlbanen": "Spiegelstrecke",
    "GLID & OPVIND · TESTBANE": "GLEITEN & AUFWIND · TESTSTRECKE",
    "GLID & OPVIND": "GLEITEN & AUFWIND",
    "Svæv": "Gleiten",
    "Vælg et andet navn": "Wähle einen anderen Namen",
    "FLOK & FORMATION · TESTBANE": "SCHWARM & FORMATION · TESTSTRECKE",
    "FLOK & FORMATION": "SCHWARM & FORMATION",
    "Fuglesværm": "Vogelschwarm",
    "Klistermærke fundet! Se det i albummet i reden": "Sticker gefunden! Schau ihn dir im Album im Nest an",
    "KLISTERMÆRKER": "STICKER",
    "Fem skjulte klistermærker i hver bane. Hold øje, mens du flyver.": "Fünf versteckte Sticker auf jeder Strecke. Halte beim Fliegen die Augen offen.",
    "Flokken": "Der Schwarm",
    "UDFORDRER": "HERAUSFORDERER",
    "NYT": "NEU",
    "FLOKKEN": "DER SCHWARM",
    "ALLE MOD ALLE I EN STOR HIMMEL": "ALLE GEGEN ALLE IN EINEM GROSSEN HIMMEL",
    "Få sølv (50 point) i {0} for at åbne bonusbanen {1}.": "Hol Silber (50 Punkte) in {0}, um die Bonusstrecke {1} zu öffnen.",
    "UGENS BONUS": "WOCHENBONUS",
    "DOBBELT BELØNNING · {0} DAGE TILBAGE": "DOPPELTE BELOHNUNG · NOCH {0} TAGE",
    "Ugens bonus: +{0} fjer til reden": "Wochenbonus: +{0} Federn fürs Nest",
    "2× FJER · {0} DAGE": "2× FEDERN · {0} TAGE",
    // Introkort før banen (10. okt.)
    "Hold venstre side = op · højre side = ned": "Links halten = hoch · rechts halten = runter",
    "Tryk for at baske · slip for at falde": "Tippen zum Flattern · loslassen zum Fallen",
    "Flyv mellem søjlerne og saml stjerner. Banen bliver hurtigere, og hullerne bliver mindre.": "Fliege zwischen den Säulen und sammle Sterne. Es wird schneller, die Lücken kleiner.",
    "Pas på slanger, der hopper op, og edderkopper, der hænger i spind.": "Achtung vor Schlangen, die hochspringen, und Spinnen im Netz.",
    "Slikstårne ruller og står skævt. Find hullet i tide.": "Süßigkeitentürme rollen und stehen schief. Finde rechtzeitig die Lücke.",
    "Flappy: flyv gennem hullerne mellem skorstenene.": "Flappy: fliege durch die Lücken zwischen den Schornsteinen.",
    "Flappy: hullerne skifter højde, mens du flyver.": "Flappy: die Lücken wechseln beim Fliegen die Höhe.",
    "Flappy: den sværeste af de tre. Små huller og høj fart.": "Flappy: die schwerste der drei. Kleine Lücken, hohes Tempo.",
    "Følg tunnelen, og rør ikke væggene.": "Folge dem Tunnel und berühre nicht die Wände.",
    "Tunnelen snor sig mere og bliver smallere.": "Der Tunnel windet sich stärker und wird enger.",
    "Den hurtigste tunnel. Hold dig i midten.": "Der schnellste Tunnel. Bleib in der Mitte.",
    "Containerne flytter sig. Pas på kranekroge og måger.": "Die Container bewegen sich. Achtung vor Kranhaken und Möwen.",
    "Lyset slukker langsomt. Saml lanterner for at kunne se.": "Das Licht geht langsam aus. Sammle Laternen, um zu sehen.",
    "Vinden skubber dig. Pas på møllevinger og drager.": "Der Wind schiebt dich. Achtung vor Rotorblättern und Drachen.",
    "Lavaen stiger. Saml kølesten, og undgå bomber og meteorer.": "Die Lava steigt. Sammle Kühlsteine und weiche Bomben und Meteoren aus.",
    "Glat styring: Bert glider efter. Styr i god tid.": "Glatte Steuerung: Bert rutscht nach. Lenke früh.",
    "Spis mad, og tryk på 💩 for at ramme mål nedenunder.": "Iss Futter und tippe 💩, um Ziele unten zu treffen.",
    "Koncert: kom forbi boldene, når publikum laver bølgen.": "Konzert: komm an den Bällen vorbei, wenn das Publikum die Welle macht.",
    "Flyv med flokken, og undgå rovfuglen, når den varsles.": "Fliege mit dem Schwarm und weiche dem angekündigten Raubvogel aus.",
    "Stormen kaster ting efter dig. Hold øje med pilene.": "Der Sturm wirft Dinge nach dir. Achte auf die Pfeile.",
    "Flyv gennem tre skyporte, og ring med klokken. Portene bliver mindre.": "Fliege durch drei Wolkentore und läute die Glocke. Die Tore werden kleiner.",
    "Ingen vingeslag: op koster fart, ned giver fart. Find opvinden, og flyv langt.": "Kein Flügelschlag: hoch kostet Tempo, runter gibt Tempo. Finde Aufwinde und fliege weit.",
    "Hver 10. stjerne i træk giver en fugl i flokken. Et sammenstød koster en fugl i stedet for turen.": "Jeder 10. Stern in Folge bringt einen Vogel. Ein Zusammenstoß kostet einen Vogel statt des Flugs.",
    "Saml stjerner, og undgå forhindringerne.": "Sammle Sterne und weiche den Hindernissen aus.",
    "BONUSBANE": "BONUSSTRECKE",
    "SPEJLVENDT": "GESPIEGELT",
    "Rekord {0} · bronze 20 · sølv 50 · guld 100": "Rekord {0} · Bronze 20 · Silber 50 · Gold 100",
    "Bronze 20 · sølv 50 · guld 100": "Bronze 20 · Silber 50 · Gold 100",
    "TRYK FOR AT FLYVE": "TIPPEN ZUM FLIEGEN",
    "BONUSBANE · {0}": "BONUSSTRECKE · {0}",
    "Hjertet i halsen: 10 nærdødsoplevelser på én tur": "Herz in der Hose: 10 Beinahe-Treffer in einem Flug",
    "Dødsforagt: 25 nærdødsoplevelser på én tur": "Todesmutig: 25 Beinahe-Treffer in einem Flug",
    "Kort og godt: 20 point på under 20 sekunder": "Kurz und gut: 20 Punkte in unter 20 Sekunden",
    "Stjernestøvsuger: 50 stjerner på én tur": "Sternensauger: 50 Sterne in einem Flug",
    "Power-samler: 5 power-ups på én tur": "Power-Sammler: 5 Power-ups in einem Flug",
    "Comeback: brug et redningsliv, og slå din rekord": "Comeback: nutze ein Rettungsleben und brich deinen Rekord",
    "Stabil: 5 ture i træk over 50 point": "Beständig: 5 Flüge in Folge über 50 Punkte",
    "Turist: 6 forskellige baner på én dag": "Tourist: 6 verschiedene Strecken an einem Tag",
    "Ren luft: 100 point uden power-ups og redning": "Saubere Luft: 100 Punkte ohne Power-ups und Rettung",
    "Udholdende: 4 minutter på én tur": "Ausdauer: 4 Minuten in einem Flug",
    "Dobbelt op: slå din rekord to gange samme dag": "Doppelt hält besser: brich deinen Rekord zweimal an einem Tag",
    "Allround: bronze på en Classic-, en Flappy- og en Tunnel-bane samme dag": "Allrounder: Bronze auf einer Classic-, Flappy- und Tunnel-Strecke am selben Tag",
    "Ny rekord på {0}!": "Neuer Rekord auf {0}!",
    "Din {0}. bedste tur ud af {1} her": "Dein {0}. bester Flug von {1} hier",
    "Bedre end {0} % af dine ture her": "Besser als {0} % deiner Flüge hier",
    "{0} nærdødsoplevelser": "{0} Beinahe-Treffer",
    "Længste stjernerække: x{0}": "Längste Sternenserie: x{0}",
    "{0} power-ups taget": "{0} Power-ups genommen",
    "I luften i {0}": "In der Luft für {0}",
    "{0} gyldne fjer fundet": "{0} goldene Federn gefunden",
    "{0} fugle i flokken til sidst": "{0} Vögel im Schwarm am Ende",
    "Det kan kun gå fremad herfra. Prøv at holde dig midt på skærmen.": "Ab jetzt geht es nur bergauf. Bleib möglichst in der Bildschirmmitte.",
    "Dit snit her er {0}. Næste tur sidder den!": "Dein Schnitt hier ist {0}. Der nächste Flug sitzt!",
    "TURE": "FLÜGE",
    "{0} mønter til samlefigurer": "{0} Münzen für Sammelfiguren",
    "Almindelig": "Gewöhnlich",
    "Sjælden": "Selten",
    "Episk": "Episch",
    "Legendarisk": "Legendär",
    "SAMLEFIGURER": "SAMMELFIGUREN",
    "ÅBN PAKKE · {0} MØNTER": "PACK ÖFFNEN · {0} MÜNZEN",
    "BYT 3 DUBLETTER ({0})": "3 DOPPELTE TAUSCHEN ({0})",
    "Pakke med 3 figurer, den sidste mindst sjælden. Chancer: almindelig 70 %, sjælden 22 %, episk 7 %, legendarisk 1 %.": "Pack mit 3 Figuren, die letzte mindestens selten. Chancen: gewöhnlich 70 %, selten 22 %, episch 7 %, legendär 1 %.",
    "NY!": "NEU!",
    "DUBLET": "DOPPELT",
});
