/* Português (Brasil). As chaves são os textos dinamarqueses originais. */
window.BertI18n.register('pt', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FAÇA UM VOO PARA MARCAR SUA PRIMEIRA PONTUAÇÃO',
    ' · MÆRKE: {0}': ' · INSÍGNIA: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · JOGUE UM DUELO COM AMIGOS PARA TER UM RIVAL',
    '+{0} fjer til reden': '+{0} penas para o ninho',
    '+{0} fjer · {1} låst op': '+{0} penas · {1} desbloqueado',
    '0 / 0 POINT': '0 / 0 PONTOS',
    '20 point til bronze': '20 pontos para o bronze',
    '3 SPILFORMER · 9 BANER': '3 MODOS · 9 FASES',
    '3 baner · hold op/ned': '3 fases · segure cima/baixo',
    '3 baner · præcision': '3 fases · precisão',
    '3 baner · tap': '3 fases · toque',
    '9 baner · nye verdener': '9 fases · novos mundos',
    'ACCEPTÉR': 'ACEITAR',
    'AFSLUT TUREN': 'ENCERRAR O VOO',
    'Alle baner': 'Todas as fases',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Todos os heróis têm a mesma velocidade e área de colisão. Ganhe-os jogando ou junte penas.',
    'Alle pointkrav i trin {0} er klaret.': 'Todos os requisitos de pontos da etapa {0} foram cumpridos.',
    'Alle spil': 'Todos os jogos',
    'Alle tider': 'Sempre',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'As três tentativas foram usadas. Peça um novo duelo ao seu amigo.',
    'BANEN ER LÅST': 'FASE BLOQUEADA',
    'BEKRÆFT · {0} FJER': 'CONFIRMAR · {0} PENAS',
    'BERTS GARDEROBE': 'GUARDA-ROUPA DO BERT',
    'BERTS REDE': 'NINHO DO BERT',
    'BERTS REDNINGSREDE': 'NINHO DE RESGATE DO BERT',
    'BEVÆGELIGE TÅRNE': 'TORRES MÓVEIS',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} estrelas · só recorde local do evento',
    'Bane': 'Fase',
    'Banen er låst': 'A fase está bloqueada',
    'Bedst på level {0} · {1}': 'Melhor na fase {0} · {1}',
    'Bert The Bird appikon': 'Ícone do app Bert The Bird',
    'Bert The Bird bliver installeret': 'Bert The Bird está sendo instalado',
    'Bert The Bird er installeret': 'Bert The Bird está instalado',
    'Bert The Bird spilcanvas': 'Área de jogo do Bert The Bird',
    'Bert flyver': 'Bert voando',
    'Bevægelse i koncertlys': 'Movimento nas luzes do show',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Gaste 12 penas em um giro. Cinco casas devolvem o Bert à fase. Uma casa encerra o voo.',
    'DAGENS MISSIONER': 'MISSÕES DE HOJE',
    'DAGENS RUTE': 'ROTA DE HOJE',
    'DAGENS RUTE · MÅL {0}': 'ROTA DE HOJE · META {0}',
    'DENNE TUR': 'ESTE VOO',
    'DIN FLYVETUR': 'SEU VOO',
    'DIN HELT': 'SEU HERÓI',
    'DIN SALDO': 'SEU SALDO',
    'DINE VENNEDUELLER': 'SEUS DUELOS COM AMIGOS',
    'DREJ TELEFONEN': 'GIRE O CELULAR',
    'DU ER UDFORDRET': 'VOCÊ FOI DESAFIADO',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'VOCÊ VENCEU O DUELO · desafie de volta · {0} estrelas',
    'Den sjældneste fugl · køb for fjer': 'O pássaro mais raro · compre com penas',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Esta fase não pode ser usada em duelos ranqueados com amigos.',
    'Dit navn': 'Seu nome',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Seu nome aparece no ranking e junto aos seus recordes.',
    'Du mangler fjer fra dagens missioner': 'Faltam penas das missões de hoje',
    'EDM-VERDEN · LOKALT': 'MUNDO EDM · LOCAL',
    'EPISK': 'ÉPICO',
    'EVENT · BIRD RUN · TESTBANE': 'EVENTO · BIRD RUN · FASE DE TESTE',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENTO · NEON ENCORE · FASE DE TESTE',
    'EVENT · STORMLINE · TESTBANE': 'EVENTO · STORMLINE · FASE DE TESTE',
    'EVENTYR': 'AVENTURA',
    'EVENTYR · {0}': 'AVENTURA · {0}',
    'Episk helt · kun til dig · valgt': 'Herói épico · só para você · escolhido',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Herói épico · só para você. Toque para escolher.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Uma vida de resgate permanente absorve uma colisão em cada voo. Depois de bater, você também pode gastar 12 penas em um giro de resgate. Sempre dá para continuar jogando sem energia nem espera.',
    'FAST + BEVÆGELIG': 'FIXO + MÓVEL',
    'FASTE TÅRNE': 'TORRES FIXAS',
    'FJER': 'PENAS',
    'FJER RETUR': 'PENAS DE VOLTA',
    'FJER · PRIMÆRT VINDES I SPILLET': 'PENAS · GANHE PRINCIPALMENTE JOGANDO',
    'FLYV': 'VOAR',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'VOE POR TRÊS PORTAIS DE NUVEM · ACERTE A PLACA DOURADA · ESQUERDA SOBE · DIREITA DESCE',
    'FLYV IGEN': 'VOAR DE NOVO',
    'FLYV VIDERE': 'CONTINUAR VOANDO',
    'FLYVETUREN ER SAT PÅ PAUSE': 'O VOO ESTÁ PAUSADO',
    'FODBOLD-BERT': 'BERT FUTEBOLEIRO',
    'FOKUS': 'FOCO',
    'FOKUS OM {0}': 'FOCO EM {0}',
    'FORBI': 'ERROU',
    'FORBI GULDPLADEN': 'ERROU A PLACA DOURADA',
    'FORSTÅET': 'ENTENDI',
    'FORTRYD': 'CANCELAR',
    'FORTSÆT': 'CONTINUAR',
    'FRI AF ROVFUGLEN': 'LIVRE DA AVE DE RAPINA',
    'FUGL BAGFRA': 'PÁSSARO POR TRÁS',
    'FUGLEVERDEN · LOKALT': 'MUNDO DOS PÁSSAROS · LOCAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Quatro mundos de evento locais e grátis sem ranking global',
    'Flyv samlet i 3 minutter': 'Voe 3 minutos no total',
    'Flyvetid': 'Tempo de voo',
    'Fodbold-Bert': 'Bert Futeboleiro',
    'Forbindelsen er tilbage': 'A conexão voltou',
    'Fremgang mod oplåsning': 'Progresso para desbloquear',
    'Fugle · rovfugl': 'Pássaros · ave de rapina',
    'FÆRDIG': 'PRONTO',
    'FØLG STJERNESTRØMMEN': 'SIGA O FLUXO DE ESTRELAS',
    'FØLGER DIG KORT · {0}s': 'SEGUINDO VOCÊ POR UM INSTANTE · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · O VOO TERMINA',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} RESULTADOS',
    'GODT RAMT': 'BOM ACERTO',
    'GRATIS REDNING': 'RESGATE GRÁTIS',
    'GRUNDFLYVNING': 'VOO BÁSICO',
    'GULD': 'OURO',
    'GULD-BERT': 'BERT DOURADO',
    'Guld-Bert': 'Bert Dourado',
    'HAV BERT PÅ STARTSKÆRMEN': 'TENHA O BERT NA TELA INICIAL',
    'HAVNEN': 'O PORTO',
    'Havnen': 'O Porto',
    'HENT FJER': 'PEGAR PENAS',
    'HENT SPILLET': 'BAIXAR O JOGO',
    'HENT +{0}': 'PEGAR +{0}',
    '+{0} FJER': '+{0} PENAS',
    'HENTER RESULTATER …': 'CARREGANDO RESULTADOS …',
    'HENTET': 'RECEBIDO',
    'HOLD OP/NED': 'SEGURE CIMA/BAIXO',
    'HOVEDMENU': 'MENU PRINCIPAL',
    'HVAD HEDDER DU?': 'QUAL É O SEU NOME?',
    'HVORDAN VIL DU FLYVE?': 'COMO VOCÊ QUER VOAR?',
    'HYPERFART': 'HIPERVELOCIDADE',
    'Haptisk feedback': 'Resposta tátil',
    'Har altid en pakke med · køb for fjer': 'Sempre leva um pacote · compre com penas',
    'Hele Bert The Bird er lavet til landscape.': 'Bert The Bird foi feito para a tela na horizontal.',
    'Hemmelig helt': 'Herói secreto',
    'Hent en mission syv dage i træk': 'Resgate uma missão sete dias seguidos',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Resgate {0} recompensas de missão no total; você tem {1}.',
    'Henter resultater …': 'Carregando resultados …',
    'Høj fart': 'Alta velocidade',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'No Safari: Compartilhar → Adicionar à Tela de Início. Aguarde “Pronto para jogar offline” e abra o ícone uma vez com internet antes de testar no modo avião.',
    'I dag': 'Hoje',
    'IKKE NU': 'AGORA NÃO',
    'INDSTILLINGER': 'AJUSTES',
    'INSTALLÉR WEBAPP': 'INSTALAR WEB APP',
    'ISTAPPER & SPIDSER': 'ESTALACTITES & PONTAS',
    'Isbjerget': 'O Iceberg',
    'ISBJERGET': 'O ICEBERG',
    'Bert gør klar til at flyve …': 'Bert está se preparando para voar …',
    'Ingen rekord endnu': 'Ainda sem recorde',
    'Installér som webapp': 'Instalar como web app',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Instale pelo menu do navegador. Aguarde “Pronto para jogar offline” e abra o app uma vez com internet antes de testar offline.',
    'KANT': 'BORDA',
    'KLAR DAGENS MÅL': 'CUMPRA A META DE HOJE',
    'KLARET': 'FEITO',
    'KONCERT · TESTBANE': 'SHOW · FASE DE TESTE',
    'KRANER & MÅGER': 'GUINDASTES & GAIVOTAS',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'SÓ SEUS RESULTADOS LOCAIS · O PLACAR ONLINE NÃO ESTÁ DISPONÍVEL',
    'KVALIFIKATIONSBANEN': 'A FASE CLASSIFICATÓRIA',
    'Klar dagens rute': 'Complete a rota de hoje',
    'Klar dagens rute én gang': 'Complete a rota de hoje uma vez',
    'Klar hele forrige trin og missionskravet først': 'Complete primeiro toda a etapa anterior e o requisito de missões',
    'Klar hele trin {0}: {1}.': 'Complete toda a etapa {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Complete a fase classificatória para abrir este desafio.',
    'Klar til offline-spil': 'Pronto para jogar offline',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Passe por pelo menos três bolas em uma onda do show',
    'KØB': 'COMPRAR',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'COMPRE VIDAS FIXAS OU UM GIRO DE RESGATE',
    'KØB · {0} FJER': 'COMPRAR · {0} PENAS',
    'KØBT': 'COMPRADO',
    'LAVA & BOBLER': 'LAVA & BOLHAS',
    'LEVENDE FORHINDRINGER': 'OBSTÁCULOS VIVOS',
    'LEVERING': 'ENTREGA',
    'LYD & FEEDBACK': 'SOM & RESPOSTA',
    'LYDLØS': 'SILENCIOSO',
    'Level 1 · Mål 30': 'Fase 1 · Meta 30',
    'Luk': 'Fechar',
    'Luk garderoben': 'Fechar o guarda-roupa',
    'Lydeffekter': 'Efeitos sonoros',
    'Lydløs og hurtig · køb for fjer': 'Silencioso e rápido · compre com penas',
    'LÅS OP · 20 FJER': 'DESBLOQUEAR · 20 PENAS',
    'LÅS OP · {0} FJER': 'DESBLOQUEAR · {0} PENAS',
    'LÅST BANE': 'FASE BLOQUEADA',
    'LÅST OP': 'DESBLOQUEADO',
    'LÆR KORRIDOREN': 'APRENDA O CORREDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Desbloqueado. Toque no personagem para escolher.',
    'MAKS LÅST OP': 'MÁXIMO DESBLOQUEADO',
    'MINISPIL · SKY RELAY · LOKALT': 'MINIJOGO · SKY RELAY · LOCAL',
    'MISSIONER': 'MISSÕES',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'CELULAR: LADO ESQUERDO = CIMA · LADO DIREITO = BAIXO',
    'Missioner': 'Missões',
    'Mod vinden': 'Contra o vento',
    'Musik': 'Música',
    'MÅGEN MOGENS': 'MOGENS A GAIVOTA',
    'Mågen Mogens': 'Mogens a Gaivota',
    'MÅL: 3 BOLDE': 'META: 3 BOLAS',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'META: PASSE POR UMA ONDA COM TRÊS BOLAS · ESQUERDA SOBE · DIREITA DESCE',
    'MÅL: ROVFUGL': 'META: AVE DE RAPINA',
    'MÅL: STORM': 'META: TEMPESTADE',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'META: DESVIE DE UMA AVE DE RAPINA · ESQUERDA SOBE · DIREITA DESCE',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'META: DESVIE DE UM OBJETO DA TEMPESTADE · SIGA BANDEIRAS E FOLHAS',
    'MÆRKE VUNDET': 'INSÍGNIA GANHA',
    'MØRKE & SKILTE': 'ESCURIDÃO & PLACAS',
    'Måned': 'Mês',
    'NED': 'BAIXO',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} estrelas · só recorde local do evento',
    'NINJA-BERT': 'BERT NINJA',
    'Ninja-Bert': 'Bert Ninja',
    'NIVEAU {0}! · {1}': 'NÍVEL {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING DESBLOQUEADO · VOO PERFEITO',
    'NY BANE': 'FASE NOVA',
    'NY REKORD!': 'NOVO RECORDE!',
    'NYE VERDENER': 'NOVOS MUNDOS',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NOVA ETAPA: AS TRÊS FASES ESTÃO ABERTAS · {0} estrelas coletadas',
    'NATTEBYEN': 'A CIDADE NOTURNA',
    'Nattebyen': 'A Cidade Noturna',
    'Ny mobilversion indlæst': 'Nova versão mobile carregada',
    'Nyt redningsliv låst op': 'Nova vida de resgate desbloqueada',
    'NÆSTE UDFORDRING': 'PRÓXIMO DESAFIO',
    'Nå 120 point i Desert': 'Chegue a 120 pontos em Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Chegue a 180 pontos sem perder uma estrela nem bater em nada',
    'Nå 300 point på én tur': 'Chegue a 300 pontos em um voo',
    'Nå bronze i Jungle uden redning': 'Consiga bronze em Jungle sem resgate',
    'Nå bronze i alle ni baner': 'Consiga bronze em todas as nove fases',
    'Nå bronze i alle tre Classic-baner': 'Consiga bronze nas três fases Classic',
    'Nå en streak på 12': 'Consiga uma sequência de 12',
    'OMVENDT STYRING': 'CONTROLES INVERTIDOS',
    'OP': 'CIMA',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'O modo offline ainda não está pronto · conecte-se à internet',
    'PAKKE-BERT': 'BERT PACOTE',
    'Pakke-Bert': 'Bert Pacote',
    'PERMANENT REDE-FORDEL': 'VANTAGEM PERMANENTE DO NINHO',
    'PERSONLIG REKORD': 'RECORDE PESSOAL',
    'PILOTER': 'PILOTOS',
    'POINT ×2': 'PONTOS ×2',
    'PORTE & KLOKKE': 'PORTAIS & SINO',
    'PRINSESSE SØS': 'PRINCESA SØS',
    'Prinsesse Søs': 'Princesa Søs',
    'PRÆCISION': 'PRECISÃO',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'VOO DE PRECISÃO · TESTE LOCAL',
    'PRÆCISIONSRUTE · LOKALT': 'ROTA DE PRECISÃO · LOCAL',
    'PUBLIKUMSVØLGE': 'ONDA DO PÚBLICO',
    'Pause spillet': 'Pausar o jogo',
    'Periode': 'Período',
    'Personlig highscore': 'Recorde pessoal',
    'Pilotnavn': 'Nome do piloto',
    'Pingvin med jetpack · køb for fjer': 'Pinguim com jetpack · compre com penas',
    'Point': 'Pontos',
    'Porte · vindklokke': 'Portais · sino de vento',
    'PORT {0}/3': 'PORTAL {0}/3',
    'PORT {0}/3 · {1}': 'PORTAL {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RODADA {0} · PORTAL {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'DING! +{0} · RODADA {1}',
    'Præcisionsflyvning': 'Voo de precisão',
    'RAM GULDPLADEN': 'ACERTE A PLACA DOURADA',
    'RAMT': 'ACERTOU',
    'RANGLISTE': 'RANKING',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'RESGATADO · SUAS 12 PENAS VOLTAM',
    'REDDET · {0}': 'RESGATADO · {0}',
    'REDNINGSLIV': 'VIDA DE RESGATE',
    'REDNINGSLIV 0/3': 'VIDAS DE RESGATE 0/3',
    'REDNINGSLIV {0}/{1}': 'VIDAS DE RESGATE {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'O NINHO DE RESGATE ESTÁ GIRANDO …',
    'REDNINGSSPIN': 'GIRO DE RESGATE',
    'RENT GENNEM': 'PASSAGEM LIMPA',
    'RIGGE & BOLDE': 'ESTRUTURAS & BOLAS',
    'ROTORER & BØJER': 'ROTORES & BOIAS',
    'ROVFUGL': 'AVE DE RAPINA',
    'ROVFUGL BAGFRA': 'AVE DE RAPINA POR TRÁS',
    'FUGL': 'PÁSSARO',
    'BAGFRA': 'POR TRÁS',
    'FORFRA': 'DE FRENTE',
    'RUTEN AFSLUTTET': 'ROTA CONCLUÍDA',
    'Redningsliv tilbage': 'Vidas de resgate restantes',
    'Rigge · bolde': 'Estruturas · bolas',
    'SJÆLDEN': 'RARO',
    'SKIFT BANE': 'TROCAR DE FASE',
    'SKJOLD': 'ESCUDO',
    'SKJOLD BRUGT · 2s': 'ESCUDO USADO · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · BATEU {0} DO PORTAL {1} · 0 PONTOS · TENTE DE NOVO',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 PONTOS · TENTE DE NOVO',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 PORTAIS · {1}% PRECISÃO · SÓ LOCAL',
    'TOPPEN': 'NO TOPO',
    'BUNDEN': 'NA BASE',
    'SKYRING RAMT': 'ANEL DE NUVEM ATINGIDO',
    'SPIL': 'JOGAR',
    'SPIL KVALIFIKATION': 'JOGAR CLASSIFICATÓRIA',
    'SPIL →': 'JOGAR →',
    'SPIL {0}': 'JOGAR {0}',
    'SPIN FOR AT SE DIN REDNING': 'GIRE PARA VER SEU RESGATE',
    'SPIN · 12 FJER': 'GIRAR · 12 PENAS',
    'SPIN · {0} FJER': 'GIRAR · {0} PENAS',
    'START FORFRA': 'RECOMEÇAR',
    'STARTBANE': 'FASE INICIAL',
    'STJERNEREGN': 'CHUVA DE ESTRELAS',
    'STIGER': 'SUBINDO',
    'DYKKER': 'MERGULHANDO',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · VENTO E COISAS VOANDO · {0} estrelas · só recorde local do evento',
    'STREAK REDDET · GUARD BRUGT': 'SEQUÊNCIA SALVA · GUARD USADO',
    'STORMPILOT': 'PILOTO DA TEMPESTADE',
    'Saml 20 stjerner til reden': 'Colete 20 estrelas para o ninho',
    'Saml 250 stjerner i alt': 'Colete 250 estrelas no total',
    'Scoretype': 'Tipo de pontuação',
    'Skriv dit navn': 'Digite seu nome',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Jogue Bird Run, um mundo local de pássaros. Desvie da ave de rapina anunciada. Sem ranking global.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Jogue Neon Encore, um mundo local de show. Sobreviva a uma onda inteira com pelo menos três bolas. Sem ranking global.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Jogue Sky Relay, uma rota local curta de precisão por três anéis de nuvem. O topo e a base do anel podem ser atingidos. Acerte a placa dourada do sino de vento. Sem ranking global.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Jogue Stormline, um mundo local de vento. Desvie de um objeto voador na tempestade. Sem ranking global.',
    'Spiltype': 'Modo de jogo',
    'Start Quick Flight': 'Iniciar Quick Flight',
    'Starthelt · Klar til at flyve': 'Herói inicial · Pronto para voar',
    'Starthelt': 'Herói inicial',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard pronto: salva uma estrela perdida',
    'Streak Guard reddede din streak': 'Streak Guard salvou sua sequência',
    'Sur havnemåge · køb for fjer': 'Gaivota rabugenta do porto · compre com penas',
    'SØLV': 'PRATA',
    'BRONZE': 'BRONZE',
    'Sådan virker Berts rede': 'Como funciona o ninho do Bert',
    'TAP': 'TOQUE',
    'TAP FOR AT FLYVE · {0}': 'TOQUE PARA VOAR · {0}',
    'TESTBANE': 'FASE DE TESTE',
    'TIDEN UDE': 'TEMPO ESGOTADO',
    'TILBAGE': 'VOLTAR',
    'TRYK FOR AT STARTE': 'TOQUE PARA COMEÇAR',
    'TUNG': 'PESADO',
    'TUNG · STIGER LANGSOMT': 'PESADO · SOBE DEVAGAR',
    'Tid': 'Tempo',
    'Tilgængelige helte': 'Heróis disponíveis',
    'UDFORDR EN VEN': 'DESAFIE UM AMIGO',
    'Udfordringen er klar': 'O desafio está pronto',
    'Udfordringslink klar': 'Link do desafio pronto',
    'Udfordringslink kopieret': 'Link do desafio copiado',
    'Uge': 'Semana',
    'Undvig den varslede ørn eller grib': 'Desvie da águia ou do abutre anunciado',
    'Undvig en flyvende genstand i storm eller orkan': 'Desvie de um objeto voador na tempestade ou no furacão',
    'VELKOMMEN': 'BEM-VINDO',
    'VENNEDUEL': 'DUELO COM AMIGOS',
    'VENNER': 'AMIGOS',
    'VERDEN': 'MUNDO',
    'VENNER FRA DUELLER': 'AMIGOS DOS DUELOS',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'AMIGOS DOS DUELOS · {0} RIVAIS · {1} RESULTADOS',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LADO ESQUERDO = CIMA · LADO DIREITO = BAIXO',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · ESQUERDA SOBE · DIREITA DESCE',
    'VERDEN KLARET': 'MUNDO CONCLUÍDO',
    'VERDEN KLARET · LOKALT': 'MUNDO CONCLUÍDO · LOCAL',
    'VIND & GENSTANDE': 'VENTO & OBJETOS',
    'VIND · TESTBANE': 'VENTO · FASE DE TESTE',
    'VIND · {0}': 'VENTO · {0}',
    'VINDKLOKKEN RAMT': 'SINO DE VENTO ATINGIDO',
    'VINDVERDEN · LOKALT': 'MUNDO DO VENTO · LOCAL',
    'Vindmøller': 'Os Moinhos',
    'VINDMØLLER': 'OS MOINHOS',
    'Vulkanen': 'O Vulcão',
    'VULKANEN': 'O VULCÃO',
    'FJENDER & ANGREB': 'INIMIGOS & ATAQUES',
    'FUGLETRAFIK · TESTBANE': 'TRÁFEGO DE PÁSSAROS · FASE DE TESTE',
    'FUGLE & ROVFUGL': 'PÁSSAROS & AVE DE RAPINA',
    'FLAPPY-STYRING': 'CONTROLES FLAPPY',
    'FLAPPY-STYRING · TAP': 'CONTROLES FLAPPY · TOQUE',
    'VUNDET': 'GANHO',
    'BEHOLDT': 'MANTIDO',
    'Valgt og klar til at flyve': 'Escolhido e pronto para voar',
    'Vind bronze, sølv og guld': 'Ganhe bronze, prata e ouro',
    'Vind ti vennedueller': 'Vença dez duelos com amigos',
    'Vind · genstande': 'Vento · objetos',
    'VÆLG HELT': 'ESCOLHA O HERÓI',
    'VÆLG LEVEL': 'ESCOLHA A FASE',
    'VÆLG SPILTYPE': 'ESCOLHA O MODO',
    'Vælg Bert': 'Escolher Bert', 'Vælg Blok-Johan': 'Escolher Blok-Johan', 'Vælg BlueBert': 'Escolher BlueBert', 'Vælg BoneBeak': 'Escolher BoneBeak',
    'Vælg BrainBird': 'Escolher BrainBird', 'Vælg BrickBird': 'Escolher BrickBird', 'Vælg Coopinc': 'Escolher Coopinc', 'Vælg Fodbold-Bert': 'Escolher Bert Futeboleiro',
    'Vælg Guld-Bert': 'Escolher Bert Dourado', 'Vælg InkBird': 'Escolher InkBird', 'Vælg MechaBert': 'Escolher MechaBert', 'Vælg MossHex': 'Escolher MossHex',
    'Vælg Mågen Mogens': 'Escolher Mogens a Gaivota', 'Vælg Ninja-Bert': 'Escolher Bert Ninja', 'Vælg NoirWing': 'Escolher NoirWing', 'Vælg Pakke-Bert': 'Escolher Bert Pacote',
    'Vælg Pingo': 'Escolher Pingo', 'Vælg Prinsesse Søs': 'Escolher Princesa Søs', 'Vælg PrismWing': 'Escolher PrismWing', 'Vælg SkyClaw': 'Escolher SkyClaw',
    'Vælg Storm Royale': 'Escolher Storm Royale', 'Vælg SugarRush': 'Escolher SugarRush', 'Vælg Thor Obby': 'Escolher Thor Obby',
    'Vælg bane': 'Escolher fase',
    'Vælg leaderboard': 'Escolher ranking',
    'Vælg level': 'Escolher fase',
    'Vælg spiltype': 'Escolher modo',
    'Vælg {0}, {1}': 'Escolher {0}, {1}',
    'købt': 'comprado',
    'låst op': 'desbloqueado',
    '{0} ER LÅST': '{0} ESTÁ BLOQUEADO',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} fez {1} pontos. Você tem {2} tentativas na mesma fase, e o voo dele aparece como uma sombra.',
    '{0} forsøg tilbage · slå {1} point': '{0} tentativas restantes · supere {1} pontos',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} desafiou você a superar {1} pontos. Você tem três tentativas.',
    '{0} låst op for {1} fjer': '{0} desbloqueado por {1} penas',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} bloqueado. {1}. {2} de {3}. Preço alternativo: {4} penas.',
    '{0} missionsbelønninger': '{0} recompensas de missão',
    '{0} missionsbelønninger er hentet.': '{0} recompensas de missão resgatadas.',
    '{0} point til næste medalje': '{0} pontos para a próxima medalha',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Quando os dois requisitos forem cumpridos, toda a etapa {2} se abre.',
    '{0} · {1} FASTE LIV': '{0} · {1} VIDAS FIXAS',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, bloqueado. Toque para ver o requisito',
    '{0}, åben, personlig rekord {1}': '{0}, aberto, recorde pessoal {1}',
    '{0} · Mål {1}': '{0} · Meta {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} FASES · {2}/{3} MISSÕES',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} FASES · {2}/{3} MISS.',
    '{0} BANER · {1}': '{0} FASES · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} ABERTAS · {2}',
    'DU MANGLER {0} FJER': 'FALTAM {0} PENAS',
    'BESKYTTET · {0}s': 'PROTEGIDO · {0}s',
    'ÅBN DAGENS MISSIONER': 'ABRIR MISSÕES DE HOJE',
    'ÅBN GARDEROBE · 17 HELTE': 'ABRIR GUARDA-ROUPA · 17 HERÓIS',
    'ÅNDENDE PORTE': 'PORTAIS QUE RESPIRAM',
    'Åbn dagens missioner': 'Abrir missões de hoje',
    'Åbn highscore': 'Abrir recordes',
    'Åbn indstillinger': 'Abrir configurações',
    'ÉN CHANCE MERE?': 'MAIS UMA CHANCE?',
    'Sprog': 'Idioma',
    'Automatisk (som telefonen)': 'Automático (igual ao celular)',
    'Dansk': 'Dinamarquês', 'Engelsk': 'Inglês', 'Norsk': 'Norueguês', 'Svensk': 'Sueco', 'Tysk': 'Alemão', 'Spansk': 'Espanhol', 'Fransk': 'Francês', 'Portugisisk': 'Português',
    '+1 FJER': '+1 PENA',
    'En ven': 'Um amigo',
    'Dig': 'Você',
    'REKORD': 'RECORDE',
    'Topflyvning': 'Voo perfeito',
    '{0} point i {1}': '{0} pontos em {1}',
    'en bane': 'uma fase',
    '{0} til trin {1} · {2} stjerner': '{0} para a etapa {1} · {2} estrelas',
    '{0} · {1} stjerner samlet': '{0} · {1} estrelas coletadas',
    '{0} FJER': '{0} PENAS',
    'TAP FOR AT FLYVE': 'TOQUE PARA VOAR',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Supere a pontuação do seu amigo na mesma fase. Você tem três tentativas, e o voo fantasma dele acompanha você.",
    '{0}/{1} BRONZE': '{0}/{1} BRONZE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Consiga bronze (20 pontos) nas {0} fases básicas para abrir Aventura. Você tem {1}.',
    'SØLV I {0}': 'PRATA EM {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Consiga prata (50 pontos) em {0} para abrir {1}.',
    'LAVAEN FALDER': 'A LAVA BAIXA',
    'GODT GREB · {0}s': 'BOA ADERÊNCIA · {0}s',
    'VINDSTØD · OP': 'RAJADA · CIMA',
    'VINDSTØD · NED': 'RAJADA · BAIXO',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'GELO ESCORREGADIO: ANTECIPE · PEGUE CRISTAIS DE GELO',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'CUIDADO COM AS RAJADAS · AS SETAS MOSTRAM',
    'LAVAEN STIGER · SAML KØLESTEN': 'A LAVA ESTÁ SUBINDO · PEGUE PEDRAS FRIAS',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'A LUZ APAGA DEVAGAR · PEGUE LANTERNAS',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'OS CONTÊINERES SE MEXEM · CUIDADO COM AS GAIVOTAS',
    'Fugleklat': 'Cocô de Pássaro',
    'SPIS & KLAT': 'COMA & SOLTE',
    'PARAPLYEN REDDEDE DEM': 'O GUARDA-CHUVA SALVOU',
    'GULDBIL! ×3': 'CARRO DOURADO! ×3',
    'PLASK!': 'PLOFT!',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'COMA · TOQUE 💩 PARA ACERTAR EMBAIXO',
    'Slip en klat': 'Soltar um cocô',
    'Alle helte flyver ens. Vind dem i spillet, eller spar fjer sammen.': 'Todos os heróis voam igual. Ganhe-os no jogo ou junte penas.',
    'ÅBN GARDEROBE': 'ABRIR GUARDA-ROUPA',
    'OP · EVIGT SKJOLD · INGEN REKORDER': 'OP · ESCUDO ETERNO · SEM RECORDES',
    'FORSTØR': 'AUMENTAR',
    'FORMINDSK': 'ENCOLHER',
    'FORSTØR · POINT ×2': 'AUMENTAR · PONTOS ×2',
    'FØLG TUNNELEN · HOLD VENSTRE = OP · HØJRE = NED': 'SIGA O TÚNEL · ESQUERDA = SUBIR · DIREITA = DESCER',
    // Feedback 4. okt.: reden, æg, mærker, eventyr-låse, lyd.
    "Vælg én starthelt efter 10, 20, 30 og 40 ture": "Escolha um herói inicial após 10, 20, 30 e 40 voos",
    "Nå 600 point på én tur": "Faça 600 pontos em um voo",
    "Nå guld i alle tre Classic-baner": "Ganhe ouro nas três fases Classic",
    "Kun fra et æg i reden": "Só de um ovo no ninho",
    "Kun fra et æg i reden (sjælden)": "Só de um ovo no ninho (raro)",
    "Æggebert": "Ovobert",
    "ÆGGEBERT": "OVOBERT",
    "Vælg Æggebert": "Escolha Ovobert",
    "Klæk alle helte fra rugepladsen": "Choque todos os heróis da chocadeira",
    "KLÆK ALLE": "CHOQUE TODOS",
    "Blød rede": "Ninho macio",
    "Et sted at lande. Fjer bygger den videre.": "Um lugar para pousar. As penas o ampliam.",
    "Redningsfjer": "Pena de resgate",
    "REDNINGSFJER": "PENA DE RESGATE",
    "Ét redningsliv på hver tur.": "Uma vida de resgate em cada voo.",
    "Stærkere magnet": "Ímã mais forte",
    "Magneten trækker 30 % længere.": "O ímã puxa 30% mais longe.",
    "Varmt skjold": "Escudo quente",
    "Skjoldet holder 2 sekunder længere.": "O escudo dura 2 segundos a mais.",
    "Hurtig start": "Início rápido",
    "Usårlig med ekstra fart de første 5 sekunder.": "Invencível e mais rápido nos primeiros 5 segundos.",
    "To redningsliv": "Duas vidas de resgate",
    "To redningsliv på hver tur.": "Duas vidas de resgate em cada voo.",
    "Guldrede": "Ninho dourado",
    "Stjerner giver +1 point de første 10 sekunder.": "Estrelas dão +1 ponto nos primeiros 10 segundos.",
    "Første flyvetur": "Primeiro voo",
    "Gennemfør din første tur": "Termine seu primeiro voo",
    "Første stjerne": "Primeira estrela",
    "Saml din første stjerne": "Pegue sua primeira estrela",
    "Første fjer": "Primeira pena",
    "Find din første gyldne fjer": "Encontre sua primeira pena dourada",
    "Vind din første bronzemedalje": "Ganhe sua primeira medalha de bronze",
    "Ny ven": "Novo amigo",
    "Lås din første ekstra helt op": "Desbloqueie seu primeiro herói extra",
    "Sølv": "Prata",
    "Vind sølv på en bane": "Ganhe prata em uma fase",
    "Guld": "Ouro",
    "Vind guld på en bane": "Ganhe ouro em uma fase",
    "I flow": "No embalo",
    "Nå en streak på 10": "Alcance uma sequência de 10",
    "Ustoppelig": "Imparável",
    "Nå en streak på 25": "Alcance uma sequência de 25",
    "Stjerneregn": "Chuva de estrelas",
    "Saml 100 stjerner på én tur": "Pegue 100 estrelas em um voo",
    "Højtflyver": "Voo alto",
    "Få 500 point på én tur": "Faça 500 pontos em um voo",
    "Udholdenhed": "Resistência",
    "Flyv 3 minutter på én tur": "Voe 3 minutos em um voo",
    "Fejlfri": "Impecável",
    "Guld uden redningsliv eller redningsspin": "Ouro sem vidas nem giros de resgate",
    "Klassiker": "Clássico",
    "Bronze på alle Classic-baner": "Bronze em todas as fases Classic",
    "Skorstensfejer": "Limpa-chaminés",
    "Bronze på alle Flappy-baner": "Bronze em todas as fases Flappy",
    "Tunnelrytter": "Piloto do túnel",
    "Bronze på alle Tunnel-baner": "Bronze em todas as fases Tunnel",
    "Eventyrer": "Aventureiro",
    "Lås Eventyr op": "Desbloqueie Aventura",
    "Verdensflyver": "Voador mundial",
    "Sølv på alle seks eventyrbaner": "Prata nas seis fases de aventura",
    "Lavalord": "Senhor da lava",
    "Guld på Vulkanen": "Ouro no Vulcão",
    "Mesterskytte": "Atirador de elite",
    "10 træffere i træk i Fugleklat": "10 acertos seguidos no Cocô de Pássaro",
    "Publikumsvølge": "Onda da plateia",
    "Kom forbi tre bolde i én koncertbølge": "Passe por três bolas em uma onda do show",
    "Fri af rovfuglen": "Livre do gavião",
    "Undvig den varslede rovfugl": "Desvie da ave de rapina anunciada",
    "Undvig en flyvende genstand i storm": "Desvie de um objeto voador na tempestade",
    "Portløber": "Corredor de portais",
    "Klar alle tre porte i én Sky Relay-runde": "Passe pelos três portais em uma rodada de Sky Relay",
    "Ekstranummer": "Bis",
    "Sølv i Neon Encore": "Prata no Neon Encore",
    "Pakket ind": "Embrulhado",
    "Bliv fanget af edderkoppen": "Seja pego pela aranha",
    "Snack": "Lanchinho",
    "Bliv fanget af slangen": "Seja pego pela cobra",
    "Grillkylling": "Frango assado",
    "Dø 50 gange i alt": "Bata 50 vezes no total",
    "Flokken": "O bando",
    "Lås 10 helte op": "Desbloqueie 10 heróis",
    "Redebygger": "Construtor de ninhos",
    "Saml 100 fjer i alt": "Pegue 100 penas no total",
    "GAME OVER": "FIM DE JOGO",
    "MAGNET": "ÍMÃ",
    "Få bronze på alle tre Classic-baner for at åbne Havnen.": "Ganhe bronze nas três fases Classic para abrir O Porto.",
    "Få bronze på alle tre Flappy-baner for at åbne Nattebyen.": "Ganhe bronze nas três fases Flappy para abrir A Cidade Noturna.",
    "Få bronze på alle tre Tunnel-baner for at åbne Vindmøller.": "Ganhe bronze nas três fases Tunnel para abrir Os Moinhos.",
    "Få sølv i to af Havnen, Nattebyen og Vindmøller for at åbne Vulkanen.": "Ganhe prata em dois entre O Porto, A Cidade Noturna e Os Moinhos para abrir O Vulcão.",
    "GULD PÅ EN BANE": "OURO EM UMA FASE",
    "SØLV I VULKANEN": "PRATA NO VULCÃO",
    "Få sølv i Vulkanen og guld på én af grundbanerne for at åbne Isbjerget.": "Ganhe prata no Vulcão e ouro em uma fase básica para abrir O Iceberg.",
    "SØLV I ISBJERGET": "PRATA NO ICEBERG",
    "Få sølv i Isbjerget for at åbne Fugleklat.": "Ganhe prata no Iceberg para abrir Cocô de Pássaro.",
    "ÅBNER MED EVENTYR": "ABRE COM AVENTURA",
    "Testbanerne åbner sammen med den første eventyrverden.": "As fases de teste abrem com o primeiro mundo de aventura.",
    "HEMMELIG": "SECRETO",
    "LÅST": "BLOQUEADO",
    "Låst. Tryk på helten for at se, hvordan du får den.": "Bloqueado. Toque no herói para ver como conseguir.",
    "En hemmelig helt. Den hører til et særligt pilotnavn.": "Um herói secreto. Ele pertence a um nome de piloto especial.",
    "Du kan vælge en starthelt nu.": "Você já pode escolher um herói inicial.",
    "Eller klæk den fra et æg, når reden har nået trin 4.": "Ou choque-o de um ovo quando o ninho chegar à etapa 4.",
    "REDEN ER FÆRDIG": "O NINHO ESTÁ PRONTO",
    "Alle syv trin er bygget. Flot!": "As sete etapas estão construídas. Ótimo!",
    "Du fandt et æg! Det ligger i reden og ruger.": "Você achou um ovo! Ele está chocando no ninho.",
    "VÆLG EN NY HELT": "ESCOLHA UM NOVO HERÓI",
    "Du må vælge én. De andre kan vælges efter 10 ture mere.": "Escolha um. Os outros após mais 10 voos.",
    "SENERE": "DEPOIS",
    "Én tur om dagen giver fjer": "Um voo por dia dá penas",
    "Ruger et tilfældigt æg. Saml stjerner, så klækker det.": "Chocando um ovo aleatório. Pegue estrelas e ele vai chocar.",
    "TOM": "VAZIO",
    "ALLE KLÆKKET": "TODOS CHOCADOS",
    "Alle helte er klækket": "Todos os heróis já chocaram",
    "fjer": "penas",
    "sjælden": "raro",
    "Et æg ligger i reden. Saml stjerner, så klækker det.": "Há um ovo no ninho. Pegue estrelas e ele vai chocar.",
    "ER DU SIKKER? TRYK IGEN": "TEM CERTEZA? TOQUE DE NOVO",
    "GLOBAL HIGHSCORE": "RECORDE GLOBAL",
    "Du mangler fjer. Flyv en tur, og klar dagens missioner.": "Faltam penas. Voe e complete as missões de hoje.",
    "{0}/3 CLASSIC": "{0}/3 CLASSIC",
    "{0}/3 FLAPPY": "{0}/3 FLAPPY",
    "{0}/3 TUNNEL": "{0}/3 TUNNEL",
    "SØLV {0}/2": "PRATA {0}/2",
    "LÅST · {0}/{1}": "BLOQUEADO · {0}/{1}",
    "Vælg den som starthelt efter {0} ture. Du har fløjet {1}.": "Escolha-o como herói inicial após {0} voos. Você voou {1}.",
    "Klæk alle helte fra rugepladsen. {0}/{1} klækket.": "Choque todos os heróis. {0}/{1} chocados.",
    "Bedrift: {0} ({1}/{2}).": "Façanha: {0} ({1}/{2}).",
    "Eller klæk den fra et æg i reden: sikret æg {0} fjer.": "Ou choque-o de um ovo: ovo escolhido {0} penas.",
    "Du har {0} fjer. Fjer får du af dagens missioner, en tur om dagen og sjældne fjer i banerne.": "Você tem {0} penas. Penas vêm das missões do dia, um voo por dia e penas raras nas fases.",
    "BYG · {0} FJER": "CONSTRUIR · {0} PENAS",
    "BYG · 20 FJER": "CONSTRUIR · 20 PENAS",
    "MANGLER {0} FJER": "FALTAM {0} PENAS",
    "{0} TURE FLØJET": "{0} VOOS",
    "{0} er din nu": "{0} agora é seu",
    "Ægget klækkede: {0}!": "O ovo chocou: {0}!",
    "{0} er klækket og venter i garderoben": "{0} chocou e espera no guarda-roupa",
    "Ægget: {0}/{1} stjerner": "O ovo: {0}/{1} estrelas",
    "{0} fjer fundet": "{0} penas encontradas",
    "Dag {0} i træk: +{1} fjer": "Dia {0} seguido: +{1} penas",
    "Reden: {0}/{1} til {2}": "Ninho: {0}/{1} para {2}",
    "Nyt mærke: {0}": "Nova insígnia: {0}",
    "{0} dage i træk": "{0} dias seguidos",
    "{0}/{1} STJERNER": "{0}/{1} ESTRELAS",
    "Ruger: {0}": "Chocando: {0}",
    "{0} helte kan stadig klækkes": "{0} heróis ainda podem chocar",
    "TILFÆLDIGT ÆG · {0} FJER": "OVO ALEATÓRIO · {0} PENAS",
    "SIKRET ÆG · {0} FJER": "OVO ESCOLHIDO · {0} PENAS",
    "TILFÆLDIGT ÆG": "OVO ALEATÓRIO",
    "SIKRET ÆG": "OVO ESCOLHIDO",
    "Et sikret æg med {0} ligger i reden": "Um ovo escolhido com {0} está no ninho",
    "Reden er bygget: {0}": "Ninho construído: {0}",
    "Dag {0} i træk · +{1} fjer til reden": "Dia {0} seguido · +{1} penas para o ninho",
    "Bert The Bird – flyvespil og præcisionsverdener": "Bert The Bird – jogo de voo e mundos de precisão",
    "PAUSE": "PAUSA",
    "REDEN": "O NINHO",
    "Reden": "O ninho",
    "Åbn reden": "Abrir o ninho",
    "Luk reden": "Fechar o ninho",
    "Redens trin": "Etapas do ninho",
    "NÆSTE TRIN": "PRÓXIMA ETAPA",
    "RUGEPLADSEN": "A CHOCADEIRA",
    "FLYV HVER DAG": "VOE TODO DIA",
    "MÆRKER": "INSÍGNIAS",
    "Fjer bygger reden. Hvert trin kan mærkes i spillet. Efter døden kan du bruge 12 fjer på ét redningsspin.": "As penas constroem o ninho. Cada etapa se sente no jogo. Depois de bater, você pode gastar 12 penas em um giro de resgate.",
    "Forrige helte": "Heróis anteriores",
    "Næste helte": "Próximos heróis",
    "Musikstyrke": "Volume da música",
    "Lydstyrke for effekter": "Volume dos efeitos",
    "Vælg helt til sikret æg": "Escolha o herói do ovo escolhido",
    "Banens grafik kunne ikke indlæses.": "Não foi possível carregar os gráficos da fase.",
    "Spillet kunne ikke indlæses. Prøv igen.": "Não foi possível carregar o jogo. Tente de novo.",
    "NY HELT: {0} · {1}": "NOVO HERÓI: {0} · {1}",
    "Klæk den fra et æg i reden: sikret æg {0} fjer.": "Choque-o de um ovo: ovo escolhido {0} penas.",
    "Klæk den fra et æg, når reden har nået trin 4.": "Choque-o de um ovo quando o ninho chegar à etapa 4.",
});
