/* Norsk (bokmål). Nøklene er de danske kildetekstene. */
window.BertI18n.register('nb', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FLY EN TUR FOR Å SETTE FØRSTE SCORE',
    ' · MÆRKE: {0}': ' · MERKE: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · SPILL EN VENNEDUELL FOR Å FÅ EN RIVAL',
    '+{0} fjer til reden': '+{0} fjær til redet',
    '+{0} fjer · {1} låst op': '+{0} fjær · {1} låst opp',
    '0 / 0 POINT': '0 / 0 POENG',
    '20 point til bronze': '20 poeng til bronse',
    '3 SPILFORMER · 9 BANER': '3 SPILLTYPER · 9 BANER',
    '3 baner · hold op/ned': '3 baner · hold opp/ned',
    '3 baner · præcision': '3 baner · presisjon',
    '3 baner · tap': '3 baner · trykk',
    '9 baner · nye verdener': '9 baner · nye verdener',
    'ACCEPTÉR': 'GODTA',
    'AFSLUT TUREN': 'AVSLUTT TUREN',
    'Alle baner': 'Alle baner',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Alle helter har samme fart og treffboks. Vinn dem i spillet, eller spar opp fjær.',
    'Alle pointkrav i trin {0} er klaret.': 'Alle poengkrav i trinn {0} er klart.',
    'Alle spil': 'Alle spill',
    'Alle tider': 'Alle tider',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Alle tre forsøk er brukt. Be vennen din om en ny duell.',
    'BANEN ER LÅST': 'BANEN ER LÅST',
    'BEKRÆFT · {0} FJER': 'BEKREFT · {0} FJÆR',
    'BERTS GARDEROBE': 'BERTS GARDEROBE',
    'BERTS REDE': 'BERTS REDE',
    'BERTS REDNINGSREDE': 'BERTS REDNINGSREDE',
    'BEVÆGELIGE TÅRNE': 'BEVEGELIGE TÅRN',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord',
    'Bane': 'Bane',
    'Banen er låst': 'Banen er låst',
    'Bedst på level {0} · {1}': 'Best på bane {0} · {1}',
    'Bert The Bird appikon': 'Bert The Bird appikon',
    'Bert The Bird bliver installeret': 'Bert The Bird installeres',
    'Bert The Bird er installeret': 'Bert The Bird er installert',
    'Bert The Bird spilcanvas': 'Bert The Bird spillflate',
    'Bert flyver': 'Bert flyr',
    'Bevægelse i koncertlys': 'Bevegelse i konsertlys',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Bruk 12 fjær på ett spinn. Fem felt sender Bert tilbake i banen. Ett felt avslutter turen.',
    'DAGENS MISSIONER': 'DAGENS OPPDRAG',
    'DAGENS RUTE': 'DAGENS RUTE',
    'DAGENS RUTE · MÅL {0}': 'DAGENS RUTE · MÅL {0}',
    'DENNE TUR': 'DENNE TUREN',
    'DIN FLYVETUR': 'FLYTUREN DIN',
    'DIN HELT': 'HELTEN DIN',
    'DIN SALDO': 'SALDOEN DIN',
    'DINE VENNEDUELLER': 'VENNEDUELLENE DINE',
    'DREJ TELEFONEN': 'SNU TELEFONEN',
    'DU ER UDFORDRET': 'DU ER UTFORDRET',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'DU VANT DUELLEN · utfordre tilbake · {0} stjerner',
    'Den sjældneste fugl · køb for fjer': 'Den sjeldneste fuglen · kjøp for fjær',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Denne banen kan ikke brukes til rangerte vennedueller.',
    'Dit navn': 'Navnet ditt',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Navnet ditt står på rangeringen og ved rekordene dine.',
    'Du mangler fjer fra dagens missioner': 'Du mangler fjær fra dagens oppdrag',
    'EDM-VERDEN · LOKALT': 'EDM-VERDEN · LOKALT',
    'EPISK': 'EPISK',
    'EVENT · BIRD RUN · TESTBANE': 'EVENT · BIRD RUN · TESTBANE',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENT · NEON ENCORE · TESTBANE',
    'EVENT · STORMLINE · TESTBANE': 'EVENT · STORMLINE · TESTBANE',
    'EVENTYR': 'EVENTYR',
    'EVENTYR · {0}': 'EVENTYR · {0}',
    'Episk helt · kun til dig · valgt': 'Episk helt · bare for deg · valgt',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Episk helt · bare for deg. Trykk for å velge.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Et permanent redningsliv tåler ett sammenstøt på hver tur. Etter et krasj kan du også bruke 12 fjær på ett redningsspinn. Du kan alltid spille videre uten energi eller ventetid.',
    'FAST + BEVÆGELIG': 'FAST + BEVEGELIG',
    'FASTE TÅRNE': 'FASTE TÅRN',
    'FJER': 'FJÆR',
    'FJER RETUR': 'FJÆR TILBAKE',
    'FJER · PRIMÆRT VINDES I SPILLET': 'FJÆR · VINNES FØRST OG FREMST I SPILLET',
    'FLYV': 'FLY',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'FLY GJENNOM TRE SKYPORTER · TREFF GULLPLATEN · VENSTRE OPP · HØYRE NED',
    'FLYV IGEN': 'FLY IGJEN',
    'FLYV VIDERE': 'FLY VIDERE',
    'FLYVETUREN ER SAT PÅ PAUSE': 'FLYTUREN ER SATT PÅ PAUSE',
    'FODBOLD-BERT': 'FOTBALL-BERT',
    'FOKUS': 'FOKUS',
    'FOKUS OM {0}': 'FOKUS OM {0}',
    'FORBI': 'BOM',
    'FORBI GULDPLADEN': 'BOMMET PÅ GULLPLATEN',
    'FORSTÅET': 'FORSTÅTT',
    'FORTRYD': 'ANGRE',
    'FORTSÆT': 'FORTSETT',
    'FRI AF ROVFUGLEN': 'FRI FRA ROVFUGLEN',
    'FUGL BAGFRA': 'FUGL BAKFRA',
    'FUGLEVERDEN · LOKALT': 'FUGLEVERDEN · LOKALT',
    'Fire gratis lokale eventverdener uden global rangliste': 'Fire gratis lokale eventverdener uten global rangering',
    'Flyv samlet i 3 minutter': 'Fly til sammen i 3 minutter',
    'Flyvetid': 'Flytid',
    'Fodbold-Bert': 'Fotball-Bert',
    'Forbindelsen er tilbage': 'Forbindelsen er tilbake',
    'Fremgang mod oplåsning': 'Fremgang mot opplåsing',
    'Fugle · rovfugl': 'Fugler · rovfugl',
    'FÆRDIG': 'FERDIG',
    'FØLG STJERNESTRØMMEN': 'FØLG STJERNESTRØMMEN',
    'FØLGER DIG KORT · {0}s': 'FØLGER DEG KORT · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · TUREN ER SLUTT',
    'GLOBALT': 'GLOBALT',
    'GLOBALT · {0} RESULTATER': 'GLOBALT · {0} RESULTATER',
    'GODT RAMT': 'GODT TRUFFET',
    'GRATIS REDNING': 'GRATIS REDNING',
    'GRUNDFLYVNING': 'GRUNNFLYGING',
    'GULD': 'GULL',
    'GULD-BERT': 'GULL-BERT',
    'Guld-Bert': 'Gull-Bert',
    'HAV BERT PÅ STARTSKÆRMEN': 'HA BERT PÅ HJEM-SKJERMEN',
    'HAVNEN': 'HAVNEN',
    'Havnen': 'Havnen',
    'HENT FJER': 'HENT FJÆR',
    'HENT SPILLET': 'HENT SPILLET',
    'HENT +{0}': 'HENT +{0}',
    '+{0} FJER': '+{0} FJÆR',
    'HENTER RESULTATER …': 'HENTER RESULTATER …',
    'HENTET': 'HENTET',
    'HOLD OP/NED': 'HOLD OPP/NED',
    'HOVEDMENU': 'HOVEDMENY',
    'HVAD HEDDER DU?': 'HVA HETER DU?',
    'HVORDAN VIL DU FLYVE?': 'HVORDAN VIL DU FLY?',
    'HYPERFART': 'HYPERFART',
    'Haptisk feedback': 'Haptisk tilbakemelding',
    'Har altid en pakke med · køb for fjer': 'Har alltid med en pakke · kjøp for fjær',
    'Hele Bert The Bird er lavet til landscape.': 'Hele Bert The Bird er laget for liggende skjerm.',
    'Hemmelig helt': 'Hemmelig helt',
    'Hent en mission syv dage i træk': 'Hent et oppdrag sju dager på rad',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Hent {0} oppdragsbelønninger totalt; du har {1}.',
    'Henter resultater …': 'Henter resultater …',
    'Høj fart': 'Høy fart',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'I Safari: Del → Legg til på Hjem-skjerm. Vent på «Klar til offline-spill», og åpne ikonet én gang med nett før du tester i flymodus.',
    'I dag': 'I dag',
    'IKKE NU': 'IKKE NÅ',
    'INDSTILLINGER': 'INNSTILLINGER',
    'INSTALLÉR WEBAPP': 'INSTALLER WEBAPP',
    'ISTAPPER & SPIDSER': 'ISTAPPER & SPISSER',
    'Isbjerget': 'Isfjellet',
    'ISBJERGET': 'ISFJELLET',
    'Indlæser originale Unity-assets …': 'Laster originale Unity-ressurser …',
    'Ingen rekord endnu': 'Ingen rekord ennå',
    'Installér som webapp': 'Installer som webapp',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Installer via nettleserens meny. Vent på «Klar til offline-spill», og åpne appen én gang med nett før du tester offline.',
    'KANT': 'KANT',
    'KLAR DAGENS MÅL': 'KLAR DAGENS MÅL',
    'KLARET': 'KLART',
    'KONCERT · TESTBANE': 'KONSERT · TESTBANE',
    'KRANER & MÅGER': 'KRANER & MÅKER',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'BARE DINE LOKALE RESULTATER · ONLINE-TAVLEN ER IKKE TILGJENGELIG',
    'KVALIFIKATIONSBANEN': 'KVALIFISERINGSBANEN',
    'Klar dagens rute': 'Klar dagens rute',
    'Klar dagens rute én gang': 'Klar dagens rute én gang',
    'Klar hele forrige trin og missionskravet først': 'Klar hele forrige trinn og oppdragskravet først',
    'Klar hele trin {0}: {1}.': 'Klar hele trinn {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Klar kvalifiseringsbanen for å åpne denne utfordringen.',
    'Klar til offline-spil': 'Klar til offline-spill',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Kom forbi minst tre baller i én konsertbølge',
    'KØB': 'KJØP',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'KJØP FASTE LIV ELLER ET REDNINGSSPINN',
    'KØB · {0} FJER': 'KJØP · {0} FJÆR',
    'KØBT': 'KJØPT',
    'LAVA & BOBLER': 'LAVA & BOBLER',
    'LEVENDE FORHINDRINGER': 'LEVENDE HINDRE',
    'LEVERING': 'LEVERING',
    'LYD & FEEDBACK': 'LYD & TILBAKEMELDING',
    'LYDLØS': 'LYDLØS',
    'Level 1 · Mål 30': 'Bane 1 · Mål 30',
    'Luk': 'Lukk',
    'Luk garderoben': 'Lukk garderoben',
    'Lydeffekter': 'Lydeffekter',
    'Lydløs og hurtig · køb for fjer': 'Lydløs og rask · kjøp for fjær',
    'LÅS OP · 20 FJER': 'LÅS OPP · 20 FJÆR',
    'LÅS OP · {0} FJER': 'LÅS OPP · {0} FJÆR',
    'LÅST BANE': 'LÅST BANE',
    'LÅST OP': 'LÅST OPP',
    'LÆR KORRIDOREN': 'LÆR KORRIDOREN',
    'Låst op. Tryk på figuren for at vælge.': 'Låst opp. Trykk på figuren for å velge.',
    'MAKS LÅST OP': 'MAKS LÅST OPP',
    'MINISPIL · SKY RELAY · LOKALT': 'MINISPILL · SKY RELAY · LOKALT',
    'MISSIONER': 'OPPDRAG',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MOBIL: VENSTRE SIDE = OPP · HØYRE SIDE = NED',
    'Missioner': 'Oppdrag',
    'Mod vinden': 'Mot vinden',
    'Musik': 'Musikk',
    'MÅGEN MOGENS': 'MÅKEN MOGENS',
    'Mågen Mogens': 'Måken Mogens',
    'MÅL: 3 BOLDE': 'MÅL: 3 BALLER',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'MÅL: KOM FORBI EN BØLGE MED TRE BALLER · VENSTRE OPP · HØYRE NED',
    'MÅL: ROVFUGL': 'MÅL: ROVFUGL',
    'MÅL: STORM': 'MÅL: STORM',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'MÅL: UNNGÅ EN ROVFUGL · VENSTRE OPP · HØYRE NED',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'MÅL: UNNGÅ EN STORMGJENSTAND · FØLG FLAGG OG BLADER',
    'MÆRKE VUNDET': 'MERKE VUNNET',
    'MØRKE & SKILTE': 'MØRKE & SKILT',
    'Måned': 'Måned',
    'NED': 'NED',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} stjerner · kun lokal eventrekord',
    'NINJA-BERT': 'NINJA-BERT',
    'Ninja-Bert': 'Ninja-Bert',
    'NIVEAU {0}! · {1}': 'NIVÅ {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING LÅST OPP · FEILFRI FLYGING',
    'NY BANE': 'NY BANE',
    'NY REKORD!': 'NY REKORD!',
    'NYE VERDENER': 'NYE VERDENER',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NYTT TRINN: ALLE TRE BANER ER ÅPNE · {0} stjerner samlet',
    'NATTEBYEN': 'NATTBYEN',
    'Nattebyen': 'Nattbyen',
    'Ny mobilversion indlæst': 'Ny mobilversjon lastet',
    'Nyt redningsliv låst op': 'Nytt redningsliv låst opp',
    'NÆSTE UDFORDRING': 'NESTE UTFORDRING',
    'Nå 120 point i Desert': 'Nå 120 poeng i Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Nå 180 poeng uten å bomme på en stjerne eller treffe noe',
    'Nå 300 point på én tur': 'Nå 300 poeng på én tur',
    'Nå bronze i Jungle uden redning': 'Nå bronse i Jungle uten redning',
    'Nå bronze i alle ni baner': 'Nå bronse i alle ni baner',
    'Nå bronze i alle tre Classic-baner': 'Nå bronse i alle tre Classic-baner',
    'Nå en streak på 12': 'Nå en streak på 12',
    'OMVENDT STYRING': 'OMVENDT STYRING',
    'OP': 'OPP',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Offline er ikke klart ennå · koble til nettet',
    'PAKKE-BERT': 'PAKKE-BERT',
    'Pakke-Bert': 'Pakke-Bert',
    'PERMANENT REDE-FORDEL': 'PERMANENT REDE-FORDEL',
    'PERSONLIG REKORD': 'PERSONLIG REKORD',
    'PILOTER': 'PILOTER',
    'POINT ×2': 'POENG ×2',
    'PORTE & KLOKKE': 'PORTER & KLOKKE',
    'PRINSESSE SØS': 'PRINSESSE SØS',
    'Prinsesse Søs': 'Prinsesse Søs',
    'PRÆCISION': 'PRESISJON',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'PRESISJONSFLYGING · LOKAL PRØVE',
    'PRÆCISIONSRUTE · LOKALT': 'PRESISJONSRUTE · LOKALT',
    'PUBLIKUMSVØLGE': 'PUBLIKUMSBØLGE',
    'Pause spillet': 'Pause spillet',
    'Periode': 'Periode',
    'Personlig highscore': 'Personlig rekord',
    'Pilotnavn': 'Pilotnavn',
    'Pingvin med jetpack · køb for fjer': 'Pingvin med jetpack · kjøp for fjær',
    'Point': 'Poeng',
    'Porte · vindklokke': 'Porter · vindklokke',
    'PORT {0}/3': 'PORT {0}/3',
    'PORT {0}/3 · {1}': 'PORT {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RUNDE {0} · PORT {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'KLANG! +{0} · RUNDE {1}',
    'Præcisionsflyvning': 'Presisjonsflyging',
    'RAM GULDPLADEN': 'TREFF GULLPLATEN',
    'RAMT': 'TRUFFET',
    'RANGLISTE': 'RANGERING',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'REDDET · DINE 12 FJÆR KOMMER TILBAKE',
    'REDDET · {0}': 'REDDET · {0}',
    'REDNINGSLIV': 'REDNINGSLIV',
    'REDNINGSLIV 0/3': 'REDNINGSLIV 0/3',
    'REDNINGSLIV {0}/{1}': 'REDNINGSLIV {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'REDNINGSREDET SNURRER …',
    'REDNINGSSPIN': 'REDNINGSSPINN',
    'RENT GENNEM': 'RENT GJENNOM',
    'RIGGE & BOLDE': 'RIGGER & BALLER',
    'ROTORER & BØJER': 'ROTORER & BØYER',
    'ROVFUGL': 'ROVFUGL',
    'ROVFUGL BAGFRA': 'ROVFUGL BAKFRA',
    'FUGL': 'FUGL',
    'BAGFRA': 'BAKFRA',
    'FORFRA': 'FORFRA',
    'RUTEN AFSLUTTET': 'RUTEN FULLFØRT',
    'Redningsliv tilbage': 'Redningsliv igjen',
    'Rigge · bolde': 'Rigger · baller',
    'SJÆLDEN': 'SJELDEN',
    'SKIFT BANE': 'BYTT BANE',
    'SKJOLD': 'SKJOLD',
    'SKJOLD BRUGT · 2s': 'SKJOLD BRUKT · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · TRAFF {0} AV PORT {1} · 0 POENG · PRØV IGJEN',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 POENG · PRØV IGJEN',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 PORTER · {1}% PRESISJON · KUN LOKALT',
    'TOPPEN': 'TOPPEN',
    'BUNDEN': 'BUNNEN',
    'SKYRING RAMT': 'SKYRING TRUFFET',
    'SPIL': 'SPILL',
    'SPIL KVALIFIKATION': 'SPILL KVALIFISERING',
    'SPIL →': 'SPILL →',
    'SPIL {0}': 'SPILL {0}',
    'SPIN FOR AT SE DIN REDNING': 'SPINN FOR Å SE REDNINGEN DIN',
    'SPIN · 12 FJER': 'SPINN · 12 FJÆR',
    'SPIN · {0} FJER': 'SPINN · {0} FJÆR',
    'START FORFRA': 'START PÅ NYTT',
    'STARTBANE': 'STARTBANE',
    'STJERNEREGN': 'STJERNEREGN',
    'STIGER': 'STIGER',
    'DYKKER': 'STUPER',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · VIND OG FLYGENDE TING · {0} stjerner · kun lokal eventrekord',
    'STREAK REDDET · GUARD BRUGT': 'STREAK REDDET · GUARD BRUKT',
    'STORMPILOT': 'STORMPILOT',
    'Saml 20 stjerner til reden': 'Samle 20 stjerner til redet',
    'Saml 250 stjerner i alt': 'Samle 250 stjerner totalt',
    'Scoretype': 'Scoretype',
    'Skriv dit navn': 'Skriv navnet ditt',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Spill Bird Run, lokal fugleverden. Unngå den varslede rovfuglen. Ingen global rangering.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Spill Neon Encore, lokal konsertverden. Overlev en hel bølge med minst tre baller. Ingen global rangering.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Spill Sky Relay, en kort lokal presisjonsrute gjennom tre skyringer. Ringens topp og bunn kan treffes. Treff vindklokkens gullplate. Ingen global rangering.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Spill Stormline, lokal vindverden. Unngå en flygende gjenstand i storm. Ingen global rangering.',
    'Spiltype': 'Spilltype',
    'Start Quick Flight': 'Start Quick Flight',
    'Starthelt · Klar til at flyve': 'Starthelt · Klar til å fly',
    'Starthelt': 'Starthelt',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard klar: redder én tapt stjerne',
    'Streak Guard reddede din streak': 'Streak Guard reddet streaken din',
    'Sur havnemåge · køb for fjer': 'Sur havnemåke · kjøp for fjær',
    'SØLV': 'SØLV',
    'BRONZE': 'BRONSE',
    'Sådan virker Berts rede': 'Slik virker Berts rede',
    'TAP': 'TRYKK',
    'TAP FOR AT FLYVE · {0}': 'TRYKK FOR Å FLY · {0}',
    'TESTBANE': 'TESTBANE',
    'TIDEN UDE': 'TIDEN ER UTE',
    'TILBAGE': 'TILBAKE',
    'TRYK FOR AT STARTE': 'TRYKK FOR Å STARTE',
    'TUNG': 'TUNG',
    'TUNG · STIGER LANGSOMT': 'TUNG · STIGER SAKTE',
    'Tid': 'Tid',
    'Tilgængelige helte': 'Tilgjengelige helter',
    'UDFORDR EN VEN': 'UTFORDRE EN VENN',
    'Udfordringen er klar': 'Utfordringen er klar',
    'Udfordringslink klar': 'Utfordringslenke klar',
    'Udfordringslink kopieret': 'Utfordringslenke kopiert',
    'Uge': 'Uke',
    'Undvig den varslede ørn eller grib': 'Unngå den varslede ørnen eller gribben',
    'Undvig en flyvende genstand i storm eller orkan': 'Unngå en flygende gjenstand i storm eller orkan',
    'VELKOMMEN': 'VELKOMMEN',
    'VENNEDUEL': 'VENNEDUELL',
    'VENNER': 'VENNER',
    'VERDEN': 'VERDEN',
    'VENNER FRA DUELLER': 'VENNER FRA DUELLER',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'VENSTRE SIDE = OPP · HØYRE SIDE = NED',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · VENSTRE OPP · HØYRE NED',
    'VERDEN KLARET': 'VERDEN KLART',
    'VERDEN KLARET · LOKALT': 'VERDEN KLART · LOKALT',
    'VIND & GENSTANDE': 'VIND & GJENSTANDER',
    'VIND · TESTBANE': 'VIND · TESTBANE',
    'VIND · {0}': 'VIND · {0}',
    'VINDKLOKKEN RAMT': 'VINDKLOKKEN TRUFFET',
    'VINDVERDEN · LOKALT': 'VINDVERDEN · LOKALT',
    'Vindmøller': 'Vindmøller',
    'VINDMØLLER': 'VINDMØLLER',
    'Vulkanen': 'Vulkanen',
    'VULKANEN': 'VULKANEN',
    'FJENDER & ANGREB': 'FIENDER & ANGREP',
    'FUGLETRAFIK · TESTBANE': 'FUGLETRAFIKK · TESTBANE',
    'FUGLE & ROVFUGL': 'FUGLER & ROVFUGL',
    'FLAPPY-STYRING': 'FLAPPY-STYRING',
    'FLAPPY-STYRING · TAP': 'FLAPPY-STYRING · TRYKK',
    'VUNDET': 'VUNNET',
    'BEHOLDT': 'BEHOLDT',
    'Valgt og klar til at flyve': 'Valgt og klar til å fly',
    'Vind bronze, sølv og guld': 'Vinn bronse, sølv og gull',
    'Vind ti vennedueller': 'Vinn ti vennedueller',
    'Vind · genstande': 'Vind · gjenstander',
    'VÆLG HELT': 'VELG HELT',
    'VÆLG LEVEL': 'VELG BANE',
    'VÆLG SPILTYPE': 'VELG SPILLTYPE',
    'Vælg Bert': 'Velg Bert', 'Vælg Blok-Johan': 'Velg Blok-Johan', 'Vælg BlueBert': 'Velg BlueBert', 'Vælg BoneBeak': 'Velg BoneBeak',
    'Vælg BrainBird': 'Velg BrainBird', 'Vælg BrickBird': 'Velg BrickBird', 'Vælg Coopinc': 'Velg Coopinc', 'Vælg Fodbold-Bert': 'Velg Fotball-Bert',
    'Vælg Guld-Bert': 'Velg Gull-Bert', 'Vælg InkBird': 'Velg InkBird', 'Vælg MechaBert': 'Velg MechaBert', 'Vælg MossHex': 'Velg MossHex',
    'Vælg Mågen Mogens': 'Velg Måken Mogens', 'Vælg Ninja-Bert': 'Velg Ninja-Bert', 'Vælg NoirWing': 'Velg NoirWing', 'Vælg Pakke-Bert': 'Velg Pakke-Bert',
    'Vælg Pingo': 'Velg Pingo', 'Vælg Prinsesse Søs': 'Velg Prinsesse Søs', 'Vælg PrismWing': 'Velg PrismWing', 'Vælg SkyClaw': 'Velg SkyClaw',
    'Vælg Storm Royale': 'Velg Storm Royale', 'Vælg SugarRush': 'Velg SugarRush', 'Vælg Thor Obby': 'Velg Thor Obby',
    'Vælg bane': 'Velg bane',
    'Vælg leaderboard': 'Velg rangering',
    'Vælg level': 'Velg bane',
    'Vælg spiltype': 'Velg spilltype',
    'Vælg {0}, {1}': 'Velg {0}, {1}',
    'købt': 'kjøpt',
    'låst op': 'låst opp',
    '{0} ER LÅST': '{0} ER LÅST',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} fikk {1} poeng. Du har {2} forsøk på samme bane, og flyturen deres vises som en skygge.',
    '{0} forsøg tilbage · slå {1} point': '{0} forsøk igjen · slå {1} poeng',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} har utfordret deg til å slå {1} poeng. Du har tre forsøk.',
    '{0} låst op for {1} fjer': '{0} låst opp for {1} fjær',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} låst. {1}. {2} av {3}. Alternativ pris {4} fjær.',
    '{0} missionsbelønninger': '{0} oppdragsbelønninger',
    '{0} missionsbelønninger er hentet.': '{0} oppdragsbelønninger er hentet.',
    '{0} point til næste medalje': '{0} poeng til neste medalje',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Når begge krav er oppfylt, åpnes hele trinn {2}.',
    '{0} · {1} FASTE LIV': '{0} · {1} FASTE LIV',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, låst. Trykk for å se kravet',
    '{0}, åben, personlig rekord {1}': '{0}, åpen, personlig rekord {1}',
    '{0} · Mål {1}': '{0} · Mål {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} BANER · {2}/{3} OPPDRAG',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} BANER · {2}/{3} OPPDR.',
    '{0} BANER · {1}': '{0} BANER · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} ÅPNE · {2}',
    'DU MANGLER {0} FJER': 'DU MANGLER {0} FJÆR',
    'BESKYTTET · {0}s': 'BESKYTTET · {0}s',
    'ÅBN DAGENS MISSIONER': 'ÅPNE DAGENS OPPDRAG',
    'ÅBN GARDEROBE · 17 HELTE': 'ÅPNE GARDEROBE · 17 HELTER',
    'ÅNDENDE PORTE': 'PUSTENDE PORTER',
    'Åbn dagens missioner': 'Åpne dagens oppdrag',
    'Åbn highscore': 'Åpne rekorder',
    'Åbn indstillinger': 'Åpne innstillinger',
    'ÉN CHANCE MERE?': 'ÉN SJANSE TIL?',
    'Sprog': 'Språk',
    'Automatisk (som telefonen)': 'Automatisk (som telefonen)',
    'Dansk': 'Dansk', 'Engelsk': 'Engelsk', 'Norsk': 'Norsk', 'Svensk': 'Svensk', 'Tysk': 'Tysk', 'Spansk': 'Spansk', 'Fransk': 'Fransk', 'Portugisisk': 'Portugisisk',
    '+1 FJER': '+1 FJÆR',
    'En ven': 'En venn',
    'Dig': 'Deg',
    'REKORD': 'REKORD',
    'Topflyvning': 'Toppflyging',
    '{0} point i {1}': '{0} poeng i {1}',
    'en bane': 'en bane',
    '{0} til trin {1} · {2} stjerner': '{0} til trinn {1} · {2} stjerner',
    '{0} · {1} stjerner samlet': '{0} · {1} stjerner samlet',
    '{0} FJER': '{0} FJÆR',
    'TAP FOR AT FLYVE': 'TRYKK FOR Å FLY',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Slå vennens score på nøyaktig samme bane. Du har tre forsøk, og spøkelsesflyturen deres følger deg.",
    '{0}/{1} BRONZE': '{0}/{1} BRONSE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Få bronse (20 poeng) på alle {0} grunnbanene for å åpne Eventyr. Du har {1}.',
    'SØLV I {0}': 'SØLV I {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Få sølv (50 poeng) i {0} for å åpne {1}.',
    'LAVAEN FALDER': 'LAVAEN SYNKER',
});
