/* Français. Les clés sont les textes danois d’origine. */
window.BertI18n.register('fr', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FAIS UN VOL POUR TON PREMIER SCORE',
    ' · MÆRKE: {0}': ' · BADGE : {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · JOUE UN DUEL ENTRE AMIS POUR AVOIR UN RIVAL',
    '+{0} fjer til reden': '+{0} plumes pour le nid',
    '+{0} fjer · {1} låst op': '+{0} plumes · {1} débloqué',
    '0 / 0 POINT': '0 / 0 POINTS',
    '20 point til bronze': '20 points avant le bronze',
    '3 SPILFORMER · 9 BANER': '3 MODES · 9 NIVEAUX',
    '3 baner · hold op/ned': '3 niveaux · maintenir haut/bas',
    '3 baner · præcision': '3 niveaux · précision',
    '3 baner · tap': '3 niveaux · tapoter',
    '9 baner · nye verdener': '9 niveaux · nouveaux mondes',
    'ACCEPTÉR': 'ACCEPTER',
    'AFSLUT TUREN': 'TERMINER LE VOL',
    'Alle baner': 'Tous les niveaux',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Tous les héros ont la même vitesse et la même zone de collision. Gagne-les en jouant ou économise des plumes.',
    'Alle pointkrav i trin {0} er klaret.': 'Tous les objectifs de points du palier {0} sont atteints.',
    'Alle spil': 'Tous les jeux',
    'Alle tider': 'Depuis toujours',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Les trois essais sont utilisés. Demande un nouveau duel à ton ami.',
    'BANEN ER LÅST': 'NIVEAU VERROUILLÉ',
    'BEKRÆFT · {0} FJER': 'CONFIRMER · {0} PLUMES',
    'BERTS GARDEROBE': 'LA GARDE-ROBE DE BERT',
    'BERTS REDE': 'LE NID DE BERT',
    'BERTS REDNINGSREDE': 'LE NID DE SECOURS DE BERT',
    'BEVÆGELIGE TÅRNE': 'TOURS MOBILES',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} étoiles · record d’événement local uniquement',
    'Bane': 'Niveau',
    'Banen er låst': 'Le niveau est verrouillé',
    'Bedst på level {0} · {1}': 'Meilleur au niveau {0} · {1}',
    'Bert The Bird appikon': 'Icône de l’app Bert The Bird',
    'Bert The Bird bliver installeret': 'Installation de Bert The Bird',
    'Bert The Bird er installeret': 'Bert The Bird est installé',
    'Bert The Bird spilcanvas': 'Zone de jeu Bert The Bird',
    'Bert flyver': 'Bert vole',
    'Bevægelse i koncertlys': 'Mouvement des lumières de concert',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Dépense 12 plumes pour un tour de roue. Cinq cases renvoient Bert dans le niveau. Une case termine le vol.',
    'DAGENS MISSIONER': 'MISSIONS DU JOUR',
    'DAGENS RUTE': 'PARCOURS DU JOUR',
    'DAGENS RUTE · MÅL {0}': 'PARCOURS DU JOUR · OBJECTIF {0}',
    'DENNE TUR': 'CE VOL',
    'DIN FLYVETUR': 'TON VOL',
    'DIN HELT': 'TON HÉROS',
    'DIN SALDO': 'TON SOLDE',
    'DINE VENNEDUELLER': 'TES DUELS ENTRE AMIS',
    'DREJ TELEFONEN': 'TOURNE TON TÉLÉPHONE',
    'DU ER UDFORDRET': 'TU ES DÉFIÉ',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'TU AS GAGNÉ LE DUEL · défie en retour · {0} étoiles',
    'Den sjældneste fugl · køb for fjer': 'L’oiseau le plus rare · achète avec des plumes',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Ce niveau ne peut pas servir aux duels classés entre amis.',
    'Dit navn': 'Ton nom',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Ton nom apparaît dans le classement et à côté de tes records.',
    'Du mangler fjer fra dagens missioner': 'Il te manque des plumes des missions du jour',
    'EDM-VERDEN · LOKALT': 'MONDE EDM · LOCAL',
    'EPISK': 'ÉPIQUE',
    'EVENT · BIRD RUN · TESTBANE': 'ÉVÉNEMENT · BIRD RUN · NIVEAU TEST',
    'EVENT · NEON ENCORE · TESTBANE': 'ÉVÉNEMENT · NEON ENCORE · NIVEAU TEST',
    'EVENT · STORMLINE · TESTBANE': 'ÉVÉNEMENT · STORMLINE · NIVEAU TEST',
    'EVENTYR': 'AVENTURE',
    'EVENTYR · {0}': 'AVENTURE · {0}',
    'Episk helt · kun til dig · valgt': 'Héros épique · rien que pour toi · choisi',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Héros épique · rien que pour toi. Touche pour choisir.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Une vie de secours permanente absorbe un choc à chaque vol. Après un crash, tu peux aussi dépenser 12 plumes pour un tour de roue. Tu peux toujours continuer sans énergie ni attente.',
    'FAST + BEVÆGELIG': 'FIXE + MOBILE',
    'FASTE TÅRNE': 'TOURS FIXES',
    'FJER': 'PLUMES',
    'FJER RETUR': 'PLUMES RENDUES',
    'FJER · PRIMÆRT VINDES I SPILLET': 'PLUMES · SE GAGNENT SURTOUT EN JOUANT',
    'FLYV': 'VOLER',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'TRAVERSE TROIS PORTES DE NUAGES · TOUCHE LA PLAQUE D’OR · GAUCHE MONTE · DROITE DESCEND',
    'FLYV IGEN': 'REVOLER',
    'FLYV VIDERE': 'CONTINUER',
    'FLYVETUREN ER SAT PÅ PAUSE': 'LE VOL EST EN PAUSE',
    'FODBOLD-BERT': 'BERT FOOTBALLEUR',
    'FOKUS': 'FOCUS',
    'FOKUS OM {0}': 'FOCUS DANS {0}',
    'FORBI': 'RATÉ',
    'FORBI GULDPLADEN': 'PLAQUE D’OR RATÉE',
    'FORSTÅET': 'COMPRIS',
    'FORTRYD': 'ANNULER',
    'FORTSÆT': 'CONTINUER',
    'FRI AF ROVFUGLEN': 'LIBRE DU RAPACE',
    'FUGL BAGFRA': 'OISEAU PAR DERRIÈRE',
    'FUGLEVERDEN · LOKALT': 'MONDE DES OISEAUX · LOCAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Quatre mondes d’événement locaux gratuits sans classement mondial',
    'Flyv samlet i 3 minutter': 'Vole 3 minutes au total',
    'Flyvetid': 'Temps de vol',
    'Fodbold-Bert': 'Bert Footballeur',
    'Forbindelsen er tilbage': 'La connexion est revenue',
    'Fremgang mod oplåsning': 'Progression vers le déblocage',
    'Fugle · rovfugl': 'Oiseaux · rapace',
    'FÆRDIG': 'TERMINÉ',
    'FØLG STJERNESTRØMMEN': 'SUIS LE FLUX D’ÉTOILES',
    'FØLGER DIG KORT · {0}s': 'TE SUIT UN INSTANT · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · LE VOL S’ARRÊTE',
    'GLOBALT': 'MONDIAL',
    'GLOBALT · {0} RESULTATER': 'MONDIAL · {0} RÉSULTATS',
    'GODT RAMT': 'BIEN TOUCHÉ',
    'GRATIS REDNING': 'SAUVETAGE GRATUIT',
    'GRUNDFLYVNING': 'VOL DE BASE',
    'GULD': 'OR',
    'GULD-BERT': 'BERT DORÉ',
    'Guld-Bert': 'Bert Doré',
    'HAV BERT PÅ STARTSKÆRMEN': 'GARDE BERT SUR TON ÉCRAN D’ACCUEIL',
    'HAVNEN': 'LE PORT',
    'Havnen': 'Le Port',
    'HENT FJER': 'RÉCUPÉRER LES PLUMES',
    'HENT SPILLET': 'TÉLÉCHARGER LE JEU',
    'HENT +{0}': 'RÉCUPÉRER +{0}',
    '+{0} FJER': '+{0} PLUMES',
    'HENTER RESULTATER …': 'CHARGEMENT DES RÉSULTATS …',
    'HENTET': 'RÉCUPÉRÉ',
    'HOLD OP/NED': 'MAINTENIR HAUT/BAS',
    'HOVEDMENU': 'MENU PRINCIPAL',
    'HVAD HEDDER DU?': 'COMMENT TU T’APPELLES ?',
    'HVORDAN VIL DU FLYVE?': 'COMMENT VEUX-TU VOLER ?',
    'HYPERFART': 'HYPERVITESSE',
    'Haptisk feedback': 'Retour haptique',
    'Har altid en pakke med · køb for fjer': 'A toujours un colis · achète avec des plumes',
    'Hele Bert The Bird er lavet til landscape.': 'Bert The Bird est conçu pour le mode paysage.',
    'Hemmelig helt': 'Héros secret',
    'Hent en mission syv dage i træk': 'Récupère une mission sept jours de suite',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Récupère {0} récompenses de mission au total ; tu en as {1}.',
    'Henter resultater …': 'Chargement des résultats …',
    'Høj fart': 'Grande vitesse',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'Dans Safari : Partager → Sur l’écran d’accueil. Attends « Prêt pour le jeu hors ligne » et ouvre l’icône une fois avec internet avant de tester en mode avion.',
    'I dag': 'Aujourd’hui',
    'IKKE NU': 'PAS MAINTENANT',
    'INDSTILLINGER': 'RÉGLAGES',
    'INSTALLÉR WEBAPP': 'INSTALLER LA WEB APP',
    'ISTAPPER & SPIDSER': 'STALACTITES & PICS',
    'Isbjerget': 'L’Iceberg',
    'ISBJERGET': 'L’ICEBERG',
    'Bert gør klar til at flyve …': 'Bert se prépare à voler …',
    'Ingen rekord endnu': 'Pas encore de record',
    'Installér som webapp': 'Installer comme web app',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Installe depuis le menu du navigateur. Attends « Prêt pour le jeu hors ligne » et ouvre l’app une fois avec internet avant de tester hors ligne.',
    'KANT': 'BORD',
    'KLAR DAGENS MÅL': 'ATTEINS L’OBJECTIF DU JOUR',
    'KLARET': 'RÉUSSI',
    'KONCERT · TESTBANE': 'CONCERT · NIVEAU TEST',
    'KRANER & MÅGER': 'GRUES & MOUETTES',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'TES RÉSULTATS LOCAUX SEULEMENT · LE CLASSEMENT EN LIGNE N’EST PAS DISPONIBLE',
    'KVALIFIKATIONSBANEN': 'LE NIVEAU DE QUALIFICATION',
    'Klar dagens rute': 'Réussis le parcours du jour',
    'Klar dagens rute én gang': 'Réussis le parcours du jour une fois',
    'Klar hele forrige trin og missionskravet først': 'Réussis d’abord tout le palier précédent et l’objectif de missions',
    'Klar hele trin {0}: {1}.': 'Réussis tout le palier {0} : {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Réussis le niveau de qualification pour ouvrir ce défi.',
    'Klar til offline-spil': 'Prêt pour le jeu hors ligne',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Passe au moins trois balles dans une vague de concert',
    'KØB': 'ACHETER',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'ACHÈTE DES VIES FIXES OU UN TOUR DE SECOURS',
    'KØB · {0} FJER': 'ACHETER · {0} PLUMES',
    'KØBT': 'ACHETÉ',
    'LAVA & BOBLER': 'LAVE & BULLES',
    'LEVENDE FORHINDRINGER': 'OBSTACLES VIVANTS',
    'LEVERING': 'LIVRAISON',
    'LYD & FEEDBACK': 'SON & RETOUR',
    'LYDLØS': 'SILENCIEUX',
    'Level 1 · Mål 30': 'Niveau 1 · Objectif 30',
    'Luk': 'Fermer',
    'Luk garderoben': 'Fermer la garde-robe',
    'Lydeffekter': 'Effets sonores',
    'Lydløs og hurtig · køb for fjer': 'Silencieux et rapide · achète avec des plumes',
    'LÅS OP · 20 FJER': 'DÉBLOQUER · 20 PLUMES',
    'LÅS OP · {0} FJER': 'DÉBLOQUER · {0} PLUMES',
    'LÅST BANE': 'NIVEAU VERROUILLÉ',
    'LÅST OP': 'DÉBLOQUÉ',
    'LÆR KORRIDOREN': 'APPRENDS LE COULOIR',
    'Låst op. Tryk på figuren for at vælge.': 'Débloqué. Touche le personnage pour le choisir.',
    'MAKS LÅST OP': 'MAXIMUM ATTEINT',
    'MINISPIL · SKY RELAY · LOKALT': 'MINI-JEU · SKY RELAY · LOCAL',
    'MISSIONER': 'MISSIONS',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MOBILE : CÔTÉ GAUCHE = HAUT · CÔTÉ DROIT = BAS',
    'Missioner': 'Missions',
    'Mod vinden': 'Contre le vent',
    'Musik': 'Musique',
    'MÅGEN MOGENS': 'MOGENS LA MOUETTE',
    'Mågen Mogens': 'Mogens la Mouette',
    'MÅL: 3 BOLDE': 'OBJECTIF : 3 BALLES',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'OBJECTIF : PASSE UNE VAGUE DE TROIS BALLES · GAUCHE MONTE · DROITE DESCEND',
    'MÅL: ROVFUGL': 'OBJECTIF : RAPACE',
    'MÅL: STORM': 'OBJECTIF : TEMPÊTE',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'OBJECTIF : ÉVITE UN RAPACE · GAUCHE MONTE · DROITE DESCEND',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'OBJECTIF : ÉVITE UN OBJET DE TEMPÊTE · SUIS LES DRAPEAUX ET LES FEUILLES',
    'MÆRKE VUNDET': 'BADGE GAGNÉ',
    'MØRKE & SKILTE': 'NUIT & ENSEIGNES',
    'Måned': 'Mois',
    'NED': 'BAS',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} étoiles · record d’événement local uniquement',
    'NINJA-BERT': 'BERT NINJA',
    'Ninja-Bert': 'Bert Ninja',
    'NIVEAU {0}! · {1}': 'PALIER {0} ! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING DÉBLOQUÉ · VOL PARFAIT',
    'NY BANE': 'NOUVEAU NIVEAU',
    'NY REKORD!': 'NOUVEAU RECORD !',
    'NYE VERDENER': 'NOUVEAUX MONDES',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NOUVEAU PALIER : LES TROIS NIVEAUX SONT OUVERTS · {0} étoiles récoltées',
    'NATTEBYEN': 'LA VILLE DE NUIT',
    'Nattebyen': 'La Ville de Nuit',
    'Ny mobilversion indlæst': 'Nouvelle version mobile chargée',
    'Nyt redningsliv låst op': 'Nouvelle vie de secours débloquée',
    'NÆSTE UDFORDRING': 'DÉFI SUIVANT',
    'Nå 120 point i Desert': 'Atteins 120 points dans Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Atteins 180 points sans rater une étoile ni rien toucher',
    'Nå 300 point på én tur': 'Atteins 300 points en un vol',
    'Nå bronze i Jungle uden redning': 'Obtiens le bronze dans Jungle sans sauvetage',
    'Nå bronze i alle ni baner': 'Obtiens le bronze dans les neuf niveaux',
    'Nå bronze i alle tre Classic-baner': 'Obtiens le bronze dans les trois niveaux Classic',
    'Nå en streak på 12': 'Atteins une série de 12',
    'OMVENDT STYRING': 'COMMANDES INVERSÉES',
    'OP': 'HAUT',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Le mode hors ligne n’est pas encore prêt · connecte-toi à internet',
    'PAKKE-BERT': 'BERT COLIS',
    'Pakke-Bert': 'Bert Colis',
    'PERMANENT REDE-FORDEL': 'AVANTAGE PERMANENT DU NID',
    'PERSONLIG REKORD': 'RECORD PERSONNEL',
    'PILOTER': 'PILOTES',
    'POINT ×2': 'POINTS ×2',
    'PORTE & KLOKKE': 'PORTES & CLOCHE',
    'PRINSESSE SØS': 'PRINCESSE SØS',
    'Prinsesse Søs': 'Princesse Søs',
    'PRÆCISION': 'PRÉCISION',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'VOL DE PRÉCISION · ESSAI LOCAL',
    'PRÆCISIONSRUTE · LOKALT': 'PARCOURS DE PRÉCISION · LOCAL',
    'PUBLIKUMSVØLGE': 'VAGUE DU PUBLIC',
    'Pause spillet': 'Mettre le jeu en pause',
    'Periode': 'Période',
    'Personlig highscore': 'Record personnel',
    'Pilotnavn': 'Nom de pilote',
    'Pingvin med jetpack · køb for fjer': 'Pingouin à jetpack · achète avec des plumes',
    'Point': 'Points',
    'Porte · vindklokke': 'Portes · carillon',
    'PORT {0}/3': 'PORTE {0}/3',
    'PORT {0}/3 · {1}': 'PORTE {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'MANCHE {0} · PORTE {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'DING ! +{0} · MANCHE {1}',
    'Præcisionsflyvning': 'Vol de précision',
    'RAM GULDPLADEN': 'TOUCHE LA PLAQUE D’OR',
    'RAMT': 'TOUCHÉ',
    'RANGLISTE': 'CLASSEMENT',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'SAUVÉ · TES 12 PLUMES REVIENNENT',
    'REDDET · {0}': 'SAUVÉ · {0}',
    'REDNINGSLIV': 'VIE DE SECOURS',
    'REDNINGSLIV 0/3': 'VIES DE SECOURS 0/3',
    'REDNINGSLIV {0}/{1}': 'VIES DE SECOURS {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'LE NID DE SECOURS TOURNE …',
    'REDNINGSSPIN': 'TOUR DE SECOURS',
    'RENT GENNEM': 'PASSAGE PARFAIT',
    'RIGGE & BOLDE': 'STRUCTURES & BALLES',
    'ROTORER & BØJER': 'ROTORS & BOUÉES',
    'ROVFUGL': 'RAPACE',
    'ROVFUGL BAGFRA': 'RAPACE PAR DERRIÈRE',
    'FUGL': 'OISEAU',
    'BAGFRA': 'PAR DERRIÈRE',
    'FORFRA': 'DE FACE',
    'RUTEN AFSLUTTET': 'PARCOURS TERMINÉ',
    'Redningsliv tilbage': 'Vies de secours restantes',
    'Rigge · bolde': 'Structures · balles',
    'SJÆLDEN': 'RARE',
    'SKIFT BANE': 'CHANGER DE NIVEAU',
    'SKJOLD': 'BOUCLIER',
    'SKJOLD BRUGT · 2s': 'BOUCLIER UTILISÉ · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} DE LA PORTE {1} TOUCHÉ · 0 POINT · RÉESSAIE',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 POINT · RÉESSAIE',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 PORTES · {1}% PRÉCISION · LOCAL UNIQUEMENT',
    'TOPPEN': 'LE HAUT',
    'BUNDEN': 'LE BAS',
    'SKYRING RAMT': 'ANNEAU DE NUAGE TOUCHÉ',
    'SPIL': 'JOUER',
    'SPIL KVALIFIKATION': 'JOUER LA QUALIFICATION',
    'SPIL →': 'JOUER →',
    'SPIL {0}': 'JOUER {0}',
    'SPIN FOR AT SE DIN REDNING': 'TOURNE POUR VOIR TON SAUVETAGE',
    'SPIN · 12 FJER': 'TOURNER · 12 PLUMES',
    'SPIN · {0} FJER': 'TOURNER · {0} PLUMES',
    'START FORFRA': 'RECOMMENCER',
    'STARTBANE': 'NIVEAU DE DÉPART',
    'STJERNEREGN': 'PLUIE D’ÉTOILES',
    'STIGER': 'MONTE',
    'DYKKER': 'PLONGE',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · VENT ET OBJETS VOLANTS · {0} étoiles · record d’événement local uniquement',
    'STREAK REDDET · GUARD BRUGT': 'SÉRIE SAUVÉE · GUARD UTILISÉ',
    'STORMPILOT': 'PILOTE DE TEMPÊTE',
    'Saml 20 stjerner til reden': 'Récolte 20 étoiles pour le nid',
    'Saml 250 stjerner i alt': 'Récolte 250 étoiles au total',
    'Scoretype': 'Type de score',
    'Skriv dit navn': 'Écris ton nom',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Joue à Bird Run, un monde d’oiseaux local. Évite le rapace annoncé. Pas de classement mondial.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Joue à Neon Encore, un monde de concert local. Survis à une vague entière avec au moins trois balles. Pas de classement mondial.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Joue à Sky Relay, un court parcours local de précision à travers trois anneaux de nuages. Le haut et le bas de l’anneau peuvent être touchés. Touche la plaque d’or du carillon. Pas de classement mondial.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Joue à Stormline, un monde de vent local. Évite un objet volant dans la tempête. Pas de classement mondial.',
    'Spiltype': 'Mode de jeu',
    'Start Quick Flight': 'Lancer Quick Flight',
    'Starthelt · Klar til at flyve': 'Héros de départ · Prêt à voler',
    'Starthelt': 'Héros de départ',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard prêt : sauve une étoile ratée',
    'Streak Guard reddede din streak': 'Streak Guard a sauvé ta série',
    'Sur havnemåge · køb for fjer': 'Mouette grincheuse du port · achète avec des plumes',
    'SØLV': 'ARGENT',
    'BRONZE': 'BRONZE',
    'Sådan virker Berts rede': 'Comment fonctionne le nid de Bert',
    'TAP': 'TAPOTER',
    'TAP FOR AT FLYVE · {0}': 'TAPOTE POUR VOLER · {0}',
    'TESTBANE': 'NIVEAU TEST',
    'TIDEN UDE': 'TEMPS ÉCOULÉ',
    'TILBAGE': 'RETOUR',
    'TRYK FOR AT STARTE': 'TOUCHE POUR COMMENCER',
    'TUNG': 'LOURD',
    'TUNG · STIGER LANGSOMT': 'LOURD · MONTE LENTEMENT',
    'Tid': 'Temps',
    'Tilgængelige helte': 'Héros disponibles',
    'UDFORDR EN VEN': 'DÉFIE UN AMI',
    'Udfordringen er klar': 'Le défi est prêt',
    'Udfordringslink klar': 'Lien du défi prêt',
    'Udfordringslink kopieret': 'Lien du défi copié',
    'Uge': 'Semaine',
    'Undvig den varslede ørn eller grib': 'Évite l’aigle ou le vautour annoncé',
    'Undvig en flyvende genstand i storm eller orkan': 'Évite un objet volant en tempête ou en ouragan',
    'VELKOMMEN': 'BIENVENUE',
    'VENNEDUEL': 'DUEL ENTRE AMIS',
    'VENNER': 'AMIS',
    'VERDEN': 'MONDE',
    'VENNER FRA DUELLER': 'AMIS DES DUELS',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'AMIS DES DUELS · {0} RIVAUX · {1} RÉSULTATS',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'CÔTÉ GAUCHE = HAUT · CÔTÉ DROIT = BAS',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · GAUCHE MONTE · DROITE DESCEND',
    'VERDEN KLARET': 'MONDE TERMINÉ',
    'VERDEN KLARET · LOKALT': 'MONDE TERMINÉ · LOCAL',
    'VIND & GENSTANDE': 'VENT & OBJETS',
    'VIND · TESTBANE': 'VENT · NIVEAU TEST',
    'VIND · {0}': 'VENT · {0}',
    'VINDKLOKKEN RAMT': 'CARILLON TOUCHÉ',
    'VINDVERDEN · LOKALT': 'MONDE DU VENT · LOCAL',
    'Vindmøller': 'Les Éoliennes',
    'VINDMØLLER': 'LES ÉOLIENNES',
    'Vulkanen': 'Le Volcan',
    'VULKANEN': 'LE VOLCAN',
    'FJENDER & ANGREB': 'ENNEMIS & ATTAQUES',
    'FUGLETRAFIK · TESTBANE': 'TRAFIC D’OISEAUX · NIVEAU TEST',
    'FUGLE & ROVFUGL': 'OISEAUX & RAPACE',
    'FLAPPY-STYRING': 'COMMANDES FLAPPY',
    'FLAPPY-STYRING · TAP': 'COMMANDES FLAPPY · TAPOTER',
    'VUNDET': 'GAGNÉ',
    'BEHOLDT': 'CONSERVÉ',
    'Valgt og klar til at flyve': 'Choisi et prêt à voler',
    'Vind bronze, sølv og guld': 'Gagne le bronze, l’argent et l’or',
    'Vind ti vennedueller': 'Gagne dix duels entre amis',
    'Vind · genstande': 'Vent · objets',
    'VÆLG HELT': 'CHOISIS UN HÉROS',
    'VÆLG LEVEL': 'CHOISIS UN NIVEAU',
    'VÆLG SPILTYPE': 'CHOISIS UN MODE',
    'Vælg Bert': 'Choisir Bert', 'Vælg Blok-Johan': 'Choisir Blok-Johan', 'Vælg BlueBert': 'Choisir BlueBert', 'Vælg BoneBeak': 'Choisir BoneBeak',
    'Vælg BrainBird': 'Choisir BrainBird', 'Vælg BrickBird': 'Choisir BrickBird', 'Vælg Coopinc': 'Choisir Coopinc', 'Vælg Fodbold-Bert': 'Choisir Bert Footballeur',
    'Vælg Guld-Bert': 'Choisir Bert Doré', 'Vælg InkBird': 'Choisir InkBird', 'Vælg MechaBert': 'Choisir MechaBert', 'Vælg MossHex': 'Choisir MossHex',
    'Vælg Mågen Mogens': 'Choisir Mogens la Mouette', 'Vælg Ninja-Bert': 'Choisir Bert Ninja', 'Vælg NoirWing': 'Choisir NoirWing', 'Vælg Pakke-Bert': 'Choisir Bert Colis',
    'Vælg Pingo': 'Choisir Pingo', 'Vælg Prinsesse Søs': 'Choisir Princesse Søs', 'Vælg PrismWing': 'Choisir PrismWing', 'Vælg SkyClaw': 'Choisir SkyClaw',
    'Vælg Storm Royale': 'Choisir Storm Royale', 'Vælg SugarRush': 'Choisir SugarRush', 'Vælg Thor Obby': 'Choisir Thor Obby',
    'Vælg bane': 'Choisir un niveau',
    'Vælg leaderboard': 'Choisir un classement',
    'Vælg level': 'Choisir un niveau',
    'Vælg spiltype': 'Choisir un mode',
    'Vælg {0}, {1}': 'Choisir {0}, {1}',
    'købt': 'acheté',
    'låst op': 'débloqué',
    '{0} ER LÅST': '{0} EST VERROUILLÉ',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} a fait {1} points. Tu as {2} essais sur le même niveau, et son vol apparaît comme une ombre.',
    '{0} forsøg tilbage · slå {1} point': '{0} essais restants · bats {1} points',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} te défie de battre {1} points. Tu as trois essais.',
    '{0} låst op for {1} fjer': '{0} débloqué pour {1} plumes',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} verrouillé. {1}. {2} sur {3}. Prix alternatif : {4} plumes.',
    '{0} missionsbelønninger': '{0} récompenses de mission',
    '{0} missionsbelønninger er hentet.': '{0} récompenses de mission récupérées.',
    '{0} point til næste medalje': '{0} points avant la prochaine médaille',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Quand les deux conditions sont remplies, tout le palier {2} s’ouvre.',
    '{0} · {1} FASTE LIV': '{0} · {1} VIES FIXES',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, verrouillé. Touche pour voir la condition',
    '{0}, åben, personlig rekord {1}': '{0}, ouvert, record personnel {1}',
    '{0} · Mål {1}': '{0} · Objectif {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} NIVEAUX · {2}/{3} MISSIONS',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} NIVEAUX · {2}/{3} MISS.',
    '{0} BANER · {1}': '{0} NIVEAUX · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} OUVERTS · {2}',
    'DU MANGLER {0} FJER': 'IL TE MANQUE {0} PLUMES',
    'BESKYTTET · {0}s': 'PROTÉGÉ · {0}s',
    'ÅBN DAGENS MISSIONER': 'OUVRIR LES MISSIONS DU JOUR',
    'ÅBN GARDEROBE · 17 HELTE': 'OUVRIR LA GARDE-ROBE · 17 HÉROS',
    'ÅNDENDE PORTE': 'PORTES QUI RESPIRENT',
    'Åbn dagens missioner': 'Ouvrir les missions du jour',
    'Åbn highscore': 'Ouvrir les records',
    'Åbn indstillinger': 'Ouvrir les réglages',
    'ÉN CHANCE MERE?': 'UNE CHANCE DE PLUS ?',
    'Sprog': 'Langue',
    'Automatisk (som telefonen)': 'Automatique (comme le téléphone)',
    'Dansk': 'Danois', 'Engelsk': 'Anglais', 'Norsk': 'Norvégien', 'Svensk': 'Suédois', 'Tysk': 'Allemand', 'Spansk': 'Espagnol', 'Fransk': 'Français', 'Portugisisk': 'Portugais',
    '+1 FJER': '+1 PLUME',
    'En ven': 'Un ami',
    'Dig': 'Toi',
    'REKORD': 'RECORD',
    'Topflyvning': 'Vol parfait',
    '{0} point i {1}': '{0} points dans {1}',
    'en bane': 'un niveau',
    '{0} til trin {1} · {2} stjerner': '{0} pour le palier {1} · {2} étoiles',
    '{0} · {1} stjerner samlet': '{0} · {1} étoiles récoltées',
    '{0} FJER': '{0} PLUMES',
    'TAP FOR AT FLYVE': 'TAPOTE POUR VOLER',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Bats le score de ton ami sur exactement le même niveau. Tu as trois essais, et son vol fantôme te suit.",
    '{0}/{1} BRONZE': '{0}/{1} BRONZE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Obtiens le bronze (20 points) sur les {0} niveaux de base pour ouvrir Aventure. Tu en as {1}.',
    'SØLV I {0}': 'ARGENT DANS {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Obtiens l’argent (50 points) dans {0} pour ouvrir {1}.',
    'LAVAEN FALDER': 'LA LAVE DESCEND',
    'GODT GREB · {0}s': 'BONNE PRISE · {0}s',
    'VINDSTØD · OP': 'RAFALE · HAUT',
    'VINDSTØD · NED': 'RAFALE · BAS',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'GLACE GLISSANTE : ANTICIPE · RAMASSE LES CRISTAUX DE GIVRE',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'ATTENTION AUX RAFALES · LES FLÈCHES MONTRENT LE SENS',
    'LAVAEN STIGER · SAML KØLESTEN': 'LA LAVE MONTE · RAMASSE LES PIERRES FROIDES',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'LA LUMIÈRE BAISSE LENTEMENT · RAMASSE LES LANTERNES',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'LES CONTENEURS BOUGENT · ATTENTION AUX MOUETTES',
    'Fugleklat': 'Fiente',
    'SPIS & KLAT': 'MANGE & LÂCHE',
    'PARAPLYEN REDDEDE DEM': 'LE PARAPLUIE LES A SAUVÉS',
    'GULDBIL! ×3': 'VOITURE EN OR ! ×3',
    'PLASK!': 'SPLAT !',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'MANGE · TOUCHE 💩 POUR VISER EN BAS',
    'Slip en klat': 'Lâcher une fiente',
    'Alle helte flyver ens. Vind dem i spillet, eller spar fjer sammen.': 'Tous les héros volent pareil. Gagne-les en jeu ou économise des plumes.',
    'ÅBN GARDEROBE': 'OUVRIR LE VESTIAIRE',
    'OP · EVIGT SKJOLD · INGEN REKORDER': 'OP · BOUCLIER ÉTERNEL · PAS DE RECORDS',
    'FORSTØR': 'AGRANDIR',
    'FORMINDSK': 'RÉTRÉCIR',
    'FORSTØR · POINT ×2': 'AGRANDIR · POINTS ×2',
    'FØLG TUNNELEN · HOLD VENSTRE = OP · HØJRE = NED': 'SUIS LE TUNNEL · GAUCHE = MONTER · DROITE = DESCENDRE',
    // Feedback 4. okt.: reden, æg, mærker, eventyr-låse, lyd.
    "Vælg én starthelt efter 10, 20, 30 og 40 ture": "Choisis un héros de départ après 10, 20, 30 et 40 vols",
    "Nå 600 point på én tur": "Marque 600 points en un vol",
    "Nå guld i alle tre Classic-baner": "Obtiens l'or sur les trois niveaux Classic",
    "Kun fra et æg i reden": "Seulement d'un œuf dans le nid",
    "Kun fra et æg i reden (sjælden)": "Seulement d'un œuf dans le nid (rare)",
    "Æggebert": "Œufbert",
    "ÆGGEBERT": "ŒUFBERT",
    "Vælg Æggebert": "Choisis Œufbert",
    "Klæk alle helte fra rugepladsen": "Fais éclore tous les héros du couvoir",
    "KLÆK ALLE": "FAIS TOUT ÉCLORE",
    "Blød rede": "Nid douillet",
    "Et sted at lande. Fjer bygger den videre.": "Un endroit où atterrir. Les plumes l'agrandissent.",
    "Redningsfjer": "Plume de secours",
    "REDNINGSFJER": "PLUME DE SECOURS",
    "Ét redningsliv på hver tur.": "Une vie de secours à chaque vol.",
    "Stærkere magnet": "Aimant plus fort",
    "Magneten trækker 30 % længere.": "L'aimant attire 30 % plus loin.",
    "Varmt skjold": "Bouclier chaud",
    "Skjoldet holder 2 sekunder længere.": "Le bouclier dure 2 secondes de plus.",
    "Hurtig start": "Départ rapide",
    "Usårlig med ekstra fart de første 5 sekunder.": "Invincible et plus rapide pendant les 5 premières secondes.",
    "To redningsliv": "Deux vies de secours",
    "To redningsliv på hver tur.": "Deux vies de secours à chaque vol.",
    "Guldrede": "Nid doré",
    "Stjerner giver +1 point de første 10 sekunder.": "Les étoiles donnent +1 point pendant les 10 premières secondes.",
    "Første flyvetur": "Premier vol",
    "Gennemfør din første tur": "Termine ton premier vol",
    "Første stjerne": "Première étoile",
    "Saml din første stjerne": "Ramasse ta première étoile",
    "Første fjer": "Première plume",
    "Find din første gyldne fjer": "Trouve ta première plume dorée",
    "Vind din første bronzemedalje": "Gagne ta première médaille de bronze",
    "Ny ven": "Nouvel ami",
    "Lås din første ekstra helt op": "Débloque ton premier héros bonus",
    "Sølv": "Argent",
    "Vind sølv på en bane": "Gagne l'argent sur un niveau",
    "Guld": "Or",
    "Vind guld på en bane": "Gagne l'or sur un niveau",
    "I flow": "Dans le flow",
    "Nå en streak på 10": "Atteins une série de 10",
    "Ustoppelig": "Inarrêtable",
    "Nå en streak på 25": "Atteins une série de 25",
    "Stjerneregn": "Pluie d'étoiles",
    "Saml 100 stjerner på én tur": "Ramasse 100 étoiles en un vol",
    "Højtflyver": "Haut vol",
    "Få 500 point på én tur": "Marque 500 points en un vol",
    "Udholdenhed": "Endurance",
    "Flyv 3 minutter på én tur": "Vole 3 minutes en un vol",
    "Fejlfri": "Sans faute",
    "Guld uden redningsliv eller redningsspin": "L'or sans vie ni roue de secours",
    "Klassiker": "Classique",
    "Bronze på alle Classic-baner": "Bronze sur tous les niveaux Classic",
    "Skorstensfejer": "Ramoneur",
    "Bronze på alle Flappy-baner": "Bronze sur tous les niveaux Flappy",
    "Tunnelrytter": "Cavalier du tunnel",
    "Bronze på alle Tunnel-baner": "Bronze sur tous les niveaux Tunnel",
    "Eventyrer": "Aventurier",
    "Lås Eventyr op": "Débloque Aventure",
    "Verdensflyver": "Voyageur du monde",
    "Sølv på alle seks eventyrbaner": "L'argent sur les six niveaux d'aventure",
    "Lavalord": "Seigneur de la lave",
    "Guld på Vulkanen": "L'or sur le Volcan",
    "Mesterskytte": "Tireur d'élite",
    "10 træffere i træk i Fugleklat": "10 touches d'affilée dans Fiente",
    "Publikumsvølge": "Vague du public",
    "Kom forbi tre bolde i én koncertbølge": "Passe trois ballons en une vague de concert",
    "Fri af rovfuglen": "Libéré du rapace",
    "Undvig den varslede rovfugl": "Évite le rapace annoncé",
    "Undvig en flyvende genstand i storm": "Évite un objet volant dans la tempête",
    "Portløber": "Coureur de portes",
    "Klar alle tre porte i én Sky Relay-runde": "Passe les trois portes en une manche de Sky Relay",
    "Ekstranummer": "Rappel",
    "Sølv i Neon Encore": "L'argent dans Neon Encore",
    "Pakket ind": "Emballé",
    "Bliv fanget af edderkoppen": "Fais-toi attraper par l'araignée",
    "Snack": "Casse-croûte",
    "Bliv fanget af slangen": "Fais-toi attraper par le serpent",
    "Grillkylling": "Poulet rôti",
    "Dø 50 gange i alt": "Écrase-toi 50 fois au total",
    "Flokken": "La volée",
    "Lås 10 helte op": "Débloque 10 héros",
    "Redebygger": "Bâtisseur de nid",
    "Saml 100 fjer i alt": "Ramasse 100 plumes au total",
    "GAME OVER": "PARTIE TERMINÉE",
    "MAGNET": "AIMANT",
    "Få bronze på alle tre Classic-baner for at åbne Havnen.": "Obtiens le bronze sur les trois niveaux Classic pour ouvrir Le Port.",
    "Få bronze på alle tre Flappy-baner for at åbne Nattebyen.": "Obtiens le bronze sur les trois niveaux Flappy pour ouvrir La Ville de Nuit.",
    "Få bronze på alle tre Tunnel-baner for at åbne Vindmøller.": "Obtiens le bronze sur les trois niveaux Tunnel pour ouvrir Les Éoliennes.",
    "Få sølv i to af Havnen, Nattebyen og Vindmøller for at åbne Vulkanen.": "Obtiens l'argent dans deux parmi Le Port, La Ville de Nuit et Les Éoliennes pour ouvrir Le Volcan.",
    "GULD PÅ EN BANE": "L'OR SUR UN NIVEAU",
    "SØLV I VULKANEN": "ARGENT DANS LE VOLCAN",
    "Få sølv i Vulkanen og guld på én af grundbanerne for at åbne Isbjerget.": "Obtiens l'argent dans Le Volcan et l'or sur un niveau de base pour ouvrir L'Iceberg.",
    "SØLV I ISBJERGET": "ARGENT DANS L'ICEBERG",
    "Få sølv i Isbjerget for at åbne Fugleklat.": "Obtiens l'argent dans L'Iceberg pour ouvrir Fiente.",
    "ÅBNER MED EVENTYR": "S'OUVRE AVEC AVENTURE",
    "Testbanerne åbner sammen med den første eventyrverden.": "Les niveaux test s'ouvrent avec le premier monde d'aventure.",
    "HEMMELIG": "SECRET",
    "LÅST": "VERROUILLÉ",
    "Låst. Tryk på helten for at se, hvordan du får den.": "Verrouillé. Touche le héros pour voir comment l'obtenir.",
    "En hemmelig helt. Den hører til et særligt pilotnavn.": "Un héros secret. Il appartient à un nom de pilote spécial.",
    "Du kan vælge en starthelt nu.": "Tu peux choisir un héros de départ maintenant.",
    "Eller klæk den fra et æg, når reden har nået trin 4.": "Ou fais-le éclore d'un œuf quand le nid atteint l'étape 4.",
    "REDEN ER FÆRDIG": "LE NID EST TERMINÉ",
    "Alle syv trin er bygget. Flot!": "Les sept étapes sont construites. Bravo !",
    "Du fandt et æg! Det ligger i reden og ruger.": "Tu as trouvé un œuf ! Il couve dans le nid.",
    "VÆLG EN NY HELT": "CHOISIS UN NOUVEAU HÉROS",
    "Du må vælge én. De andre kan vælges efter 10 ture mere.": "Choisis-en un. Les autres après 10 vols de plus.",
    "SENERE": "PLUS TARD",
    "Én tur om dagen giver fjer": "Un vol par jour donne des plumes",
    "Ruger et tilfældigt æg. Saml stjerner, så klækker det.": "Couve un œuf surprise. Ramasse des étoiles et il éclora.",
    "TOM": "VIDE",
    "ALLE KLÆKKET": "TOUS ÉCLOS",
    "Alle helte er klækket": "Tous les héros sont éclos",
    "fjer": "plumes",
    "sjælden": "rare",
    "Et æg ligger i reden. Saml stjerner, så klækker det.": "Un œuf est dans le nid. Ramasse des étoiles et il éclora.",
    "ER DU SIKKER? TRYK IGEN": "TU ES SÛR ? TOUCHE ENCORE",
    "GLOBAL HIGHSCORE": "MEILLEUR SCORE MONDIAL",
    "Du mangler fjer. Flyv en tur, og klar dagens missioner.": "Il te manque des plumes. Fais un vol et termine les missions du jour.",
    "{0}/3 CLASSIC": "{0}/3 CLASSIC",
    "{0}/3 FLAPPY": "{0}/3 FLAPPY",
    "{0}/3 TUNNEL": "{0}/3 TUNNEL",
    "SØLV {0}/2": "ARGENT {0}/2",
    "LÅST · {0}/{1}": "VERROUILLÉ · {0}/{1}",
    "Vælg den som starthelt efter {0} ture. Du har fløjet {1}.": "Choisis-le comme héros de départ après {0} vols. Tu en as fait {1}.",
    "Klæk alle helte fra rugepladsen. {0}/{1} klækket.": "Fais éclore tous les héros. {0}/{1} éclos.",
    "Bedrift: {0} ({1}/{2}).": "Exploit : {0} ({1}/{2}).",
    "Eller klæk den fra et æg i reden: sikret æg {0} fjer.": "Ou fais-le éclore d'un œuf : œuf choisi {0} plumes.",
    "Du har {0} fjer. Fjer får du af dagens missioner, en tur om dagen og sjældne fjer i banerne.": "Tu as {0} plumes. Tu en gagnes avec les missions du jour, un vol par jour et les plumes rares des niveaux.",
    "BYG · {0} FJER": "CONSTRUIRE · {0} PLUMES",
    "BYG · 20 FJER": "CONSTRUIRE · 20 PLUMES",
    "MANGLER {0} FJER": "IL MANQUE {0} PLUMES",
    "{0} TURE FLØJET": "{0} VOLS EFFECTUÉS",
    "{0} er din nu": "{0} est à toi",
    "Ægget klækkede: {0}!": "L'œuf a éclos : {0} !",
    "{0} er klækket og venter i garderoben": "{0} est éclos et t'attend au vestiaire",
    "Ægget: {0}/{1} stjerner": "L'œuf : {0}/{1} étoiles",
    "{0} fjer fundet": "{0} plumes trouvées",
    "Dag {0} i træk: +{1} fjer": "Jour {0} d'affilée : +{1} plumes",
    "Reden: {0}/{1} til {2}": "Nid : {0}/{1} pour {2}",
    "Nyt mærke: {0}": "Nouveau badge : {0}",
    "{0} dage i træk": "{0} jours d'affilée",
    "{0}/{1} STJERNER": "{0}/{1} ÉTOILES",
    "Ruger: {0}": "Couve : {0}",
    "{0} helte kan stadig klækkes": "{0} héros peuvent encore éclore",
    "TILFÆLDIGT ÆG · {0} FJER": "ŒUF SURPRISE · {0} PLUMES",
    "SIKRET ÆG · {0} FJER": "ŒUF CHOISI · {0} PLUMES",
    "TILFÆLDIGT ÆG": "ŒUF SURPRISE",
    "SIKRET ÆG": "ŒUF CHOISI",
    "Et sikret æg med {0} ligger i reden": "Un œuf choisi avec {0} est dans le nid",
    "Reden er bygget: {0}": "Nid construit : {0}",
    "Dag {0} i træk · +{1} fjer til reden": "Jour {0} d'affilée · +{1} plumes pour le nid",
    "Bert The Bird – flyvespil og præcisionsverdener": "Bert The Bird – jeu de vol et mondes de précision",
    "PAUSE": "PAUSE",
    "REDEN": "LE NID",
    "Reden": "Le nid",
    "Åbn reden": "Ouvrir le nid",
    "Luk reden": "Fermer le nid",
    "Redens trin": "Étapes du nid",
    "NÆSTE TRIN": "PROCHAINE ÉTAPE",
    "RUGEPLADSEN": "LE COUVOIR",
    "FLYV HVER DAG": "VOLE CHAQUE JOUR",
    "MÆRKER": "BADGES",
    "Fjer bygger reden. Hvert trin kan mærkes i spillet. Efter døden kan du bruge 12 fjer på ét redningsspin.": "Les plumes bâtissent le nid. Chaque étape se sent dans le jeu. Après une chute, tu peux dépenser 12 plumes pour une roue de secours.",
    "Forrige helte": "Héros précédents",
    "Næste helte": "Héros suivants",
    "Musikstyrke": "Volume de la musique",
    "Lydstyrke for effekter": "Volume des effets",
    "Vælg helt til sikret æg": "Choisis le héros de l'œuf choisi",
    "Banens grafik kunne ikke indlæses.": "Les graphismes du niveau n'ont pas pu être chargés.",
    "Spillet kunne ikke indlæses. Prøv igen.": "Le jeu n'a pas pu être chargé. Réessaie.",
    "NY HELT: {0} · {1}": "NOUVEAU HÉROS : {0} · {1}",
    "Klæk den fra et æg i reden: sikret æg {0} fjer.": "Fais-le éclore d'un œuf : œuf choisi {0} plumes.",
    "Klæk den fra et æg, når reden har nået trin 4.": "Fais-le éclore d'un œuf quand le nid atteint l'étape 4.",
    // Udfordringer (10. okt.)
    "Få 40 point uden redningsliv": "Marque 40 points sans vie de secours",
    "Få 80 point uden redningsliv": "Marque 80 points sans vie de secours",
    "Find en gylden fjer i en bane": "Trouve une plume dorée dans un niveau",
    "Få 60 point uden at tage en power-up": "Marque 60 points sans prendre de bonus",
    "Saml 400 stjerner i denne uge": "Ramasse 400 étoiles cette semaine",
    "Flyv 30 ture i denne uge": "Fais 30 vols cette semaine",
    "Guld på 2 forskellige baner i denne uge": "L'or sur 2 niveaux différents cette semaine",
    "Slå din egen rekord 3 gange": "Bats ton propre record 3 fois",
    "Flyv på 6 forskellige baner": "Vole sur 6 niveaux différents",
    "Flyv 30 minutter i denne uge": "Vole 30 minutes cette semaine",
    "Lynhurtig: styrt inden for 1 sekund": "Éclair : chute en moins d'1 seconde",
    "Svaret på alt: præcis 42 point": "La réponse à tout : exactement 42 points",
    "Natteravn: flyv mellem midnat og kl. 4": "Oiseau de nuit : vole entre minuit et 4 h",
    "Tålmodig: 60 sekunder uden en eneste stjerne": "Patient : 60 secondes sans une seule étoile",
    "Sultestrejke: 30 sekunder og 0 stjerner": "Grève de la faim : 30 secondes et 0 étoile",
    "Jo større de er: styrt mens du er forstørret": "Plus dure sera la chute : tombe en étant agrandi",
    "Juleflyver: flyv juleaften": "Vol de Noël : vole le soir de Noël",
    "Hattrick: tre ture i træk med samme point": "Coup du chapeau : trois vols d'affilée avec le même score",
    "Garderobe-gal: flyv med 7 forskellige helte": "Fan de vestiaire : vole avec 7 héros différents",
    "Maraton: 10 minutter på én tur": "Marathon : 10 minutes en un vol",
    "Ørkenrotte: 100 ture i Desert": "Rat du désert : 100 vols dans Desert",
    "Halvtreds: en streak på 50": "Cinquante : une série de 50",
    "Flappy-mester: 500 point i Flappy Bert": "Maître Flappy : 500 points dans Flappy Bert",
    "Bonk-serie: 5 styrt på 2 minutter": "Série de bonks : 5 chutes en 2 minutes",
    "Edderkoppens ven: fanget 10 gange": "Ami de l'araignée : attrapé 10 fois",
    "Saml {0} stjerner i dag": "Ramasse {0} étoiles aujourd'hui",
    "Flyv {0} minutter i alt i dag": "Vole {0} minutes au total aujourd'hui",
    "Nå en streak på {0}": "Atteins une série de {0}",
    "Flyv {0} ture i dag": "Fais {0} vols aujourd'hui",
    "Få {0} point på én tur": "Marque {0} points en un vol",
    "Tag {0} power-ups i dag": "Prends {0} bonus aujourd'hui",
    "Flyv {0} sekunder på én tur": "Vole {0} secondes en un vol",
    "Bronze i {0} i dag": "Bronze dans {0} aujourd'hui",
    "Sølv i {0} i dag": "Argent dans {0} aujourd'hui",
    "Guld i {0} i dag": "Or dans {0} aujourd'hui",
    "Tur nr. {0}": "Vol n° {0}",
    "{0} stjerner i alt": "{0} étoiles au total",
    "{0} fjer samlet i alt": "{0} plumes au total",
    "{0} helte": "{0} héros",
    "{0} mærker": "{0} badges",
    "Reden på trin {0}": "Nid à l'étape {0}",
    "{0} æg klækket": "{0} œufs éclos",
    "{0}: guld": "{0} : or",
    "{0}: 200 point": "{0} : 200 points",
    "{0}: 60 point uden redning og power-ups": "{0} : 60 points sans secours ni bonus",
    "??? (hemmelig udfordring)": "??? (défi secret)",
    "Tæt på: {0} ({1}/{2})": "Presque : {0} ({1}/{2})",
    "+{0} fjer · {1}": "+{0} plumes · {1}",
    "UGENS UDFORDRINGER": "DÉFIS DE LA SEMAINE",
    "UDFORDRINGER": "DÉFIS",
    "MILEPÆLE": "ÉTAPES",
    "MESTERSKAB": "MAÎTRISE",
    "HEMMELIGE": "SECRETS",
    "NIVEAU {0}!": "NIVEAU {0} !",
    "HVOR SKAL BERT HEN?": "OÙ VA BERT ?",
    "DIN REJSE": "TON VOYAGE",
    "Ørkenen": "Le désert",
    "Junglen": "La jungle",
    "Himlen": "Le ciel",
    "Byen": "La ville",
    "Tunnelen": "Le tunnel",
    "Natten": "La nuit",
    "Vinden": "Le vent",
    "Isen": "La glace",
    "Fugleklat-øen": "L'île Fiente",
    "Spejlbanen": "Niveau miroir",
    "GLID & OPVIND · TESTBANE": "PLANE & ASCENDANCES · NIVEAU TEST",
    "GLID & OPVIND": "PLANE & ASCENDANCES",
    "Svæv": "Planer",
    "Vælg et andet navn": "Choisis un autre nom",
    "FLOK & FORMATION · TESTBANE": "VOLÉE & FORMATION · NIVEAU TEST",
    "FLOK & FORMATION": "VOLÉE & FORMATION",
    "Fuglesværm": "Nuée d'oiseaux",
    "Klistermærke fundet! Se det i albummet i reden": "Autocollant trouvé ! Regarde-le dans l'album du nid",
    "KLISTERMÆRKER": "AUTOCOLLANTS",
    "Fem skjulte klistermærker i hver bane. Hold øje, mens du flyver.": "Cinq autocollants cachés dans chaque niveau. Ouvre l'œil en volant.",
    "Flokken": "La Volée",
    "UDFORDRER": "CHALLENGER",
    "NYT": "NOUVEAU",
    "FLOKKEN": "LA VOLÉE",
    "ALLE MOD ALLE I EN STOR HIMMEL": "TOUS CONTRE TOUS DANS UN GRAND CIEL",
});
