/* English. Keys are the Danish source texts; {0}, {1} … are values filled in at runtime. */
window.BertI18n.register('en', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FLY A RUN TO SET YOUR FIRST SCORE',
    ' · MÆRKE: {0}': ' · BADGE: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · PLAY A FRIEND DUEL TO GET A RIVAL',
    '+{0} fjer til reden': '+{0} feathers for the nest',
    '+{0} fjer · {1} låst op': '+{0} feathers · {1} unlocked',
    '0 / 0 POINT': '0 / 0 POINTS',
    '20 point til bronze': '20 points to bronze',
    '3 SPILFORMER · 9 BANER': '3 GAME MODES · 9 LEVELS',
    '3 baner · hold op/ned': '3 levels · hold up/down',
    '3 baner · præcision': '3 levels · precision',
    '3 baner · tap': '3 levels · tap',
    '9 baner · nye verdener': '9 levels · new worlds',
    'ACCEPTÉR': 'ACCEPT',
    'AFSLUT TUREN': 'END THE RUN',
    'Alle baner': 'All levels',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Every hero has the same speed and hitbox. Win them in the game, or save up feathers.',
    'Alle pointkrav i trin {0} er klaret.': 'All score requirements in tier {0} are complete.',
    'Alle spil': 'All games',
    'Alle tider': 'All time',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'All three attempts are used. Ask your friend for a new duel.',
    'BANEN ER LÅST': 'LEVEL LOCKED',
    'BEKRÆFT · {0} FJER': 'CONFIRM · {0} FEATHERS',
    'BERTS GARDEROBE': "BERT'S WARDROBE",
    'BERTS REDE': "BERT'S NEST",
    'BERTS REDNINGSREDE': "BERT'S RESCUE NEST",
    'BEVÆGELIGE TÅRNE': 'MOVING TOWERS',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} stars · local event record only',
    'Bane': 'Level',
    'Banen er låst': 'The level is locked',
    'Bedst på level {0} · {1}': 'Best on level {0} · {1}',
    'Bert The Bird appikon': 'Bert The Bird app icon',
    'Bert The Bird bliver installeret': 'Bert The Bird is being installed',
    'Bert The Bird er installeret': 'Bert The Bird is installed',
    'Bert The Bird spilcanvas': 'Bert The Bird game canvas',
    'Bert flyver': 'Bert flying',
    'Bevægelse i koncertlys': 'Motion in concert lights',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Spend 12 feathers on one spin. Five fields send Bert back into the level. One field ends the run.',
    'DAGENS MISSIONER': "TODAY'S MISSIONS",
    'DAGENS RUTE': "TODAY'S ROUTE",
    'DAGENS RUTE · MÅL {0}': "TODAY'S ROUTE · GOAL {0}",
    'DENNE TUR': 'THIS RUN',
    'DIN FLYVETUR': 'YOUR FLIGHT',
    'DIN HELT': 'YOUR HERO',
    'DIN SALDO': 'YOUR BALANCE',
    'DINE VENNEDUELLER': 'YOUR FRIEND DUELS',
    'DREJ TELEFONEN': 'ROTATE YOUR PHONE',
    'DU ER UDFORDRET': 'YOU HAVE BEEN CHALLENGED',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'YOU WON THE DUEL · challenge back · {0} stars',
    'Den sjældneste fugl · køb for fjer': 'The rarest bird · buy with feathers',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'This level cannot be used for ranked friend duels.',
    'Dit navn': 'Your name',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Your name appears on the leaderboard and next to your records.',
    'Du mangler fjer fra dagens missioner': "You need feathers from today's missions",
    'EDM-VERDEN · LOKALT': 'EDM WORLD · LOCAL',
    'EPISK': 'EPIC',
    'EVENT · BIRD RUN · TESTBANE': 'EVENT · BIRD RUN · TEST LEVEL',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENT · NEON ENCORE · TEST LEVEL',
    'EVENT · STORMLINE · TESTBANE': 'EVENT · STORMLINE · TEST LEVEL',
    'EVENTYR': 'ADVENTURE',
    'EVENTYR · {0}': 'ADVENTURE · {0}',
    'Episk helt · kun til dig · valgt': 'Epic hero · just for you · selected',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Epic hero · just for you. Tap to select.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'A permanent rescue life absorbs one crash on every run. After a crash you can also spend 12 feathers on one rescue spin. You can always keep playing with no energy or waiting.',
    'FAST + BEVÆGELIG': 'FIXED + MOVING',
    'FASTE TÅRNE': 'FIXED TOWERS',
    'FJER': 'FEATHERS',
    'FJER RETUR': 'FEATHERS BACK',
    'FJER · PRIMÆRT VINDES I SPILLET': 'FEATHERS · MOSTLY WON IN THE GAME',
    'FLYV': 'FLY',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'FLY THROUGH THREE CLOUD GATES · HIT THE GOLD PLATE · LEFT UP · RIGHT DOWN',
    'FLYV IGEN': 'FLY AGAIN',
    'FLYV VIDERE': 'KEEP FLYING',
    'FLYVETUREN ER SAT PÅ PAUSE': 'THE FLIGHT IS PAUSED',
    'FODBOLD-BERT': 'FOOTBALL BERT',
    'FOKUS': 'FOCUS',
    'FOKUS OM {0}': 'FOCUS IN {0}',
    'FORBI': 'MISSED',
    'FORBI GULDPLADEN': 'MISSED THE GOLD PLATE',
    'FORSTÅET': 'GOT IT',
    'FORTRYD': 'CANCEL',
    'FORTSÆT': 'CONTINUE',
    'FRI AF ROVFUGLEN': 'FREE OF THE RAPTOR',
    'FUGL BAGFRA': 'BIRD FROM BEHIND',
    'FUGLEVERDEN · LOKALT': 'BIRD WORLD · LOCAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Four free local event worlds without a global leaderboard',
    'Flyv samlet i 3 minutter': 'Fly for 3 minutes in total',
    'Flyvetid': 'Flight time',
    'Fodbold-Bert': 'Football Bert',
    'Forbindelsen er tilbage': 'Connection is back',
    'Fremgang mod oplåsning': 'Progress towards unlocking',
    'Fugle · rovfugl': 'Birds · raptor',
    'FÆRDIG': 'DONE',
    'FØLG STJERNESTRØMMEN': 'FOLLOW THE STAR STREAM',
    'FØLGER DIG KORT · {0}s': 'TRACKING YOU BRIEFLY · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · THE RUN ENDS',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} RESULTS',
    'GODT RAMT': 'GOOD HIT',
    'GRATIS REDNING': 'FREE RESCUE',
    'GRUNDFLYVNING': 'BASIC FLIGHT',
    'GULD': 'GOLD',
    'GULD-BERT': 'GOLD BERT',
    'Guld-Bert': 'Gold Bert',
    'HAV BERT PÅ STARTSKÆRMEN': 'KEEP BERT ON YOUR HOME SCREEN',
    'HAVNEN': 'THE HARBOUR',
    'Havnen': 'The Harbour',
    'HENT FJER': 'CLAIM FEATHERS',
    'HENT SPILLET': 'GET THE GAME',
    'HENT +{0}': 'CLAIM +{0}',
    '+{0} FJER': '+{0} FEATHERS',
    'HENTER RESULTATER …': 'LOADING RESULTS …',
    'HENTET': 'CLAIMED',
    'HOLD OP/NED': 'HOLD UP/DOWN',
    'HOVEDMENU': 'MAIN MENU',
    'HVAD HEDDER DU?': "WHAT'S YOUR NAME?",
    'HVORDAN VIL DU FLYVE?': 'HOW DO YOU WANT TO FLY?',
    'HYPERFART': 'HYPERSPEED',
    'Haptisk feedback': 'Haptic feedback',
    'Har altid en pakke med · køb for fjer': 'Always carries a parcel · buy with feathers',
    'Hele Bert The Bird er lavet til landscape.': 'All of Bert The Bird is made for landscape.',
    'Hemmelig helt': 'Secret hero',
    'Hent en mission syv dage i træk': 'Claim a mission seven days in a row',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Claim {0} mission rewards in total; you have {1}.',
    'Henter resultater …': 'Loading results …',
    'Høj fart': 'High speed',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'In Safari: Share → Add to Home Screen. Wait for “Ready for offline play”, and open the icon once while online before testing in airplane mode.',
    'I dag': 'Today',
    'IKKE NU': 'NOT NOW',
    'INDSTILLINGER': 'SETTINGS',
    'INSTALLÉR WEBAPP': 'INSTALL WEB APP',
    'ISTAPPER & SPIDSER': 'ICICLES & SPIKES',
    'Isbjerget': 'The Iceberg',
    'ISBJERGET': 'THE ICEBERG',
    'Bert gør klar til at flyve …': 'Bert is getting ready to fly …',
    'Ingen rekord endnu': 'No record yet',
    'Installér som webapp': 'Install as web app',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Install from the browser menu. Wait for “Ready for offline play”, and open the app once while online before testing offline.',
    'KANT': 'EDGE',
    'KLAR DAGENS MÅL': "COMPLETE TODAY'S GOAL",
    'KLARET': 'DONE',
    'KONCERT · TESTBANE': 'CONCERT · TEST LEVEL',
    'KRANER & MÅGER': 'CRANES & GULLS',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'ONLY YOUR LOCAL RESULTS · ONLINE SCOREBOARD IS NOT AVAILABLE',
    'KVALIFIKATIONSBANEN': 'THE QUALIFYING LEVEL',
    'Klar dagens rute': "Complete today's route",
    'Klar dagens rute én gang': "Complete today's route once",
    'Klar hele forrige trin og missionskravet først': 'Complete the whole previous tier and the mission requirement first',
    'Klar hele trin {0}: {1}.': 'Complete all of tier {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Complete the qualifying level to open this challenge.',
    'Klar til offline-spil': 'Ready for offline play',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Get past at least three balls in one concert wave',
    'KØB': 'BUY',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'BUY PERMANENT LIVES OR A RESCUE SPIN',
    'KØB · {0} FJER': 'BUY · {0} FEATHERS',
    'KØBT': 'BOUGHT',
    'LAVA & BOBLER': 'LAVA & BUBBLES',
    'LEVEL 1 · DESERT': 'LEVEL 1 · DESERT',
    'LEVENDE FORHINDRINGER': 'LIVING OBSTACLES',
    'LEVERING': 'DELIVERY',
    'LYD & FEEDBACK': 'SOUND & FEEDBACK',
    'LYDLØS': 'SILENT',
    'Level 1 · Mål 30': 'Level 1 · Goal 30',
    'Luk': 'Close',
    'Luk garderoben': 'Close the wardrobe',
    'Lydeffekter': 'Sound effects',
    'Lydløs og hurtig · køb for fjer': 'Silent and fast · buy with feathers',
    'LÅS OP · 20 FJER': 'UNLOCK · 20 FEATHERS',
    'LÅS OP · {0} FJER': 'UNLOCK · {0} FEATHERS',
    'LÅST BANE': 'LOCKED LEVEL',
    'LÅST OP': 'UNLOCKED',
    'LÆR KORRIDOREN': 'LEARN THE CORRIDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Unlocked. Tap the character to select.',
    'MAKS LÅST OP': 'MAX UNLOCKED',
    'MINISPIL · SKY RELAY · LOKALT': 'MINI GAME · SKY RELAY · LOCAL',
    'MISSIONER': 'MISSIONS',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MOBILE: LEFT SIDE = UP · RIGHT SIDE = DOWN',
    'Missioner': 'Missions',
    'Mod vinden': 'Against the wind',
    'Musik': 'Music',
    'MÅGEN MOGENS': 'MOGENS THE GULL',
    'Mågen Mogens': 'Mogens the Gull',
    'MÅL: 3 BOLDE': 'GOAL: 3 BALLS',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'GOAL: GET PAST A WAVE WITH THREE BALLS · LEFT UP · RIGHT DOWN',
    'MÅL: ROVFUGL': 'GOAL: RAPTOR',
    'MÅL: STORM': 'GOAL: STORM',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'GOAL: DODGE A RAPTOR · LEFT UP · RIGHT DOWN',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'GOAL: DODGE A STORM OBJECT · FOLLOW FLAGS AND LEAVES',
    'MÆRKE VUNDET': 'BADGE WON',
    'MØRKE & SKILTE': 'DARKNESS & SIGNS',
    'Måned': 'Month',
    'NED': 'DOWN',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} stars · local event record only',
    'NINJA-BERT': 'NINJA BERT',
    'Ninja-Bert': 'Ninja Bert',
    'NIVEAU {0}! · {1}': 'LEVEL {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING UNLOCKED · FLAWLESS FLIGHT',
    'NY BANE': 'NEW LEVEL',
    'NY REKORD!': 'NEW RECORD!',
    'NYE VERDENER': 'NEW WORLDS',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NEW TIER: ALL THREE LEVELS ARE OPEN · {0} stars collected',
    'NATTEBYEN': 'NIGHT CITY',
    'Nattebyen': 'Night City',
    'Ny mobilversion indlæst': 'New mobile version loaded',
    'Nyt redningsliv låst op': 'New rescue life unlocked',
    'NÆSTE UDFORDRING': 'NEXT CHALLENGE',
    'Nå 120 point i Desert': 'Reach 120 points in Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Reach 180 points without missing a star or hitting anything',
    'Nå 300 point på én tur': 'Reach 300 points in one run',
    'Nå bronze i Jungle uden redning': 'Reach bronze in Jungle without a rescue',
    'Nå bronze i alle ni baner': 'Reach bronze in all nine levels',
    'Nå bronze i alle tre Classic-baner': 'Reach bronze in all three Classic levels',
    'Nå en streak på 12': 'Reach a streak of 12',
    'OMVENDT STYRING': 'REVERSED CONTROLS',
    'OP': 'UP',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Offline is not ready yet · connect to the internet',
    'PAKKE-BERT': 'PARCEL BERT',
    'Pakke-Bert': 'Parcel Bert',
    'PERMANENT REDE-FORDEL': 'PERMANENT NEST PERK',
    'PERSONLIG REKORD': 'PERSONAL BEST',
    'PILOTER': 'PILOTS',
    'POINT ×2': 'POINTS ×2',
    'PORTE & KLOKKE': 'GATES & BELL',
    'PRINSESSE SØS': 'PRINCESS SØS',
    'Prinsesse Søs': 'Princess Søs',
    'PRÆCISION': 'PRECISION',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'PRECISION FLIGHT · LOCAL TRIAL',
    'PRÆCISIONSRUTE · LOKALT': 'PRECISION ROUTE · LOCAL',
    'PUBLIKUMSVØLGE': 'CROWD WAVE',
    'Pause spillet': 'Pause the game',
    'Periode': 'Period',
    'Personlig highscore': 'Personal high score',
    'Pilotnavn': 'Pilot name',
    'Pingvin med jetpack · køb for fjer': 'Penguin with a jetpack · buy with feathers',
    'Point': 'Points',
    'Porte · vindklokke': 'Gates · wind chime',
    'PORT {0}/3': 'GATE {0}/3',
    'PORT {0}/3 · {1}': 'GATE {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'ROUND {0} · GATE {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'DING! +{0} · ROUND {1}',
    'Præcisionsflyvning': 'Precision flight',
    'RAM GULDPLADEN': 'HIT THE GOLD PLATE',
    'RAMT': 'HIT',
    'RANGLISTE': 'LEADERBOARD',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'RESCUED · YOUR 12 FEATHERS COME BACK',
    'REDDET · {0}': 'RESCUED · {0}',
    'REDNINGSLIV': 'RESCUE LIFE',
    'REDNINGSLIV 0/3': 'RESCUE LIVES 0/3',
    'REDNINGSLIV {0}/{1}': 'RESCUE LIVES {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'THE RESCUE NEST IS SPINNING …',
    'REDNINGSSPIN': 'RESCUE SPIN',
    'RENT GENNEM': 'CLEAN THROUGH',
    'RIGGE & BOLDE': 'RIGS & BALLS',
    'ROTORER & BØJER': 'ROTORS & BUOYS',
    'ROVFUGL': 'RAPTOR',
    'ROVFUGL BAGFRA': 'RAPTOR FROM BEHIND',
    'FUGL': 'BIRD',
    'BAGFRA': 'FROM BEHIND',
    'FORFRA': 'FROM THE FRONT',
    'RUTEN AFSLUTTET': 'ROUTE FINISHED',
    'Redningsliv tilbage': 'Rescue lives left',
    'Rigge · bolde': 'Rigs · balls',
    'SJÆLDEN': 'RARE',
    'SKIFT BANE': 'CHANGE LEVEL',
    'SKJOLD': 'SHIELD',
    'SKJOLD BRUGT · 2s': 'SHIELD USED · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · HIT THE {0} OF GATE {1} · 0 POINTS · TRY AGAIN',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 POINTS · TRY AGAIN',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 GATES · {1}% PRECISION · LOCAL ONLY',
    'TOPPEN': 'TOP',
    'BUNDEN': 'BOTTOM',
    'SKYRING RAMT': 'CLOUD RING HIT',
    'SPIL': 'PLAY',
    'SPIL KVALIFIKATION': 'PLAY QUALIFIER',
    'SPIL →': 'PLAY →',
    'SPIL {0}': 'PLAY {0}',
    'SPIN FOR AT SE DIN REDNING': 'SPIN TO SEE YOUR RESCUE',
    'SPIN · 12 FJER': 'SPIN · 12 FEATHERS',
    'SPIN · {0} FJER': 'SPIN · {0} FEATHERS',
    'START FORFRA': 'START OVER',
    'STARTBANE': 'STARTING LEVEL',
    'STJERNEREGN': 'STAR SHOWER',
    'STIGER': 'CLIMBING',
    'DYKKER': 'DIVING',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · WIND AND FLYING THINGS · {0} stars · local event record only',
    'STREAK REDDET · GUARD BRUGT': 'STREAK SAVED · GUARD USED',
    'STORMPILOT': 'STORM PILOT',
    'Saml 20 stjerner til reden': 'Collect 20 stars for the nest',
    'Saml 250 stjerner i alt': 'Collect 250 stars in total',
    'Scoretype': 'Score type',
    'Skriv dit navn': 'Type your name',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Play Bird Run, a local bird world. Dodge the announced raptor. No global leaderboard.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Play Neon Encore, a local concert world. Survive a whole wave with at least three balls. No global leaderboard.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Play Sky Relay, a short local precision route through three cloud rings. The top and bottom of a ring can be hit. Hit the gold plate of the wind chime. No global leaderboard.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Play Stormline, a local wind world. Dodge a flying object in a storm. No global leaderboard.',
    'Spiltype': 'Game mode',
    'Start Quick Flight': 'Start Quick Flight',
    'Starthelt · Klar til at flyve': 'Starting hero · Ready to fly',
    'Starthelt': 'Starting hero',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard ready: saves one missed star',
    'Streak Guard reddede din streak': 'Streak Guard saved your streak',
    'Sur havnemåge · køb for fjer': 'Grumpy harbour gull · buy with feathers',
    'SØLV': 'SILVER',
    'BRONZE': 'BRONZE',
    'Sådan virker Berts rede': "How Bert's nest works",
    'TAP': 'TAP',
    'TAP FOR AT FLYVE · {0}': 'TAP TO FLY · {0}',
    'TESTBANE': 'TEST LEVEL',
    'TIDEN UDE': 'TIME IS UP',
    'TILBAGE': 'BACK',
    'TRYK FOR AT STARTE': 'TAP TO START',
    'TUNG': 'HEAVY',
    'TUNG · STIGER LANGSOMT': 'HEAVY · CLIMBS SLOWLY',
    'Tid': 'Time',
    'Tilgængelige helte': 'Available heroes',
    'UDFORDR EN VEN': 'CHALLENGE A FRIEND',
    'Udfordringen er klar': 'The challenge is ready',
    'Udfordringslink klar': 'Challenge link ready',
    'Udfordringslink kopieret': 'Challenge link copied',
    'Uge': 'Week',
    'Undvig den varslede ørn eller grib': 'Dodge the announced eagle or vulture',
    'Undvig en flyvende genstand i storm eller orkan': 'Dodge a flying object in a storm or hurricane',
    'VELKOMMEN': 'WELCOME',
    'VENNEDUEL': 'FRIEND DUEL',
    'VENNER': 'FRIENDS',
    'VERDEN': 'WORLD',
    'VENNER FRA DUELLER': 'FRIENDS FROM DUELS',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'FRIENDS FROM DUELS · {0} RIVALS · {1} RESULTS',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LEFT SIDE = UP · RIGHT SIDE = DOWN',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · LEFT UP · RIGHT DOWN',
    'VERDEN KLARET': 'WORLD COMPLETE',
    'VERDEN KLARET · LOKALT': 'WORLD COMPLETE · LOCAL',
    'VIND & GENSTANDE': 'WIND & OBJECTS',
    'VIND · TESTBANE': 'WIND · TEST LEVEL',
    'VIND · {0}': 'WIND · {0}',
    'VINDKLOKKEN RAMT': 'WIND CHIME HIT',
    'VINDVERDEN · LOKALT': 'WIND WORLD · LOCAL',
    'Vindmøller': 'Wind Turbines',
    'VINDMØLLER': 'WIND TURBINES',
    'Vulkanen': 'The Volcano',
    'VULKANEN': 'THE VOLCANO',
    'FJENDER & ANGREB': 'ENEMIES & ATTACKS',
    'FUGLETRAFIK · TESTBANE': 'BIRD TRAFFIC · TEST LEVEL',
    'FUGLE & ROVFUGL': 'BIRDS & RAPTOR',
    'FLAPPY-STYRING': 'FLAPPY CONTROLS',
    'FLAPPY-STYRING · TAP': 'FLAPPY CONTROLS · TAP',
    'VUNDET': 'WON',
    'BEHOLDT': 'KEPT',
    'Valgt og klar til at flyve': 'Selected and ready to fly',
    'Vind bronze, sølv og guld': 'Win bronze, silver and gold',
    'Vind ti vennedueller': 'Win ten friend duels',
    'Vind · genstande': 'Wind · objects',
    'VÆLG HELT': 'CHOOSE HERO',
    'VÆLG LEVEL': 'CHOOSE LEVEL',
    'VÆLG SPILTYPE': 'CHOOSE GAME MODE',
    'Vælg Bert': 'Select Bert',
    'Vælg Blok-Johan': 'Select Blok-Johan',
    'Vælg BlueBert': 'Select BlueBert',
    'Vælg BoneBeak': 'Select BoneBeak',
    'Vælg BrainBird': 'Select BrainBird',
    'Vælg BrickBird': 'Select BrickBird',
    'Vælg Coopinc': 'Select Coopinc',
    'Vælg Fodbold-Bert': 'Select Football Bert',
    'Vælg Guld-Bert': 'Select Gold Bert',
    'Vælg InkBird': 'Select InkBird',
    'Vælg MechaBert': 'Select MechaBert',
    'Vælg MossHex': 'Select MossHex',
    'Vælg Mågen Mogens': 'Select Mogens the Gull',
    'Vælg Ninja-Bert': 'Select Ninja Bert',
    'Vælg NoirWing': 'Select NoirWing',
    'Vælg Pakke-Bert': 'Select Parcel Bert',
    'Vælg Pingo': 'Select Pingo',
    'Vælg Prinsesse Søs': 'Select Princess Søs',
    'Vælg PrismWing': 'Select PrismWing',
    'Vælg SkyClaw': 'Select SkyClaw',
    'Vælg Storm Royale': 'Select Storm Royale',
    'Vælg SugarRush': 'Select SugarRush',
    'Vælg Thor Obby': 'Select Thor Obby',
    'Vælg bane': 'Choose level',
    'Vælg leaderboard': 'Choose leaderboard',
    'Vælg level': 'Choose level',
    'Vælg spiltype': 'Choose game mode',
    'Vælg {0}, {1}': 'Select {0}, {1}',
    'købt': 'bought',
    'låst op': 'unlocked',
    '{0} ER LÅST': '{0} IS LOCKED',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} scored {1} points. You have {2} attempts on the same level, and their flight is shown as a shadow.',
    '{0} forsøg tilbage · slå {1} point': '{0} attempts left · beat {1} points',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} has challenged you to beat {1} points. You have three attempts.',
    '{0} låst op for {1} fjer': '{0} unlocked for {1} feathers',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} locked. {1}. {2} of {3}. Alternative price {4} feathers.',
    '{0} missionsbelønninger': '{0} mission rewards',
    '{0} missionsbelønninger er hentet.': '{0} mission rewards have been claimed.',
    '{0} point til næste medalje': '{0} points to the next medal',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} When both requirements are met, all of tier {2} opens.',
    '{0} · {1} FASTE LIV': '{0} · {1} PERMANENT LIVES',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, locked. Tap to see the unlock requirement',
    '{0}, åben, personlig rekord {1}': '{0}, open, personal best {1}',
    '{0} · Mål {1}': '{0} · Goal {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} LEVELS · {2}/{3} MISSIONS',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} LEVELS · {2}/{3} MISS.',
    '{0} BANER · {1}': '{0} LEVELS · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} OPEN · {2}',
    'DU MANGLER {0} FJER': 'YOU NEED {0} MORE FEATHERS',
    'BESKYTTET · {0}s': 'PROTECTED · {0}s',
    'ÅBN DAGENS MISSIONER': "OPEN TODAY'S MISSIONS",
    'ÅBN GARDEROBE · 17 HELTE': 'OPEN WARDROBE · 17 HEROES',
    'ÅNDENDE PORTE': 'BREATHING GATES',
    'Åbn dagens missioner': "Open today's missions",
    'Åbn highscore': 'Open high score',
    'Åbn indstillinger': 'Open settings',
    'ÉN CHANCE MERE?': 'ONE MORE CHANCE?',
    'SPIL IGEN': 'PLAY AGAIN',
    'Sprog': 'Language',
    'Automatisk (som telefonen)': 'Automatic (same as the phone)',
    'Dansk': 'Danish',
    'Engelsk': 'English',
    'Sproget skifter, når spillet genindlæses.': 'The language changes when the game reloads.',
    '+1 FJER': '+1 FEATHER',
    'ISBJERGET': 'THE ICEBERG',
    'En ven': 'A friend',
    'REKORD': 'RECORD',
    'Topflyvning': 'Top flight',
    '{0} point i {1}': '{0} points in {1}',
    'en bane': 'a level',
    '{0} til trin {1} · {2} stjerner': '{0} for tier {1} · {2} stars',
    '{0} · {1} stjerner samlet': '{0} · {1} stars collected',
    '{0} FJER': '{0} FEATHERS',
    'TAP FOR AT FLYVE': 'TAP TO FLY',
    'Dig': 'You',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Beat your friend's score on exactly the same level. You have three attempts, and their ghost flight follows you.",
    '{0}/{1} BRONZE': '{0}/{1} BRONZE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Get bronze (20 points) on all {0} base levels to open Adventure. You have {1}.',
    'SØLV I {0}': 'SILVER IN {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Get silver (50 points) in {0} to open {1}.',
    'LAVAEN FALDER': 'THE LAVA SINKS',
    'GODT GREB · {0}s': 'GOOD GRIP · {0}s',
    'VINDSTØD · OP': 'GUST · UP',
    'VINDSTØD · NED': 'GUST · DOWN',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'SLIPPERY ICE: STEER EARLY · COLLECT FROST CRYSTALS',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'WATCH THE GUSTS · THE ARROWS SHOW THE WAY',
    'LAVAEN STIGER · SAML KØLESTEN': 'THE LAVA IS RISING · COLLECT COOLING STONES',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'THE LIGHT FADES SLOWLY · COLLECT LANTERNS',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'THE CONTAINERS MOVE · WATCH OUT FOR GULLS',
    'Fugleklat': 'Bird Drop',
    'SPIS & KLAT': 'EAT & DROP',
    'PARAPLYEN REDDEDE DEM': 'THE UMBRELLA SAVED THEM',
    'GULDBIL! ×3': 'GOLD CAR! ×3',
    'PLASK!': 'SPLAT!',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'EAT FOOD · TAP 💩 TO HIT TARGETS BELOW',
    'Slip en klat': 'Drop a splat',
    'Alle helte flyver ens. Vind dem i spillet, eller spar fjer sammen.': 'All heroes fly the same. Win them in the game or save up feathers.',
    'ÅBN GARDEROBE': 'OPEN WARDROBE',
    'OP · EVIGT SKJOLD · INGEN REKORDER': 'OP · ENDLESS SHIELD · NO RECORDS',
    'FORSTØR': 'GROW',
    'FORMINDSK': 'SHRINK',
    'FORSTØR · POINT ×2': 'GROW · POINTS ×2',
    'FØLG TUNNELEN · HOLD VENSTRE = OP · HØJRE = NED': 'FOLLOW THE TUNNEL · HOLD LEFT = UP · RIGHT = DOWN',
    'FLOT!': 'NICE!',
    'PERFEKT!': 'PERFECT!',
    'UTROLIGT!': 'AMAZING!',
    'LEGENDARISK!': 'LEGENDARY!',
    'BERT-NIVEAU!': 'BERT LEVEL!',
    // Feedback 4. okt.: reden, æg, mærker, eventyr-låse, lyd.
    "Vælg én starthelt efter 10, 20, 30 og 40 ture": "Pick one starter hero after 10, 20, 30 and 40 runs",
    "Nå 600 point på én tur": "Score 600 points in one run",
    "Nå guld i alle tre Classic-baner": "Get gold on all three Classic levels",
    "Kun fra et æg i reden": "Only from an egg in the nest",
    "Kun fra et æg i reden (sjælden)": "Only from an egg in the nest (rare)",
    "Æggebert": "Eggbert",
    "ÆGGEBERT": "EGGBERT",
    "Vælg Æggebert": "Choose Eggbert",
    "Klæk alle helte fra rugepladsen": "Hatch every hero from the hatchery",
    "KLÆK ALLE": "HATCH ALL",
    "Blød rede": "Soft nest",
    "Et sted at lande. Fjer bygger den videre.": "A place to land. Feathers build it further.",
    "Redningsfjer": "Rescue feather",
    "REDNINGSFJER": "RESCUE FEATHER",
    "Ét redningsliv på hver tur.": "One rescue life every run.",
    "Stærkere magnet": "Stronger magnet",
    "Magneten trækker 30 % længere.": "The magnet pulls 30% further.",
    "Varmt skjold": "Warm shield",
    "Skjoldet holder 2 sekunder længere.": "The shield lasts 2 seconds longer.",
    "Hurtig start": "Quick start",
    "Usårlig med ekstra fart de første 5 sekunder.": "Invincible with extra speed for the first 5 seconds.",
    "To redningsliv": "Two rescue lives",
    "To redningsliv på hver tur.": "Two rescue lives every run.",
    "Guldrede": "Golden nest",
    "Stjerner giver +1 point de første 10 sekunder.": "Stars give +1 point for the first 10 seconds.",
    "Første flyvetur": "First flight",
    "Gennemfør din første tur": "Finish your first run",
    "Første stjerne": "First star",
    "Saml din første stjerne": "Collect your first star",
    "Første fjer": "First feather",
    "Find din første gyldne fjer": "Find your first golden feather",
    "Vind din første bronzemedalje": "Win your first bronze medal",
    "Ny ven": "New friend",
    "Lås din første ekstra helt op": "Unlock your first extra hero",
    "Sølv": "Silver",
    "Vind sølv på en bane": "Win silver on a level",
    "Guld": "Gold",
    "Vind guld på en bane": "Win gold on a level",
    "I flow": "In the flow",
    "Nå en streak på 10": "Reach a streak of 10",
    "Ustoppelig": "Unstoppable",
    "Nå en streak på 25": "Reach a streak of 25",
    "Stjerneregn": "Star shower",
    "Saml 100 stjerner på én tur": "Collect 100 stars in one run",
    "Højtflyver": "High flyer",
    "Få 500 point på én tur": "Score 500 points in one run",
    "Udholdenhed": "Endurance",
    "Flyv 3 minutter på én tur": "Fly 3 minutes in one run",
    "Fejlfri": "Flawless",
    "Guld uden redningsliv eller redningsspin": "Gold without rescue lives or rescue spins",
    "Klassiker": "Classic master",
    "Bronze på alle Classic-baner": "Bronze on every Classic level",
    "Skorstensfejer": "Chimney sweep",
    "Bronze på alle Flappy-baner": "Bronze on every Flappy level",
    "Tunnelrytter": "Tunnel rider",
    "Bronze på alle Tunnel-baner": "Bronze on every Tunnel level",
    "Eventyrer": "Adventurer",
    "Lås Eventyr op": "Unlock Adventure",
    "Verdensflyver": "World flyer",
    "Sølv på alle seks eventyrbaner": "Silver on all six adventure levels",
    "Lavalord": "Lava lord",
    "Guld på Vulkanen": "Gold on the Volcano",
    "Mesterskytte": "Sharpshooter",
    "10 træffere i træk i Fugleklat": "10 hits in a row in Bird Drop",
    "Publikumsvølge": "Crowd wave",
    "Kom forbi tre bolde i én koncertbølge": "Get past three balls in one concert wave",
    "Fri af rovfuglen": "Free of the hawk",
    "Undvig den varslede rovfugl": "Dodge the announced bird of prey",
    "Undvig en flyvende genstand i storm": "Dodge a flying object in a storm",
    "Portløber": "Gate runner",
    "Klar alle tre porte i én Sky Relay-runde": "Clear all three gates in one Sky Relay round",
    "Ekstranummer": "Encore",
    "Sølv i Neon Encore": "Silver in Neon Encore",
    "Pakket ind": "All wrapped up",
    "Bliv fanget af edderkoppen": "Get caught by the spider",
    "Snack": "Snack",
    "Bliv fanget af slangen": "Get caught by the snake",
    "Grillkylling": "Roast chicken",
    "Dø 50 gange i alt": "Crash 50 times in total",
    "Flokken": "The flock",
    "Lås 10 helte op": "Unlock 10 heroes",
    "Redebygger": "Nest builder",
    "Saml 100 fjer i alt": "Collect 100 feathers in total",
    "GAME OVER": "GAME OVER",
    "MAGNET": "MAGNET",
    "Få bronze på alle tre Classic-baner for at åbne Havnen.": "Get bronze on all three Classic levels to open The Harbour.",
    "Få bronze på alle tre Flappy-baner for at åbne Nattebyen.": "Get bronze on all three Flappy levels to open Night City.",
    "Få bronze på alle tre Tunnel-baner for at åbne Vindmøller.": "Get bronze on all three Tunnel levels to open Wind Turbines.",
    "Få sølv i to af Havnen, Nattebyen og Vindmøller for at åbne Vulkanen.": "Get silver in two of The Harbour, Night City and Wind Turbines to open The Volcano.",
    "GULD PÅ EN BANE": "GOLD ON A LEVEL",
    "SØLV I VULKANEN": "SILVER IN THE VOLCANO",
    "Få sølv i Vulkanen og guld på én af grundbanerne for at åbne Isbjerget.": "Get silver in The Volcano and gold on one of the base levels to open The Iceberg.",
    "SØLV I ISBJERGET": "SILVER IN THE ICEBERG",
    "Få sølv i Isbjerget for at åbne Fugleklat.": "Get silver in The Iceberg to open Bird Drop.",
    "ÅBNER MED EVENTYR": "OPENS WITH ADVENTURE",
    "Testbanerne åbner sammen med den første eventyrverden.": "The test levels open with the first adventure world.",
    "HEMMELIG": "SECRET",
    "LÅST": "LOCKED",
    "Låst. Tryk på helten for at se, hvordan du får den.": "Locked. Tap the hero to see how to get it.",
    "En hemmelig helt. Den hører til et særligt pilotnavn.": "A secret hero. It belongs to a special pilot name.",
    "Du kan vælge en starthelt nu.": "You can pick a starter hero now.",
    "Eller klæk den fra et æg, når reden har nået trin 4.": "Or hatch it from an egg once the nest reaches step 4.",
    "REDEN ER FÆRDIG": "THE NEST IS FINISHED",
    "Alle syv trin er bygget. Flot!": "All seven steps are built. Great!",
    "Du fandt et æg! Det ligger i reden og ruger.": "You found an egg! It's warming in the nest.",
    "VÆLG EN NY HELT": "CHOOSE A NEW HERO",
    "Du må vælge én. De andre kan vælges efter 10 ture mere.": "Pick one. The others can be picked after 10 more runs.",
    "SENERE": "LATER",
    "Én tur om dagen giver fjer": "One run a day gives feathers",
    "Ruger et tilfældigt æg. Saml stjerner, så klækker det.": "Warming a random egg. Collect stars and it will hatch.",
    "TOM": "EMPTY",
    "ALLE KLÆKKET": "ALL HATCHED",
    "Alle helte er klækket": "Every hero has hatched",
    "fjer": "feathers",
    "sjælden": "rare",
    "Et æg ligger i reden. Saml stjerner, så klækker det.": "An egg is in the nest. Collect stars and it will hatch.",
    "ER DU SIKKER? TRYK IGEN": "ARE YOU SURE? TAP AGAIN",
    "GLOBAL HIGHSCORE": "GLOBAL HIGH SCORE",
    "Du mangler fjer. Flyv en tur, og klar dagens missioner.": "You need more feathers. Fly a run and finish today's missions.",
    "{0}/3 CLASSIC": "{0}/3 CLASSIC",
    "{0}/3 FLAPPY": "{0}/3 FLAPPY",
    "{0}/3 TUNNEL": "{0}/3 TUNNEL",
    "SØLV {0}/2": "SILVER {0}/2",
    "LÅST · {0}/{1}": "LOCKED · {0}/{1}",
    "Vælg den som starthelt efter {0} ture. Du har fløjet {1}.": "Pick it as a starter hero after {0} runs. You have flown {1}.",
    "Klæk alle helte fra rugepladsen. {0}/{1} klækket.": "Hatch every hero from the hatchery. {0}/{1} hatched.",
    "Bedrift: {0} ({1}/{2}).": "Feat: {0} ({1}/{2}).",
    "Eller klæk den fra et æg i reden: sikret æg {0} fjer.": "Or hatch it from an egg in the nest: chosen egg {0} feathers.",
    "Du har {0} fjer. Fjer får du af dagens missioner, en tur om dagen og sjældne fjer i banerne.": "You have {0} feathers. You get feathers from daily missions, one run a day and rare feathers on the levels.",
    "BYG · {0} FJER": "BUILD · {0} FEATHERS",
    "BYG · 20 FJER": "BUILD · 20 FEATHERS",
    "MANGLER {0} FJER": "NEED {0} FEATHERS",
    "{0} TURE FLØJET": "{0} RUNS FLOWN",
    "{0} er din nu": "{0} is yours now",
    "Ægget klækkede: {0}!": "The egg hatched: {0}!",
    "{0} er klækket og venter i garderoben": "{0} has hatched and is waiting in the wardrobe",
    "Ægget: {0}/{1} stjerner": "The egg: {0}/{1} stars",
    "{0} fjer fundet": "{0} feathers found",
    "Dag {0} i træk: +{1} fjer": "Day {0} in a row: +{1} feathers",
    "Reden: {0}/{1} til {2}": "Nest: {0}/{1} to {2}",
    "Nyt mærke: {0}": "New badge: {0}",
    "{0} dage i træk": "{0} days in a row",
    "{0}/{1} STJERNER": "{0}/{1} STARS",
    "Ruger: {0}": "Hatching: {0}",
    "{0} helte kan stadig klækkes": "{0} heroes can still hatch",
    "TILFÆLDIGT ÆG · {0} FJER": "RANDOM EGG · {0} FEATHERS",
    "SIKRET ÆG · {0} FJER": "CHOSEN EGG · {0} FEATHERS",
    "TILFÆLDIGT ÆG": "RANDOM EGG",
    "SIKRET ÆG": "CHOSEN EGG",
    "Et sikret æg med {0} ligger i reden": "A chosen egg with {0} is in the nest",
    "Reden er bygget: {0}": "Nest built: {0}",
    "Dag {0} i træk · +{1} fjer til reden": "Day {0} in a row · +{1} feathers for the nest",
    "Bert The Bird – flyvespil og præcisionsverdener": "Bert The Bird – flying game and precision worlds",
    "PAUSE": "PAUSE",
    "REDEN": "THE NEST",
    "Reden": "The nest",
    "Åbn reden": "Open the nest",
    "Luk reden": "Close the nest",
    "Redens trin": "Nest steps",
    "NÆSTE TRIN": "NEXT STEP",
    "RUGEPLADSEN": "THE HATCHERY",
    "FLYV HVER DAG": "FLY EVERY DAY",
    "MÆRKER": "BADGES",
    "Fjer bygger reden. Hvert trin kan mærkes i spillet. Efter døden kan du bruge 12 fjer på ét redningsspin.": "Feathers build the nest. Every step can be felt in the game. After a crash you can spend 12 feathers on one rescue spin.",
    "Forrige helte": "Previous heroes",
    "Næste helte": "Next heroes",
    "Musikstyrke": "Music volume",
    "Lydstyrke for effekter": "Effects volume",
    "Vælg helt til sikret æg": "Choose hero for chosen egg",
    "Norsk": "Norwegian",
    "Svensk": "Swedish",
    "Tysk": "German",
    "Spansk": "Spanish",
    "Fransk": "French",
    "Portugisisk": "Portuguese",
    "Banens grafik kunne ikke indlæses.": "The level art could not be loaded.",
    "Spillet kunne ikke indlæses. Prøv igen.": "The game could not be loaded. Try again.",
    "NY HELT: {0} · {1}": "NEW HERO: {0} · {1}",
    "Klæk den fra et æg i reden: sikret æg {0} fjer.": "Hatch it from an egg in the nest: chosen egg {0} feathers.",
    "Klæk den fra et æg, når reden har nået trin 4.": "Hatch it from an egg once the nest reaches step 4.",
    // Udfordringer (10. okt.)
    "Få 40 point uden redningsliv": "Score 40 without a rescue life",
    "Få 80 point uden redningsliv": "Score 80 without a rescue life",
    "Find en gylden fjer i en bane": "Find a golden feather on a level",
    "Få 60 point uden at tage en power-up": "Score 60 without taking a power-up",
    "Saml 400 stjerner i denne uge": "Collect 400 stars this week",
    "Flyv 30 ture i denne uge": "Fly 30 runs this week",
    "Guld på 2 forskellige baner i denne uge": "Gold on 2 different levels this week",
    "Slå din egen rekord 3 gange": "Beat your own record 3 times",
    "Flyv på 6 forskellige baner": "Fly on 6 different levels",
    "Flyv 30 minutter i denne uge": "Fly 30 minutes this week",
    "Lynhurtig: styrt inden for 1 sekund": "Lightning fast: crash within 1 second",
    "Svaret på alt: præcis 42 point": "The answer to everything: exactly 42 points",
    "Natteravn: flyv mellem midnat og kl. 4": "Night owl: fly between midnight and 4 am",
    "Tålmodig: 60 sekunder uden en eneste stjerne": "Patient: 60 seconds without a single star",
    "Sultestrejke: 30 sekunder og 0 stjerner": "Hunger strike: 30 seconds and 0 stars",
    "Jo større de er: styrt mens du er forstørret": "The bigger they are: crash while grown",
    "Juleflyver: flyv juleaften": "Christmas flyer: fly on Christmas Eve",
    "Hattrick: tre ture i træk med samme point": "Hat-trick: three runs in a row with the same score",
    "Garderobe-gal: flyv med 7 forskellige helte": "Wardrobe fan: fly with 7 different heroes",
    "Maraton: 10 minutter på én tur": "Marathon: 10 minutes in one run",
    "Ørkenrotte: 100 ture i Desert": "Desert rat: 100 runs in Desert",
    "Halvtreds: en streak på 50": "Fifty: a streak of 50",
    "Flappy-mester: 500 point i Flappy Bert": "Flappy master: 500 points in Flappy Bert",
    "Bonk-serie: 5 styrt på 2 minutter": "Bonk streak: 5 crashes in 2 minutes",
    "Edderkoppens ven: fanget 10 gange": "Spider's friend: caught 10 times",
    "Saml {0} stjerner i dag": "Collect {0} stars today",
    "Flyv {0} minutter i alt i dag": "Fly {0} minutes in total today",
    "Nå en streak på {0}": "Reach a streak of {0}",
    "Flyv {0} ture i dag": "Fly {0} runs today",
    "Få {0} point på én tur": "Score {0} points in one run",
    "Tag {0} power-ups i dag": "Take {0} power-ups today",
    "Flyv {0} sekunder på én tur": "Fly {0} seconds in one run",
    "Bronze i {0} i dag": "Bronze in {0} today",
    "Sølv i {0} i dag": "Silver in {0} today",
    "Guld i {0} i dag": "Gold in {0} today",
    "Tur nr. {0}": "Run no. {0}",
    "{0} stjerner i alt": "{0} stars in total",
    "{0} fjer samlet i alt": "{0} feathers collected in total",
    "{0} helte": "{0} heroes",
    "{0} mærker": "{0} badges",
    "Reden på trin {0}": "Nest at step {0}",
    "{0} æg klækket": "{0} eggs hatched",
    "{0}: guld": "{0}: gold",
    "{0}: 200 point": "{0}: 200 points",
    "{0}: 60 point uden redning og power-ups": "{0}: 60 points without rescue or power-ups",
    "??? (hemmelig udfordring)": "??? (secret challenge)",
    "Tæt på: {0} ({1}/{2})": "Almost there: {0} ({1}/{2})",
    "+{0} fjer · {1}": "+{0} feathers · {1}",
    "UGENS UDFORDRINGER": "THIS WEEK'S CHALLENGES",
    "UDFORDRINGER": "CHALLENGES",
    "MILEPÆLE": "MILESTONES",
    "MESTERSKAB": "MASTERY",
    "HEMMELIGE": "SECRET",
    "NIVEAU {0}!": "LEVEL {0}!",
    "HVOR SKAL BERT HEN?": "WHERE IS BERT GOING?",
    "DIN REJSE": "YOUR JOURNEY",
    "Ørkenen": "The desert",
    "Junglen": "The jungle",
    "Himlen": "The sky",
    "Byen": "The city",
    "Tunnelen": "The tunnel",
    "Natten": "The night",
    "Vinden": "The wind",
    "Isen": "The ice",
    "Fugleklat-øen": "Bird Drop Island",
    "Spejlbanen": "Mirror level",
    "GLID & OPVIND · TESTBANE": "GLIDE & THERMALS · TEST LEVEL",
    "GLID & OPVIND": "GLIDE & THERMALS",
    "Svæv": "Glide",
    "Vælg et andet navn": "Pick another name",
    "FLOK & FORMATION · TESTBANE": "FLOCK & FORMATION · TEST LEVEL",
    "FLOK & FORMATION": "FLOCK & FORMATION",
    "Fuglesværm": "Bird swarm",
    "Klistermærke fundet! Se det i albummet i reden": "Sticker found! See it in the album in the nest",
    "KLISTERMÆRKER": "STICKERS",
    "Fem skjulte klistermærker i hver bane. Hold øje, mens du flyver.": "Five hidden stickers on each level. Keep your eyes open while you fly.",
    "Flokken": "The Flock",
    "UDFORDRER": "CHALLENGER",
    "NYT": "NEW",
    "FLOKKEN": "THE FLOCK",
    "ALLE MOD ALLE I EN STOR HIMMEL": "EVERYONE AGAINST EVERYONE IN A BIG SKY",
    "Få sølv (50 point) i {0} for at åbne bonusbanen {1}.": "Get silver (50 points) in {0} to open the bonus level {1}.",
    "UGENS BONUS": "WEEKLY BONUS",
    "DOBBELT BELØNNING · {0} DAGE TILBAGE": "DOUBLE REWARDS · {0} DAYS LEFT",
    "Ugens bonus: +{0} fjer til reden": "Weekly bonus: +{0} feathers for the nest",
    "2× FJER · {0} DAGE": "2× FEATHERS · {0} DAYS",
    // Introkort før banen (10. okt.)
    "Hold venstre side = op · højre side = ned": "Hold left side = up · right side = down",
    "Tryk for at baske · slip for at falde": "Tap to flap · let go to fall",
    "Flyv mellem søjlerne og saml stjerner. Banen bliver hurtigere, og hullerne bliver mindre.": "Fly between the pillars and collect stars. It gets faster and the gaps get smaller.",
    "Pas på slanger, der hopper op, og edderkopper, der hænger i spind.": "Watch out for snakes that jump up and spiders hanging in webs.",
    "Slikstårne ruller og står skævt. Find hullet i tide.": "Candy towers roll and lean. Find the gap in time.",
    "Flappy: flyv gennem hullerne mellem skorstenene.": "Flappy: fly through the gaps between the chimneys.",
    "Flappy: hullerne skifter højde, mens du flyver.": "Flappy: the gaps change height while you fly.",
    "Flappy: den sværeste af de tre. Små huller og høj fart.": "Flappy: the hardest of the three. Small gaps, high speed.",
    "Følg tunnelen, og rør ikke væggene.": "Follow the tunnel and don't touch the walls.",
    "Tunnelen snor sig mere og bliver smallere.": "The tunnel twists more and gets narrower.",
    "Den hurtigste tunnel. Hold dig i midten.": "The fastest tunnel. Stay in the middle.",
    "Containerne flytter sig. Pas på kranekroge og måger.": "The containers move. Watch out for crane hooks and gulls.",
    "Lyset slukker langsomt. Saml lanterner for at kunne se.": "The light slowly fades. Collect lanterns to see.",
    "Vinden skubber dig. Pas på møllevinger og drager.": "The wind pushes you. Watch out for turbine blades and kites.",
    "Lavaen stiger. Saml kølesten, og undgå bomber og meteorer.": "The lava rises. Collect cooling stones and avoid bombs and meteors.",
    "Glat styring: Bert glider efter. Styr i god tid.": "Slippery controls: Bert slides. Steer early.",
    "Spis mad, og tryk på 💩 for at ramme mål nedenunder.": "Eat food, and tap 💩 to hit targets below.",
    "Koncert: kom forbi boldene, når publikum laver bølgen.": "Concert: get past the balls when the crowd does the wave.",
    "Flyv med flokken, og undgå rovfuglen, når den varsles.": "Fly with the flock and dodge the bird of prey when it is announced.",
    "Stormen kaster ting efter dig. Hold øje med pilene.": "The storm throws things at you. Watch the arrows.",
    "Flyv gennem tre skyporte, og ring med klokken. Portene bliver mindre.": "Fly through three cloud gates and ring the bell. The gates get smaller.",
    "Ingen vingeslag: op koster fart, ned giver fart. Find opvinden, og flyv langt.": "No wingbeats: up costs speed, down gives speed. Find the thermals and fly far.",
    "Hver 10. stjerne i træk giver en fugl i flokken. Et sammenstød koster en fugl i stedet for turen.": "Every 10th star in a row adds a bird to the flock. A crash costs a bird instead of the run.",
    "Saml stjerner, og undgå forhindringerne.": "Collect stars and avoid the obstacles.",
    "BONUSBANE": "BONUS LEVEL",
    "SPEJLVENDT": "MIRRORED",
    "Rekord {0} · bronze 20 · sølv 50 · guld 100": "Record {0} · bronze 20 · silver 50 · gold 100",
    "Bronze 20 · sølv 50 · guld 100": "Bronze 20 · silver 50 · gold 100",
    "TRYK FOR AT FLYVE": "TAP TO FLY",
    "BONUSBANE · {0}": "BONUS LEVEL · {0}",
});
