/* Svenska. Nycklarna är de danska källtexterna. */
window.BertI18n.register('sv', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FLYG EN TUR FÖR ATT SÄTTA FÖRSTA POÄNGEN',
    ' · MÆRKE: {0}': ' · MÄRKE: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · SPELA EN VÄNDUELL FÖR ATT FÅ EN RIVAL',
    '+{0} fjer til reden': '+{0} fjädrar till boet',
    '+{0} fjer · {1} låst op': '+{0} fjädrar · {1} upplåst',
    '0 / 0 POINT': '0 / 0 POÄNG',
    '20 point til bronze': '20 poäng till brons',
    '3 SPILFORMER · 9 BANER': '3 SPELLÄGEN · 9 BANOR',
    '3 baner · hold op/ned': '3 banor · håll upp/ned',
    '3 baner · præcision': '3 banor · precision',
    '3 baner · tap': '3 banor · tryck',
    '9 baner · nye verdener': '9 banor · nya världar',
    'ACCEPTÉR': 'ACCEPTERA',
    'AFSLUT TUREN': 'AVSLUTA TUREN',
    'Alle baner': 'Alla banor',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Alla hjältar har samma fart och träffyta. Vinn dem i spelet eller spara ihop fjädrar.',
    'Alle pointkrav i trin {0} er klaret.': 'Alla poängkrav i steg {0} är klara.',
    'Alle spil': 'Alla spel',
    'Alle tider': 'Alla tider',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Alla tre försök är använda. Be din vän om en ny duell.',
    'BANEN ER LÅST': 'BANAN ÄR LÅST',
    'BEKRÆFT · {0} FJER': 'BEKRÄFTA · {0} FJÄDRAR',
    'BERTS GARDEROBE': 'BERTS GARDEROB',
    'BERTS REDE': 'BERTS BO',
    'BERTS REDNINGSREDE': 'BERTS RÄDDNINGSBO',
    'BEVÆGELIGE TÅRNE': 'RÖRLIGA TORN',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} stjärnor · endast lokalt eventrekord',
    'Bane': 'Bana',
    'Banen er låst': 'Banan är låst',
    'Bedst på level {0} · {1}': 'Bäst på bana {0} · {1}',
    'Bert The Bird appikon': 'Bert The Bird appikon',
    'Bert The Bird bliver installeret': 'Bert The Bird installeras',
    'Bert The Bird er installeret': 'Bert The Bird är installerat',
    'Bert The Bird spilcanvas': 'Bert The Bird spelyta',
    'Bert flyver': 'Bert flyger',
    'Bevægelse i koncertlys': 'Rörelse i konsertljus',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Använd 12 fjädrar på ett snurr. Fem fält skickar Bert tillbaka i banan. Ett fält avslutar turen.',
    'DAGENS MISSIONER': 'DAGENS UPPDRAG',
    'DAGENS RUTE': 'DAGENS RUTT',
    'DAGENS RUTE · MÅL {0}': 'DAGENS RUTT · MÅL {0}',
    'DENNE TUR': 'DENNA TUR',
    'DIN FLYVETUR': 'DIN FLYGTUR',
    'DIN HELT': 'DIN HJÄLTE',
    'DIN SALDO': 'DITT SALDO',
    'DINE VENNEDUELLER': 'DINA VÄNDUELLER',
    'DREJ TELEFONEN': 'VRID TELEFONEN',
    'DU ER UDFORDRET': 'DU ÄR UTMANAD',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'DU VANN DUELLEN · utmana tillbaka · {0} stjärnor',
    'Den sjældneste fugl · køb for fjer': 'Den sällsyntaste fågeln · köp för fjädrar',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Den här banan kan inte användas till rankade vändueller.',
    'Dit navn': 'Ditt namn',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Ditt namn står på topplistan och vid dina rekord.',
    'Du mangler fjer fra dagens missioner': 'Du saknar fjädrar från dagens uppdrag',
    'EDM-VERDEN · LOKALT': 'EDM-VÄRLD · LOKALT',
    'EPISK': 'EPISK',
    'EVENT · BIRD RUN · TESTBANE': 'EVENT · BIRD RUN · TESTBANA',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENT · NEON ENCORE · TESTBANA',
    'EVENT · STORMLINE · TESTBANE': 'EVENT · STORMLINE · TESTBANA',
    'EVENTYR': 'ÄVENTYR',
    'EVENTYR · {0}': 'ÄVENTYR · {0}',
    'Episk helt · kun til dig · valgt': 'Episk hjälte · bara för dig · vald',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Episk hjälte · bara för dig. Tryck för att välja.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Ett permanent räddningsliv tar emot en krock på varje tur. Efter en krasch kan du dessutom använda 12 fjädrar på ett räddningssnurr. Du kan alltid spela vidare utan energi eller väntetid.',
    'FAST + BEVÆGELIG': 'FAST + RÖRLIG',
    'FASTE TÅRNE': 'FASTA TORN',
    'FJER': 'FJÄDRAR',
    'FJER RETUR': 'FJÄDRAR TILLBAKA',
    'FJER · PRIMÆRT VINDES I SPILLET': 'FJÄDRAR · VINNS FRÄMST I SPELET',
    'FLYV': 'FLYG',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'FLYG GENOM TRE MOLNPORTAR · TRÄFFA GULDPLATTAN · VÄNSTER UPP · HÖGER NED',
    'FLYV IGEN': 'FLYG IGEN',
    'FLYV VIDERE': 'FLYG VIDARE',
    'FLYVETUREN ER SAT PÅ PAUSE': 'FLYGTUREN ÄR PAUSAD',
    'FODBOLD-BERT': 'FOTBOLLS-BERT',
    'FOKUS': 'FOKUS',
    'FOKUS OM {0}': 'FOKUS OM {0}',
    'FORBI': 'MISS',
    'FORBI GULDPLADEN': 'MISSADE GULDPLATTAN',
    'FORSTÅET': 'UPPFATTAT',
    'FORTRYD': 'ÅNGRA',
    'FORTSÆT': 'FORTSÄTT',
    'FRI AF ROVFUGLEN': 'FRI FRÅN ROVFÅGELN',
    'FUGL BAGFRA': 'FÅGEL BAKIFRÅN',
    'FUGLEVERDEN · LOKALT': 'FÅGELVÄRLD · LOKALT',
    'Fire gratis lokale eventverdener uden global rangliste': 'Fyra gratis lokala eventvärldar utan global topplista',
    'Flyv samlet i 3 minutter': 'Flyg sammanlagt i 3 minuter',
    'Flyvetid': 'Flygtid',
    'Fodbold-Bert': 'Fotbolls-Bert',
    'Forbindelsen er tilbage': 'Anslutningen är tillbaka',
    'Fremgang mod oplåsning': 'Framsteg mot upplåsning',
    'Fugle · rovfugl': 'Fåglar · rovfågel',
    'FÆRDIG': 'KLAR',
    'FØLG STJERNESTRØMMEN': 'FÖLJ STJÄRNSTRÖMMEN',
    'FØLGER DIG KORT · {0}s': 'FÖLJER DIG KORT · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · TUREN ÄR SLUT',
    'GLOBALT': 'GLOBALT',
    'GLOBALT · {0} RESULTATER': 'GLOBALT · {0} RESULTAT',
    'GODT RAMT': 'BRA TRÄFF',
    'GRATIS REDNING': 'GRATIS RÄDDNING',
    'GRUNDFLYVNING': 'GRUNDFLYGNING',
    'GULD': 'GULD',
    'GULD-BERT': 'GULD-BERT',
    'Guld-Bert': 'Guld-Bert',
    'HAV BERT PÅ STARTSKÆRMEN': 'HA BERT PÅ HEMSKÄRMEN',
    'HAVNEN': 'HAMNEN',
    'Havnen': 'Hamnen',
    'HENT FJER': 'HÄMTA FJÄDRAR',
    'HENT SPILLET': 'HÄMTA SPELET',
    'HENT +{0}': 'HÄMTA +{0}',
    '+{0} FJER': '+{0} FJÄDRAR',
    'HENTER RESULTATER …': 'HÄMTAR RESULTAT …',
    'HENTET': 'HÄMTAD',
    'HOLD OP/NED': 'HÅLL UPP/NED',
    'HOVEDMENU': 'HUVUDMENY',
    'HVAD HEDDER DU?': 'VAD HETER DU?',
    'HVORDAN VIL DU FLYVE?': 'HUR VILL DU FLYGA?',
    'HYPERFART': 'HYPERFART',
    'Haptisk feedback': 'Haptisk feedback',
    'Har altid en pakke med · køb for fjer': 'Har alltid ett paket med sig · köp för fjädrar',
    'Hele Bert The Bird er lavet til landscape.': 'Hela Bert The Bird är gjort för liggande läge.',
    'Hemmelig helt': 'Hemlig hjälte',
    'Hent en mission syv dage i træk': 'Hämta ett uppdrag sju dagar i rad',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Hämta {0} uppdragsbelöningar totalt; du har {1}.',
    'Henter resultater …': 'Hämtar resultat …',
    'Høj fart': 'Hög fart',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'I Safari: Dela → Lägg till på hemskärmen. Vänta på ”Redo för offlinespel” och öppna ikonen en gång med nät innan du testar i flygplansläge.',
    'I dag': 'I dag',
    'IKKE NU': 'INTE NU',
    'INDSTILLINGER': 'INSTÄLLNINGAR',
    'INSTALLÉR WEBAPP': 'INSTALLERA WEBBAPP',
    'ISTAPPER & SPIDSER': 'ISTAPPAR & SPETSAR',
    'Isbjerget': 'Isberget',
    'ISBJERGET': 'ISBERGET',
    'Bert gør klar til at flyve …': 'Bert gör sig redo att flyga …',
    'Ingen rekord endnu': 'Inget rekord ännu',
    'Installér som webapp': 'Installera som webbapp',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Installera via webbläsarens meny. Vänta på ”Redo för offlinespel” och öppna appen en gång med nät innan du testar offline.',
    'KANT': 'KANT',
    'KLAR DAGENS MÅL': 'KLARA DAGENS MÅL',
    'KLARET': 'KLART',
    'KONCERT · TESTBANE': 'KONSERT · TESTBANA',
    'KRANER & MÅGER': 'KRANAR & MÅSAR',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'BARA DINA LOKALA RESULTAT · ONLINETAVLAN ÄR INTE TILLGÄNGLIG',
    'KVALIFIKATIONSBANEN': 'KVALBANAN',
    'Klar dagens rute': 'Klara dagens rutt',
    'Klar dagens rute én gang': 'Klara dagens rutt en gång',
    'Klar hele forrige trin og missionskravet først': 'Klara hela föregående steg och uppdragskravet först',
    'Klar hele trin {0}: {1}.': 'Klara hela steg {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Klara kvalbanan för att öppna den här utmaningen.',
    'Klar til offline-spil': 'Redo för offlinespel',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Ta dig förbi minst tre bollar i en konsertvåg',
    'KØB': 'KÖP',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'KÖP FASTA LIV ELLER ETT RÄDDNINGSSNURR',
    'KØB · {0} FJER': 'KÖP · {0} FJÄDRAR',
    'KØBT': 'KÖPT',
    'LAVA & BOBLER': 'LAVA & BUBBLOR',
    'LEVENDE FORHINDRINGER': 'LEVANDE HINDER',
    'LEVERING': 'LEVERANS',
    'LYD & FEEDBACK': 'LJUD & FEEDBACK',
    'LYDLØS': 'LJUDLÖS',
    'Level 1 · Mål 30': 'Bana 1 · Mål 30',
    'Luk': 'Stäng',
    'Luk garderoben': 'Stäng garderoben',
    'Lydeffekter': 'Ljudeffekter',
    'Lydløs og hurtig · køb for fjer': 'Ljudlös och snabb · köp för fjädrar',
    'LÅS OP · 20 FJER': 'LÅS UPP · 20 FJÄDRAR',
    'LÅS OP · {0} FJER': 'LÅS UPP · {0} FJÄDRAR',
    'LÅST BANE': 'LÅST BANA',
    'LÅST OP': 'UPPLÅST',
    'LÆR KORRIDOREN': 'LÄR DIG KORRIDOREN',
    'Låst op. Tryk på figuren for at vælge.': 'Upplåst. Tryck på figuren för att välja.',
    'MAKS LÅST OP': 'MAX UPPLÅST',
    'MINISPIL · SKY RELAY · LOKALT': 'MINISPEL · SKY RELAY · LOKALT',
    'MISSIONER': 'UPPDRAG',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'MOBIL: VÄNSTER SIDA = UPP · HÖGER SIDA = NED',
    'Missioner': 'Uppdrag',
    'Mod vinden': 'Mot vinden',
    'Musik': 'Musik',
    'MÅGEN MOGENS': 'MÅSEN MOGENS',
    'Mågen Mogens': 'Måsen Mogens',
    'MÅL: 3 BOLDE': 'MÅL: 3 BOLLAR',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'MÅL: TA DIG FÖRBI EN VÅG MED TRE BOLLAR · VÄNSTER UPP · HÖGER NED',
    'MÅL: ROVFUGL': 'MÅL: ROVFÅGEL',
    'MÅL: STORM': 'MÅL: STORM',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'MÅL: UNDVIK EN ROVFÅGEL · VÄNSTER UPP · HÖGER NED',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'MÅL: UNDVIK ETT STORMFÖREMÅL · FÖLJ FLAGGOR OCH LÖV',
    'MÆRKE VUNDET': 'MÄRKE VUNNET',
    'MØRKE & SKILTE': 'MÖRKER & SKYLTAR',
    'Måned': 'Månad',
    'NED': 'NED',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} stjärnor · endast lokalt eventrekord',
    'NINJA-BERT': 'NINJA-BERT',
    'Ninja-Bert': 'Ninja-Bert',
    'NIVEAU {0}! · {1}': 'NIVÅ {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING UPPLÅST · FELFRI FLYGNING',
    'NY BANE': 'NY BANA',
    'NY REKORD!': 'NYTT REKORD!',
    'NYE VERDENER': 'NYA VÄRLDAR',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NYTT STEG: ALLA TRE BANOR ÄR ÖPPNA · {0} stjärnor samlade',
    'NATTEBYEN': 'NATTSTADEN',
    'Nattebyen': 'Nattstaden',
    'Ny mobilversion indlæst': 'Ny mobilversion laddad',
    'Nyt redningsliv låst op': 'Nytt räddningsliv upplåst',
    'NÆSTE UDFORDRING': 'NÄSTA UTMANING',
    'Nå 120 point i Desert': 'Nå 120 poäng i Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Nå 180 poäng utan att missa en stjärna eller träffa något',
    'Nå 300 point på én tur': 'Nå 300 poäng på en tur',
    'Nå bronze i Jungle uden redning': 'Nå brons i Jungle utan räddning',
    'Nå bronze i alle ni baner': 'Nå brons i alla nio banor',
    'Nå bronze i alle tre Classic-baner': 'Nå brons i alla tre Classic-banor',
    'Nå en streak på 12': 'Nå en streak på 12',
    'OMVENDT STYRING': 'OMVÄND STYRNING',
    'OP': 'UPP',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Offline är inte klart än · anslut till nätet',
    'PAKKE-BERT': 'PAKET-BERT',
    'Pakke-Bert': 'Paket-Bert',
    'PERMANENT REDE-FORDEL': 'PERMANENT BO-FÖRDEL',
    'PERSONLIG REKORD': 'PERSONLIGT REKORD',
    'PILOTER': 'PILOTER',
    'POINT ×2': 'POÄNG ×2',
    'PORTE & KLOKKE': 'PORTAR & KLOCKA',
    'PRINSESSE SØS': 'PRINSESSAN SØS',
    'Prinsesse Søs': 'Prinsessan Søs',
    'PRÆCISION': 'PRECISION',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'PRECISIONSFLYGNING · LOKALT PROV',
    'PRÆCISIONSRUTE · LOKALT': 'PRECISIONSRUTT · LOKALT',
    'PUBLIKUMSVØLGE': 'PUBLIKVÅG',
    'Pause spillet': 'Pausa spelet',
    'Periode': 'Period',
    'Personlig highscore': 'Personligt rekord',
    'Pilotnavn': 'Pilotnamn',
    'Pingvin med jetpack · køb for fjer': 'Pingvin med jetpack · köp för fjädrar',
    'Point': 'Poäng',
    'Porte · vindklokke': 'Portar · vindspel',
    'PORT {0}/3': 'PORT {0}/3',
    'PORT {0}/3 · {1}': 'PORT {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RUNDA {0} · PORT {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'KLANG! +{0} · RUNDA {1}',
    'Præcisionsflyvning': 'Precisionsflygning',
    'RAM GULDPLADEN': 'TRÄFFA GULDPLATTAN',
    'RAMT': 'TRÄFF',
    'RANGLISTE': 'TOPPLISTA',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'RÄDDAD · DINA 12 FJÄDRAR KOMMER TILLBAKA',
    'REDDET · {0}': 'RÄDDAD · {0}',
    'REDNINGSLIV': 'RÄDDNINGSLIV',
    'REDNINGSLIV 0/3': 'RÄDDNINGSLIV 0/3',
    'REDNINGSLIV {0}/{1}': 'RÄDDNINGSLIV {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'RÄDDNINGSBOET SNURRAR …',
    'REDNINGSSPIN': 'RÄDDNINGSSNURR',
    'RENT GENNEM': 'RENT IGENOM',
    'RIGGE & BOLDE': 'RIGGAR & BOLLAR',
    'ROTORER & BØJER': 'ROTORER & BOJAR',
    'ROVFUGL': 'ROVFÅGEL',
    'ROVFUGL BAGFRA': 'ROVFÅGEL BAKIFRÅN',
    'FUGL': 'FÅGEL',
    'BAGFRA': 'BAKIFRÅN',
    'FORFRA': 'FRAMIFRÅN',
    'RUTEN AFSLUTTET': 'RUTTEN AVSLUTAD',
    'Redningsliv tilbage': 'Räddningsliv kvar',
    'Rigge · bolde': 'Riggar · bollar',
    'SJÆLDEN': 'SÄLLSYNT',
    'SKIFT BANE': 'BYT BANA',
    'SKJOLD': 'SKÖLD',
    'SKJOLD BRUGT · 2s': 'SKÖLD ANVÄND · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · TRÄFFADE {0} AV PORT {1} · 0 POÄNG · FÖRSÖK IGEN',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 POÄNG · FÖRSÖK IGEN',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 PORTAR · {1}% PRECISION · ENDAST LOKALT',
    'TOPPEN': 'TOPPEN',
    'BUNDEN': 'BOTTEN',
    'SKYRING RAMT': 'MOLNRING TRÄFFAD',
    'SPIL': 'SPELA',
    'SPIL KVALIFIKATION': 'SPELA KVAL',
    'SPIL →': 'SPELA →',
    'SPIL {0}': 'SPELA {0}',
    'SPIN FOR AT SE DIN REDNING': 'SNURRA FÖR ATT SE DIN RÄDDNING',
    'SPIN · 12 FJER': 'SNURRA · 12 FJÄDRAR',
    'SPIN · {0} FJER': 'SNURRA · {0} FJÄDRAR',
    'START FORFRA': 'BÖRJA OM',
    'STARTBANE': 'STARTBANA',
    'STJERNEREGN': 'STJÄRNREGN',
    'STIGER': 'STIGER',
    'DYKKER': 'DYKER',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · VIND OCH FLYGANDE SAKER · {0} stjärnor · endast lokalt eventrekord',
    'STREAK REDDET · GUARD BRUGT': 'STREAK RÄDDAD · GUARD ANVÄND',
    'STORMPILOT': 'STORMPILOT',
    'Saml 20 stjerner til reden': 'Samla 20 stjärnor till boet',
    'Saml 250 stjerner i alt': 'Samla 250 stjärnor totalt',
    'Scoretype': 'Poängtyp',
    'Skriv dit navn': 'Skriv ditt namn',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Spela Bird Run, lokal fågelvärld. Undvik den varnade rovfågeln. Ingen global topplista.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Spela Neon Encore, lokal konsertvärld. Överlev en hel våg med minst tre bollar. Ingen global topplista.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Spela Sky Relay, en kort lokal precisionsrutt genom tre molnringar. Ringens topp och botten kan träffas. Träffa vindspelets guldplatta. Ingen global topplista.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Spela Stormline, lokal vindvärld. Undvik ett flygande föremål i storm. Ingen global topplista.',
    'Spiltype': 'Spelläge',
    'Start Quick Flight': 'Starta Quick Flight',
    'Starthelt · Klar til at flyve': 'Starthjälte · Redo att flyga',
    'Starthelt': 'Starthjälte',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard redo: räddar en missad stjärna',
    'Streak Guard reddede din streak': 'Streak Guard räddade din streak',
    'Sur havnemåge · køb for fjer': 'Sur hamnmås · köp för fjädrar',
    'SØLV': 'SILVER',
    'BRONZE': 'BRONS',
    'Sådan virker Berts rede': 'Så fungerar Berts bo',
    'TAP': 'TRYCK',
    'TAP FOR AT FLYVE · {0}': 'TRYCK FÖR ATT FLYGA · {0}',
    'TESTBANE': 'TESTBANA',
    'TIDEN UDE': 'TIDEN ÄR UTE',
    'TILBAGE': 'TILLBAKA',
    'TRYK FOR AT STARTE': 'TRYCK FÖR ATT STARTA',
    'TUNG': 'TUNG',
    'TUNG · STIGER LANGSOMT': 'TUNG · STIGER LÅNGSAMT',
    'Tid': 'Tid',
    'Tilgængelige helte': 'Tillgängliga hjältar',
    'UDFORDR EN VEN': 'UTMANA EN VÄN',
    'Udfordringen er klar': 'Utmaningen är klar',
    'Udfordringslink klar': 'Utmaningslänk klar',
    'Udfordringslink kopieret': 'Utmaningslänk kopierad',
    'Uge': 'Vecka',
    'Undvig den varslede ørn eller grib': 'Undvik den varnade örnen eller gamen',
    'Undvig en flyvende genstand i storm eller orkan': 'Undvik ett flygande föremål i storm eller orkan',
    'VELKOMMEN': 'VÄLKOMMEN',
    'VENNEDUEL': 'VÄNDUELL',
    'VENNER': 'VÄNNER',
    'VERDEN': 'VÄRLDEN',
    'VENNER FRA DUELLER': 'VÄNNER FRÅN DUELLER',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'VÄNNER FRÅN DUELLER · {0} RIVALER · {1} RESULTAT',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'VÄNSTER SIDA = UPP · HÖGER SIDA = NED',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · VÄNSTER UPP · HÖGER NED',
    'VERDEN KLARET': 'VÄRLDEN KLARAD',
    'VERDEN KLARET · LOKALT': 'VÄRLDEN KLARAD · LOKALT',
    'VIND & GENSTANDE': 'VIND & FÖREMÅL',
    'VIND · TESTBANE': 'VIND · TESTBANA',
    'VIND · {0}': 'VIND · {0}',
    'VINDKLOKKEN RAMT': 'VINDSPELET TRÄFFAT',
    'VINDVERDEN · LOKALT': 'VINDVÄRLD · LOKALT',
    'Vindmøller': 'Vindkraftverken',
    'VINDMØLLER': 'VINDKRAFTVERKEN',
    'Vulkanen': 'Vulkanen',
    'VULKANEN': 'VULKANEN',
    'FJENDER & ANGREB': 'FIENDER & ANFALL',
    'FUGLETRAFIK · TESTBANE': 'FÅGELTRAFIK · TESTBANA',
    'FUGLE & ROVFUGL': 'FÅGLAR & ROVFÅGEL',
    'FLAPPY-STYRING': 'FLAPPY-STYRNING',
    'FLAPPY-STYRING · TAP': 'FLAPPY-STYRNING · TRYCK',
    'VUNDET': 'VUNNEN',
    'BEHOLDT': 'BEHÅLLEN',
    'Valgt og klar til at flyve': 'Vald och redo att flyga',
    'Vind bronze, sølv og guld': 'Vinn brons, silver och guld',
    'Vind ti vennedueller': 'Vinn tio vändueller',
    'Vind · genstande': 'Vind · föremål',
    'VÆLG HELT': 'VÄLJ HJÄLTE',
    'VÆLG LEVEL': 'VÄLJ BANA',
    'VÆLG SPILTYPE': 'VÄLJ SPELLÄGE',
    'Vælg Bert': 'Välj Bert', 'Vælg Blok-Johan': 'Välj Blok-Johan', 'Vælg BlueBert': 'Välj BlueBert', 'Vælg BoneBeak': 'Välj BoneBeak',
    'Vælg BrainBird': 'Välj BrainBird', 'Vælg BrickBird': 'Välj BrickBird', 'Vælg Coopinc': 'Välj Coopinc', 'Vælg Fodbold-Bert': 'Välj Fotbolls-Bert',
    'Vælg Guld-Bert': 'Välj Guld-Bert', 'Vælg InkBird': 'Välj InkBird', 'Vælg MechaBert': 'Välj MechaBert', 'Vælg MossHex': 'Välj MossHex',
    'Vælg Mågen Mogens': 'Välj Måsen Mogens', 'Vælg Ninja-Bert': 'Välj Ninja-Bert', 'Vælg NoirWing': 'Välj NoirWing', 'Vælg Pakke-Bert': 'Välj Paket-Bert',
    'Vælg Pingo': 'Välj Pingo', 'Vælg Prinsesse Søs': 'Välj Prinsessan Søs', 'Vælg PrismWing': 'Välj PrismWing', 'Vælg SkyClaw': 'Välj SkyClaw',
    'Vælg Storm Royale': 'Välj Storm Royale', 'Vælg SugarRush': 'Välj SugarRush', 'Vælg Thor Obby': 'Välj Thor Obby',
    'Vælg bane': 'Välj bana',
    'Vælg leaderboard': 'Välj topplista',
    'Vælg level': 'Välj bana',
    'Vælg spiltype': 'Välj spelläge',
    'Vælg {0}, {1}': 'Välj {0}, {1}',
    'købt': 'köpt',
    'låst op': 'upplåst',
    '{0} ER LÅST': '{0} ÄR LÅST',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} fick {1} poäng. Du har {2} försök på samma bana, och deras flygning visas som en skugga.',
    '{0} forsøg tilbage · slå {1} point': '{0} försök kvar · slå {1} poäng',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} har utmanat dig att slå {1} poäng. Du har tre försök.',
    '{0} låst op for {1} fjer': '{0} upplåst för {1} fjädrar',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} låst. {1}. {2} av {3}. Alternativt pris {4} fjädrar.',
    '{0} missionsbelønninger': '{0} uppdragsbelöningar',
    '{0} missionsbelønninger er hentet.': '{0} uppdragsbelöningar är hämtade.',
    '{0} point til næste medalje': '{0} poäng till nästa medalj',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} När båda kraven är uppfyllda öppnas hela steg {2}.',
    '{0} · {1} FASTE LIV': '{0} · {1} FASTA LIV',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, låst. Tryck för att se kravet',
    '{0}, åben, personlig rekord {1}': '{0}, öppen, personligt rekord {1}',
    '{0} · Mål {1}': '{0} · Mål {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} BANOR · {2}/{3} UPPDRAG',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} BANOR · {2}/{3} UPPDR.',
    '{0} BANER · {1}': '{0} BANOR · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} ÖPPNA · {2}',
    'DU MANGLER {0} FJER': 'DU SAKNAR {0} FJÄDRAR',
    'BESKYTTET · {0}s': 'SKYDDAD · {0}s',
    'ÅBN DAGENS MISSIONER': 'ÖPPNA DAGENS UPPDRAG',
    'ÅBN GARDEROBE · 17 HELTE': 'ÖPPNA GARDEROB · 17 HJÄLTAR',
    'ÅNDENDE PORTE': 'ANDANDE PORTAR',
    'Åbn dagens missioner': 'Öppna dagens uppdrag',
    'Åbn highscore': 'Öppna rekord',
    'Åbn indstillinger': 'Öppna inställningar',
    'ÉN CHANCE MERE?': 'EN CHANS TILL?',
    'Sprog': 'Språk',
    'Automatisk (som telefonen)': 'Automatiskt (som telefonen)',
    'Dansk': 'Danska', 'Engelsk': 'Engelska', 'Norsk': 'Norska', 'Svensk': 'Svenska', 'Tysk': 'Tyska', 'Spansk': 'Spanska', 'Fransk': 'Franska', 'Portugisisk': 'Portugisiska',
    '+1 FJER': '+1 FJÄDER',
    'En ven': 'En vän',
    'Dig': 'Du',
    'REKORD': 'REKORD',
    'Topflyvning': 'Toppflygning',
    '{0} point i {1}': '{0} poäng i {1}',
    'en bane': 'en bana',
    '{0} til trin {1} · {2} stjerner': '{0} till steg {1} · {2} stjärnor',
    '{0} · {1} stjerner samlet': '{0} · {1} stjärnor samlade',
    '{0} FJER': '{0} FJÄDRAR',
    'TAP FOR AT FLYVE': 'TRYCK FÖR ATT FLYGA',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Slå din väns poäng på exakt samma bana. Du har tre försök, och deras spökflygning följer dig.",
    '{0}/{1} BRONZE': '{0}/{1} BRONS',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Ta brons (20 poäng) på alla {0} grundbanor för att öppna Äventyr. Du har {1}.',
    'SØLV I {0}': 'SILVER I {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Ta silver (50 poäng) i {0} för att öppna {1}.',
    'LAVAEN FALDER': 'LAVAN SJUNKER',
    'GODT GREB · {0}s': 'BRA GREPP · {0}s',
    'VINDSTØD · OP': 'VINDBY · UPP',
    'VINDSTØD · NED': 'VINDBY · NED',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'HALT IS: STYR I GOD TID · SAMLA FROSTKRISTALLER',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'AKTA VINDBYARNA · PILARNA VISAR VÄGEN',
    'LAVAEN STIGER · SAML KØLESTEN': 'LAVAN STIGER · SAMLA KYLSTENAR',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'LJUSET SLOCKNAR SAKTA · SAMLA LYKTOR',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'CONTAINRARNA FLYTTAR SIG · AKTA MÅSARNA',
    'Fugleklat': 'Fågelklick',
    'SPIS & KLAT': 'ÄT & SLÄPP',
    'PARAPLYEN REDDEDE DEM': 'PARAPLYET RÄDDADE DEM',
    'GULDBIL! ×3': 'GULDBIL! ×3',
    'PLASK!': 'PLASK!',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'ÄT MAT · TRYCK 💩 FÖR ATT TRÄFFA MÅL UNDER DIG',
    'Slip en klat': 'Släpp en klick',
    'Alle helte flyver ens. Vind dem i spillet, eller spar fjer sammen.': 'Alla hjältar flyger lika. Vinn dem i spelet eller spara fjädrar.',
    'ÅBN GARDEROBE': 'ÖPPNA GARDEROBEN',
    'OP · EVIGT SKJOLD · INGEN REKORDER': 'OP · EVIG SKÖLD · INGA REKORD',
    'FORSTØR': 'FÖRSTORA',
    'FORMINDSK': 'FÖRMINSKA',
    'FORSTØR · POINT ×2': 'FÖRSTORA · POÄNG ×2',
    'FØLG TUNNELEN · HOLD VENSTRE = OP · HØJRE = NED': 'FÖLJ TUNNELN · HÅLL VÄNSTER = UPP · HÖGER = NER',
    // Feedback 4. okt.: reden, æg, mærker, eventyr-låse, lyd.
    "Vælg én starthelt efter 10, 20, 30 og 40 ture": "Välj en starthjälte efter 10, 20, 30 och 40 rundor",
    "Nå 600 point på én tur": "Få 600 poäng på en runda",
    "Nå guld i alle tre Classic-baner": "Ta guld på alla tre Classic-banor",
    "Kun fra et æg i reden": "Bara från ett ägg i boet",
    "Kun fra et æg i reden (sjælden)": "Bara från ett ägg i boet (sällsynt)",
    "Æggebert": "Äggbert",
    "ÆGGEBERT": "ÄGGBERT",
    "Vælg Æggebert": "Välj Äggbert",
    "Klæk alle helte fra rugepladsen": "Kläck alla hjältar från kläckplatsen",
    "KLÆK ALLE": "KLÄCK ALLA",
    "Blød rede": "Mjukt bo",
    "Et sted at lande. Fjer bygger den videre.": "En plats att landa. Fjädrar bygger vidare.",
    "Redningsfjer": "Räddningsfjäder",
    "REDNINGSFJER": "RÄDDNINGSFJÄDER",
    "Ét redningsliv på hver tur.": "Ett räddningsliv varje runda.",
    "Stærkere magnet": "Starkare magnet",
    "Magneten trækker 30 % længere.": "Magneten drar 30 % längre.",
    "Varmt skjold": "Varm sköld",
    "Skjoldet holder 2 sekunder længere.": "Skölden håller 2 sekunder längre.",
    "Hurtig start": "Snabb start",
    "Usårlig med ekstra fart de første 5 sekunder.": "Osårbar med extra fart de första 5 sekunderna.",
    "To redningsliv": "Två räddningsliv",
    "To redningsliv på hver tur.": "Två räddningsliv varje runda.",
    "Guldrede": "Guldbo",
    "Stjerner giver +1 point de første 10 sekunder.": "Stjärnor ger +1 poäng de första 10 sekunderna.",
    "Første flyvetur": "Första flygturen",
    "Gennemfør din første tur": "Slutför din första runda",
    "Første stjerne": "Första stjärnan",
    "Saml din første stjerne": "Samla din första stjärna",
    "Første fjer": "Första fjädern",
    "Find din første gyldne fjer": "Hitta din första gyllene fjäder",
    "Vind din første bronzemedalje": "Vinn din första bronsmedalj",
    "Ny ven": "Ny vän",
    "Lås din første ekstra helt op": "Lås upp din första extra hjälte",
    "Sølv": "Silver",
    "Vind sølv på en bane": "Vinn silver på en bana",
    "Guld": "Guld",
    "Vind guld på en bane": "Vinn guld på en bana",
    "I flow": "I flow",
    "Nå en streak på 10": "Nå en streak på 10",
    "Ustoppelig": "Ostoppbar",
    "Nå en streak på 25": "Nå en streak på 25",
    "Stjerneregn": "Stjärnregn",
    "Saml 100 stjerner på én tur": "Samla 100 stjärnor på en runda",
    "Højtflyver": "Högflygare",
    "Få 500 point på én tur": "Få 500 poäng på en runda",
    "Udholdenhed": "Uthållighet",
    "Flyv 3 minutter på én tur": "Flyg 3 minuter på en runda",
    "Fejlfri": "Felfri",
    "Guld uden redningsliv eller redningsspin": "Guld utan räddningsliv eller räddningssnurr",
    "Klassiker": "Klassiker",
    "Bronze på alle Classic-baner": "Brons på alla Classic-banor",
    "Skorstensfejer": "Sotare",
    "Bronze på alle Flappy-baner": "Brons på alla Flappy-banor",
    "Tunnelrytter": "Tunnelryttare",
    "Bronze på alle Tunnel-baner": "Brons på alla Tunnel-banor",
    "Eventyrer": "Äventyrare",
    "Lås Eventyr op": "Lås upp Äventyr",
    "Verdensflyver": "Världsflygare",
    "Sølv på alle seks eventyrbaner": "Silver på alla sex äventyrsbanor",
    "Lavalord": "Lavaherre",
    "Guld på Vulkanen": "Guld på Vulkanen",
    "Mesterskytte": "Mästerskytt",
    "10 træffere i træk i Fugleklat": "10 träffar i rad i Fågelklick",
    "Publikumsvølge": "Publikvåg",
    "Kom forbi tre bolde i én koncertbølge": "Ta dig förbi tre bollar i en konsertvåg",
    "Fri af rovfuglen": "Fri från rovfågeln",
    "Undvig den varslede rovfugl": "Undvik den varslade rovfågeln",
    "Undvig en flyvende genstand i storm": "Undvik ett flygande föremål i storm",
    "Portløber": "Portlöpare",
    "Klar alle tre porte i én Sky Relay-runde": "Klara alla tre portar i en Sky Relay-runda",
    "Ekstranummer": "Extranummer",
    "Sølv i Neon Encore": "Silver i Neon Encore",
    "Pakket ind": "Inpackad",
    "Bliv fanget af edderkoppen": "Bli fångad av spindeln",
    "Snack": "Mellanmål",
    "Bliv fanget af slangen": "Bli fångad av ormen",
    "Grillkylling": "Grillkyckling",
    "Dø 50 gange i alt": "Krascha 50 gånger totalt",
    "Flokken": "Flocken",
    "Lås 10 helte op": "Lås upp 10 hjältar",
    "Redebygger": "Bobyggare",
    "Saml 100 fjer i alt": "Samla 100 fjädrar totalt",
    "GAME OVER": "GAME OVER",
    "MAGNET": "MAGNET",
    "Få bronze på alle tre Classic-baner for at åbne Havnen.": "Ta brons på alla tre Classic-banor för att öppna Hamnen.",
    "Få bronze på alle tre Flappy-baner for at åbne Nattebyen.": "Ta brons på alla tre Flappy-banor för att öppna Nattstaden.",
    "Få bronze på alle tre Tunnel-baner for at åbne Vindmøller.": "Ta brons på alla tre Tunnel-banor för att öppna Vindkraftverken.",
    "Få sølv i to af Havnen, Nattebyen og Vindmøller for at åbne Vulkanen.": "Ta silver i två av Hamnen, Nattstaden och Vindkraftverken för att öppna Vulkanen.",
    "GULD PÅ EN BANE": "GULD PÅ EN BANA",
    "SØLV I VULKANEN": "SILVER I VULKANEN",
    "Få sølv i Vulkanen og guld på én af grundbanerne for at åbne Isbjerget.": "Ta silver i Vulkanen och guld på en av grundbanorna för att öppna Isberget.",
    "SØLV I ISBJERGET": "SILVER I ISBERGET",
    "Få sølv i Isbjerget for at åbne Fugleklat.": "Ta silver i Isberget för att öppna Fågelklick.",
    "ÅBNER MED EVENTYR": "ÖPPNAS MED ÄVENTYR",
    "Testbanerne åbner sammen med den første eventyrverden.": "Testbanorna öppnas med den första äventyrsvärlden.",
    "HEMMELIG": "HEMLIG",
    "LÅST": "LÅST",
    "Låst. Tryk på helten for at se, hvordan du får den.": "Låst. Tryck på hjälten för att se hur du får den.",
    "En hemmelig helt. Den hører til et særligt pilotnavn.": "En hemlig hjälte. Den hör till ett speciellt pilotnamn.",
    "Du kan vælge en starthelt nu.": "Du kan välja en starthjälte nu.",
    "Eller klæk den fra et æg, når reden har nået trin 4.": "Eller kläck den ur ett ägg när boet når steg 4.",
    "REDEN ER FÆRDIG": "BOET ÄR KLART",
    "Alle syv trin er bygget. Flot!": "Alla sju steg är byggda. Snyggt!",
    "Du fandt et æg! Det ligger i reden og ruger.": "Du hittade ett ägg! Det ruvas i boet.",
    "VÆLG EN NY HELT": "VÄLJ EN NY HJÄLTE",
    "Du må vælge én. De andre kan vælges efter 10 ture mere.": "Välj en. De andra kan väljas efter 10 rundor till.",
    "SENERE": "SENARE",
    "Én tur om dagen giver fjer": "En runda om dagen ger fjädrar",
    "Ruger et tilfældigt æg. Saml stjerner, så klækker det.": "Ruvar ett slumpat ägg. Samla stjärnor så kläcks det.",
    "TOM": "TOM",
    "ALLE KLÆKKET": "ALLA KLÄCKTA",
    "Alle helte er klækket": "Alla hjältar är kläckta",
    "fjer": "fjädrar",
    "sjælden": "sällsynt",
    "Et æg ligger i reden. Saml stjerner, så klækker det.": "Ett ägg ligger i boet. Samla stjärnor så kläcks det.",
    "ER DU SIKKER? TRYK IGEN": "ÄR DU SÄKER? TRYCK IGEN",
    "GLOBAL HIGHSCORE": "GLOBAL TOPPLISTA",
    "Du mangler fjer. Flyv en tur, og klar dagens missioner.": "Du saknar fjädrar. Flyg en runda och klara dagens uppdrag.",
    "{0}/3 CLASSIC": "{0}/3 CLASSIC",
    "{0}/3 FLAPPY": "{0}/3 FLAPPY",
    "{0}/3 TUNNEL": "{0}/3 TUNNEL",
    "SØLV {0}/2": "SILVER {0}/2",
    "LÅST · {0}/{1}": "LÅST · {0}/{1}",
    "Vælg den som starthelt efter {0} ture. Du har fløjet {1}.": "Välj den som starthjälte efter {0} rundor. Du har flugit {1}.",
    "Klæk alle helte fra rugepladsen. {0}/{1} klækket.": "Kläck alla hjältar från kläckplatsen. {0}/{1} kläckta.",
    "Bedrift: {0} ({1}/{2}).": "Bedrift: {0} ({1}/{2}).",
    "Eller klæk den fra et æg i reden: sikret æg {0} fjer.": "Eller kläck den ur ett ägg i boet: valt ägg {0} fjädrar.",
    "Du har {0} fjer. Fjer får du af dagens missioner, en tur om dagen og sjældne fjer i banerne.": "Du har {0} fjädrar. Fjädrar får du av dagens uppdrag, en runda om dagen och sällsynta fjädrar på banorna.",
    "BYG · {0} FJER": "BYGG · {0} FJÄDRAR",
    "BYG · 20 FJER": "BYGG · 20 FJÄDRAR",
    "MANGLER {0} FJER": "SAKNAR {0} FJÄDRAR",
    "{0} TURE FLØJET": "{0} RUNDOR FLUGNA",
    "{0} er din nu": "{0} är din nu",
    "Ægget klækkede: {0}!": "Ägget kläcktes: {0}!",
    "{0} er klækket og venter i garderoben": "{0} har kläckts och väntar i garderoben",
    "Ægget: {0}/{1} stjerner": "Ägget: {0}/{1} stjärnor",
    "{0} fjer fundet": "{0} fjädrar hittade",
    "Dag {0} i træk: +{1} fjer": "Dag {0} i rad: +{1} fjädrar",
    "Reden: {0}/{1} til {2}": "Boet: {0}/{1} till {2}",
    "Nyt mærke: {0}": "Nytt märke: {0}",
    "{0} dage i træk": "{0} dagar i rad",
    "{0}/{1} STJERNER": "{0}/{1} STJÄRNOR",
    "Ruger: {0}": "Ruvar: {0}",
    "{0} helte kan stadig klækkes": "{0} hjältar kan fortfarande kläckas",
    "TILFÆLDIGT ÆG · {0} FJER": "SLUMPÄGG · {0} FJÄDRAR",
    "SIKRET ÆG · {0} FJER": "VALT ÄGG · {0} FJÄDRAR",
    "TILFÆLDIGT ÆG": "SLUMPÄGG",
    "SIKRET ÆG": "VALT ÄGG",
    "Et sikret æg med {0} ligger i reden": "Ett valt ägg med {0} ligger i boet",
    "Reden er bygget: {0}": "Boet är byggt: {0}",
    "Dag {0} i træk · +{1} fjer til reden": "Dag {0} i rad · +{1} fjädrar till boet",
    "Bert The Bird – flyvespil og præcisionsverdener": "Bert The Bird – flygspel och precisionsvärldar",
    "PAUSE": "PAUS",
    "REDEN": "BOET",
    "Reden": "Boet",
    "Åbn reden": "Öppna boet",
    "Luk reden": "Stäng boet",
    "Redens trin": "Boets steg",
    "NÆSTE TRIN": "NÄSTA STEG",
    "RUGEPLADSEN": "KLÄCKPLATSEN",
    "FLYV HVER DAG": "FLYG VARJE DAG",
    "MÆRKER": "MÄRKEN",
    "Fjer bygger reden. Hvert trin kan mærkes i spillet. Efter døden kan du bruge 12 fjer på ét redningsspin.": "Fjädrar bygger boet. Varje steg märks i spelet. Efter en krasch kan du använda 12 fjädrar på ett räddningssnurr.",
    "Forrige helte": "Föregående hjältar",
    "Næste helte": "Nästa hjältar",
    "Musikstyrke": "Musikvolym",
    "Lydstyrke for effekter": "Effektvolym",
    "Vælg helt til sikret æg": "Välj hjälte för valt ägg",
    "Banens grafik kunne ikke indlæses.": "Banans grafik kunde inte laddas.",
    "Spillet kunne ikke indlæses. Prøv igen.": "Spelet kunde inte laddas. Försök igen.",
    "NY HELT: {0} · {1}": "NY HJÄLTE: {0} · {1}",
    "Klæk den fra et æg i reden: sikret æg {0} fjer.": "Kläck den ur ett ägg i boet: valt ägg {0} fjädrar.",
    "Klæk den fra et æg, når reden har nået trin 4.": "Kläck den ur ett ägg när boet når steg 4.",
    // Udfordringer (10. okt.)
    "Få 40 point uden redningsliv": "Få 40 poäng utan räddningsliv",
    "Få 80 point uden redningsliv": "Få 80 poäng utan räddningsliv",
    "Find en gylden fjer i en bane": "Hitta en gyllene fjäder på en bana",
    "Få 60 point uden at tage en power-up": "Få 60 poäng utan att ta en power-up",
    "Saml 400 stjerner i denne uge": "Samla 400 stjärnor denna vecka",
    "Flyv 30 ture i denne uge": "Flyg 30 rundor denna vecka",
    "Guld på 2 forskellige baner i denne uge": "Guld på 2 olika banor denna vecka",
    "Slå din egen rekord 3 gange": "Slå ditt eget rekord 3 gånger",
    "Flyv på 6 forskellige baner": "Flyg på 6 olika banor",
    "Flyv 30 minutter i denne uge": "Flyg 30 minuter denna vecka",
    "Lynhurtig: styrt inden for 1 sekund": "Blixtsnabb: krascha inom 1 sekund",
    "Svaret på alt: præcis 42 point": "Svaret på allt: exakt 42 poäng",
    "Natteravn: flyv mellem midnat og kl. 4": "Nattuggla: flyg mellan midnatt och kl. 4",
    "Tålmodig: 60 sekunder uden en eneste stjerne": "Tålmodig: 60 sekunder utan en enda stjärna",
    "Sultestrejke: 30 sekunder og 0 stjerner": "Hungerstrejk: 30 sekunder och 0 stjärnor",
    "Jo større de er: styrt mens du er forstørret": "Ju större de är: krascha medan du är förstorad",
    "Juleflyver: flyv juleaften": "Julflygare: flyg på julafton",
    "Hattrick: tre ture i træk med samme point": "Hattrick: tre rundor i rad med samma poäng",
    "Garderobe-gal: flyv med 7 forskellige helte": "Garderobsgalen: flyg med 7 olika hjältar",
    "Maraton: 10 minutter på én tur": "Maraton: 10 minuter på en runda",
    "Ørkenrotte: 100 ture i Desert": "Ökenråtta: 100 rundor i Desert",
    "Halvtreds: en streak på 50": "Femtio: en streak på 50",
    "Flappy-mester: 500 point i Flappy Bert": "Flappy-mästare: 500 poäng i Flappy Bert",
    "Bonk-serie: 5 styrt på 2 minutter": "Bonk-serie: 5 krascher på 2 minuter",
    "Edderkoppens ven: fanget 10 gange": "Spindelns vän: fångad 10 gånger",
    "Saml {0} stjerner i dag": "Samla {0} stjärnor i dag",
    "Flyv {0} minutter i alt i dag": "Flyg {0} minuter totalt i dag",
    "Nå en streak på {0}": "Nå en streak på {0}",
    "Flyv {0} ture i dag": "Flyg {0} rundor i dag",
    "Få {0} point på én tur": "Få {0} poäng på en runda",
    "Tag {0} power-ups i dag": "Ta {0} power-ups i dag",
    "Flyv {0} sekunder på én tur": "Flyg {0} sekunder på en runda",
    "Bronze i {0} i dag": "Brons i {0} i dag",
    "Sølv i {0} i dag": "Silver i {0} i dag",
    "Guld i {0} i dag": "Guld i {0} i dag",
    "Tur nr. {0}": "Runda nr {0}",
    "{0} stjerner i alt": "{0} stjärnor totalt",
    "{0} fjer samlet i alt": "{0} fjädrar totalt",
    "{0} helte": "{0} hjältar",
    "{0} mærker": "{0} märken",
    "Reden på trin {0}": "Boet på steg {0}",
    "{0} æg klækket": "{0} ägg kläckta",
    "{0}: guld": "{0}: guld",
    "{0}: 200 point": "{0}: 200 poäng",
    "{0}: 60 point uden redning og power-ups": "{0}: 60 poäng utan räddning och power-ups",
    "??? (hemmelig udfordring)": "??? (hemlig utmaning)",
    "Tæt på: {0} ({1}/{2})": "Nästan: {0} ({1}/{2})",
    "+{0} fjer · {1}": "+{0} fjädrar · {1}",
    "UGENS UDFORDRINGER": "VECKANS UTMANINGAR",
    "UDFORDRINGER": "UTMANINGAR",
    "MILEPÆLE": "MILSTOLPAR",
    "MESTERSKAB": "MÄSTERSKAP",
    "HEMMELIGE": "HEMLIGA",
    "NIVEAU {0}!": "NIVÅ {0}!",
    "HVOR SKAL BERT HEN?": "VART SKA BERT?",
    "DIN REJSE": "DIN RESA",
    "Ørkenen": "Öknen",
    "Junglen": "Djungeln",
    "Himlen": "Himlen",
    "Byen": "Staden",
    "Tunnelen": "Tunneln",
    "Natten": "Natten",
    "Vinden": "Vinden",
    "Isen": "Isen",
    "Fugleklat-øen": "Fågelklick-ön",
    "Spejlbanen": "Spegelbanan",
    "GLID & OPVIND · TESTBANE": "GLID & UPPVIND · TESTBANA",
    "GLID & OPVIND": "GLID & UPPVIND",
    "Svæv": "Sväva",
    "Vælg et andet navn": "Välj ett annat namn",
    "FLOK & FORMATION · TESTBANE": "FLOCK & FORMATION · TESTBANA",
    "FLOK & FORMATION": "FLOCK & FORMATION",
    "Fuglesværm": "Fågelsvärm",
    "Klistermærke fundet! Se det i albummet i reden": "Klistermärke hittat! Se det i albumet i boet",
    "KLISTERMÆRKER": "KLISTERMÄRKEN",
    "Fem skjulte klistermærker i hver bane. Hold øje, mens du flyver.": "Fem gömda klistermärken på varje bana. Håll utkik medan du flyger.",
});
