/* Deutsch. Die Schlüssel sind die dänischen Ausgangstexte. */
window.BertI18n.register('de', {
    ' · FLYV EN TUR FOR AT SÆTTE FØRSTE SCORE': ' · FLIEG EINE RUNDE FÜR DEINEN ERSTEN SCORE',
    ' · MÆRKE: {0}': ' · ABZEICHEN: {0}',
    ' · SPIL EN VENNEDUEL FOR AT FÅ EN RIVAL': ' · SPIEL EIN FREUNDESDUELL FÜR EINEN RIVALEN',
    '+{0} fjer til reden': '+{0} Federn fürs Nest',
    '+{0} fjer · {1} låst op': '+{0} Federn · {1} freigeschaltet',
    '0 / 0 POINT': '0 / 0 PUNKTE',
    '20 point til bronze': '20 Punkte bis Bronze',
    '3 SPILFORMER · 9 BANER': '3 SPIELMODI · 9 LEVEL',
    '3 baner · hold op/ned': '3 Level · halten hoch/runter',
    '3 baner · præcision': '3 Level · Präzision',
    '3 baner · tap': '3 Level · tippen',
    '9 baner · nye verdener': '9 Level · neue Welten',
    'ACCEPTÉR': 'ANNEHMEN',
    'AFSLUT TUREN': 'RUNDE BEENDEN',
    'Alle baner': 'Alle Level',
    'Alle helte har samme fart og collider. Vind dem i spillet, eller spar fjer sammen.': 'Alle Helden haben dieselbe Geschwindigkeit und Hitbox. Gewinne sie im Spiel oder spare Federn.',
    'Alle pointkrav i trin {0} er klaret.': 'Alle Punktanforderungen in Stufe {0} sind erfüllt.',
    'Alle spil': 'Alle Spiele',
    'Alle tider': 'Gesamt',
    'Alle tre forsøg er brugt. Bed din ven om en ny duel.': 'Alle drei Versuche sind verbraucht. Bitte deinen Freund um ein neues Duell.',
    'BANEN ER LÅST': 'LEVEL GESPERRT',
    'BEKRÆFT · {0} FJER': 'BESTÄTIGEN · {0} FEDERN',
    'BERTS GARDEROBE': 'BERTS GARDEROBE',
    'BERTS REDE': 'BERTS NEST',
    'BERTS REDNINGSREDE': 'BERTS RETTUNGSNEST',
    'BEVÆGELIGE TÅRNE': 'BEWEGLICHE TÜRME',
    'BIRD RUN{0} · {1} stjerner · kun lokal eventrekord': 'BIRD RUN{0} · {1} Sterne · nur lokaler Eventrekord',
    'Bane': 'Level',
    'Banen er låst': 'Das Level ist gesperrt',
    'Bedst på level {0} · {1}': 'Bestwert in Level {0} · {1}',
    'Bert The Bird appikon': 'Bert The Bird App-Symbol',
    'Bert The Bird bliver installeret': 'Bert The Bird wird installiert',
    'Bert The Bird er installeret': 'Bert The Bird ist installiert',
    'Bert The Bird spilcanvas': 'Bert The Bird Spielfläche',
    'Bert flyver': 'Bert fliegt',
    'Bevægelse i koncertlys': 'Bewegung im Konzertlicht',
    'Brug 12 fjer på ét spin. Fem felter sender Bert tilbage i banen. Ét felt afslutter turen.': 'Setze 12 Federn für eine Drehung ein. Fünf Felder schicken Bert zurück ins Level. Ein Feld beendet die Runde.',
    'DAGENS MISSIONER': 'TAGESMISSIONEN',
    'DAGENS RUTE': 'TAGESROUTE',
    'DAGENS RUTE · MÅL {0}': 'TAGESROUTE · ZIEL {0}',
    'DENNE TUR': 'DIESE RUNDE',
    'DIN FLYVETUR': 'DEIN FLUG',
    'DIN HELT': 'DEIN HELD',
    'DIN SALDO': 'DEIN GUTHABEN',
    'DINE VENNEDUELLER': 'DEINE FREUNDESDUELLE',
    'DREJ TELEFONEN': 'DREH DEIN HANDY',
    'DU ER UDFORDRET': 'DU WURDEST HERAUSGEFORDERT',
    'DU VANDT DUELLEN · udfordr tilbage · {0} stjerner': 'DU HAST DAS DUELL GEWONNEN · fordere zurück · {0} Sterne',
    'Den sjældneste fugl · køb for fjer': 'Der seltenste Vogel · mit Federn kaufen',
    'Denne bane kan ikke bruges til ranked vennesdueller.': 'Dieses Level kann nicht für gewertete Freundesduelle genutzt werden.',
    'Dit navn': 'Dein Name',
    'Dit navn står på ranglisten og ved dine rekorder.': 'Dein Name steht in der Rangliste und bei deinen Rekorden.',
    'Du mangler fjer fra dagens missioner': 'Dir fehlen Federn aus den Tagesmissionen',
    'EDM-VERDEN · LOKALT': 'EDM-WELT · LOKAL',
    'EPISK': 'EPISCH',
    'EVENT · BIRD RUN · TESTBANE': 'EVENT · BIRD RUN · TESTLEVEL',
    'EVENT · NEON ENCORE · TESTBANE': 'EVENT · NEON ENCORE · TESTLEVEL',
    'EVENT · STORMLINE · TESTBANE': 'EVENT · STORMLINE · TESTLEVEL',
    'EVENTYR': 'ABENTEUER',
    'EVENTYR · {0}': 'ABENTEUER · {0}',
    'Episk helt · kun til dig · valgt': 'Epischer Held · nur für dich · gewählt',
    'Episk helt · kun til dig. Tryk for at vælge.': 'Epischer Held · nur für dich. Tippen zum Auswählen.',
    'Et permanent redningsliv absorberer ét sammenstød på hver tur. Efter døden kan du desuden bruge 12 fjer på ét redningsspin. Du kan altid spille videre uden energi eller ventetid.': 'Ein dauerhaftes Rettungsleben fängt pro Runde einen Zusammenstoß ab. Nach einem Crash kannst du außerdem 12 Federn für eine Rettungsdrehung einsetzen. Du kannst immer ohne Energie oder Wartezeit weiterspielen.',
    'FAST + BEVÆGELIG': 'FEST + BEWEGLICH',
    'FASTE TÅRNE': 'FESTE TÜRME',
    'FJER': 'FEDERN',
    'FJER RETUR': 'FEDERN ZURÜCK',
    'FJER · PRIMÆRT VINDES I SPILLET': 'FEDERN · VOR ALLEM IM SPIEL GEWINNEN',
    'FLYV': 'FLIEGEN',
    'FLYV GENNEM TRE SKY-PORTE · RAM GULDPLADEN · VENSTRE OP · HØJRE NED': 'FLIEG DURCH DREI WOLKENTORE · TRIFF DIE GOLDPLATTE · LINKS HOCH · RECHTS RUNTER',
    'FLYV IGEN': 'NOCHMAL FLIEGEN',
    'FLYV VIDERE': 'WEITERFLIEGEN',
    'FLYVETUREN ER SAT PÅ PAUSE': 'DER FLUG IST PAUSIERT',
    'FODBOLD-BERT': 'FUSSBALL-BERT',
    'FOKUS': 'FOKUS',
    'FOKUS OM {0}': 'FOKUS IN {0}',
    'FORBI': 'VORBEI',
    'FORBI GULDPLADEN': 'GOLDPLATTE VERFEHLT',
    'FORSTÅET': 'VERSTANDEN',
    'FORTRYD': 'ABBRECHEN',
    'FORTSÆT': 'WEITER',
    'FRI AF ROVFUGLEN': 'DEM RAUBVOGEL ENTKOMMEN',
    'FUGL BAGFRA': 'VOGEL VON HINTEN',
    'FUGLEVERDEN · LOKALT': 'VOGELWELT · LOKAL',
    'Fire gratis lokale eventverdener uden global rangliste': 'Vier kostenlose lokale Eventwelten ohne globale Rangliste',
    'Flyv samlet i 3 minutter': 'Flieg insgesamt 3 Minuten',
    'Flyvetid': 'Flugzeit',
    'Fodbold-Bert': 'Fußball-Bert',
    'Forbindelsen er tilbage': 'Verbindung ist wieder da',
    'Fremgang mod oplåsning': 'Fortschritt bis zur Freischaltung',
    'Fugle · rovfugl': 'Vögel · Raubvogel',
    'FÆRDIG': 'FERTIG',
    'FØLG STJERNESTRØMMEN': 'FOLGE DEM STERNENSTROM',
    'FØLGER DIG KORT · {0}s': 'FOLGT DIR KURZ · {0}s',
    'GAME OVER · TUREN SLUTTER': 'GAME OVER · DIE RUNDE ENDET',
    'GLOBALT': 'GLOBAL',
    'GLOBALT · {0} RESULTATER': 'GLOBAL · {0} ERGEBNISSE',
    'GODT RAMT': 'GUT GETROFFEN',
    'GRATIS REDNING': 'GRATIS-RETTUNG',
    'GRUNDFLYVNING': 'GRUNDFLUG',
    'GULD': 'GOLD',
    'GULD-BERT': 'GOLD-BERT',
    'Guld-Bert': 'Gold-Bert',
    'HAV BERT PÅ STARTSKÆRMEN': 'BERT AUF DEM HOME-BILDSCHIRM',
    'HAVNEN': 'DER HAFEN',
    'Havnen': 'Der Hafen',
    'HENT FJER': 'FEDERN ABHOLEN',
    'HENT SPILLET': 'SPIEL HOLEN',
    'HENT +{0}': 'ABHOLEN +{0}',
    '+{0} FJER': '+{0} FEDERN',
    'HENTER RESULTATER …': 'LADE ERGEBNISSE …',
    'HENTET': 'ABGEHOLT',
    'HOLD OP/NED': 'HALTEN HOCH/RUNTER',
    'HOVEDMENU': 'HAUPTMENÜ',
    'HVAD HEDDER DU?': 'WIE HEISST DU?',
    'HVORDAN VIL DU FLYVE?': 'WIE WILLST DU FLIEGEN?',
    'HYPERFART': 'HYPERSPEED',
    'Haptisk feedback': 'Haptisches Feedback',
    'Har altid en pakke med · køb for fjer': 'Hat immer ein Paket dabei · mit Federn kaufen',
    'Hele Bert The Bird er lavet til landscape.': 'Bert The Bird ist komplett fürs Querformat gemacht.',
    'Hemmelig helt': 'Geheimer Held',
    'Hent en mission syv dage i træk': 'Hol sieben Tage in Folge eine Mission ab',
    'Hent {0} missionsbelønninger i alt; du har {1}.': 'Hol insgesamt {0} Missionsbelohnungen ab; du hast {1}.',
    'Henter resultater …': 'Lade Ergebnisse …',
    'Høj fart': 'Hohes Tempo',
    'I Safari: Del → Føj til hjemmeskærm. Vent på “Klar til offline-spil”, og åbn ikonet én gang med net før du tester i flytilstand.': 'In Safari: Teilen → Zum Home-Bildschirm. Warte auf „Bereit für Offline-Spiel“ und öffne das Symbol einmal mit Internet, bevor du den Flugmodus testest.',
    'I dag': 'Heute',
    'IKKE NU': 'NICHT JETZT',
    'INDSTILLINGER': 'EINSTELLUNGEN',
    'INSTALLÉR WEBAPP': 'WEB-APP INSTALLIEREN',
    'ISTAPPER & SPIDSER': 'EISZAPFEN & SPITZEN',
    'Isbjerget': 'Der Eisberg',
    'ISBJERGET': 'DER EISBERG',
    'Indlæser originale Unity-assets …': 'Lade originale Unity-Assets …',
    'Ingen rekord endnu': 'Noch kein Rekord',
    'Installér som webapp': 'Als Web-App installieren',
    'Installér via browserens menu. Vent på “Klar til offline-spil”, og åbn appen én gang med net før du tester offline.': 'Über das Browsermenü installieren. Warte auf „Bereit für Offline-Spiel“ und öffne die App einmal mit Internet, bevor du offline testest.',
    'KANT': 'RAND',
    'KLAR DAGENS MÅL': 'TAGESZIEL SCHAFFEN',
    'KLARET': 'GESCHAFFT',
    'KONCERT · TESTBANE': 'KONZERT · TESTLEVEL',
    'KRANER & MÅGER': 'KRÄNE & MÖWEN',
    'KUN DINE LOKALE RESULTATER · ONLINE SCOREBOARD ER IKKE TILGÆNGELIGT': 'NUR DEINE LOKALEN ERGEBNISSE · ONLINE-RANGLISTE NICHT VERFÜGBAR',
    'KVALIFIKATIONSBANEN': 'DAS QUALIFIKATIONSLEVEL',
    'Klar dagens rute': 'Schaff die Tagesroute',
    'Klar dagens rute én gang': 'Schaff die Tagesroute einmal',
    'Klar hele forrige trin og missionskravet først': 'Schaff zuerst die ganze vorherige Stufe und die Missionsanforderung',
    'Klar hele trin {0}: {1}.': 'Schaff ganz Stufe {0}: {1}.',
    'Klar kvalifikationsbanen for at åbne denne udfordring.': 'Schaff das Qualifikationslevel, um diese Herausforderung zu öffnen.',
    'Klar til offline-spil': 'Bereit für Offline-Spiel',
    'Kom forbi mindst tre bolde i én koncertbølge': 'Komm in einer Konzertwelle an mindestens drei Bällen vorbei',
    'KØB': 'KAUFEN',
    'KØB FASTE LIV ELLER ET REDNINGSSPIN': 'KAUF FESTE LEBEN ODER EINE RETTUNGSDREHUNG',
    'KØB · {0} FJER': 'KAUFEN · {0} FEDERN',
    'KØBT': 'GEKAUFT',
    'LAVA & BOBLER': 'LAVA & BLASEN',
    'LEVENDE FORHINDRINGER': 'LEBENDIGE HINDERNISSE',
    'LEVERING': 'LIEFERUNG',
    'LYD & FEEDBACK': 'TON & FEEDBACK',
    'LYDLØS': 'LAUTLOS',
    'Level 1 · Mål 30': 'Level 1 · Ziel 30',
    'Luk': 'Schließen',
    'Luk garderoben': 'Garderobe schließen',
    'Lydeffekter': 'Soundeffekte',
    'Lydløs og hurtig · køb for fjer': 'Lautlos und schnell · mit Federn kaufen',
    'LÅS OP · 20 FJER': 'FREISCHALTEN · 20 FEDERN',
    'LÅS OP · {0} FJER': 'FREISCHALTEN · {0} FEDERN',
    'LÅST BANE': 'GESPERRTES LEVEL',
    'LÅST OP': 'FREIGESCHALTET',
    'LÆR KORRIDOREN': 'LERN DEN KORRIDOR',
    'Låst op. Tryk på figuren for at vælge.': 'Freigeschaltet. Tippe auf die Figur, um sie zu wählen.',
    'MAKS LÅST OP': 'MAXIMUM ERREICHT',
    'MINISPIL · SKY RELAY · LOKALT': 'MINISPIEL · SKY RELAY · LOKAL',
    'MISSIONER': 'MISSIONEN',
    'MOBIL: VENSTRE SIDE = OP · HØJRE SIDE = NED': 'HANDY: LINKE SEITE = HOCH · RECHTE SEITE = RUNTER',
    'Missioner': 'Missionen',
    'Mod vinden': 'Gegen den Wind',
    'Musik': 'Musik',
    'MÅGEN MOGENS': 'MÖWE MOGENS',
    'Mågen Mogens': 'Möwe Mogens',
    'MÅL: 3 BOLDE': 'ZIEL: 3 BÄLLE',
    'MÅL: KOM FORBI EN BØLGE MED TRE BOLDE · VENSTRE OP · HØJRE NED': 'ZIEL: KOMM AN EINER WELLE MIT DREI BÄLLEN VORBEI · LINKS HOCH · RECHTS RUNTER',
    'MÅL: ROVFUGL': 'ZIEL: RAUBVOGEL',
    'MÅL: STORM': 'ZIEL: STURM',
    'MÅL: UNDVIG EN ROVFUGL · VENSTRE OP · HØJRE NED': 'ZIEL: WEICH EINEM RAUBVOGEL AUS · LINKS HOCH · RECHTS RUNTER',
    'MÅL: UNDVIG EN STORMGENSTAND · FØLG FLAG OG BLADE': 'ZIEL: WEICH EINEM STURMOBJEKT AUS · FOLGE FAHNEN UND BLÄTTERN',
    'MÆRKE VUNDET': 'ABZEICHEN GEWONNEN',
    'MØRKE & SKILTE': 'DUNKELHEIT & SCHILDER',
    'Måned': 'Monat',
    'NED': 'RUNTER',
    'NEON ENCORE · {0} stjerner · kun lokal eventrekord': 'NEON ENCORE · {0} Sterne · nur lokaler Eventrekord',
    'NINJA-BERT': 'NINJA-BERT',
    'Ninja-Bert': 'Ninja-Bert',
    'NIVEAU {0}! · {1}': 'STUFE {0}! · {1}',
    'NOIRWING LÅST OP · FEJLFRI FLYVNING': 'NOIRWING FREIGESCHALTET · FEHLERFREIER FLUG',
    'NY BANE': 'NEUES LEVEL',
    'NY REKORD!': 'NEUER REKORD!',
    'NYE VERDENER': 'NEUE WELTEN',
    'NYT TRIN: ALLE TRE BANER ER ÅBNE · {0} stjerner samlet': 'NEUE STUFE: ALLE DREI LEVEL SIND OFFEN · {0} Sterne gesammelt',
    'NATTEBYEN': 'DIE NACHTSTADT',
    'Nattebyen': 'Die Nachtstadt',
    'Ny mobilversion indlæst': 'Neue Mobilversion geladen',
    'Nyt redningsliv låst op': 'Neues Rettungsleben freigeschaltet',
    'NÆSTE UDFORDRING': 'NÄCHSTE HERAUSFORDERUNG',
    'Nå 120 point i Desert': 'Erreiche 120 Punkte in Desert',
    'Nå 180 point uden at misse en stjerne eller ramme noget': 'Erreiche 180 Punkte, ohne einen Stern zu verpassen oder etwas zu treffen',
    'Nå 300 point på én tur': 'Erreiche 300 Punkte in einer Runde',
    'Nå bronze i Jungle uden redning': 'Erreiche Bronze in Jungle ohne Rettung',
    'Nå bronze i alle ni baner': 'Erreiche Bronze in allen neun Leveln',
    'Nå bronze i alle tre Classic-baner': 'Erreiche Bronze in allen drei Classic-Leveln',
    'Nå en streak på 12': 'Erreiche einen Streak von 12',
    'OMVENDT STYRING': 'UMGEKEHRTE STEUERUNG',
    'OP': 'HOCH',
    'ORIGINAL': 'ORIGINAL',
    'Offline er ikke klar endnu · forbind til nettet': 'Offline ist noch nicht bereit · verbinde dich mit dem Internet',
    'PAKKE-BERT': 'PAKET-BERT',
    'Pakke-Bert': 'Paket-Bert',
    'PERMANENT REDE-FORDEL': 'DAUERHAFTER NEST-VORTEIL',
    'PERSONLIG REKORD': 'PERSÖNLICHER REKORD',
    'PILOTER': 'PILOTEN',
    'POINT ×2': 'PUNKTE ×2',
    'PORTE & KLOKKE': 'TORE & GLOCKE',
    'PRINSESSE SØS': 'PRINZESSIN SØS',
    'Prinsesse Søs': 'Prinzessin Søs',
    'PRÆCISION': 'PRÄZISION',
    'PRÆCISIONSFLYVNING · LOKAL PRØVE': 'PRÄZISIONSFLUG · LOKALE PROBE',
    'PRÆCISIONSRUTE · LOKALT': 'PRÄZISIONSROUTE · LOKAL',
    'PUBLIKUMSVØLGE': 'PUBLIKUMSWELLE',
    'Pause spillet': 'Spiel pausieren',
    'Periode': 'Zeitraum',
    'Personlig highscore': 'Persönlicher Highscore',
    'Pilotnavn': 'Pilotenname',
    'Pingvin med jetpack · køb for fjer': 'Pinguin mit Jetpack · mit Federn kaufen',
    'Point': 'Punkte',
    'Porte · vindklokke': 'Tore · Windspiel',
    'PORT {0}/3': 'TOR {0}/3',
    'PORT {0}/3 · {1}': 'TOR {0}/3 · {1}',
    'RUNDE {0} · PORT {1}/3': 'RUNDE {0} · TOR {1}/3',
    'KLANG! +{0} · RUNDE {1}': 'KLANG! +{0} · RUNDE {1}',
    'Præcisionsflyvning': 'Präzisionsflug',
    'RAM GULDPLADEN': 'TRIFF DIE GOLDPLATTE',
    'RAMT': 'GETROFFEN',
    'RANGLISTE': 'RANGLISTE',
    'REDDET · DINE 12 FJER KOMMER RETUR': 'GERETTET · DEINE 12 FEDERN KOMMEN ZURÜCK',
    'REDDET · {0}': 'GERETTET · {0}',
    'REDNINGSLIV': 'RETTUNGSLEBEN',
    'REDNINGSLIV 0/3': 'RETTUNGSLEBEN 0/3',
    'REDNINGSLIV {0}/{1}': 'RETTUNGSLEBEN {0}/{1}',
    'REDNINGSREDEN SNURRER …': 'DAS RETTUNGSNEST DREHT SICH …',
    'REDNINGSSPIN': 'RETTUNGSDREHUNG',
    'RENT GENNEM': 'SAUBER DURCH',
    'RIGGE & BOLDE': 'TRAVERSEN & BÄLLE',
    'ROTORER & BØJER': 'ROTOREN & BOJEN',
    'ROVFUGL': 'RAUBVOGEL',
    'ROVFUGL BAGFRA': 'RAUBVOGEL VON HINTEN',
    'FUGL': 'VOGEL',
    'BAGFRA': 'VON HINTEN',
    'FORFRA': 'VON VORN',
    'RUTEN AFSLUTTET': 'ROUTE BEENDET',
    'Redningsliv tilbage': 'Rettungsleben übrig',
    'Rigge · bolde': 'Traversen · Bälle',
    'SJÆLDEN': 'SELTEN',
    'SKIFT BANE': 'LEVEL WECHSELN',
    'SKJOLD': 'SCHILD',
    'SKJOLD BRUGT · 2s': 'SCHILD VERBRAUCHT · 2s',
    'SKY RELAY · RAMT {0} AF PORT {1} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} VON TOR {1} GETROFFEN · 0 PUNKTE · NOCHMAL',
    'SKY RELAY · {0} · 0 POINT · PRØV IGEN': 'SKY RELAY · {0} · 0 PUNKTE · NOCHMAL',
    'SKY RELAY · {0}/3 PORTE · {1}% PRÆCISION · KUN LOKALT': 'SKY RELAY · {0}/3 TORE · {1}% PRÄZISION · NUR LOKAL',
    'TOPPEN': 'OBEN',
    'BUNDEN': 'UNTEN',
    'SKYRING RAMT': 'WOLKENRING GETROFFEN',
    'SPIL': 'SPIELEN',
    'SPIL KVALIFIKATION': 'QUALIFIKATION SPIELEN',
    'SPIL →': 'SPIELEN →',
    'SPIL {0}': '{0} SPIELEN',
    'SPIN FOR AT SE DIN REDNING': 'DREH, UM DEINE RETTUNG ZU SEHEN',
    'SPIN · 12 FJER': 'DREHEN · 12 FEDERN',
    'SPIN · {0} FJER': 'DREHEN · {0} FEDERN',
    'START FORFRA': 'VON VORN',
    'STARTBANE': 'STARTLEVEL',
    'STJERNEREGN': 'STERNENREGEN',
    'STIGER': 'STEIGT',
    'DYKKER': 'STÜRZT',
    'STORMLINE · VIND OG FLYVENDE TING · {0} stjerner · kun lokal eventrekord': 'STORMLINE · WIND UND FLIEGENDE DINGE · {0} Sterne · nur lokaler Eventrekord',
    'STREAK REDDET · GUARD BRUGT': 'STREAK GERETTET · GUARD VERBRAUCHT',
    'STORMPILOT': 'STURMPILOT',
    'Saml 20 stjerner til reden': 'Sammle 20 Sterne fürs Nest',
    'Saml 250 stjerner i alt': 'Sammle insgesamt 250 Sterne',
    'Scoretype': 'Wertung',
    'Skriv dit navn': 'Gib deinen Namen ein',
    'Spil Bird Run, lokal fugleverden. Undvig den varslede rovfugl. Ingen global rangliste.': 'Spiel Bird Run, eine lokale Vogelwelt. Weich dem angekündigten Raubvogel aus. Keine globale Rangliste.',
    'Spil Neon Encore, lokal koncertverden. Overlev en hel bølge med mindst tre bolde. Ingen global rangliste.': 'Spiel Neon Encore, eine lokale Konzertwelt. Überlebe eine ganze Welle mit mindestens drei Bällen. Keine globale Rangliste.',
    'Spil Sky Relay, en kort lokal præcisionsrute gennem tre skyringe. Ringens top og bund kan rammes. Ram vindklokkens guldplade. Ingen global rangliste.': 'Spiel Sky Relay, eine kurze lokale Präzisionsroute durch drei Wolkenringe. Oben und unten kann man die Ringe treffen. Triff die Goldplatte des Windspiels. Keine globale Rangliste.',
    'Spil Stormline, lokal vindverden. Undvig en flyvende genstand i storm. Ingen global rangliste.': 'Spiel Stormline, eine lokale Windwelt. Weich einem fliegenden Objekt im Sturm aus. Keine globale Rangliste.',
    'Spiltype': 'Spielmodus',
    'Start Quick Flight': 'Quick Flight starten',
    'Starthelt · Klar til at flyve': 'Startheld · Bereit zum Fliegen',
    'Starthelt': 'Startheld',
    'Streak Guard klar: redder én mistet stjerne': 'Streak Guard bereit: rettet einen verpassten Stern',
    'Streak Guard reddede din streak': 'Streak Guard hat deinen Streak gerettet',
    'Sur havnemåge · køb for fjer': 'Griesgrämige Hafenmöwe · mit Federn kaufen',
    'SØLV': 'SILBER',
    'BRONZE': 'BRONZE',
    'Sådan virker Berts rede': 'So funktioniert Berts Nest',
    'TAP': 'TIPPEN',
    'TAP FOR AT FLYVE · {0}': 'TIPPEN ZUM FLIEGEN · {0}',
    'TESTBANE': 'TESTLEVEL',
    'TIDEN UDE': 'ZEIT ABGELAUFEN',
    'TILBAGE': 'ZURÜCK',
    'TRYK FOR AT STARTE': 'TIPPEN ZUM STARTEN',
    'TUNG': 'SCHWER',
    'TUNG · STIGER LANGSOMT': 'SCHWER · STEIGT LANGSAM',
    'Tid': 'Zeit',
    'Tilgængelige helte': 'Verfügbare Helden',
    'UDFORDR EN VEN': 'FREUND HERAUSFORDERN',
    'Udfordringen er klar': 'Die Herausforderung ist bereit',
    'Udfordringslink klar': 'Herausforderungslink bereit',
    'Udfordringslink kopieret': 'Herausforderungslink kopiert',
    'Uge': 'Woche',
    'Undvig den varslede ørn eller grib': 'Weich dem angekündigten Adler oder Geier aus',
    'Undvig en flyvende genstand i storm eller orkan': 'Weich einem fliegenden Objekt in Sturm oder Orkan aus',
    'VELKOMMEN': 'WILLKOMMEN',
    'VENNEDUEL': 'FREUNDESDUELL',
    'VENNER': 'FREUNDE',
    'VERDEN': 'WELT',
    'VENNER FRA DUELLER': 'FREUNDE AUS DUELLEN',
    'VENNER FRA DUELLER · {0} RIVALER · {1} RESULTATER': 'FREUNDE AUS DUELLEN · {0} RIVALEN · {1} ERGEBNISSE',
    'VENSTRE SIDE = OP · HØJRE SIDE = NED': 'LINKE SEITE = HOCH · RECHTE SEITE = RUNTER',
    '{0} · VENSTRE OP · HØJRE NED': '{0} · LINKS HOCH · RECHTS RUNTER',
    'VERDEN KLARET': 'WELT GESCHAFFT',
    'VERDEN KLARET · LOKALT': 'WELT GESCHAFFT · LOKAL',
    'VIND & GENSTANDE': 'WIND & OBJEKTE',
    'VIND · TESTBANE': 'WIND · TESTLEVEL',
    'VIND · {0}': 'WIND · {0}',
    'VINDKLOKKEN RAMT': 'WINDSPIEL GETROFFEN',
    'VINDVERDEN · LOKALT': 'WINDWELT · LOKAL',
    'Vindmøller': 'Windräder',
    'VINDMØLLER': 'WINDRÄDER',
    'Vulkanen': 'Der Vulkan',
    'VULKANEN': 'DER VULKAN',
    'FJENDER & ANGREB': 'FEINDE & ANGRIFFE',
    'FUGLETRAFIK · TESTBANE': 'VOGELVERKEHR · TESTLEVEL',
    'FUGLE & ROVFUGL': 'VÖGEL & RAUBVOGEL',
    'FLAPPY-STYRING': 'FLAPPY-STEUERUNG',
    'FLAPPY-STYRING · TAP': 'FLAPPY-STEUERUNG · TIPPEN',
    'VUNDET': 'GEWONNEN',
    'BEHOLDT': 'BEHALTEN',
    'Valgt og klar til at flyve': 'Gewählt und bereit zum Fliegen',
    'Vind bronze, sølv og guld': 'Gewinne Bronze, Silber und Gold',
    'Vind ti vennedueller': 'Gewinne zehn Freundesduelle',
    'Vind · genstande': 'Wind · Objekte',
    'VÆLG HELT': 'HELD WÄHLEN',
    'VÆLG LEVEL': 'LEVEL WÄHLEN',
    'VÆLG SPILTYPE': 'SPIELMODUS WÄHLEN',
    'Vælg Bert': 'Bert wählen', 'Vælg Blok-Johan': 'Blok-Johan wählen', 'Vælg BlueBert': 'BlueBert wählen', 'Vælg BoneBeak': 'BoneBeak wählen',
    'Vælg BrainBird': 'BrainBird wählen', 'Vælg BrickBird': 'BrickBird wählen', 'Vælg Coopinc': 'Coopinc wählen', 'Vælg Fodbold-Bert': 'Fußball-Bert wählen',
    'Vælg Guld-Bert': 'Gold-Bert wählen', 'Vælg InkBird': 'InkBird wählen', 'Vælg MechaBert': 'MechaBert wählen', 'Vælg MossHex': 'MossHex wählen',
    'Vælg Mågen Mogens': 'Möwe Mogens wählen', 'Vælg Ninja-Bert': 'Ninja-Bert wählen', 'Vælg NoirWing': 'NoirWing wählen', 'Vælg Pakke-Bert': 'Paket-Bert wählen',
    'Vælg Pingo': 'Pingo wählen', 'Vælg Prinsesse Søs': 'Prinzessin Søs wählen', 'Vælg PrismWing': 'PrismWing wählen', 'Vælg SkyClaw': 'SkyClaw wählen',
    'Vælg Storm Royale': 'Storm Royale wählen', 'Vælg SugarRush': 'SugarRush wählen', 'Vælg Thor Obby': 'Thor Obby wählen',
    'Vælg bane': 'Level wählen',
    'Vælg leaderboard': 'Rangliste wählen',
    'Vælg level': 'Level wählen',
    'Vælg spiltype': 'Spielmodus wählen',
    'Vælg {0}, {1}': '{0} wählen, {1}',
    'købt': 'gekauft',
    'låst op': 'freigeschaltet',
    '{0} ER LÅST': '{0} IST GESPERRT',
    '{0} fik {1} point. Du har {2} forsøg på den samme bane, og deres flyvning vises som en skygge.': '{0} hat {1} Punkte erreicht. Du hast {2} Versuche im selben Level, und der Flug wird als Schatten gezeigt.',
    '{0} forsøg tilbage · slå {1} point': '{0} Versuche übrig · schlag {1} Punkte',
    '{0} har udfordret dig til at slå {1} point. Du har tre forsøg.': '{0} fordert dich heraus, {1} Punkte zu schlagen. Du hast drei Versuche.',
    '{0} låst op for {1} fjer': '{0} für {1} Federn freigeschaltet',
    '{0} låst. {1}. {2} af {3}. Alternativ pris {4} fjer.': '{0} gesperrt. {1}. {2} von {3}. Alternativ {4} Federn.',
    '{0} missionsbelønninger': '{0} Missionsbelohnungen',
    '{0} missionsbelønninger er hentet.': '{0} Missionsbelohnungen sind abgeholt.',
    '{0} point til næste medalje': '{0} Punkte bis zur nächsten Medaille',
    '{0} {1} Når begge krav er opfyldt, åbner hele trin {2}.': '{0} {1} Sind beide Anforderungen erfüllt, öffnet sich ganz Stufe {2}.',
    '{0} · {1} FASTE LIV': '{0} · {1} FESTE LEBEN',
    '{0}, låst. Tryk for at se oplåsningskravet': '{0}, gesperrt. Tippen für die Anforderung',
    '{0}, åben, personlig rekord {1}': '{0}, offen, persönlicher Rekord {1}',
    '{0} · Mål {1}': '{0} · Ziel {1}',
    '{0}/{1} BANER · {2}/{3} MISSIONER': '{0}/{1} LEVEL · {2}/{3} MISSIONEN',
    '{0}/{1} BANER · {2}/{3} MISS.': '{0}/{1} LEVEL · {2}/{3} MISS.',
    '{0} BANER · {1}': '{0} LEVEL · {1}',
    '{0}/{1} ÅBNE · {2}': '{0}/{1} OFFEN · {2}',
    'DU MANGLER {0} FJER': 'DIR FEHLEN {0} FEDERN',
    'BESKYTTET · {0}s': 'GESCHÜTZT · {0}s',
    'ÅBN DAGENS MISSIONER': 'TAGESMISSIONEN ÖFFNEN',
    'ÅBN GARDEROBE · 17 HELTE': 'GARDEROBE ÖFFNEN · 17 HELDEN',
    'ÅNDENDE PORTE': 'ATMENDE TORE',
    'Åbn dagens missioner': 'Tagesmissionen öffnen',
    'Åbn highscore': 'Highscore öffnen',
    'Åbn indstillinger': 'Einstellungen öffnen',
    'ÉN CHANCE MERE?': 'NOCH EINE CHANCE?',
    'Sprog': 'Sprache',
    'Automatisk (som telefonen)': 'Automatisch (wie das Handy)',
    'Dansk': 'Dänisch', 'Engelsk': 'Englisch', 'Norsk': 'Norwegisch', 'Svensk': 'Schwedisch', 'Tysk': 'Deutsch', 'Spansk': 'Spanisch', 'Fransk': 'Französisch', 'Portugisisk': 'Portugiesisch',
    '+1 FJER': '+1 FEDER',
    'En ven': 'Ein Freund',
    'Dig': 'Du',
    'REKORD': 'REKORD',
    'Topflyvning': 'Spitzenflug',
    '{0} point i {1}': '{0} Punkte in {1}',
    'en bane': 'einem Level',
    '{0} til trin {1} · {2} stjerner': '{0} bis Stufe {1} · {2} Sterne',
    '{0} · {1} stjerner samlet': '{0} · {1} Sterne gesammelt',
    '{0} FJER': '{0} FEDERN',
    'TAP FOR AT FLYVE': 'TIPPEN ZUM FLIEGEN',
    'Slå din vens score på præcis samme bane. Du har tre forsøg, og deres spøgelsesflyvning følger dig.': "Schlag den Score deines Freundes im selben Level. Du hast drei Versuche, und sein Geisterflug begleitet dich.",
    '{0}/{1} BRONZE': '{0}/{1} BRONZE',
    'Få bronze (20 point) på alle {0} grundbaner for at åbne Eventyr. Du har {1}.': 'Hol Bronze (20 Punkte) in allen {0} Grundlevels, um Abenteuer zu öffnen. Du hast {1}.',
    'SØLV I {0}': 'SILBER IN {0}',
    'Få sølv (50 point) i {0} for at åbne {1}.': 'Hol Silber (50 Punkte) in {0}, um {1} zu öffnen.',
    'LAVAEN FALDER': 'DIE LAVA SINKT',
    'GODT GREB · {0}s': 'GUTER GRIFF · {0}s',
    'VINDSTØD · OP': 'BÖE · HOCH',
    'VINDSTØD · NED': 'BÖE · RUNTER',
    'GLAT IS: STYR I GOD TID · SAML FROSTKRYSTALLER': 'GLATTES EIS: FRÜH LENKEN · FROSTKRISTALLE SAMMELN',
    'PAS PÅ VINDSTØD · PILENE VISER VEJEN': 'ACHTUNG BÖEN · DIE PFEILE ZEIGEN DIE RICHTUNG',
    'LAVAEN STIGER · SAML KØLESTEN': 'DIE LAVA STEIGT · KÜHLSTEINE SAMMELN',
    'LYSET SLUKKER LANGSOMT · SAML LANTERNER': 'DAS LICHT ERLISCHT LANGSAM · LATERNEN SAMMELN',
    'CONTAINERNE FLYTTER SIG · PAS PÅ MÅGERNE': 'DIE CONTAINER BEWEGEN SICH · VORSICHT MÖWEN',
    'Fugleklat': 'Vogelklecks',
    'SPIS & KLAT': 'FRESSEN & KLECKSEN',
    'PARAPLYEN REDDEDE DEM': 'DER SCHIRM HAT SIE GERETTET',
    'GULDBIL! ×3': 'GOLDAUTO! ×3',
    'PLASK!': 'PLATSCH!',
    'SPIS MAD · TRYK 💩 FOR AT RAMME MÅL NEDENUNDER': 'FRISS FUTTER · TIPPE 💩, UM ZIELE UNTEN ZU TREFFEN',
    'Slip en klat': 'Klecks fallen lassen',
});
